@startuml
skinparam defaultFontSize 11
class Payment {
  -String updatedAt
  #float duration
  -long level
  +getActive()
}
class Shipment {
  +boolean type
  -String code
  +double description
  +processUpdatedat()
  +getScore()
}
interface Return {
  -String description
  -boolean phone
  #String active
  +long quantity
  +createDescription()
}
abstract class Supplier {
  -String id
  -float quantity
  +float note
  +getScore()
  +deletePrice()
  +deleteId()
  +saveTotal()
}
interface Warehouse {
  -long total
  +double quantity
  +double level
  +Date active
  +calculateTotal()
  +sendType()
  +sendActive()
}
abstract class Category {
  +Date code
  #double description
  #float address
  +processScore()
}
Category ..|> Warehouse
Supplier --o Shipment
Payment ..> Shipment : "0..1"
Return --* Category
Return ..|> Shipment
@enduml