@startuml
skinparam ArrowColor #555555
class Payment {
  -Date email
  -String name
  +double amount
  -Date active
  +calculateNote()
  +saveId()
  +saveNote()
}
abstract class Product {
  +double quantity
  #Date updatedAt
  +findType()
  +deleteEmail()
  +setType()
  +cancelTotal()
}
class Warehouse {
  -float email
  #boolean address
  +createName()
}
abstract class Return {
  #Date duration
  +boolean description
  +int type
  +int email
  +validateLevel()
  +getAmount()
  +updateTotal()
  +createEmail()
}
class Invoice {
  +double email
  +boolean amount
  -boolean type
  +sendAddress()
  +updateCreatedat()
}
class Order {
  +int description
  #float address
  +float code
  +boolean level
  +deleteActive()
}
Product --o Warehouse
Invoice ..|> Payment
Return ..|> Warehouse
Product ..|> Invoice
@enduml