@startuml
skinparam monochrome true
skinparam defaultFontSize 13
class User {
  +Date note
  #String type
  -boolean phone
  +processPrice()
  +updateName()
  +sendPrice()
  +createPrice()
}
class Album {
  #long name
  -String updatedAt
  #double address
  +long status
  +getType()
  +validateAddress()
  +updateAmount()
  +saveId()
}
abstract class Profile {
  #double amount
  #boolean name
  #double duration
  +updateAddress()
  +createQuantity()
  +sendLevel()
}
class Message {
  #boolean status
  -boolean quantity
  +setDuration()
  +findPrice()
}
class Report {
  +Date createdAt
  -int description
  +updateQuantity()
  +sendAmount()
  +processCode()
}
class Hashtag {
  -int duration
  +Date name
  +double code
  +savePrice()
  +cancelDuration()
  +updateDuration()
  +validatePhone()
}
interface Like {
  #int id
  +String active
  #long quantity
  +calculateAmount()
}
Report --|> Like
Like --o Hashtag
User ..> Like : "*"
Report ..|> Album
Like --o Profile
@enduml