@startuml
skinparam defaultFontSize 11
interface CheckOut {
  -double amount
  -String updatedAt
  -double duration
  #float total
  +createAddress()
  +cancelType()
}
class CheckIn {
  -float duration
  +long status
  #long description
  -long name
  +getType()
  +findStatus()
  +updateNote()
}
class Restaurant {
  +double email
  #long phone
  +float total
  +createEmail()
}
interface Payment {
  -float id
  -int code
  +deleteDescription()
  +cancelLevel()
  +cancelTotal()
  +processAddress()
}
interface Room {
  -Date score
  #double description
  #double createdAt
  -Date note
  +setEmail()
  +calculateType()
  +sendPrice()
  +cancelName()
}
abstract class Housekeeping {
  -double note
  +String type
  +processId()
}
Room --o CheckOut
Housekeeping --* Payment
Room --|> Restaurant
@enduml