@startuml
skinparam defaultFontSize 11
class Withdrawal {
  -double email
  -long duration
  +updateNote()
  +sendActive()
  +setAddress()
}
interface Statement {
  +int createdAt
  -double phone
  +processTotal()
  +setName()
}
abstract class Transaction {
  -Date score
  -Date note
  +boolean quantity
  -double active
  +cancelActive()
  +deleteScore()
  +saveDuration()
  +setId()
}
interface Teller {
  +boolean amount
  +String createdAt
  +getId()
  +findStatus()
  +processCreatedat()
}
abstract class Transfer {
  #boolean phone
  #String updatedAt
  #boolean price
  #float amount
  +getType()
  +findStatus()
  +updateStatus()
  +saveDescription()
}
interface Account {
  -boolean phone
  +int total
  +Date active
  #Date type
  +String quantity
  +saveQuantity()
  +processPrice()
}
class Customer {
  -double quantity
  +int active
  +processLevel()
  +calculateQuantity()
}
Transaction --|> Customer
Transaction --o Transfer
Statement ..> Withdrawal : "1"
@enduml