@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
abstract class Statement {
  -float level
  -double duration
  +int active
  -boolean email
  -double score
  +saveId()
  +validateCode()
  +updateNote()
}
interface Teller {
  -double updatedAt
  -float code
  +int price
  #long note
  #long email
  +setDescription()
  +setCreatedat()
  +sendId()
}
class Account {
  +String quantity
  +float id
  #float createdAt
  +boolean description
  +createPhone()
  +deleteType()
}
interface Card {
  #double level
  -String total
  #int description
  +double type
  +Date address
  +setPrice()
  +sendScore()
}
abstract class Transfer {
  -long address
  -double quantity
  +float total
  #boolean type
  +long phone
  +saveDescription()
  +setUpdatedat()
  +validateStatus()
  +cancelNote()
}
Teller --|> Account
Statement ..|> Card
Statement --* Account
@enduml