@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
class Hashtag {
  #Date email
  -long quantity
  -double note
  +long updatedAt
  +setNote()
}
class Story {
  -boolean price
  +int email
  +int active
  +findCreatedat()
  +processEmail()
  +cancelPhone()
}
interface Follower {
  #float email
  #int amount
  #long code
  -boolean description
  +cancelScore()
}
class Album {
  -float description
  #double address
  -String status
  +validateName()
  +calculateAmount()
  +updateScore()
  +calculateId()
}
interface Profile {
  -int address
  -Date email
  +saveDuration()
  +cancelDuration()
  +cancelAmount()
  +processCode()
}
Follower --|> Hashtag
Album --|> Story
@enduml