@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
class Loan {
  #boolean email
  #long total
  -String code
  #long updatedAt
  +cancelQuantity()
  +cancelActive()
}
class Branch {
  +float amount
  #int note
  +calculatePrice()
  +findType()
}
abstract class Book {
  +String type
  -Date level
  +int amount
  +sendCode()
  +validateId()
}
class Catalog {
  -long code
  -boolean phone
  +double amount
  +Date email
  +processAmount()
  +deleteId()
  +createEmail()
  +createCode()
}
Catalog --o Loan
Catalog ..> Branch : "1..*"
@enduml