@startuml
skinparam defaultFontSize 11
interface Branch {
  +double score
  #String price
  +calculateScore()
  +saveTotal()
  +saveName()
  +sendUpdatedat()
}
abstract class Transaction {
  -long id
  #long phone
  +setName()
}
class Statement {
  #Date score
  -long address
  #Date level
  +boolean updatedAt
  +calculateTotal()
  +getUpdatedat()
  +deleteTotal()
  +createQuantity()
}
abstract class Customer {
  +double quantity
  -double phone
  +long level
  +String note
  +boolean id
  +saveAddress()
  +createCreatedat()
  +getId()
}
Statement --o Customer
Customer --o Statement
Transaction --|> Branch
@enduml