@startuml

abstract class Shipment {
  #String quantity
  -Date level
  +getDuration()
  +deleteUpdatedat()
}
abstract class Product {
  #String updatedAt
  -long total
  #long code
  +setPrice()
  +findAmount()
  +getTotal()
  +setScore()
}
class Cart {
  #float quantity
  +float amount
  -String phone
  +double price
  #int total
  +findAddress()
}
class Review {
  -boolean level
  #double email
  -long code
  #boolean id
  +savePrice()
  +deleteAddress()
  +setStatus()
}
Shipment --* Product
Shipment --* Cart
@enduml