@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
interface Route {
  +boolean price
  -long updatedAt
  -boolean id
  +setDescription()
}
abstract class Inventory {
  #String status
  +int level
  +createType()
  +validatePrice()
}
class Warehouse {
  -String type
  #float active
  +double total
  -double description
  +findStatus()
  +sendActive()
  +createPhone()
  +calculateAmount()
}
interface Package {
  #long createdAt
  -long active
  -long price
  -float name
  +calculateUpdatedat()
  +calculateDuration()
}
Warehouse --o Inventory
Inventory ..|> Package
@enduml