@startuml
skinparam monochrome true
class Booking {
  #float phone
  #boolean code
  #double active
  -boolean description
  +deleteTotal()
  +calculatePrice()
}
abstract class Room {
  -boolean createdAt
  #boolean id
  #String score
  #double email
  +boolean total
  +calculateLevel()
  +validateType()
  +updateDescription()
}
interface CheckOut {
  -Date id
  +boolean total
  +updateActive()
}
class Service {
  -boolean address
  -Date id
  -Date note
  +float quantity
  +processName()
  +calculateNote()
  +sendLevel()
}
class Amenity {
  #String total
  -double updatedAt
  #double level
  +findEmail()
  +getDuration()
}
class Restaurant {
  -double description
  #Date phone
  #boolean createdAt
  +validateUpdatedat()
  +findTotal()
}
class Housekeeping {
  +double id
  -double total
  +updateEmail()
  +calculatePrice()
  +setEmail()
  +updateDuration()
}
Amenity --> Housekeeping : "*"
Amenity --> Service : "1..*"
@enduml