@startuml
skinparam monochrome true
skinparam shadowing true
class Attendance {
  #float quantity
  +Date duration
  +String price
  +findType()
  +updateScore()
  +createName()
  +sendUpdatedat()
}
interface Library {
  -int type
  +String id
  #boolean note
  #String level
  +boolean phone
  +setCreatedat()
  +calculateTotal()
}
class Schedule {
  -double duration
  -String active
  +long type
  +validateTotal()
  +validateActive()
  +deleteLevel()
}
class Book {
  +long id
  +double price
  #int createdAt
  +boolean status
  +Date amount
  +setQuantity()
}
Schedule --> Attendance : "0..1"
Book --* Schedule
@enduml