@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
class Story {
  -boolean type
  +double description
  +setCreatedat()
  +findAmount()
}
class Like {
  #double note
  -boolean createdAt
  +processPrice()
}
interface Post {
  +float name
  #String code
  +getType()
  +cancelName()
}
interface Follower {
  #Date name
  #double price
  #boolean code
  +validatePrice()
}
interface Profile {
  -boolean active
  #double phone
  +findDescription()
  +cancelType()
}
class Report {
  -long price
  -String active
  #Date address
  +setUpdatedat()
  +validateDuration()
  +createAddress()
}
Follower ..> Post : "0..1"
Like ..|> Follower
Profile ..|> Like
@enduml