@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
interface Card {
  -boolean type
  -float description
  -int total
  +cancelNote()
  +setCreatedat()
  +sendScore()
  +deleteDescription()
}
class Statement {
  +String code
  -double email
  #int price
  -double description
  #boolean amount
  +getCreatedat()
  +cancelAmount()
}
abstract class Interest {
  +double amount
  +double price
  +long description
  +cancelAmount()
  +sendId()
}
abstract class Teller {
  +long updatedAt
  +double note
  +calculateActive()
  +saveType()
}
class Transfer {
  #double quantity
  +float description
  #Date createdAt
  +double updatedAt
  +findAmount()
  +setAddress()
}
abstract class Withdrawal {
  +double score
  -float status
  +getPhone()
}
Transfer --o Teller
Withdrawal --o Teller
Statement --* Transfer
@enduml