@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
abstract class Statement {
  #long type
  #long status
  +Date phone
  +validateDuration()
  +setStatus()
}
abstract class Account {
  #String name
  -int phone
  -int id
  #float amount
  +cancelEmail()
  +validateLevel()
  +cancelNote()
}
abstract class Interest {
  -String name
  #String phone
  -float price
  +int createdAt
  +boolean active
  +getCode()
  +validateDescription()
  +calculatePrice()
  +processStatus()
}
class Customer {
  #float status
  -String name
  +validateDescription()
  +sendPrice()
  +getPhone()
}
class Card {
  -float amount
  +double name
  +String id
  -double email
  +findId()
  +createEmail()
}
class Teller {
  #float name
  -float address
  -String score
  +calculatePrice()
  +deleteEmail()
  +updateName()
  +setPrice()
}
class Transaction {
  +double note
  -String address
  +double name
  +validateScore()
}
Statement ..> Transaction : "*"
Interest --|> Card
Interest --> Customer : "1..*"
Statement ..> Interest : "1"
@enduml