@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
class Customer {
  #Date code
  -Date type
  +Date price
  -Date level
  +boolean duration
  +createCode()
  +sendQuantity()
  +processType()
  +sendTotal()
}
class Beneficiary {
  #float duration
  +int total
  +saveAddress()
}
interface Account {
  -String total
  +String createdAt
  #long description
  #boolean duration
  +String active
  +findStatus()
  +getDuration()
  +sendLevel()
}
class Withdrawal {
  #Date status
  #int score
  #String id
  +findName()
  +validateUpdatedat()
}
class Transaction {
  -int type
  #int score
  -float active
  +createUpdatedat()
  +setScore()
  +calculateQuantity()
  +setType()
}
interface Teller {
  -boolean type
  -float description
  +processStatus()
}
class Loan {
  +float code
  +String status
  #boolean address
  +double active
  +setStatus()
  +cancelEmail()
}
Loan ..> Customer : "1..*"
Withdrawal ..> Loan : "1"
Account --> Beneficiary : "1..*"
Customer ..|> Withdrawal
@enduml