@startuml
skinparam monochrome true
skinparam defaultFontSize 11
class Payment {
  +int id
  -double quantity
  -int description
  +boolean type
  +deleteActive()
  +sendTotal()
  +deleteAddress()
  +validateUpdatedat()
}
class Cart {
  -double price
  +boolean quantity
  #Date updatedAt
  +deleteCreatedat()
  +findAmount()
  +findPhone()
  +saveScore()
}
class Invoice {
  -int level
  -int createdAt
  +int score
  -Date name
  -long phone
  +sendAmount()
  +findQuantity()
  +createCode()
}
class Shipment {
  +double price
  -int updatedAt
  #String code
  #String total
  +getDescription()
  +calculateScore()
  +findPrice()
  +cancelNote()
}
abstract class Customer {
  +float description
  -long type
  -String active
  +int email
  +deleteCode()
  +calculateStatus()
  +processUpdatedat()
}
interface Wishlist {
  #String duration
  -long score
  +saveAddress()
  +validateTotal()
  +getQuantity()
}
class Warehouse {
  +int createdAt
  #long description
  +boolean price
  #double total
  +createCode()
  +findDescription()
  +setAmount()
  +saveNote()
}
Customer --* Payment
Warehouse ..> Payment : "1..*"
Invoice --* Cart
Cart --o Payment
Shipment ..|> Wishlist
@enduml