@startuml
skinparam defaultFontSize 11
class Tracking {
  -Date total
  #float id
  #boolean amount
  -double level
  +saveUpdatedat()
  +cancelName()
  +setActive()
  +calculateType()
}
interface Driver {
  +String createdAt
  #double score
  +boolean total
  -boolean updatedAt
  +saveDescription()
  +saveDuration()
  +deleteStatus()
  +validateNote()
}
class Vehicle {
  +int status
  #int id
  #long active
  +processCode()
}
abstract class Inventory {
  #int status
  -Date quantity
  -long price
  +updateCode()
  +findDescription()
  +getCreatedat()
}
Driver --o Inventory
Driver ..> Tracking : "1..*"
@enduml