@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
class Notification {
  -float code
  #long createdAt
  #boolean name
  +Date total
  #boolean updatedAt
  +calculateEmail()
  +cancelTotal()
}
class Hashtag {
  +boolean email
  #Date total
  +setType()
  +getStatus()
}
interface Group {
  +long code
  +int createdAt
  -boolean active
  -long note
  +updateAddress()
  +validateScore()
  +validateQuantity()
}
class Report {
  #long updatedAt
  +int amount
  -int address
  #double status
  +processUpdatedat()
  +validateDescription()
}
class Like {
  #Date phone
  -double address
  +String status
  +validateDescription()
  +validatePhone()
  +processDescription()
}
class Follower {
  -long code
  -boolean type
  +Date quantity
  +double status
  -double active
  +updateQuantity()
  +setPrice()
  +getQuantity()
}
Hashtag --o Report
Group ..> Notification : "0..1"
@enduml