@startuml
skinparam monochrome true
skinparam shadowing true
class Order {
  +String quantity
  #double type
  +int status
  -String note
  +sendUpdatedat()
  +saveType()
  +setId()
}
class Wishlist {
  -String code
  +double note
  #Date level
  +double type
  +validateCode()
}
interface Shipment {
  -int id
  +Date name
  #double note
  +double quantity
  +createId()
  +cancelAmount()
}
class Invoice {
  #float total
  +long type
  -boolean status
  -long level
  +processActive()
}
abstract class Return {
  +double email
  +long price
  +float description
  +sendDuration()
  +setDescription()
  +calculateScore()
}
class Payment {
  +String level
  #String description
  -float total
  +findNote()
  +validateName()
  +saveName()
}
Shipment --o Order
Order ..> Payment : "*"
@enduml