@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
class Post {
  #float quantity
  -String score
  +saveDescription()
  +calculatePrice()
  +savePhone()
  +sendQuantity()
}
class Like {
  #int address
  #Date email
  +double id
  +cancelEmail()
}
class Group {
  -Date score
  +String createdAt
  +String level
  +cancelAddress()
  +createDescription()
  +updateDuration()
}
class Profile {
  +long address
  -int name
  #String description
  #long email
  +saveCreatedat()
}
abstract class Hashtag {
  -String email
  +double duration
  +updateLevel()
  +createDescription()
  +sendId()
}
Post --|> Hashtag
Profile ..> Post : "1"
Like --> Post : "*"
@enduml