@startuml
skinparam monochrome true
skinparam shadowing true
class Order {
  #float active
  #Date total
  +float createdAt
  #String amount
  #long description
  +saveCreatedat()
  +findScore()
}
class Return {
  -int status
  +double name
  #long active
  #int duration
  +boolean level
  +validateActive()
  +createEmail()
  +validateScore()
}
class Invoice {
  #String code
  -double phone
  -double email
  -int level
  +updateName()
  +findType()
  +deleteCode()
  +validateDuration()
}
class Supplier {
  -float address
  #float description
  -boolean total
  +boolean note
  #int code
  +saveCreatedat()
  +setStatus()
  +cancelCode()
  +saveDuration()
}
class Shipment {
  +Date score
  -int phone
  #double address
  +cancelUpdatedat()
  +createCreatedat()
  +processDuration()
}
class Customer {
  #Date code
  +double active
  +float address
  +getDescription()
  +createNote()
  +findNote()
  +saveScore()
}
Customer --o Invoice
Shipment --> Order : "*"
Customer ..> Shipment : "1"
@enduml