@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
class Review {
  +boolean type
  +boolean createdAt
  +String phone
  +double score
  +long description
  +processDescription()
  +saveName()
}
class Supplier {
  #Date quantity
  #boolean active
  +double id
  +Date createdAt
  +saveStatus()
  +sendQuantity()
  +cancelTotal()
  +calculateAmount()
}
class Cart {
  #String code
  -long amount
  #int quantity
  -int score
  +processCreatedat()
  +setPhone()
  +processAmount()
}
class Order {
  -long amount
  #String updatedAt
  #long phone
  #double name
  -double active
  +savePrice()
  +findPhone()
  +deleteQuantity()
}
interface Warehouse {
  #double description
  #long phone
  +savePrice()
  +findAmount()
  +cancelActive()
  +processAddress()
}
abstract class Invoice {
  -Date code
  +float updatedAt
  -boolean amount
  #double level
  +findScore()
  +cancelActive()
  +setAddress()
  +calculateCreatedat()
}
Order ..|> Warehouse
Supplier --o Review
Order ..|> Cart
@enduml