@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
class Loan {
  +float description
  -Date address
  +double note
  +boolean id
  +String level
  +getEmail()
  +deleteLevel()
  +cancelTotal()
  +calculateId()
}
interface Branch {
  -long amount
  -double email
  -boolean code
  #Date note
  +sendId()
  +updateUpdatedat()
  +setScore()
}
class Withdrawal {
  #long price
  -Date code
  +double status
  +float duration
  +sendDescription()
}
abstract class Customer {
  +double amount
  #double status
  +boolean active
  #long phone
  +getDescription()
  +createCreatedat()
  +setAddress()
  +updatePhone()
}
class Statement {
  -float active
  -float id
  +long total
  #Date status
  +cancelScore()
  +processNote()
  +getCode()
  +calculateScore()
}
Loan --> Statement : "1"
Statement ..> Withdrawal : "1"
@enduml