@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
class Housekeeping {
  -String amount
  -int description
  -String address
  +findDuration()
  +findNote()
  +deleteUpdatedat()
  +deleteTotal()
}
interface Invoice {
  -double level
  -long id
  +createEmail()
  +saveQuantity()
  +getAmount()
  +saveTotal()
}
interface Staff {
  +boolean quantity
  +Date address
  -int status
  +int active
  -long type
  +processPhone()
  +sendTotal()
}
class Amenity {
  -int id
  #float quantity
  +saveType()
  +saveDescription()
  +createId()
}
Amenity --|> Staff
Housekeeping ..|> Invoice
@enduml