@startuml
skinparam defaultFontSize 11
class Transfer {
  +String total
  #double description
  +setId()
}
abstract class Card {
  +long level
  #Date quantity
  +createEmail()
  +calculateAmount()
}
abstract class Teller {
  #Date name
  +boolean score
  -float type
  +int phone
  +setDuration()
  +setDescription()
  +updateEmail()
}
class Beneficiary {
  -float type
  +boolean updatedAt
  -String code
  #Date duration
  +getType()
  +calculateQuantity()
  +createQuantity()
}
interface Interest {
  #String duration
  -double createdAt
  +sendTotal()
  +processLevel()
}
class Branch {
  +long id
  #Date price
  +Date email
  +String active
  +sendAddress()
  +deleteType()
  +cancelDescription()
  +saveDuration()
}
Card --o Transfer
Beneficiary --* Transfer
Teller --o Card
@enduml