@startuml
skinparam monochrome true
skinparam defaultFontSize 11
class Customer {
  -long amount
  #long price
  -String address
  +processEmail()
}
interface Category {
  -long score
  -Date email
  -int type
  -long code
  +setDuration()
  +updateScore()
  +validateDuration()
  +updatePhone()
}
class Return {
  -Date address
  -int score
  +getDescription()
  +deleteEmail()
  +updateAddress()
  +calculateActive()
}
class Shipment {
  +Date price
  #double quantity
  -String updatedAt
  +updateCode()
  +deletePhone()
  +getAmount()
}
Shipment --o Customer
Return ..> Category : "0..1"
@enduml