@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
interface Member {
  #int score
  +double email
  -boolean description
  +createId()
  +updateUpdatedat()
  +sendLevel()
}
interface Shelf {
  #long email
  -long type
  +boolean duration
  #boolean phone
  #float total
  +sendQuantity()
  +validateAmount()
}
class Publisher {
  -boolean level
  +String price
  +findId()
  +cancelAmount()
  +updateCreatedat()
}
interface Reservation {
  +int amount
  -long description
  +setType()
  +cancelCode()
  +setName()
  +createAddress()
}
Shelf --> Reservation : "0..1"
Shelf --o Member
@enduml