@startuml
skinparam defaultFontSize 13
class Branch {
  #double active
  #float level
  +float phone
  -float createdAt
  +setTotal()
  +findPhone()
}
class Loan {
  -double id
  +boolean type
  +Date name
  +processScore()
}
interface Beneficiary {
  +float description
  #Date id
  +sendCode()
  +setQuantity()
}
class Interest {
  #float id
  #int duration
  #boolean score
  -int address
  #Date level
  +deleteQuantity()
  +deletePhone()
  +processType()
  +validateDescription()
}
Branch ..> Loan : "*"
Branch ..> Interest : "1..*"
Loan --* Beneficiary
@enduml