@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Branch {
  #Date total
  +float createdAt
  +setStatus()
  +updateEmail()
  +updateActive()
}
class Teller {
  +double code
  -long email
  -String amount
  -int price
  +getDuration()
  +getDescription()
  +createActive()
  +processActive()
}
abstract class Card {
  +float id
  +double code
  -boolean score
  +setPrice()
}
class Customer {
  +double code
  #String type
  +float phone
  -Date level
  #float id
  +processType()
  +updateCode()
}
class Withdrawal {
  #Date name
  +double code
  -String id
  +boolean level
  #Date total
  +calculateQuantity()
  +updateName()
  +validateId()
}
interface Deposit {
  -float email
  #float score
  #long level
  +boolean description
  #float price
  +getName()
  +processEmail()
  +updateCreatedat()
  +calculateAmount()
}
Deposit --> Withdrawal : "*"
Branch ..|> Withdrawal
Branch --> Teller : "1"
Teller --* Customer
@enduml