@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class User {
  -float status
  +boolean note
  +String createdAt
  #boolean type
  -int active
  +getNote()
  +findPhone()
  +setScore()
  +deleteDescription()
}
class Album {
  -float type
  +int email
  #float score
  +setAmount()
  +deletePhone()
  +sendStatus()
}
class Notification {
  #boolean price
  -double name
  +String duration
  #String updatedAt
  #long score
  +sendStatus()
  +validateDuration()
  +cancelDescription()
  +deleteScore()
}
class Follower {
  #float updatedAt
  +Date total
  +sendAddress()
  +setScore()
  +cancelType()
}
class Story {
  #boolean active
  +String duration
  #boolean note
  #int name
  +saveCreatedat()
  +setName()
  +calculatePhone()
  +processLevel()
}
class Report {
  -float duration
  -String createdAt
  +int total
  +float note
  +getName()
}
class Group {
  #long status
  +Date email
  -double type
  #String updatedAt
  #boolean address
  +validateName()
  +processUpdatedat()
}
Report ..|> Story
Report --* Album
Album ..|> Story
note right of User : Social Media domain
@enduml