@startuml

class Doctor {
  +long updatedAt
  +double price
  +sendId()
  +updateQuantity()
}
class LabTest {
  #String createdAt
  #long price
  -String code
  +boolean quantity
  +int note
  +cancelPhone()
  +calculateDuration()
}
class Billing {
  #int total
  -boolean status
  +createLevel()
  +calculateActive()
  +findId()
  +deleteCreatedat()
}
abstract class Diagnosis {
  -double phone
  #boolean duration
  -boolean total
  -String amount
  +boolean code
  +saveCode()
  +createScore()
  +saveActive()
  +deleteDuration()
}
Billing --|> Doctor
Diagnosis --o LabTest
Doctor ..|> LabTest
@enduml