@startuml
skinparam monochrome true
skinparam shadowing true
class Payment {
  +boolean type
  +float status
  -float name
  #long price
  +updateDescription()
}
interface Amenity {
  #float amount
  +long total
  +processAddress()
}
class Room {
  +boolean level
  #double price
  -int createdAt
  +saveLevel()
  +processAmount()
  +setAddress()
}
interface Housekeeping {
  +double total
  -boolean address
  +long description
  +createActive()
  +deleteUpdatedat()
  +saveType()
  +updateTotal()
}
class CheckIn {
  +Date email
  -boolean note
  +int score
  +validateQuantity()
  +deleteName()
}
Amenity --> CheckIn : "1..*"
Housekeeping ..|> Amenity
@enduml