@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
abstract class Album {
  #String updatedAt
  +String duration
  +double price
  -int quantity
  +float name
  +createQuantity()
}
class Notification {
  -float phone
  #long active
  #float address
  -Date price
  #double description
  +saveEmail()
  +getCode()
}
abstract class Comment {
  #Date quantity
  #long email
  #int amount
  +String status
  +deletePhone()
}
abstract class Like {
  #boolean status
  -Date address
  +updateDescription()
  +deleteUpdatedat()
  +getCreatedat()
}
class Profile {
  +double price
  #boolean updatedAt
  -String phone
  +updateEmail()
  +findCreatedat()
  +findPrice()
}
class Hashtag {
  +float duration
  #int score
  +Date description
  +sendNote()
  +cancelCode()
  +getActive()
  +getName()
}
Hashtag --> Comment : "0..1"
@enduml