@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
class Like {
  +float email
  #long id
  +boolean price
  +findDescription()
  +saveType()
}
class Message {
  -Date code
  +float name
  #long price
  +saveLevel()
  +processUpdatedat()
}
class Profile {
  -long quantity
  -boolean score
  #long active
  #double total
  +saveDuration()
  +createUpdatedat()
  +validateTotal()
  +calculateNote()
}
interface User {
  #float code
  +long duration
  -String price
  #String description
  -float note
  +saveNote()
  +updateCreatedat()
}
class Report {
  +boolean status
  +double email
  -long amount
  #long duration
  +long code
  +calculateNote()
  +updateTotal()
  +processPhone()
  +deleteEmail()
}
abstract class Album {
  #int description
  #double note
  #long duration
  #long status
  +sendDescription()
  +updateActive()
}
Report ..> Album : "*"
Profile ..|> Report
note right of Like : Social Media domain
@enduml