@startuml
skinparam defaultFontSize 13
class Invoice {
  -double note
  +Date address
  +boolean amount
  +calculatePrice()
}
class Restaurant {
  +int total
  -String note
  #float phone
  #int active
  +setQuantity()
  +processScore()
}
class Reservation {
  #int description
  -float type
  +processEmail()
  +calculateName()
}
abstract class Guest {
  #int quantity
  #long name
  +updateAddress()
  +createName()
  +findPhone()
  +calculateAmount()
}
Invoice --* Guest
Guest --|> Restaurant
Reservation --* Restaurant
@enduml