@startuml
skinparam monochrome true
skinparam ArrowColor #555555
abstract class Warehouse {
  +Date description
  -String amount
  +long duration
  #int name
  +double type
  +createDescription()
}
class Product {
  #Date address
  +int price
  +sendPhone()
}
interface Customer {
  #int score
  #boolean phone
  +setPrice()
  +cancelUpdatedat()
  +processCode()
}
class Cart {
  -long status
  #long phone
  -long description
  #String total
  +long email
  +updateName()
  +deleteScore()
}
class Return {
  -long id
  +long score
  +boolean amount
  -float quantity
  +findId()
  +processLevel()
}
Warehouse ..> Cart : "0..1"
Customer ..|> Warehouse
note right of Warehouse : Ecommerce domain
@enduml