@startuml
skinparam defaultFontSize 11
class Order {
  -String duration
  +int address
  #long score
  +cancelName()
  +getAmount()
}
class Warehouse {
  +Date code
  #boolean score
  -String phone
  +Date note
  +cancelTotal()
  +processStatus()
  +findType()
  +sendAddress()
}
class Coupon {
  -boolean status
  +Date phone
  +double note
  #float name
  +saveAddress()
  +findDuration()
}
abstract class Category {
  -Date code
  +Date price
  -int total
  +float updatedAt
  +processCreatedat()
}
class Supplier {
  #int updatedAt
  #long quantity
  -Date address
  #int amount
  +getCode()
  +setPrice()
  +processPhone()
}
class Cart {
  #long name
  +int updatedAt
  +String quantity
  +updateQuantity()
  +cancelCode()
}
Supplier --|> Category
Category --> Order : "*"
Category --* Warehouse
@enduml