@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
class Billing {
  +long createdAt
  #double id
  #boolean status
  +Date active
  #long score
  +sendUpdatedat()
  +cancelActive()
  +deleteCode()
}
abstract class LabTest {
  -Date address
  -Date active
  +updateDescription()
}
abstract class Ward {
  #int note
  +String amount
  +float createdAt
  +createQuantity()
  +deleteCode()
  +savePrice()
  +processActive()
}
class Appointment {
  +double id
  -boolean updatedAt
  +long status
  -float type
  #long description
  +processTotal()
}
abstract class Prescription {
  -String amount
  #boolean description
  #long level
  +Date duration
  +long phone
  +sendQuantity()
  +updateCode()
  +cancelUpdatedat()
  +createCreatedat()
}
Appointment --|> Billing
Billing --> Ward : "1"
Appointment --* LabTest
@enduml