@startuml
skinparam monochrome true
interface Coupon {
  #String name
  +boolean code
  +Date email
  -double id
  +findName()
}
class Supplier {
  -Date amount
  +int createdAt
  +boolean active
  +setUpdatedat()
}
abstract class Invoice {
  +double code
  #Date active
  +getScore()
  +updatePrice()
}
class Customer {
  -long note
  #double updatedAt
  +validateDescription()
  +processId()
  +processPhone()
}
class Wishlist {
  +String address
  -int score
  +long createdAt
  #double phone
  +updateAddress()
  +updateStatus()
  +sendScore()
  +findName()
}
interface Order {
  -int code
  #int note
  +processCreatedat()
  +saveCreatedat()
}
class Payment {
  +String note
  -float description
  -double active
  +float type
  +deleteScore()
  +getCreatedat()
}
Customer --o Coupon
Wishlist --> Customer : "*"
Customer ..> Order : "*"
Supplier --o Wishlist
note right of Coupon : Ecommerce domain
@enduml