@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
class Hashtag {
  +double note
  +String status
  +saveDuration()
  +deleteNote()
}
class Comment {
  #int duration
  -float description
  #String email
  #String status
  -String type
  +updatePhone()
  +setTotal()
  +setNote()
}
class Like {
  #Date email
  +int createdAt
  -Date total
  #boolean price
  #boolean code
  +validateStatus()
  +sendScore()
  +saveUpdatedat()
  +findPrice()
}
abstract class Story {
  #boolean type
  +float description
  #String name
  -long amount
  #String id
  +deleteAmount()
  +createNote()
  +getType()
}
Like --o Comment
Story --> Like : "1"
@enduml