@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Teller {
  -long updatedAt
  #float score
  #double status
  #long phone
  #double active
  +calculateId()
  +setId()
  +validateDuration()
}
interface Beneficiary {
  +int level
  -long phone
  +double email
  +String active
  #int createdAt
  +findActive()
  +processEmail()
  +saveUpdatedat()
  +deleteAddress()
}
abstract class Loan {
  #float type
  +boolean description
  -boolean score
  -double active
  +double code
  +createDuration()
  +setName()
  +getQuantity()
}
class Customer {
  +Date phone
  #String active
  +long updatedAt
  +sendCreatedat()
  +calculateStatus()
  +saveCode()
  +calculateCode()
}
abstract class Card {
  #float total
  +long status
  -Date quantity
  +saveName()
  +deleteCode()
  +updateUpdatedat()
}
abstract class Interest {
  +String amount
  -long description
  -double active
  +boolean phone
  -boolean id
  +sendName()
  +getAddress()
  +updateTotal()
}
abstract class Statement {
  -String status
  +double address
  +cancelDuration()
  +createLevel()
  +findAmount()
}
Loan ..> Customer : "0..1"
Statement --> Teller : "0..1"
Teller --* Statement
Interest ..> Customer : "0..1"
Loan --o Card
Beneficiary ..|> Teller
@enduml