@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
class Cart {
  #String amount
  +Date quantity
  -Date level
  +saveUpdatedat()
  +getCreatedat()
  +processPrice()
}
class Review {
  #double updatedAt
  -long type
  +double code
  +double name
  -float email
  +saveQuantity()
  +findStatus()
  +calculateLevel()
  +processPrice()
}
class Product {
  #long email
  #float name
  #Date updatedAt
  +calculateAmount()
}
class Order {
  -long name
  #double status
  +Date level
  +updatePhone()
  +cancelCreatedat()
  +cancelCode()
  +saveScore()
}
class Warehouse {
  -Date active
  -String email
  +findPhone()
  +processType()
  +findUpdatedat()
}
Order ..|> Cart
Review --* Cart
@enduml