@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
abstract class Profile {
  #double type
  -int note
  +double createdAt
  +cancelScore()
}
interface Hashtag {
  +Date email
  -String createdAt
  #float note
  -float quantity
  #double duration
  +processNote()
}
class Message {
  +Date level
  #Date description
  +processCreatedat()
  +updateName()
  +validateNote()
  +deleteName()
}
class Story {
  -Date total
  #Date createdAt
  -String note
  #boolean address
  -Date amount
  +deleteScore()
  +findUpdatedat()
  +createAmount()
}
class Report {
  #boolean duration
  -float createdAt
  +saveCode()
  +deletePrice()
}
Story --> Hashtag : "0..1"
Profile --> Story : "1"
Hashtag --> Report : "*"
@enduml