@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
class CheckIn {
  +boolean quantity
  +Date amount
  +int price
  +cancelLevel()
  +getType()
}
class CheckOut {
  #double status
  #int updatedAt
  +boolean address
  +sendPhone()
  +setQuantity()
  +calculateScore()
}
class Room {
  -long id
  +boolean amount
  +validateCode()
  +processAmount()
  +sendNote()
}
interface Invoice {
  #String address
  +Date active
  -int description
  -float createdAt
  +findId()
  +cancelCreatedat()
  +processDuration()
}
class Guest {
  #float quantity
  +String code
  #long description
  +Date email
  #long createdAt
  +setQuantity()
  +setAmount()
}
CheckOut ..|> Invoice
CheckIn ..> Guest : "1"
Guest --> Room : "*"
Guest --> CheckIn : "1..*"
@enduml