@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam ArrowColor #555555
abstract class User {
  #boolean duration
  +double status
  +calculateAddress()
  +getStatus()
  +createTotal()
}
abstract class Follower {
  -double price
  +Date description
  +calculateNote()
  +validateCreatedat()
}
class Message {
  #String status
  +long note
  -double code
  #String level
  -boolean type
  +createNote()
  +processTotal()
  +cancelAmount()
}
abstract class Profile {
  #long quantity
  +boolean code
  +processUpdatedat()
  +findAddress()
  +validateNote()
  +createScore()
}
class Hashtag {
  +double phone
  #boolean quantity
  -int email
  +Date score
  +long code
  +calculateStatus()
  +updateAmount()
  +cancelAmount()
  +setScore()
}
class Report {
  +boolean type
  #long score
  #int status
  #float total
  +updateQuantity()
  +findPhone()
  +processLevel()
  +setAmount()
}
class Comment {
  -boolean name
  -int id
  -double active
  #int createdAt
  +long description
  +processUpdatedat()
  +cancelActive()
}
Message --> Hashtag : "*"
Comment --* Report
Hashtag --o User
Hashtag --* Report
@enduml