@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
abstract class Branch {
  +long duration
  -String code
  +deleteActive()
  +deleteDuration()
}
class Loan {
  +long description
  -int level
  +Date score
  #String type
  +String id
  +setDescription()
  +sendQuantity()
  +sendScore()
  +cancelPhone()
}
interface Publisher {
  -float type
  +float amount
  +boolean email
  #double duration
  -Date price
  +createNote()
  +findScore()
}
abstract class Member {
  -float address
  -int status
  #boolean note
  #float id
  +sendStatus()
  +setNote()
}
Member ..|> Loan
Member --> Publisher : "*"
Member ..|> Branch
@enduml