@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
abstract class Post {
  #float address
  #int code
  -int duration
  #Date score
  +getId()
  +cancelEmail()
  +sendType()
}
class Notification {
  +double duration
  +boolean score
  +setId()
  +processActive()
}
class Group {
  -int quantity
  -long amount
  #Date description
  -float active
  -Date total
  +getLevel()
  +setStatus()
  +setNote()
  +processCreatedat()
}
class Album {
  +String name
  +boolean score
  +deleteTotal()
  +validateDuration()
  +calculateNote()
}
class Report {
  +long amount
  -double quantity
  #Date type
  +savePrice()
  +validateAddress()
  +processCreatedat()
}
abstract class User {
  #int duration
  +boolean email
  +getNote()
  +cancelEmail()
  +saveAddress()
}
Album --o Notification
Report --* Album
User --* Notification
note right of Post : Social Media domain
@enduml