@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
class Room {
  #boolean price
  +int amount
  +int name
  +deletePhone()
}
interface CheckOut {
  -float code
  #double updatedAt
  +sendQuantity()
  +sendActive()
  +processLevel()
}
class CheckIn {
  #boolean createdAt
  #boolean id
  +float price
  -float note
  +getDescription()
  +deleteUpdatedat()
}
interface Housekeeping {
  +int createdAt
  #String id
  +getNote()
  +updateAddress()
}
class Guest {
  +float email
  -String level
  +boolean name
  +float type
  #double id
  +getQuantity()
  +getType()
  +calculateAddress()
  +sendName()
}
Guest --o CheckOut
CheckOut ..|> CheckIn
Room --* Housekeeping
@enduml