@startuml
skinparam ArrowColor #555555
abstract class Teller {
  +double total
  -int status
  -String active
  #float type
  +long createdAt
  +sendUpdatedat()
}
abstract class Customer {
  +Date active
  #long id
  #double total
  +float type
  +float name
  +getCreatedat()
  +updateScore()
}
class Interest {
  -double score
  #float description
  #float updatedAt
  +Date code
  +validateLevel()
  +findNote()
  +deleteStatus()
}
interface Loan {
  -Date createdAt
  -String quantity
  #float amount
  #boolean description
  #int active
  +setCode()
  +cancelId()
}
class Beneficiary {
  #boolean createdAt
  +int id
  -int code
  #boolean status
  +sendEmail()
  +processLevel()
  +processQuantity()
  +calculateNote()
}
abstract class Deposit {
  +String status
  -int email
  +String active
  #Date duration
  +setQuantity()
  +setAmount()
  +findCreatedat()
  +createDescription()
}
class Branch {
  +float level
  -Date description
  -String total
  +updateDuration()
  +processAddress()
}
Loan --o Deposit
Deposit --* Branch
@enduml