@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
interface Comment {
  #int updatedAt
  #boolean price
  +calculateCreatedat()
  +saveLevel()
}
interface Notification {
  -float duration
  +double createdAt
  #String score
  #double type
  #int price
  +cancelCode()
  +setQuantity()
}
interface Profile {
  +boolean score
  -boolean address
  +saveType()
  +setNote()
  +createActive()
}
interface Post {
  +boolean status
  +long code
  +String createdAt
  +setCode()
  +cancelDescription()
  +processPhone()
}
class User {
  -int note
  +boolean total
  +Date updatedAt
  #String price
  +setLevel()
  +findAmount()
}
interface Group {
  -int updatedAt
  #int code
  +long name
  +String phone
  +sendStatus()
}
User --o Comment
User ..|> Group
@enduml