@startuml
skinparam monochrome true
skinparam ArrowColor #555555
abstract class Teller {
  +int name
  -float level
  +long type
  +saveCreatedat()
  +calculatePrice()
}
abstract class Transaction {
  -float description
  -long level
  +Date createdAt
  #String amount
  +validateType()
  +cancelQuantity()
  +updateDuration()
}
class Account {
  -Date description
  -float updatedAt
  +calculateAddress()
  +updateUpdatedat()
}
abstract class Transfer {
  +int code
  -boolean description
  +sendCreatedat()
}
abstract class Beneficiary {
  -boolean id
  +double type
  +Date duration
  +float total
  +sendLevel()
  +sendType()
  +findAddress()
  +createUpdatedat()
}
Transfer --o Transaction
Account ..|> Transaction
@enduml