@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
interface Booking {
  -Date duration
  #int score
  #double phone
  #int active
  #String createdAt
  +cancelStatus()
  +setCreatedat()
}
abstract class Restaurant {
  -Date description
  -double type
  -Date status
  +sendAmount()
  +getUpdatedat()
}
class Invoice {
  #double phone
  +float id
  #Date duration
  +createId()
  +cancelDescription()
  +cancelAmount()
}
class Service {
  #boolean type
  -float code
  -Date active
  #Date score
  +setPrice()
  +getName()
  +sendStatus()
  +findName()
}
interface Reservation {
  #long updatedAt
  +Date active
  -float level
  +saveQuantity()
  +createAddress()
}
class Room {
  #int phone
  #Date total
  +findCreatedat()
  +findAddress()
  +deletePhone()
}
class CheckOut {
  #float address
  #long updatedAt
  -boolean id
  +updateActive()
  +setQuantity()
  +getDuration()
  +findPrice()
}
Reservation --o CheckOut
CheckOut --> Invoice : "1"
@enduml