@startuml
skinparam monochrome true
class Interest {
  #String score
  #String address
  -double email
  #int price
  +sendStatus()
  +calculatePrice()
  +sendEmail()
}
interface Transfer {
  -int status
  #boolean id
  -String note
  -float email
  +float duration
  +getCreatedat()
  +validateNote()
  +getDescription()
  +deleteType()
}
abstract class Card {
  #long description
  -Date id
  +processName()
  +processLevel()
  +setPhone()
}
class Transaction {
  -double code
  #float id
  #float address
  +float amount
  +getPrice()
}
class Branch {
  #String amount
  -float price
  +float description
  -float active
  +Date type
  +createCreatedat()
  +processLevel()
}
class Deposit {
  #long address
  -int code
  -double score
  +float createdAt
  -int status
  +validateEmail()
  +cancelAddress()
  +processUpdatedat()
  +setAddress()
}
Transaction --o Deposit
Transaction --|> Branch
@enduml