@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
class Profile {
  +long createdAt
  +double status
  #double code
  +Date email
  +calculateNote()
  +sendActive()
  +saveDescription()
  +updatePrice()
}
abstract class Report {
  +String id
  #boolean code
  +long updatedAt
  -String createdAt
  +getName()
  +validateScore()
  +validateCreatedat()
}
class Follower {
  #long phone
  #Date note
  #boolean quantity
  #String email
  -String createdAt
  +setAmount()
  +processType()
}
abstract class Story {
  +boolean code
  -long active
  +getCode()
  +sendType()
  +processEmail()
}
abstract class Hashtag {
  +boolean amount
  +Date level
  +findAmount()
  +getPrice()
  +calculateId()
  +updateEmail()
}
interface Notification {
  #float updatedAt
  +String quantity
  +String address
  -boolean code
  +findNote()
  +validatePhone()
}
Report --|> Hashtag
Notification --o Profile
Story ..> Follower : "1..*"
Notification --> Follower : "1..*"
@enduml