@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
class Branch {
  +int description
  -Date level
  +String duration
  +Date active
  +validateTotal()
  +sendAmount()
  +calculateName()
}
class Loan {
  -Date price
  -long note
  +calculateAmount()
  +calculateCode()
}
interface Transfer {
  -String score
  -float total
  +setDescription()
  +validateActive()
}
class Teller {
  #long price
  #boolean level
  +calculateStatus()
}
abstract class Interest {
  +boolean score
  +float type
  #double amount
  -Date duration
  +float level
  +updateEmail()
  +findId()
  +updateCreatedat()
  +getAddress()
}
Loan ..> Transfer : "*"
Transfer --o Teller
Branch --> Teller : "1..*"
@enduml