@startuml
skinparam defaultFontSize 13
class Payment {
  +String duration
  -long total
  +boolean score
  +Date active
  +boolean id
  +cancelName()
  +createActive()
  +createDescription()
}
class Reservation {
  -long level
  -int status
  #String active
  +float quantity
  +long phone
  +validateNote()
  +processLevel()
}
interface Guest {
  -float phone
  #double email
  +boolean level
  -double quantity
  -long id
  +findEmail()
  +getScore()
  +processEmail()
}
class Restaurant {
  -Date id
  +double name
  #int amount
  #long quantity
  -int description
  +deleteAddress()
  +updateStatus()
  +createUpdatedat()
}
class Room {
  #float phone
  #double total
  +long score
  -String id
  +cancelActive()
  +cancelNote()
  +deleteCreatedat()
  +createAddress()
}
Reservation ..> Room : "1"
Guest --o Room
@enduml