@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
class Category {
  +double type
  +long amount
  #boolean description
  +calculateAmount()
}
abstract class Invoice {
  +int duration
  -int id
  #double createdAt
  +String amount
  +saveActive()
  +validateQuantity()
  +processDescription()
}
interface Return {
  #float type
  -float score
  -int duration
  -String id
  +validateCreatedat()
  +createCode()
  +sendName()
}
class Shipment {
  -double updatedAt
  +Date quantity
  #boolean total
  +float name
  +findDescription()
}
Shipment ..|> Return
Shipment ..|> Category
@enduml