@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Statement {
  #Date email
  #String duration
  #double score
  +updateCode()
  +processLevel()
}
class Beneficiary {
  +float level
  #int phone
  +double active
  +Date total
  #double quantity
  +createActive()
}
abstract class Withdrawal {
  +long score
  -long description
  -Date amount
  +deleteStatus()
  +cancelType()
  +processCreatedat()
  +cancelPhone()
}
class Deposit {
  #int active
  #String status
  +int createdAt
  +updateDuration()
  +validateLevel()
}
abstract class Account {
  #long note
  +String status
  -double total
  +getScore()
  +getStatus()
}
interface Loan {
  #double code
  #int createdAt
  +String email
  #long updatedAt
  +String phone
  +setUpdatedat()
  +createQuantity()
  +createTotal()
  +sendDescription()
}
Loan ..> Account : "*"
Withdrawal ..|> Deposit
@enduml