@startuml
skinparam monochrome true
skinparam defaultFontSize 11
interface Profile {
  +float duration
  +int description
  #boolean amount
  -float level
  +findDescription()
  +getDescription()
  +updateTotal()
}
class Message {
  +long level
  +long note
  #float createdAt
  +saveId()
  +processLevel()
}
class Story {
  -int name
  #boolean level
  #Date email
  -int score
  +validateTotal()
}
class User {
  +int level
  +int score
  -double createdAt
  -double duration
  +processStatus()
}
class Like {
  #boolean level
  +double email
  +createDuration()
  +updateCode()
  +getNote()
}
abstract class Comment {
  -double quantity
  +String total
  #double note
  +String type
  -boolean code
  +createNote()
  +validateAddress()
  +createScore()
  +setStatus()
}
interface Notification {
  +boolean amount
  #double createdAt
  #double price
  +String note
  +int quantity
  +savePrice()
  +sendPhone()
}
Comment ..|> User
Story --> Notification : "1..*"
Story --|> User
note right of Profile : Social Media domain
@enduml