@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
abstract class Amenity {
  #String level
  #Date name
  -double description
  #int active
  -String id
  +cancelId()
}
interface Staff {
  +int updatedAt
  #float amount
  #double status
  -String price
  +calculateScore()
  +getQuantity()
  +sendName()
  +setId()
}
class Booking {
  -Date phone
  +int note
  +long name
  #double createdAt
  -boolean id
  +deleteEmail()
  +saveUpdatedat()
  +saveAddress()
}
class Service {
  +boolean total
  +Date phone
  +int email
  +String code
  +calculateName()
}
Amenity ..|> Service
Amenity --o Staff
@enduml