@startuml
skinparam shadowing true
class Billing {
  #String score
  #String phone
  #double code
  #boolean email
  -double quantity
  +createActive()
  +deleteId()
}
class LabTest {
  #String score
  -float duration
  -String id
  #long total
  +savePrice()
  +sendDuration()
  +createCreatedat()
  +deleteCreatedat()
}
class Appointment {
  #boolean amount
  +boolean address
  +Date email
  +updateScore()
}
interface Insurance {
  +float type
  #String level
  +deleteId()
}
interface Nurse {
  +float updatedAt
  -boolean name
  +createScore()
  +validateId()
  +processCreatedat()
  +createTotal()
}
LabTest --o Insurance
Nurse --> Appointment : "0..1"
Billing ..> Appointment : "1"
Appointment --* Nurse
@enduml