@startuml
skinparam ArrowColor #555555
interface Hospital {
  #String updatedAt
  #long note
  #Date name
  +getAddress()
}
class Diagnosis {
  #String email
  +double quantity
  -float note
  #int total
  +calculateStatus()
  +getStatus()
}
interface Patient {
  +double status
  #double updatedAt
  -long createdAt
  +String name
  -float id
  +cancelId()
}
class MedicalRecord {
  #long duration
  -boolean id
  #double note
  -int total
  -String score
  +saveQuantity()
  +deleteCreatedat()
}
Diagnosis --o Patient
Diagnosis ..> MedicalRecord : "1"
@enduml