@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
class Booking {
  #long type
  -int score
  -double description
  +float address
  +deleteEmail()
}
class Restaurant {
  -String address
  +long id
  +boolean total
  +sendDuration()
}
class CheckOut {
  +long status
  -boolean note
  -boolean name
  -double type
  +calculateId()
}
class Service {
  +boolean note
  -int type
  +long phone
  #String price
  +saveAmount()
}
CheckOut ..> Booking : "1"
Restaurant --> CheckOut : "1"
@enduml