@startuml
skinparam shadowing true
class Like {
  +String address
  #boolean quantity
  +validateDuration()
}
class Story {
  -String total
  -boolean email
  +int price
  -int name
  -int createdAt
  +saveAddress()
  +calculateId()
  +calculateActive()
  +deletePrice()
}
class Notification {
  +long description
  #float score
  +long email
  #Date active
  +createAddress()
  +savePrice()
}
interface Comment {
  +boolean address
  +boolean phone
  #float quantity
  +int active
  +sendPhone()
  +createName()
}
abstract class Group {
  -float quantity
  +long price
  +cancelDuration()
  +calculateStatus()
  +saveTotal()
  +deleteTotal()
}
class Message {
  -String level
  +String price
  +int note
  +findNote()
  +findTotal()
  +sendId()
  +setCreatedat()
}
Message --o Story
Notification ..> Group : "1"
Story ..> Group : "1..*"
Like --|> Comment
@enduml