@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
interface Card {
  -boolean note
  -int address
  #float description
  -boolean code
  -double type
  +getUpdatedat()
}
class Deposit {
  -int address
  -String id
  +setType()
  +createCode()
  +validateStatus()
  +deleteUpdatedat()
}
interface Statement {
  #boolean status
  -int id
  +float active
  +saveId()
}
class Teller {
  -long amount
  #double id
  +findScore()
}
class Customer {
  -boolean price
  #Date duration
  +setDuration()
  +sendLevel()
}
Card --|> Teller
Teller --|> Card
Deposit ..> Teller : "0..1"
Statement --|> Teller
@enduml