@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Librarian {
  -Date description
  #double quantity
  +int note
  -float type
  +saveUpdatedat()
}
abstract class Member {
  +boolean duration
  -Date id
  #String price
  -double description
  +processLevel()
}
interface Publisher {
  +long type
  #Date phone
  #boolean updatedAt
  #Date total
  #float score
  +saveTotal()
  +validateId()
}
abstract class Loan {
  -boolean phone
  -String score
  +int name
  +setAmount()
}
interface Renewal {
  +int duration
  -int description
  #Date type
  +updateActive()
  +getPhone()
  +updateDescription()
  +processType()
}
Loan ..> Publisher : "0..1"
Renewal ..> Member : "1..*"
Librarian --> Publisher : "1..*"
@enduml