@startuml
skinparam defaultFontSize 11
class Exam {
  +int id
  -Date address
  +String level
  #float duration
  -boolean active
  +calculateUpdatedat()
  +saveStatus()
  +saveName()
  +validateId()
}
class Department {
  #int createdAt
  -long score
  #int level
  +findLevel()
  +saveName()
}
interface Library {
  #double phone
  #Date name
  +createName()
  +deleteUpdatedat()
  +processAmount()
}
interface Teacher {
  -double duration
  +double updatedAt
  #long score
  +long status
  +saveEmail()
  +updateLevel()
  +saveUpdatedat()
}
class Assignment {
  +boolean price
  #int name
  -boolean createdAt
  -double score
  +getPhone()
  +calculateCode()
}
Assignment ..|> Department
Library --o Exam
Teacher --|> Library
Exam --* Department
@enduml