@startuml
skinparam shadowing true
interface Return {
  #float price
  -long phone
  -int quantity
  +getTotal()
  +getType()
  +sendPrice()
  +deleteUpdatedat()
}
class Category {
  -boolean price
  +float description
  #double status
  +long note
  -float name
  +validateScore()
}
abstract class Cart {
  +Date active
  -long description
  #float status
  +long updatedAt
  -float id
  +getAddress()
  +createCreatedat()
  +savePhone()
  +setScore()
}
class Shipment {
  -Date address
  +int score
  +processLevel()
  +processPrice()
  +cancelUpdatedat()
}
class Coupon {
  +int note
  #double type
  +double duration
  #boolean status
  #Date phone
  +createStatus()
  +getDescription()
  +calculatePhone()
  +cancelName()
}
class Order {
  +boolean quantity
  #Date duration
  +getCode()
}
class Warehouse {
  -boolean total
  +double duration
  +long phone
  +createDuration()
  +validateStatus()
}
Return ..> Category : "*"
Cart --o Category
Return --* Warehouse
Category ..> Return : "0..1"
Return ..|> Shipment
@enduml