@startuml
skinparam monochrome true
skinparam ArrowColor #555555
abstract class User {
  #long type
  -int phone
  #long email
  #double createdAt
  +Date status
  +updateStatus()
  +findId()
  +setQuantity()
  +processCreatedat()
}
abstract class Album {
  -int score
  #boolean address
  +validateUpdatedat()
  +calculateAddress()
  +getId()
  +findDuration()
}
class Post {
  #double active
  +int address
  #float id
  +long name
  +getName()
  +sendLevel()
  +saveUpdatedat()
}
class Profile {
  -Date total
  #Date duration
  +calculateDescription()
  +findDescription()
  +getCreatedat()
  +cancelNote()
}
Album --|> Profile
Profile --o User
@enduml