@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
interface Notification {
  +Date total
  -int price
  +boolean amount
  -Date id
  +findActive()
}
class Comment {
  +int id
  -boolean code
  #int email
  -int note
  +int duration
  +processScore()
  +sendScore()
  +validateUpdatedat()
}
class Follower {
  -boolean name
  -boolean description
  #long active
  +processDescription()
  +sendUpdatedat()
}
interface Report {
  +double duration
  -long total
  +sendName()
}
interface User {
  #long description
  #double address
  +cancelLevel()
}
User ..> Report : "1..*"
User --* Follower
note right of Notification : Social Media domain
@enduml