@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
class Invoice {
  +Date description
  +boolean active
  +cancelQuantity()
  +deleteCreatedat()
  +setQuantity()
}
abstract class Cart {
  -boolean id
  +String status
  #int score
  +double code
  +processUpdatedat()
  +validateUpdatedat()
  +deleteAmount()
  +validateStatus()
}
class Review {
  -int address
  -float score
  +deleteActive()
  +getScore()
  +calculateAmount()
  +createPrice()
}
class Order {
  -boolean email
  #int quantity
  +boolean duration
  #double createdAt
  +createType()
}
interface Coupon {
  -int active
  +float name
  +findId()
}
abstract class Product {
  +double type
  #Date quantity
  +long code
  +findQuantity()
  +calculateId()
  +getCode()
}
class Supplier {
  #int status
  #double description
  +updateActive()
  +sendCode()
  +updateAmount()
  +calculateNote()
}
Supplier ..> Invoice : "1"
Order --* Review
Order --o Supplier
@enduml