@startuml
skinparam ArrowColor #555555
class Shelf {
  -boolean phone
  -int description
  #Date quantity
  +getCreatedat()
  +sendStatus()
}
class Renewal {
  +String name
  #boolean code
  +boolean createdAt
  -int phone
  #Date email
  +getLevel()
  +updateId()
  +createId()
}
class Loan {
  #long email
  -String id
  -long active
  +long duration
  +validatePrice()
  +calculateCode()
}
class Branch {
  -long name
  #int address
  +deleteName()
}
class Book {
  -Date status
  #float code
  -int address
  -int email
  +setPhone()
  +cancelName()
  +validateAmount()
  +sendScore()
}
Branch --|> Book
Shelf --> Loan : "0..1"
Shelf --> Renewal : "0..1"
Branch --o Loan
@enduml