@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
class Assignment {
  #long status
  #Date total
  -int level
  +setScore()
}
class Exam {
  +double duration
  -int address
  -String active
  -Date total
  +double updatedAt
  +calculatePrice()
  +setEmail()
}
abstract class Grade {
  #double phone
  -long id
  #Date active
  +long type
  -long code
  +setEmail()
}
class Student {
  #double type
  #float code
  +calculateUpdatedat()
  +calculatePrice()
}
class Teacher {
  +long status
  #String phone
  -int active
  +sendDuration()
  +createDescription()
}
class Library {
  +boolean name
  -long phone
  #float amount
  #long price
  +boolean code
  +findCode()
  +createPhone()
  +getStatus()
  +deleteName()
}
class Course {
  #int amount
  #float type
  -int quantity
  +setAmount()
  +deleteAmount()
}
Library ..|> Course
Teacher ..> Grade : "1"
Exam ..> Library : "1..*"
Student --o Course
Student --o Exam
@enduml