@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
interface Payment {
  -int score
  +Date updatedAt
  +processType()
  +getLevel()
  +saveCode()
  +deleteTotal()
}
interface Invoice {
  -boolean name
  #String type
  +float description
  -boolean amount
  +processAddress()
  +processEmail()
  +processEmail()
}
abstract class Wishlist {
  #double amount
  -int note
  #double name
  +deleteTotal()
}
abstract class Return {
  #double createdAt
  #String active
  -int price
  +processUpdatedat()
  +processAmount()
  +savePrice()
}
class Coupon {
  -int level
  -boolean note
  +calculateEmail()
}
class Shipment {
  +Date createdAt
  +int code
  -boolean name
  -Date id
  -String active
  +cancelUpdatedat()
}
class Cart {
  -double score
  -double updatedAt
  +double duration
  +deleteCode()
  +createName()
  +findDescription()
}
Shipment ..|> Return
Cart ..> Coupon : "*"
Wishlist --o Return
Payment --|> Cart
Coupon ..> Invoice : "0..1"
Wishlist --|> Invoice
note right of Payment : Ecommerce domain
@enduml