@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
class Invoice {
  +int status
  #int code
  +cancelTotal()
  +findActive()
  +createPhone()
}
interface Customer {
  -int amount
  +int email
  +Date active
  -String level
  -boolean type
  +updateUpdatedat()
}
class Supplier {
  #long email
  #double name
  -String duration
  +float createdAt
  +Date address
  +validateAmount()
  +processPhone()
  +updateAddress()
  +validateName()
}
abstract class Category {
  -String id
  #boolean total
  #int duration
  -int updatedAt
  +cancelCreatedat()
}
class Payment {
  #Date active
  #long address
  #double quantity
  #long level
  +setAmount()
  +sendId()
  +processNote()
  +processCreatedat()
}
interface Return {
  -double phone
  +float active
  #Date total
  +deleteName()
  +savePrice()
  +updateDescription()
  +createLevel()
}
abstract class Order {
  #float note
  -int amount
  -int level
  #float code
  +setId()
}
Invoice --* Category
Order ..|> Category
Payment ..|> Order
@enduml