@startuml
skinparam defaultFontSize 11
class Assignment {
  -int email
  #long phone
  -boolean address
  -double status
  +double createdAt
  +setScore()
  +sendAmount()
  +setCreatedat()
  +findStatus()
}
class Department {
  -float duration
  #int code
  +setPhone()
  +updateCreatedat()
  +findAmount()
}
class Library {
  #double amount
  #boolean active
  -int score
  -boolean createdAt
  -boolean id
  +getTotal()
}
class Book {
  #String amount
  -float name
  +validateTotal()
}
interface Teacher {
  -Date description
  -long phone
  #boolean status
  +boolean note
  #int id
  +validateUpdatedat()
  +sendCode()
  +createAddress()
}
Assignment ..> Library : "1"
Assignment ..|> Department
Teacher ..> Assignment : "*"
@enduml