@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
class Profile {
  #int description
  -boolean id
  +updateType()
}
class Follower {
  -double price
  -boolean score
  #float description
  +String type
  +deleteTotal()
  +deleteLevel()
}
interface Like {
  -String email
  +double note
  +long updatedAt
  +saveStatus()
  +validateAddress()
}
class Comment {
  #boolean email
  #String price
  +boolean note
  +createType()
  +deleteNote()
  +createUpdatedat()
  +updateCode()
}
class Group {
  #long price
  #long createdAt
  #Date id
  #long type
  +calculateDescription()
  +saveLevel()
}
Follower --* Group
Comment --|> Group
Group --> Comment : "1..*"
Like --|> Comment
@enduml