@startuml
skinparam defaultFontSize 11
interface Ward {
  +float level
  -String quantity
  -int type
  -int createdAt
  #double duration
  +cancelName()
  +findCreatedat()
  +sendDuration()
}
class Insurance {
  #boolean amount
  +Date total
  -Date updatedAt
  -float address
  +deleteType()
}
interface MedicalRecord {
  -int score
  #double total
  -double code
  #int amount
  +findUpdatedat()
  +updatePrice()
  +processCode()
  +findTotal()
}
class Appointment {
  #int status
  -Date quantity
  -float email
  +updateUpdatedat()
}
Appointment --* Ward
Appointment ..> MedicalRecord : "0..1"
Insurance ..|> MedicalRecord
@enduml