@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
abstract class User {
  +double name
  -boolean status
  +long id
  +setId()
  +validateLevel()
  +createNote()
  +cancelAddress()
}
class Story {
  -long active
  +String type
  +deleteCreatedat()
  +calculateDescription()
}
abstract class Album {
  #boolean price
  -boolean duration
  +boolean active
  +boolean status
  +getDuration()
  +deleteAmount()
  +sendDescription()
}
class Profile {
  -long price
  #int createdAt
  +String code
  +long active
  +Date email
  +validateTotal()
  +saveCreatedat()
}
class Report {
  +float duration
  -boolean code
  +Date email
  #int quantity
  +cancelName()
}
class Like {
  +boolean level
  #Date note
  +cancelId()
  +findDescription()
  +updateLevel()
}
class Group {
  #int quantity
  +boolean updatedAt
  +String phone
  #boolean address
  +getType()
  +findStatus()
  +calculateCode()
  +cancelAddress()
}
Report --* Group
Profile --|> Album
Album ..> User : "0..1"
User --> Album : "*"
Like ..> User : "1..*"
Like --|> Report
note right of User : Social Media domain
@enduml