@startuml

class Teacher {
  -double phone
  #Date status
  #double code
  +saveActive()
  +setAddress()
  +validateDuration()
}
class Department {
  +float duration
  +boolean price
  +double phone
  #double score
  -String level
  +setId()
}
abstract class Exam {
  +double createdAt
  #long note
  #String quantity
  #long amount
  -double type
  +setScore()
  +deleteQuantity()
}
class Assignment {
  +String total
  +float id
  +Date level
  +findNote()
  +getUpdatedat()
}
class Student {
  -float id
  -long duration
  +float amount
  #String code
  -int createdAt
  +updateCode()
}
Student --o Teacher
Department --* Student
Teacher ..> Exam : "1..*"
Exam --* Assignment
@enduml