@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
class Branch {
  -float description
  -String score
  -boolean quantity
  +validateStatus()
  +cancelScore()
}
class Account {
  #String score
  +double duration
  +cancelTotal()
  +findActive()
  +createCode()
}
class Beneficiary {
  #double status
  +long score
  +sendActive()
  +sendPhone()
  +saveType()
  +updateStatus()
}
abstract class Withdrawal {
  -long duration
  +int description
  -float email
  +saveAmount()
}
class Loan {
  -boolean name
  -float duration
  +int email
  -long updatedAt
  #long total
  +getPrice()
}
Account --> Beneficiary : "1..*"
Branch --o Loan
Beneficiary --* Account
@enduml