@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
interface Profile {
  +String level
  -double note
  -int quantity
  #double address
  +String id
  +processNote()
  +createAmount()
}
class Story {
  -int code
  #String duration
  +getType()
  +calculateDescription()
  +sendType()
  +processScore()
}
abstract class Notification {
  +String code
  #float updatedAt
  +processCode()
}
class Hashtag {
  -int address
  #boolean createdAt
  #float code
  -long updatedAt
  -Date status
  +deleteUpdatedat()
  +calculatePhone()
}
Notification --|> Hashtag
Profile --> Story : "1"
@enduml