@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
abstract class Profile {
  #int code
  +float duration
  -long total
  -double active
  +validateUpdatedat()
}
class Like {
  +float level
  +double price
  +Date amount
  +validateDuration()
  +findTotal()
  +deleteCode()
  +sendType()
}
interface Notification {
  -float status
  +long code
  +float phone
  -Date score
  #Date active
  +deleteDescription()
  +deleteStatus()
}
interface Album {
  +boolean code
  +int address
  -Date active
  +findScore()
  +setAmount()
  +createScore()
}
Notification ..|> Like
Notification --* Profile
@enduml