@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
abstract class Group {
  +double duration
  +String id
  +long status
  +validateLevel()
  +updateNote()
  +sendScore()
}
interface Message {
  #Date name
  #String duration
  +boolean updatedAt
  +String note
  +double level
  +saveUpdatedat()
}
interface Notification {
  -float score
  -double id
  #int name
  +long note
  #double total
  +deleteQuantity()
}
abstract class Story {
  +int amount
  #boolean createdAt
  -long note
  +Date email
  +calculateCode()
  +createEmail()
}
abstract class Post {
  +double total
  +float description
  -int phone
  +validateLevel()
  +setCreatedat()
  +processAmount()
}
Notification --o Message
Group ..> Post : "1"
@enduml