@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
class Like {
  -String updatedAt
  -long type
  +double phone
  +saveNote()
  +sendActive()
}
class Story {
  #int description
  #float type
  +findScore()
  +cancelDescription()
  +createName()
  +calculateCode()
}
class Album {
  -float quantity
  #float name
  +processQuantity()
  +calculateActive()
}
class Post {
  #long note
  +Date active
  -float level
  -boolean email
  +updateUpdatedat()
  +updateName()
  +updateAmount()
}
class Report {
  #double status
  +double price
  #int email
  +sendQuantity()
  +getAmount()
  +deleteTotal()
  +deleteCreatedat()
}
Post --o Report
Report ..|> Post
Report --> Album : "*"
@enduml