@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
class Payment {
  +long description
  +float status
  -float price
  +createScore()
  +cancelAmount()
  +sendTotal()
  +cancelNote()
}
class Cart {
  #float type
  #float level
  +int name
  +double description
  +updateUpdatedat()
  +cancelNote()
}
interface Invoice {
  #String price
  +String name
  +int updatedAt
  +String note
  -float description
  +deleteId()
  +calculateId()
  +sendPhone()
  +findEmail()
}
class Product {
  #double duration
  #int createdAt
  +boolean updatedAt
  -Date status
  +updateDuration()
  +calculateUpdatedat()
  +createTotal()
}
class Supplier {
  -boolean email
  +int createdAt
  +float id
  -Date note
  +cancelScore()
}
abstract class Order {
  #boolean type
  +boolean active
  #float updatedAt
  #float address
  +saveStatus()
}
Product --* Payment
Supplier --* Product
@enduml