@startuml
skinparam defaultFontSize 13
interface Reservation {
  #String score
  #int price
  #int name
  -long email
  +findTotal()
}
interface Book {
  -int active
  -Date email
  +validateActive()
}
interface Librarian {
  +int id
  -int quantity
  +sendAddress()
}
interface Publisher {
  +String address
  +double score
  #Date amount
  +cancelUpdatedat()
  +calculatePhone()
  +getDuration()
  +deleteName()
}
class Fine {
  #Date note
  +long status
  -double code
  +Date level
  #float type
  +savePhone()
}
Book --o Publisher
Reservation --|> Librarian
@enduml