@startuml
skinparam monochrome true
skinparam defaultFontSize 11
interface Beneficiary {
  #Date id
  +long status
  +deletePhone()
  +cancelPrice()
}
class Transfer {
  +boolean description
  #int createdAt
  #double quantity
  #int phone
  -double code
  +calculateCreatedat()
  +createAmount()
  +validateStatus()
}
class Statement {
  #boolean phone
  #long note
  +processScore()
}
class Card {
  #Date address
  -String code
  #long score
  +String duration
  -String name
  +setPrice()
  +setAmount()
}
Transfer --|> Statement
Transfer --> Beneficiary : "*"
@enduml