@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
class Publisher {
  +long address
  #String amount
  +int duration
  +processType()
  +findUpdatedat()
}
class Catalog {
  +long id
  #int status
  +long duration
  -double score
  +processEmail()
  +deleteScore()
  +calculateName()
}
interface Librarian {
  +boolean duration
  +long amount
  +validateEmail()
  +calculateAmount()
  +cancelType()
}
class Reservation {
  #Date address
  -int createdAt
  -int updatedAt
  +deleteDescription()
  +saveType()
  +createPhone()
}
class Book {
  +float createdAt
  #boolean status
  -int note
  #long updatedAt
  +setCode()
}
abstract class Author {
  #Date level
  -long type
  -Date score
  +boolean status
  +sendId()
  +getDuration()
}
class Fine {
  -int status
  #long description
  +int type
  +calculateNote()
  +getStatus()
}
Reservation ..> Catalog : "*"
Librarian ..|> Publisher
Publisher ..|> Fine
Reservation ..> Book : "0..1"
@enduml