@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
class Course {
  +boolean level
  #float total
  +sendActive()
  +setDuration()
  +setAddress()
}
interface Classroom {
  +String phone
  -long active
  #float note
  -Date total
  +deleteName()
  +findName()
  +processStatus()
  +saveUpdatedat()
}
abstract class Assignment {
  #Date code
  -boolean score
  #String quantity
  #long level
  +findStatus()
  +calculateDuration()
  +sendNote()
  +calculateCode()
}
interface Student {
  -int code
  #double quantity
  +float price
  -boolean address
  +int createdAt
  +cancelCode()
  +sendAmount()
  +sendDuration()
  +processQuantity()
}
interface Book {
  #String total
  +boolean createdAt
  +saveAmount()
}
class Library {
  -boolean note
  -String price
  +validateScore()
}
class Teacher {
  #long name
  -int note
  +Date email
  +getActive()
  +calculateCode()
  +calculateUpdatedat()
  +saveNote()
}
Classroom --* Library
Course --o Library
Teacher --|> Book
@enduml