@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
abstract class Follower {
  #long phone
  +int address
  +createQuantity()
}
interface Hashtag {
  +long active
  -boolean duration
  +cancelLevel()
  +validateAddress()
}
abstract class Report {
  +long score
  #String status
  +validateDuration()
  +deleteDescription()
  +updateLevel()
}
class Notification {
  +boolean note
  #Date code
  +Date quantity
  #int description
  #double phone
  +calculateUpdatedat()
}
class Post {
  -String phone
  +long quantity
  -double amount
  +deletePrice()
  +deleteTotal()
  +updateId()
  +saveNote()
}
Report ..> Follower : "0..1"
Hashtag --* Follower
@enduml