@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
class Report {
  +Date level
  #double note
  #float updatedAt
  +cancelAddress()
}
class Comment {
  #Date quantity
  -float note
  +long amount
  #double level
  #float address
  +validateType()
}
class Follower {
  #long price
  -long note
  -String name
  +boolean address
  +double duration
  +setType()
  +getTotal()
  +saveActive()
}
interface Hashtag {
  -long createdAt
  +boolean active
  -double name
  +findScore()
  +processDescription()
  +setStatus()
  +saveId()
}
class Group {
  #String amount
  -double code
  #boolean status
  -float total
  -long score
  +cancelEmail()
  +saveNote()
  +calculateAddress()
  +getCode()
}
Hashtag ..> Comment : "0..1"
Report ..|> Hashtag
Follower --|> Hashtag
@enduml