@startuml
skinparam defaultFontSize 13
class Service {
  -long total
  -long status
  +createAmount()
}
class Restaurant {
  #float id
  #Date address
  -float duration
  #String score
  +findScore()
}
class CheckIn {
  +int amount
  +double note
  -boolean active
  +boolean price
  +deleteCreatedat()
}
class Amenity {
  +long type
  +float code
  +validateUpdatedat()
}
class Invoice {
  #long address
  +int quantity
  +boolean active
  +updatePhone()
  +getId()
  +validatePrice()
}
Invoice --o Amenity
Service --o Amenity
Restaurant --|> Service
@enduml