@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
class Restaurant {
  +Date type
  +boolean level
  #boolean createdAt
  #long address
  +findId()
}
class Staff {
  #String address
  #float createdAt
  #boolean quantity
  +float amount
  +updateDuration()
}
interface CheckIn {
  -double score
  +int address
  #Date status
  +float name
  -Date total
  +setUpdatedat()
}
abstract class Payment {
  #boolean price
  -double id
  #Date phone
  +cancelPrice()
  +updateQuantity()
  +createType()
}
class CheckOut {
  +boolean address
  +long active
  +findEmail()
  +getCode()
  +calculateTotal()
}
class Room {
  #Date total
  +int active
  #float code
  +cancelUpdatedat()
}
Room --* CheckIn
Payment ..> Staff : "0..1"
@enduml