@startuml
skinparam shadowing true
abstract class Manifest {
  +double name
  +boolean price
  +validateEmail()
  +deleteAddress()
  +createAddress()
}
interface Tracking {
  -int active
  +double score
  -boolean quantity
  +createEmail()
  +setPrice()
}
interface Driver {
  #long quantity
  #Date name
  #String duration
  +updateDuration()
  +deleteScore()
  +createActive()
  +cancelDescription()
}
class Inventory {
  -long duration
  #boolean phone
  #boolean email
  +String active
  +processAddress()
  +calculateLevel()
  +getPrice()
}
interface FuelLog {
  #boolean description
  -Date phone
  -boolean id
  #float createdAt
  #boolean active
  +processAddress()
  +createActive()
}
FuelLog --o Tracking
Tracking --> Inventory : "*"
Tracking ..> Driver : "*"
@enduml