@startuml
skinparam shadowing true
interface Fine {
  -Date description
  +int total
  #String duration
  +long createdAt
  +validateType()
  +saveDescription()
  +createType()
}
class Catalog {
  #String createdAt
  +long id
  +getType()
  +validateAddress()
}
class Reservation {
  +String email
  #String amount
  +processTotal()
  +calculateStatus()
}
class Renewal {
  #String note
  #float level
  -String quantity
  #int id
  +String createdAt
  +findName()
  +updateCode()
  +createType()
}
abstract class Branch {
  #float createdAt
  -float address
  +updateUpdatedat()
  +getNote()
  +getId()
}
class Publisher {
  +Date total
  -Date active
  #double note
  +cancelTotal()
  +sendActive()
  +cancelQuantity()
  +cancelStatus()
}
Reservation --o Catalog
Branch --> Reservation : "0..1"
Renewal ..|> Reservation
Fine --> Reservation : "0..1"
@enduml