@startuml
skinparam monochrome true
skinparam defaultFontSize 13
class Transaction {
  -int note
  #double duration
  #float active
  -boolean createdAt
  #String quantity
  +processDescription()
}
class Interest {
  +Date email
  +Date type
  +deletePhone()
  +getActive()
  +validateAddress()
  +deleteDuration()
}
interface Account {
  +boolean address
  -float email
  +Date type
  #Date score
  #double total
  +calculateNote()
}
class Withdrawal {
  +Date id
  -boolean createdAt
  -double description
  +deleteType()
  +saveDuration()
}
class Statement {
  #Date amount
  -String active
  -boolean description
  +setName()
}
class Customer {
  #float type
  #double description
  +processPrice()
  +setDuration()
}
Withdrawal --o Account
Statement ..|> Customer
Customer ..> Transaction : "*"
Withdrawal --* Statement
@enduml