@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Group {
  #Date createdAt
  #double phone
  #float type
  #int quantity
  +Date level
  +deleteAddress()
  +sendCreatedat()
  +setStatus()
}
abstract class Story {
  #String updatedAt
  +double phone
  -float id
  -Date duration
  +calculateStatus()
}
class Like {
  +String score
  -float price
  #long level
  #String email
  +cancelName()
  +validateAddress()
  +createCreatedat()
}
class Hashtag {
  -boolean id
  +Date score
  -double phone
  +cancelDescription()
}
class Notification {
  #float updatedAt
  +String price
  +int description
  +findName()
  +sendPhone()
  +deleteCreatedat()
  +sendPrice()
}
Like --* Hashtag
Story --|> Hashtag
Hashtag ..> Group : "1..*"
Notification ..> Hashtag : "1..*"
note right of Group : Social Media domain
@enduml