@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
class Room {
  #float active
  -Date description
  -float code
  +sendScore()
  +deleteDuration()
}
abstract class Reservation {
  #double email
  +long name
  -int phone
  #Date price
  #boolean amount
  +processCode()
  +createName()
  +deleteActive()
}
interface CheckIn {
  #String name
  -float id
  -double code
  #long quantity
  +getTotal()
  +deleteDescription()
}
class CheckOut {
  -int name
  -Date note
  +Date total
  +Date updatedAt
  +processStatus()
}
class Staff {
  #long updatedAt
  -long code
  #int price
  -int total
  +boolean score
  +deleteId()
  +findEmail()
  +saveAddress()
}
class Payment {
  #String updatedAt
  -long active
  -long email
  +validateAmount()
  +processCreatedat()
  +deletePrice()
  +findTotal()
}
Reservation ..> Payment : "0..1"
CheckOut --o Reservation
Room --> CheckOut : "*"
@enduml