@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
interface Category {
  #boolean amount
  -Date price
  +createName()
  +validateEmail()
}
interface Shipment {
  +float quantity
  #int amount
  #double score
  #String id
  #boolean type
  +saveAmount()
  +sendNote()
}
class Customer {
  #boolean active
  -String code
  +double total
  -double id
  +processId()
  +saveName()
  +calculateUpdatedat()
  +processAmount()
}
class Invoice {
  -double score
  -int code
  #float address
  #String active
  +sendId()
}
abstract class Wishlist {
  +boolean code
  #int name
  +getUpdatedat()
  +sendDescription()
  +createPhone()
  +cancelCreatedat()
}
Invoice --* Wishlist
Invoice ..|> Customer
Shipment --|> Customer
@enduml