@startuml
skinparam monochrome true
skinparam defaultFontSize 11
class Department {
  -String quantity
  +boolean address
  -double phone
  -String level
  +validateActive()
  +calculateActive()
  +processNote()
}
class Course {
  +Date note
  -boolean score
  #boolean level
  +calculateNote()
  +setScore()
  +setId()
}
class Grade {
  +double address
  -int total
  +sendStatus()
  +getLevel()
  +sendDescription()
}
interface Attendance {
  +Date address
  #int name
  -double amount
  #boolean quantity
  #int code
  +cancelTotal()
  +getPrice()
  +saveScore()
  +processScore()
}
abstract class Book {
  #boolean address
  #double createdAt
  #int description
  +int quantity
  +double phone
  +validateScore()
  +deleteTotal()
  +createName()
}
class Schedule {
  -float price
  +boolean address
  #Date quantity
  +getDuration()
}
class Teacher {
  -Date updatedAt
  +String quantity
  #double type
  +Date email
  +setLevel()
  +createCreatedat()
}
Schedule --o Teacher
Teacher --|> Course
Schedule --> Department : "1"
Course --|> Book
@enduml