@startuml
skinparam shadowing true
class Librarian {
  +Date email
  -float level
  +String duration
  +calculateEmail()
  +setPhone()
  +calculateCreatedat()
  +deletePrice()
}
interface Catalog {
  +boolean updatedAt
  +String id
  -Date total
  +validateTotal()
  +deleteAddress()
  +createStatus()
}
class Author {
  -double name
  +String duration
  +sendCreatedat()
  +sendActive()
}
abstract class Branch {
  #float quantity
  #Date amount
  +saveScore()
  +createActive()
}
abstract class Book {
  +double id
  #int amount
  -long phone
  #Date status
  +calculateAddress()
  +createName()
  +getLevel()
  +findUpdatedat()
}
class Publisher {
  +String duration
  -double score
  +saveDuration()
}
class Renewal {
  +int createdAt
  -Date address
  +findDescription()
}
Librarian --|> Catalog
Book ..> Publisher : "*"
Publisher ..> Renewal : "*"
Catalog ..> Book : "0..1"
Catalog --|> Librarian
@enduml