@startuml

class Group {
  +boolean type
  +double email
  +updateAmount()
  +validateCode()
}
class Post {
  #String updatedAt
  #double address
  #long level
  +Date price
  +validatePrice()
  +processDescription()
  +deleteCreatedat()
  +getUpdatedat()
}
class Message {
  -Date code
  -Date duration
  +processTotal()
  +getEmail()
  +updateLevel()
  +setDuration()
}
class User {
  -double updatedAt
  +float phone
  -float level
  #Date code
  +createDuration()
}
abstract class Hashtag {
  -Date duration
  #String phone
  +Date name
  #float note
  +findName()
  +deletePhone()
  +saveStatus()
  +setId()
}
interface Story {
  #boolean level
  -int id
  +getNote()
  +sendName()
}
interface Comment {
  -double status
  +float description
  +int phone
  #float quantity
  -double price
  +cancelDuration()
  +sendEmail()
}
Story --o Comment
Group --> Hashtag : "1..*"
Story --> Message : "1..*"
Story --* Group
Group ..> Story : "*"
@enduml