@startuml
skinparam defaultFontSize 11
class Statement {
  #String type
  -float score
  +saveQuantity()
  +cancelName()
  +saveLevel()
  +createAmount()
}
class Customer {
  #boolean total
  +double updatedAt
  +float code
  +float address
  +sendPrice()
  +processAddress()
  +validatePrice()
  +setLevel()
}
class Account {
  -double phone
  #int active
  #float createdAt
  -double status
  +findPhone()
  +getUpdatedat()
  +processScore()
}
class Card {
  #boolean active
  -boolean quantity
  #boolean duration
  +long name
  +sendActive()
  +sendLevel()
  +findCreatedat()
  +createUpdatedat()
}
class Deposit {
  +String price
  #boolean id
  +double note
  +setPrice()
}
interface Interest {
  #Date level
  +Date code
  +saveName()
  +saveAddress()
  +createPrice()
  +validateUpdatedat()
}
class Loan {
  #float quantity
  -int status
  -int id
  +double total
  +createLevel()
  +findAddress()
}
Loan --* Card
Interest --o Statement
@enduml