@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
class User {
  -long active
  +float id
  -int total
  -long status
  +sendUpdatedat()
}
class Follower {
  #double note
  #int email
  +getQuantity()
  +sendUpdatedat()
  +validateId()
  +setId()
}
class Group {
  #long total
  #int status
  +setAmount()
  +saveName()
  +validateLevel()
  +setCreatedat()
}
class Message {
  #boolean address
  -float active
  #Date updatedAt
  -int code
  +sendDuration()
  +findName()
  +saveCreatedat()
  +validateNote()
}
class Album {
  +int active
  +boolean type
  +findPhone()
}
Follower ..|> Album
Album --> Follower : "1..*"
User --> Message : "1..*"
@enduml