@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
abstract class Story {
  -long type
  -long email
  -Date score
  +updatePhone()
  +calculateAddress()
  +processActive()
}
class Report {
  #long description
  #Date amount
  +double name
  -String code
  #double email
  +deleteEmail()
}
class Hashtag {
  -Date address
  #String type
  +long description
  #double active
  +getPrice()
  +createAmount()
  +getScore()
}
interface Profile {
  #float amount
  -float phone
  +int type
  +deletePhone()
}
interface User {
  #double name
  +Date phone
  #long active
  #float amount
  +findNote()
  +findActive()
}
interface Message {
  +Date duration
  -double createdAt
  +double price
  +saveUpdatedat()
  +saveEmail()
  +cancelNote()
}
abstract class Post {
  -long code
  #float quantity
  +createId()
  +validatePhone()
  +processCode()
}
User --|> Message
User --* Report
Profile --* Hashtag
User --o Hashtag
Post --|> Hashtag
Post --* Message
note right of Story : Social Media domain
@enduml