@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
class Message {
  #Date duration
  +long email
  +double score
  #double address
  +Date amount
  +processId()
  +processAddress()
  +cancelActive()
}
abstract class Comment {
  #String score
  -boolean type
  +updatePrice()
  +sendEmail()
  +updateNote()
}
interface Hashtag {
  -boolean updatedAt
  +boolean description
  -int price
  +saveEmail()
  +processScore()
  +deleteTotal()
}
class Notification {
  -boolean address
  #float score
  +deletePrice()
}
class Post {
  -float address
  -boolean code
  +findAddress()
  +saveType()
  +sendAddress()
}
class Follower {
  +long level
  +Date duration
  +validateType()
  +getDuration()
  +createEmail()
  +cancelAddress()
}
class Report {
  #float code
  +float active
  +createNote()
}
Message --o Follower
Post --* Notification
@enduml