@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
class Account {
  #String description
  #float type
  +getQuantity()
  +processTotal()
  +sendActive()
}
class Transfer {
  -float code
  -int status
  -boolean id
  #float note
  +getQuantity()
}
class Deposit {
  -long note
  +int total
  #long createdAt
  +long address
  +deleteType()
  +getAddress()
  +deleteDescription()
  +createDuration()
}
interface Loan {
  -Date amount
  -boolean score
  -String email
  -long type
  +float name
  +deleteId()
  +getCode()
  +sendDuration()
  +sendCreatedat()
}
class Interest {
  -double level
  -long phone
  -Date amount
  +cancelStatus()
  +createAmount()
}
Transfer ..> Interest : "1"
Account ..> Interest : "1..*"
@enduml