@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
abstract class Service {
  -double amount
  -int name
  -double price
  #double total
  #double duration
  +getCode()
  +sendEmail()
  +sendCreatedat()
  +calculatePrice()
}
class Payment {
  +String address
  -boolean score
  +calculateAmount()
  +updateCreatedat()
}
abstract class Room {
  -String createdAt
  +Date type
  #String active
  #double id
  -double quantity
  +calculatePhone()
  +getStatus()
  +updateCreatedat()
  +findNote()
}
class CheckIn {
  -Date status
  -double level
  +String amount
  #float updatedAt
  +float email
  +calculateAmount()
}
abstract class Reservation {
  #int score
  -double description
  -boolean phone
  +findType()
  +createAmount()
  +cancelActive()
}
interface Staff {
  +String status
  #long code
  +validateDescription()
}
Payment --* CheckIn
Room --|> Service
Reservation --o Payment
@enduml