@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
abstract class Return {
  +float status
  +boolean id
  -double duration
  #boolean price
  +setName()
  +deleteNote()
  +getUpdatedat()
}
class Warehouse {
  -int updatedAt
  -int createdAt
  +calculateCode()
  +setAmount()
  +deleteType()
}
class Customer {
  +Date id
  -long total
  +createType()
  +updateQuantity()
}
class Payment {
  -String active
  +int description
  +saveCreatedat()
  +saveId()
  +setQuantity()
}
Payment ..|> Customer
@enduml