@startuml
skinparam monochrome true
abstract class Comment {
  -float id
  #double email
  +float note
  -String price
  +calculateType()
  +deleteActive()
  +cancelAmount()
  +findAddress()
}
abstract class Notification {
  -Date total
  #String phone
  -double duration
  +double note
  #int quantity
  +processScore()
}
abstract class Profile {
  +float amount
  #String email
  +long active
  +createPhone()
}
class Post {
  #Date type
  -boolean note
  +boolean total
  -float level
  +int email
  +createActive()
  +updateNote()
}
interface Album {
  #float name
  -double address
  +setName()
  +cancelCode()
  +saveDescription()
}
interface Follower {
  +String active
  #String note
  +cancelName()
}
Comment --* Post
Album ..|> Profile
@enduml