@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
interface Warehouse {
  +double type
  #long phone
  -Date status
  -float quantity
  -double id
  +updateScore()
}
interface Wishlist {
  -float duration
  +boolean type
  +createTotal()
  +calculateAmount()
}
interface Invoice {
  +String updatedAt
  -int active
  #boolean price
  #boolean type
  +setTotal()
}
abstract class Cart {
  #int amount
  -boolean updatedAt
  +deleteQuantity()
  +updateUpdatedat()
  +deleteLevel()
}
class Order {
  #long price
  +long description
  +processUpdatedat()
}
class Payment {
  #boolean price
  #long id
  +deletePhone()
  +sendEmail()
  +sendDescription()
}
abstract class Supplier {
  -boolean note
  +boolean description
  #Date id
  -float duration
  #float amount
  +saveName()
}
Warehouse --* Payment
Supplier ..> Invoice : "0..1"
Cart --> Wishlist : "1"
Invoice --o Wishlist
@enduml