@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
class Diagnosis {
  -int amount
  +Date name
  #float score
  +validateAddress()
}
class LabTest {
  -float note
  +float duration
  +float active
  -float amount
  +findPhone()
  +getAmount()
}
class Treatment {
  #double total
  #boolean status
  +processId()
  +processCode()
}
class Doctor {
  #long address
  #boolean code
  +double score
  -int type
  +cancelLevel()
  +calculateActive()
}
abstract class Prescription {
  -Date updatedAt
  +boolean duration
  -long description
  #double status
  #double type
  +sendPrice()
}
Prescription --o LabTest
Prescription --o Diagnosis
Prescription --o Doctor
Diagnosis ..|> Prescription
@enduml