@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
interface Card {
  #int active
  #boolean updatedAt
  #int type
  -long description
  +deleteStatus()
  +findNote()
}
class Transfer {
  +float description
  +long email
  #Date total
  #long score
  +long code
  +deleteUpdatedat()
  +getQuantity()
  +updateQuantity()
}
class Statement {
  #Date amount
  -float total
  +findScore()
  +saveId()
  +setType()
}
class Withdrawal {
  -float description
  #boolean email
  -float type
  -double code
  +sendPhone()
  +deleteEmail()
  +createScore()
}
class Account {
  +long active
  +int address
  -Date updatedAt
  -boolean code
  +setLevel()
  +createName()
  +calculateAmount()
  +sendEmail()
}
class Teller {
  +boolean name
  #boolean phone
  +int total
  +deleteDescription()
  +createCreatedat()
  +calculateEmail()
}
Transfer ..> Withdrawal : "1..*"
Transfer --|> Statement
Account --> Transfer : "1"
Statement ..> Teller : "1..*"
@enduml