@startuml
skinparam ArrowColor #555555
abstract class Hashtag {
  +int description
  -float name
  +long total
  -Date email
  +processQuantity()
  +validateLevel()
}
abstract class Follower {
  -double name
  -int type
  -long active
  +getLevel()
  +deleteAmount()
  +findAmount()
}
class Like {
  -long id
  +long code
  -float description
  +createLevel()
  +cancelStatus()
}
class Report {
  -double address
  -Date code
  +float createdAt
  +setLevel()
  +createDuration()
  +calculateName()
  +savePhone()
}
Report --|> Like
Hashtag --> Like : "*"
@enduml