@startuml
skinparam monochrome true
skinparam defaultFontSize 11
class Coupon {
  #Date level
  +String amount
  #float quantity
  +sendUpdatedat()
}
abstract class Customer {
  +float phone
  +String id
  +validateCreatedat()
  +createName()
  +saveAddress()
}
class Supplier {
  #int total
  #Date address
  #boolean phone
  +calculateLevel()
  +getPhone()
  +findQuantity()
  +updateStatus()
}
class Warehouse {
  #float code
  -Date status
  #String note
  #float level
  +Date address
  +setDescription()
  +deleteDescription()
  +updateCreatedat()
}
abstract class Product {
  +String type
  -float amount
  +Date level
  #double phone
  +setName()
  +saveNote()
}
class Return {
  #double email
  -long code
  -Date updatedAt
  +setId()
  +calculateAddress()
}
Warehouse --> Product : "1..*"
Supplier --o Product
Supplier ..> Customer : "1..*"
Product --> Coupon : "0..1"
@enduml