@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Beneficiary {
  +String score
  -double quantity
  #Date price
  -int duration
  +double active
  +deleteScore()
  +calculateLevel()
  +calculateDescription()
  +findUpdatedat()
}
class Transaction {
  -Date amount
  +long address
  -float score
  +saveNote()
}
class Statement {
  +long total
  #long phone
  +sendType()
  +validateStatus()
}
interface Transfer {
  #double updatedAt
  #int duration
  +setStatus()
}
abstract class Account {
  #Date updatedAt
  +Date level
  +cancelCreatedat()
  +getAddress()
  +calculateDuration()
}
interface Interest {
  +float duration
  -double note
  +String updatedAt
  +calculateType()
  +findId()
  +processLevel()
}
class Customer {
  -float id
  +boolean updatedAt
  -int quantity
  +Date status
  #float level
  +deleteNote()
  +deleteActive()
}
Account --|> Interest
Statement --* Account
@enduml