@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Teacher {
  +double level
  +Date total
  +Date amount
  +updateScore()
  +deleteStatus()
}
class Book {
  -long type
  +long address
  +boolean updatedAt
  -int status
  +deleteScore()
  +setAddress()
  +cancelDescription()
}
class Enrollment {
  -int level
  +float note
  #String email
  +Date name
  +saveStatus()
  +validateActive()
  +findStatus()
  +cancelTotal()
}
class Department {
  -float address
  -float quantity
  -boolean email
  +findCreatedat()
  +setPrice()
}
class Classroom {
  #double quantity
  +long type
  #String createdAt
  +findActive()
}
Enrollment --o Teacher
Enrollment --* Book
@enduml