@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
interface Story {
  #int code
  +long active
  +validateCreatedat()
  +saveUpdatedat()
  +updateDuration()
  +createActive()
}
abstract class Report {
  +String email
  +float score
  +sendCreatedat()
  +updateQuantity()
  +processQuantity()
  +updateDescription()
}
interface User {
  +Date duration
  -boolean email
  -Date type
  -boolean quantity
  +Date phone
  +cancelName()
}
class Profile {
  +double type
  +boolean note
  +createDescription()
  +deleteScore()
  +cancelAddress()
}
interface Notification {
  -long active
  -boolean price
  +double duration
  #long status
  -float code
  +calculateLevel()
  +saveName()
  +processStatus()
}
class Group {
  +boolean duration
  +float price
  #Date phone
  +double note
  #String id
  +createActive()
  +processCreatedat()
  +calculatePhone()
}
Profile --o Story
Notification --o Profile
@enduml