@startuml
skinparam monochrome true
skinparam ArrowColor #555555
interface Product {
  -double note
  +long updatedAt
  +long total
  -Date code
  +updateCreatedat()
  +saveDescription()
  +getTotal()
}
class Invoice {
  -String email
  #int code
  +sendCode()
  +getEmail()
  +deleteScore()
  +updateScore()
}
class Warehouse {
  #boolean score
  #Date address
  -float name
  #double email
  #int phone
  +getAmount()
  +saveId()
  +cancelPhone()
}
abstract class Order {
  #long id
  -int updatedAt
  +double description
  -float duration
  +validateActive()
}
class Return {
  +float note
  #Date type
  +saveId()
  +savePrice()
  +sendCode()
  +getCode()
}
class Cart {
  #String type
  +double status
  +deleteId()
  +setLevel()
  +cancelType()
}
Return --|> Order
Invoice --o Return
Warehouse ..|> Order
note right of Product : Ecommerce domain
@enduml