@startuml
skinparam ArrowColor #555555
interface Profile {
  +String total
  +Date name
  +calculateCode()
  +sendDuration()
  +sendQuantity()
  +deletePhone()
}
abstract class Comment {
  -float updatedAt
  #long email
  #int active
  +updateAddress()
  +cancelPrice()
  +cancelDuration()
  +calculateStatus()
}
abstract class Story {
  +int code
  #double type
  +double status
  -float address
  +deleteActive()
  +updateNote()
}
abstract class User {
  +Date status
  -Date total
  #double createdAt
  +validateType()
  +savePhone()
  +createTotal()
  +deleteName()
}
class Notification {
  #float note
  -String type
  +cancelNote()
  +setTotal()
  +updateType()
}
Comment --> Profile : "*"
Notification --o Profile
@enduml