@startuml
skinparam defaultFontSize 13
class Story {
  +Date duration
  +float type
  #double code
  +calculateType()
  +setLevel()
  +validateDuration()
  +getScore()
}
interface Message {
  #String note
  #float active
  +double type
  #String level
  +processId()
  +getActive()
  +getTotal()
  +findPhone()
}
class Group {
  +float phone
  #String updatedAt
  -float code
  +int type
  #Date active
  +sendLevel()
  +deleteUpdatedat()
  +deleteActive()
  +deleteScore()
}
class User {
  +Date price
  +int duration
  -double updatedAt
  -String quantity
  -Date type
  +deleteAmount()
  +findUpdatedat()
  +cancelType()
  +deleteScore()
}
abstract class Follower {
  -double address
  +String total
  #int status
  +sendScore()
}
Group --|> Story
Story --* Message
Story ..> Follower : "1"
@enduml