@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
abstract class Loan {
  #float id
  +double price
  #float description
  +cancelName()
  +sendNote()
  +calculateStatus()
  +findCreatedat()
}
interface Teller {
  +float description
  -int active
  +Date type
  +cancelNote()
  +validateQuantity()
  +saveCode()
  +cancelAmount()
}
class Statement {
  +String createdAt
  -long name
  +long code
  +long score
  +sendStatus()
  +findEmail()
  +processStatus()
}
abstract class Withdrawal {
  #String quantity
  -boolean duration
  +String createdAt
  +validateStatus()
  +processAmount()
}
Withdrawal --* Statement
Statement ..> Withdrawal : "*"
@enduml