@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
class Library {
  +Date status
  #int code
  -float name
  +cancelType()
  +saveAddress()
}
class Attendance {
  -long score
  #boolean type
  +updateStatus()
}
abstract class Course {
  -Date phone
  -long type
  +getActive()
  +validateCode()
  +getUpdatedat()
  +createCode()
}
abstract class Teacher {
  #Date active
  -float level
  -long price
  +deleteQuantity()
  +deleteCreatedat()
  +createLevel()
  +deleteName()
}
class Assignment {
  #int total
  +String note
  +String createdAt
  +int email
  -long price
  +sendStatus()
  +updateScore()
}
class Book {
  -float address
  +long type
  +getLevel()
  +deleteDescription()
  +createPrice()
}
class Grade {
  +boolean total
  #double updatedAt
  -boolean createdAt
  +deleteStatus()
  +setAmount()
  +calculateDuration()
  +findType()
}
Course --> Grade : "1..*"
Teacher ..> Attendance : "*"
Grade --> Course : "*"
Library ..> Assignment : "1..*"
@enduml