@startuml
skinparam monochrome true
skinparam defaultFontSize 13
abstract class Album {
  -long price
  -float type
  +calculateDuration()
  +updateNote()
}
interface Report {
  #long price
  -Date amount
  +long status
  +setTotal()
  +deleteLevel()
}
abstract class Profile {
  -String note
  #boolean active
  +int quantity
  +int level
  +cancelStatus()
}
class Group {
  -double score
  #String active
  #long email
  -Date phone
  +updateStatus()
}
class Post {
  #float score
  +boolean duration
  #boolean note
  +int updatedAt
  +int active
  +saveTotal()
  +deleteCode()
  +findScore()
}
class Story {
  #double name
  +double active
  #float email
  +cancelName()
  +deleteType()
  +calculateNote()
  +cancelDescription()
}
abstract class User {
  #long price
  #int code
  #double type
  +createType()
  +calculateId()
  +setDescription()
  +createScore()
}
Profile ..> Story : "1"
Group ..|> Report
Report --* Post
@enduml