@startuml

abstract class Loan {
  #int quantity
  -String address
  +setLevel()
  +setCode()
  +sendUpdatedat()
}
class Teller {
  #double quantity
  -String updatedAt
  +saveScore()
  +deleteAddress()
}
abstract class Customer {
  +float type
  +double active
  +float level
  +sendQuantity()
}
abstract class Branch {
  #float createdAt
  -float code
  #String email
  #float amount
  +deleteName()
  +updateScore()
  +deleteDuration()
}
class Account {
  #float active
  #float code
  +int createdAt
  +deleteNote()
  +processStatus()
}
class Deposit {
  #double note
  +int level
  -double duration
  +sendPrice()
}
Branch --|> Account
Customer ..|> Loan
Branch ..> Loan : "0..1"
Customer --* Deposit
@enduml