@startuml
skinparam monochrome true
skinparam defaultFontSize 11
abstract class Message {
  -double email
  +Date score
  #double level
  +savePhone()
  +cancelNote()
  +getType()
}
abstract class Hashtag {
  -float updatedAt
  -Date address
  +float status
  #Date level
  -boolean code
  +cancelNote()
  +updateDuration()
}
interface Group {
  #Date status
  -float description
  -String type
  #double phone
  #double amount
  +savePrice()
  +setCreatedat()
}
interface Album {
  #long name
  -float status
  +validateId()
}
class Report {
  #float id
  -boolean address
  #String score
  #long note
  +getCode()
}
interface User {
  #double name
  #double type
  +boolean address
  +Date note
  -int amount
  +updateAmount()
}
class Story {
  #Date address
  #long updatedAt
  +cancelUpdatedat()
}
Story --> Album : "1..*"
Album --* Hashtag
note right of Message : Social Media domain
@enduml