@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Message {
  #float price
  -boolean id
  #boolean address
  #String email
  -String updatedAt
  +saveQuantity()
  +createUpdatedat()
  +findDuration()
}
abstract class Notification {
  #int score
  #boolean address
  #long type
  +boolean amount
  +deleteName()
  +getScore()
}
class Group {
  -Date score
  -long phone
  -Date note
  #long email
  +findNote()
  +setAddress()
}
class Hashtag {
  +long level
  #int active
  #Date updatedAt
  +float createdAt
  -String score
  +findNote()
}
class Album {
  #int code
  -int createdAt
  #float duration
  +validateCode()
  +saveAddress()
  +processUpdatedat()
  +updateType()
}
class Follower {
  -double code
  -boolean score
  +deleteEmail()
  +createStatus()
  +deleteActive()
}
abstract class User {
  -boolean duration
  #boolean active
  #long note
  +setId()
  +cancelEmail()
  +getAmount()
}
User --|> Group
Hashtag --* Notification
User --o Hashtag
@enduml