@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
class Guest {
  -boolean total
  -int type
  #int level
  +processName()
  +processCreatedat()
  +deletePrice()
  +processId()
}
class CheckOut {
  +double email
  #Date quantity
  +sendName()
}
abstract class CheckIn {
  -long description
  -double address
  +getDescription()
}
class Service {
  #String score
  #boolean email
  +long type
  -Date amount
  -double active
  +deleteCreatedat()
}
Guest --* Service
CheckOut --> Service : "0..1"
note right of Guest : Hotel domain
@enduml