@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
class Library {
  -long quantity
  #double note
  -long status
  +calculateDescription()
  +getEmail()
  +getNote()
  +cancelTotal()
}
interface Course {
  -String type
  -float total
  +updateLevel()
  +calculateStatus()
}
class Classroom {
  #float updatedAt
  +boolean type
  -String price
  +calculateCreatedat()
}
interface Assignment {
  -float type
  +String note
  -int description
  #float active
  #String address
  +getTotal()
  +createActive()
  +updateDescription()
}
class Exam {
  #boolean score
  #Date price
  +int updatedAt
  +createEmail()
}
interface Schedule {
  #float email
  +int note
  -String amount
  +sendStatus()
  +deleteCode()
  +saveDuration()
  +calculatePrice()
}
Schedule ..|> Assignment
Library --* Schedule
Assignment ..> Exam : "1"
@enduml