@startuml
skinparam shadowing true
class Service {
  -float phone
  -Date status
  #boolean active
  +deleteDuration()
  +processAmount()
  +getStatus()
}
class Staff {
  +String type
  +String active
  -boolean duration
  +double name
  -int email
  +cancelName()
  +calculateType()
  +updateQuantity()
}
interface Restaurant {
  #long type
  -double address
  +createAddress()
}
class Payment {
  +Date updatedAt
  -boolean total
  -int code
  #int price
  +String type
  +calculateUpdatedat()
  +updateAmount()
  +saveLevel()
}
interface Room {
  -float total
  +long note
  +float level
  -long quantity
  #long duration
  +createCreatedat()
  +calculateAmount()
  +cancelActive()
  +cancelId()
}
interface Housekeeping {
  #double amount
  #long email
  +float total
  -String duration
  +float description
  +savePrice()
  +findLevel()
  +getLevel()
  +validateId()
}
Service --* Restaurant
Staff ..|> Service
Staff --o Housekeeping
@enduml