@startuml
skinparam shadowing true
class Transfer {
  #String status
  #float createdAt
  #boolean level
  +cancelActive()
}
abstract class Teller {
  +Date id
  -double email
  -Date updatedAt
  +double note
  +updateScore()
  +validateNote()
  +findStatus()
  +updateEmail()
}
class Statement {
  -double level
  -long active
  +String updatedAt
  +boolean note
  +createPhone()
}
class Withdrawal {
  -String level
  +boolean type
  -String id
  +int createdAt
  +getAmount()
  +validateAddress()
}
class Account {
  +float quantity
  #String address
  #long name
  +boolean note
  +updateDescription()
  +updateLevel()
}
class Customer {
  #Date price
  #double quantity
  +boolean email
  +deleteType()
  +processAddress()
  +processLevel()
  +validateUpdatedat()
}
interface Branch {
  -Date quantity
  +String level
  #boolean score
  +validateActive()
  +saveType()
  +updateUpdatedat()
  +processDescription()
}
Withdrawal --|> Statement
Branch ..> Customer : "0..1"
Withdrawal --o Account
@enduml