@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
class Hashtag {
  +long email
  -double address
  -double createdAt
  #double amount
  #long status
  +validateQuantity()
  +sendPhone()
  +deleteType()
  +sendType()
}
class Follower {
  -boolean total
  #float quantity
  #long duration
  +getQuantity()
  +saveType()
}
interface Story {
  -float address
  #String status
  +double active
  -Date price
  +sendLevel()
  +getTotal()
  +validateActive()
}
abstract class Like {
  #boolean level
  #long createdAt
  -float duration
  #int updatedAt
  +deleteDescription()
  +validateLevel()
  +calculateQuantity()
  +calculateStatus()
}
abstract class Report {
  #double level
  #String duration
  -int description
  +String type
  #Date amount
  +processAddress()
}
Follower --* Story
Report ..> Hashtag : "1"
Follower --o Hashtag
@enduml