@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
class Hashtag {
  #float description
  -float score
  +setDuration()
}
class Album {
  #float duration
  -Date createdAt
  #Date description
  #String status
  #int address
  +createAmount()
  +processCreatedat()
}
interface Profile {
  +Date quantity
  +int description
  +setScore()
}
abstract class Report {
  #long score
  #String active
  -Date code
  -Date status
  -String description
  +savePhone()
  +setStatus()
  +findActive()
  +setActive()
}
class User {
  #long address
  +float note
  #Date active
  -double phone
  +long level
  +getPrice()
}
class Story {
  +String active
  +String phone
  +calculateQuantity()
  +cancelStatus()
}
class Message {
  #String total
  #long email
  +findAmount()
}
Story ..> User : "0..1"
User --|> Profile
note right of Hashtag : Social Media domain
@enduml