@startuml
skinparam ArrowColor #555555
class User {
  -long id
  +String updatedAt
  +double duration
  #String email
  +processScore()
  +sendTotal()
  +calculateCreatedat()
}
interface Group {
  -long quantity
  #String phone
  #double createdAt
  #long id
  +calculateAddress()
}
abstract class Hashtag {
  +double note
  -int quantity
  +float createdAt
  +findName()
  +getNote()
  +setCode()
  +updateId()
}
abstract class Post {
  -Date type
  #float score
  +long amount
  +setAmount()
}
abstract class Comment {
  #float type
  -int note
  -int quantity
  -int updatedAt
  #int name
  +saveQuantity()
}
class Message {
  +boolean phone
  +boolean code
  +processPhone()
  +validateQuantity()
}
Hashtag --o Comment
Hashtag --o Message
User --o Comment
@enduml