@startuml

class Withdrawal {
  +boolean score
  +boolean amount
  +setAddress()
  +updateQuantity()
  +setId()
  +deleteActive()
}
class Teller {
  #String phone
  -Date address
  #long code
  +processDescription()
  +getEmail()
  +getActive()
}
class Customer {
  +long duration
  #Date total
  +float id
  #long level
  -long type
  +sendLevel()
  +createQuantity()
  +setScore()
  +validateId()
}
interface Interest {
  +String level
  +double amount
  +updateStatus()
  +deleteEmail()
}
abstract class Deposit {
  -long level
  -long description
  +int total
  +calculateAmount()
  +getUpdatedat()
  +setNote()
  +createPrice()
}
Interest --> Teller : "1"
Deposit ..> Customer : "*"
Customer --|> Deposit
Deposit --* Teller
@enduml