@startuml

abstract class Shelf {
  +float createdAt
  #float total
  -Date phone
  +processDuration()
  +findUpdatedat()
  +cancelId()
  +setUpdatedat()
}
class Member {
  #boolean quantity
  +double description
  -String createdAt
  +boolean id
  #float updatedAt
  +deletePrice()
  +saveCode()
  +getScore()
}
class Loan {
  -float quantity
  -double score
  +cancelPrice()
  +updateDuration()
  +validateDuration()
  +saveType()
}
class Publisher {
  +float active
  -double description
  +deleteTotal()
  +calculateLevel()
  +updateNote()
  +deleteName()
}
Loan --> Shelf : "1"
Publisher --* Shelf
@enduml