@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
interface Schedule {
  -long quantity
  +int id
  -boolean updatedAt
  -float address
  +getNote()
  +createQuantity()
  +calculateCode()
  +getEmail()
}
class Course {
  -boolean price
  +Date duration
  #float active
  +createActive()
  +processId()
  +validateScore()
}
class Exam {
  #double id
  +float description
  +getPrice()
  +calculateAddress()
  +getEmail()
  +validateCode()
}
class Library {
  #float total
  +long level
  #String name
  #Date createdAt
  +processTotal()
  +deleteActive()
  +cancelPrice()
  +validateLevel()
}
Course ..> Schedule : "1"
Exam --o Library
Course --> Library : "1"
@enduml