@startuml
skinparam monochrome true
skinparam defaultFontSize 11
class Coupon {
  #double price
  +double amount
  +int email
  -long level
  -int id
  +updateLevel()
  +setName()
  +setDescription()
  +saveCode()
}
class Invoice {
  #float phone
  #long id
  -float total
  +long active
  +cancelCreatedat()
  +processEmail()
}
interface Cart {
  +String level
  -long active
  +double price
  +processActive()
}
interface Return {
  +double active
  #boolean name
  #boolean total
  +sendAmount()
  +createTotal()
}
interface Category {
  #double email
  +int active
  +String code
  #Date duration
  +calculatePhone()
  +cancelDescription()
}
class Payment {
  #int note
  -float description
  -int amount
  #boolean updatedAt
  -Date phone
  +updateActive()
  +setCreatedat()
  +getEmail()
  +saveId()
}
class Supplier {
  +float note
  +boolean email
  +Date quantity
  +Date address
  +float type
  +setActive()
}
Return --* Coupon
Category --o Supplier
@enduml