@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
class Statement {
  #int email
  #boolean createdAt
  -String code
  +setDuration()
  +saveAddress()
}
class Beneficiary {
  #boolean quantity
  #int duration
  -int address
  #int amount
  +setStatus()
  +processStatus()
}
abstract class Interest {
  #double amount
  -long address
  +boolean active
  -long name
  +sendDescription()
  +getUpdatedat()
  +createUpdatedat()
  +updatePrice()
}
class Card {
  +int duration
  #int price
  +findCode()
  +updateStatus()
  +updateEmail()
}
Beneficiary ..|> Interest
Interest --* Beneficiary
@enduml