@startuml
skinparam ArrowColor #555555
interface Route {
  +Date score
  #float name
  +boolean duration
  +double id
  +saveDescription()
  +calculateUpdatedat()
  +findActive()
  +processNote()
}
class Package {
  -String id
  #long active
  +createPhone()
  +sendDuration()
  +getId()
}
interface Customer {
  #double status
  #int level
  #double type
  +String description
  #boolean updatedAt
  +processLevel()
  +validateActive()
}
abstract class FuelLog {
  -double code
  +int name
  -Date type
  -int total
  +boolean description
  +processLevel()
  +createScore()
}
class Vehicle {
  #long email
  #long createdAt
  #boolean phone
  +double code
  +String duration
  +saveUpdatedat()
}
Customer ..> FuelLog : "1..*"
FuelLog ..> Customer : "*"
Route --* Customer
Route --> Package : "1"
@enduml