@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
abstract class Message {
  #boolean note
  +boolean phone
  #long active
  #String type
  +processType()
  +calculatePrice()
  +findCreatedat()
  +createAddress()
}
class Hashtag {
  +long createdAt
  -double duration
  +String id
  -Date description
  +double email
  +getStatus()
}
class Like {
  +double quantity
  #float duration
  +validateDuration()
  +setId()
  +cancelAmount()
  +deleteScore()
}
class Post {
  -Date duration
  #Date id
  +double note
  +setActive()
  +sendUpdatedat()
  +findTotal()
  +calculateAmount()
}
class Story {
  #Date phone
  +double note
  +sendAmount()
  +findEmail()
  +processDuration()
  +processLevel()
}
class Profile {
  -float duration
  -boolean total
  +float description
  +validateUpdatedat()
  +createCode()
  +validateTotal()
  +processScore()
}
abstract class Group {
  -boolean email
  -float code
  +String note
  #Date type
  +String total
  +createActive()
}
Hashtag --|> Message
Story ..> Profile : "0..1"
Hashtag --* Like
Group ..> Hashtag : "*"
Like --o Message
Story --o Message
@enduml