@startuml
skinparam defaultFontSize 13
class Hashtag {
  +long phone
  -Date active
  +deleteName()
  +calculateTotal()
  +cancelDuration()
  +saveDuration()
}
class Follower {
  #String status
  #Date description
  +findCode()
  +findName()
  +getQuantity()
}
class Album {
  +float description
  #long score
  -boolean active
  -String email
  #double duration
  +sendId()
  +getEmail()
  +processPrice()
  +updatePrice()
}
class Profile {
  +int total
  +float createdAt
  #boolean quantity
  +boolean status
  #float id
  +findTotal()
  +cancelLevel()
  +calculateCreatedat()
  +updateUpdatedat()
}
class Report {
  +int email
  #float description
  #int id
  +processStatus()
}
class Like {
  #long status
  -String type
  -int active
  -Date score
  +getEmail()
  +validateAmount()
  +updatePhone()
}
Hashtag --* Like
Hashtag ..> Profile : "*"
Report --|> Profile
@enduml