@startuml
skinparam ArrowColor #555555
interface Librarian {
  +String score
  -float description
  -String updatedAt
  #Date email
  +calculateName()
  +deleteUpdatedat()
  +deleteQuantity()
  +setTotal()
}
interface Reservation {
  -long status
  #Date phone
  +sendName()
}
abstract class Book {
  -boolean score
  -boolean createdAt
  +deleteCode()
  +updateName()
}
class Fine {
  #int status
  +double amount
  #boolean price
  #String type
  #boolean updatedAt
  +updateTotal()
  +calculateCreatedat()
}
Book ..|> Reservation
Librarian ..> Book : "0..1"
@enduml