@startuml
skinparam monochrome true
abstract class User {
  +float name
  +Date address
  +validateScore()
  +getPhone()
  +setId()
  +findCode()
}
abstract class Profile {
  +int code
  +String description
  #double status
  -float note
  +getEmail()
  +findEmail()
}
class Follower {
  #float code
  #int id
  -int updatedAt
  #int amount
  +float description
  +calculateEmail()
  +setAddress()
  +sendCode()
  +updateNote()
}
class Like {
  +boolean price
  -String createdAt
  +String description
  +String code
  +setLevel()
  +findType()
  +validateCreatedat()
}
Like --> Profile : "1"
Like --o Follower
@enduml