@startuml
skinparam shadowing true
class CheckIn {
  +float code
  +int price
  +getPrice()
  +cancelId()
}
class Restaurant {
  +String score
  +boolean total
  #boolean description
  #float level
  +getQuantity()
  +calculateStatus()
  +calculateNote()
}
class Room {
  -float address
  #long price
  -boolean email
  +saveDescription()
}
interface CheckOut {
  #double name
  +boolean id
  +validateEmail()
}
Room --|> CheckOut
Room ..> Restaurant : "1..*"
Restaurant --> Room : "*"
@enduml