@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
class Loan {
  -float status
  +int note
  +String description
  +saveName()
  +processCode()
  +createPhone()
  +validateAddress()
}
abstract class Account {
  +float amount
  -float address
  #boolean type
  #String status
  +deleteType()
  +sendName()
}
abstract class Card {
  #long active
  +Date address
  +long price
  +validateQuantity()
}
interface Teller {
  -int code
  #boolean description
  +sendDuration()
  +findCode()
  +processEmail()
}
class Withdrawal {
  -boolean createdAt
  +long id
  -long name
  -boolean total
  -long updatedAt
  +validateLevel()
  +cancelPrice()
}
abstract class Transfer {
  +int email
  +String description
  +createEmail()
  +setTotal()
  +setPrice()
}
Withdrawal --o Teller
Account --|> Transfer
@enduml