@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
abstract class Group {
  +long createdAt
  +int price
  +setAddress()
  +calculatePhone()
}
class Profile {
  +float total
  -String type
  #double active
  +getScore()
  +findName()
  +deleteName()
}
interface Notification {
  +int createdAt
  -String updatedAt
  -int phone
  +boolean address
  -String amount
  +setEmail()
  +getPrice()
  +processActive()
  +validateId()
}
interface Message {
  +float amount
  +boolean active
  -int address
  +long total
  -Date type
  +sendDescription()
  +sendUpdatedat()
  +cancelDuration()
}
class Album {
  #boolean id
  -String note
  #int address
  +getName()
}
class User {
  #boolean note
  +long phone
  +Date code
  +updateEmail()
}
Profile ..|> Group
Notification --> Message : "*"
Notification --o Profile
@enduml