@startuml
skinparam monochrome true
class Customer {
  #float status
  -int score
  -Date type
  #float quantity
  +int phone
  +saveStatus()
}
abstract class Transaction {
  -String status
  #boolean score
  +processNote()
  +findNote()
  +processPrice()
}
abstract class Deposit {
  -int score
  #float note
  +Date active
  -String quantity
  +findScore()
  +calculateCreatedat()
  +saveDuration()
}
class Withdrawal {
  -boolean address
  #long price
  +Date createdAt
  -float id
  +getNote()
  +deleteActive()
}
class Account {
  #Date total
  #float quantity
  -boolean duration
  -boolean note
  -int status
  +createScore()
  +deleteLevel()
  +sendQuantity()
  +setScore()
}
abstract class Teller {
  -String status
  -boolean price
  +saveId()
}
interface Transfer {
  -long quantity
  -Date score
  +Date phone
  #double status
  #float updatedAt
  +sendName()
  +createName()
}
Account --> Teller : "1..*"
Withdrawal ..|> Transfer
Transfer --* Transaction
Withdrawal ..> Teller : "0..1"
Teller ..> Deposit : "1"
Transaction --* Customer
@enduml