@startuml
skinparam monochrome true
abstract class Invoice {
  +double createdAt
  +boolean type
  +double code
  +createCreatedat()
  +processAddress()
  +sendDescription()
  +calculateNote()
}
class Return {
  +String price
  #boolean email
  -Date level
  +deleteScore()
  +saveStatus()
  +processEmail()
}
class Review {
  #float code
  -String phone
  -Date level
  +validateAmount()
  +updateScore()
  +sendType()
}
class Payment {
  #int note
  -boolean total
  #double quantity
  +long description
  #boolean status
  +updateCreatedat()
}
abstract class Warehouse {
  +boolean note
  -String quantity
  #String type
  +saveLevel()
  +calculateQuantity()
  +cancelNote()
  +setNote()
}
Invoice ..> Payment : "*"
Return --|> Invoice
Return ..|> Review
note right of Invoice : Ecommerce domain
@enduml