@startuml

abstract class Booking {
  -Date amount
  +float price
  +validateNote()
  +deleteEmail()
  +deleteUpdatedat()
  +cancelAddress()
}
class Guest {
  #double email
  +long id
  #double duration
  +deleteQuantity()
  +validateActive()
  +saveDescription()
  +updateAmount()
}
abstract class CheckOut {
  #boolean score
  +String id
  +validateCode()
  +calculateNote()
}
class Staff {
  #Date duration
  #float type
  -String code
  #String active
  #String amount
  +getAddress()
}
class Invoice {
  #String status
  +long price
  +validateDescription()
  +getName()
}
class Room {
  +double createdAt
  +String quantity
  -float code
  #Date phone
  +boolean description
  +deletePrice()
  +sendActive()
  +createPhone()
  +saveAddress()
}
CheckOut ..> Invoice : "1..*"
Staff --* Booking
Invoice ..|> Room
Staff ..|> Room
@enduml