@startuml
skinparam ArrowColor #555555
class Schedule {
  #double phone
  -boolean name
  +validateTotal()
  +processCode()
  +createActive()
}
abstract class Classroom {
  #String code
  +Date active
  #Date note
  +int amount
  -long score
  +getUpdatedat()
  +setPrice()
}
abstract class Book {
  -Date total
  +float id
  +saveTotal()
  +sendUpdatedat()
  +cancelQuantity()
}
class Attendance {
  -long price
  +float amount
  -Date total
  -String type
  #int quantity
  +setLevel()
  +getDescription()
  +deleteScore()
  +updateAmount()
}
interface Library {
  #double score
  #float amount
  +boolean price
  -double description
  +sendDescription()
  +validateId()
}
class Exam {
  -int active
  +long type
  +cancelQuantity()
}
Exam --> Book : "0..1"
Classroom --> Exam : "1"
Classroom --o Attendance
Book --> Classroom : "1"
Library --> Schedule : "1..*"
@enduml