@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
class Deposit {
  #String type
  -String active
  #long phone
  #String amount
  +float email
  +processAddress()
  +deleteScore()
  +deleteEmail()
}
class Loan {
  #String total
  #long active
  +double amount
  +calculatePrice()
  +deleteId()
  +sendId()
  +updateName()
}
class Withdrawal {
  -double code
  +Date type
  +updateNote()
  +findType()
}
class Card {
  #float status
  +int code
  +saveScore()
  +sendNote()
}
Withdrawal --o Deposit
Card ..> Deposit : "0..1"
Withdrawal --|> Card
@enduml