@startuml
skinparam defaultFontSize 13
class Review {
  +double updatedAt
  +double score
  +double email
  -float note
  +long total
  +updateActive()
  +findId()
  +findScore()
  +deleteCode()
}
class Wishlist {
  -float updatedAt
  #double quantity
  #long name
  +sendType()
  +findEmail()
  +saveName()
}
class Invoice {
  #boolean description
  +long address
  #int price
  #double type
  +calculateAddress()
  +deleteActive()
}
class Product {
  -double name
  -float description
  -long price
  +setType()
  +setDescription()
  +cancelQuantity()
  +createType()
}
Invoice --|> Product
Product --|> Review
@enduml