@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
abstract class Customer {
  #String createdAt
  #float quantity
  +deletePhone()
  +setScore()
  +savePhone()
  +updatePrice()
}
interface Payment {
  #Date quantity
  #int email
  #float code
  +setPrice()
  +createAddress()
}
abstract class Return {
  #String note
  -int score
  #Date id
  +createType()
  +calculateDuration()
  +calculateLevel()
  +calculateNote()
}
class Supplier {
  -Date level
  +Date type
  +boolean email
  +long active
  +processUpdatedat()
  +setStatus()
  +updateQuantity()
  +findName()
}
Customer --* Supplier
Customer ..|> Return
Return --* Customer
@enduml