@startuml
skinparam defaultFontSize 11
class Loan {
  +double email
  +String note
  +findName()
  +sendName()
  +createName()
}
class Deposit {
  +long description
  -float duration
  -boolean note
  -String code
  +processCreatedat()
  +getAddress()
}
class Account {
  +long email
  -Date price
  -long id
  #float updatedAt
  +double type
  +getNote()
}
class Interest {
  -String address
  #long id
  #boolean quantity
  +String score
  +boolean note
  +deleteNote()
  +saveCode()
  +validateAddress()
  +createScore()
}
abstract class Card {
  -double price
  +float score
  -int amount
  #String quantity
  #Date email
  +cancelAmount()
}
class Withdrawal {
  -boolean type
  +String email
  -int code
  #boolean createdAt
  +createDescription()
  +setScore()
  +saveDuration()
}
Interest ..> Card : "1..*"
Withdrawal ..> Account : "*"
@enduml