@startuml
skinparam monochrome true
skinparam defaultFontSize 11
interface Album {
  +Date quantity
  -long name
  +getCode()
  +setPhone()
  +validateAmount()
  +validateDuration()
}
abstract class Follower {
  #long type
  #double note
  #int active
  +calculateType()
  +sendUpdatedat()
}
class Profile {
  #long address
  -Date phone
  -float note
  +findName()
  +findAmount()
}
class Like {
  -float duration
  -double type
  #float status
  #double phone
  #boolean name
  +findPrice()
  +calculateEmail()
  +setName()
}
class Post {
  #int phone
  +String id
  +double updatedAt
  #Date code
  +findCreatedat()
  +updateCode()
  +findName()
}
class Report {
  +long duration
  #double createdAt
  #String type
  +long email
  +deletePrice()
  +saveType()
  +validateEmail()
}
abstract class User {
  +double quantity
  +int active
  #String score
  -Date createdAt
  #boolean address
  +calculateDescription()
}
Album ..|> Follower
Follower --> User : "0..1"
@enduml