@startuml
skinparam monochrome true
skinparam defaultFontSize 11
class Customer {
  #boolean status
  #int note
  -double code
  #double description
  +long name
  +sendNote()
  +setScore()
  +deleteType()
}
class Return {
  +float id
  #int price
  +Date createdAt
  #int address
  #String type
  +deleteCreatedat()
  +processAmount()
  +findStatus()
  +sendDescription()
}
class Shipment {
  -int type
  +int level
  +float email
  -float updatedAt
  -Date createdAt
  +findLevel()
}
class Product {
  #float level
  -boolean score
  +double code
  +cancelCode()
  +getUpdatedat()
  +sendStatus()
}
interface Wishlist {
  -double note
  +Date phone
  #boolean updatedAt
  +getTotal()
  +sendPrice()
  +setUpdatedat()
}
abstract class Warehouse {
  #Date updatedAt
  -String total
  #float amount
  +cancelQuantity()
  +cancelLevel()
  +validateDuration()
}
class Coupon {
  +boolean id
  #long createdAt
  -boolean quantity
  #int code
  #String address
  +validateCreatedat()
  +sendLevel()
  +createId()
}
Shipment --|> Warehouse
Coupon ..|> Return
Coupon --|> Shipment
@enduml