@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
class Report {
  -Date status
  +String id
  -Date type
  +validateNote()
  +setName()
  +findPrice()
  +calculateNote()
}
abstract class Profile {
  -double score
  -long description
  +savePhone()
  +findUpdatedat()
}
class User {
  +double name
  -Date type
  #float id
  +cancelPhone()
  +cancelActive()
}
class Comment {
  #long name
  -double score
  +double email
  +double description
  -String address
  +createEmail()
}
class Message {
  +String phone
  -double email
  -Date total
  -boolean createdAt
  -boolean id
  +updateEmail()
  +validateType()
}
abstract class Hashtag {
  #float amount
  -double name
  -String createdAt
  +float price
  -long note
  +sendName()
  +validateQuantity()
  +cancelUpdatedat()
}
Message --> Profile : "1..*"
Message --> Report : "*"
Report --* Message
Message --> User : "0..1"
@enduml