@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
interface Deposit {
  #float email
  -long note
  +float total
  -int phone
  +saveCode()
}
class Withdrawal {
  -String type
  -long note
  -Date quantity
  +String phone
  +findUpdatedat()
  +sendAddress()
  +validateActive()
}
class Branch {
  #boolean id
  -double duration
  #Date level
  +createTotal()
  +updateLevel()
  +saveDescription()
}
abstract class Loan {
  -float id
  #int total
  -boolean code
  +sendAmount()
}
class Account {
  #boolean createdAt
  #Date description
  -Date active
  #float amount
  +createType()
  +cancelQuantity()
  +validateAmount()
}
Branch --|> Withdrawal
Deposit --* Branch
@enduml