@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
class Loan {
  -Date level
  -double note
  +saveNote()
  +cancelType()
}
class Book {
  -float phone
  +double updatedAt
  #int code
  +double status
  +cancelPrice()
  +findUpdatedat()
  +saveName()
}
interface Publisher {
  #boolean total
  -boolean type
  +createCode()
}
class Member {
  -String description
  -Date phone
  +boolean total
  +sendDescription()
}
Member --* Loan
Member --> Book : "1"
@enduml