@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
abstract class Inventory {
  -long level
  #String duration
  #String updatedAt
  -Date email
  +calculateEmail()
  +sendCode()
}
class Vehicle {
  #float description
  -double email
  +boolean total
  +saveDescription()
  +setDuration()
}
class Package {
  #long email
  +boolean address
  +getStatus()
  +setCode()
  +sendNote()
}
interface Driver {
  #String email
  +Date createdAt
  -int score
  +deleteLevel()
  +cancelStatus()
  +calculateUpdatedat()
}
Package --> Driver : "1"
@enduml