@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
abstract class Story {
  #float duration
  -String address
  #Date amount
  +deleteAddress()
  +validatePrice()
  +findAmount()
  +sendPrice()
}
class Hashtag {
  -float price
  #int id
  +long email
  +int code
  +calculateNote()
}
class Message {
  #long id
  #int description
  +sendName()
  +updateDescription()
  +updateDescription()
}
abstract class Like {
  +long score
  #long code
  +String id
  +createAddress()
}
class Notification {
  -Date type
  -String active
  -String score
  +boolean name
  #long createdAt
  +cancelQuantity()
  +sendPhone()
  +saveActive()
  +saveName()
}
class Post {
  +String phone
  #boolean code
  #long price
  -long email
  #float quantity
  +validateStatus()
}
Notification --o Post
Hashtag --> Message : "*"
note right of Story : Social Media domain
@enduml