@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
interface Housekeeping {
  +double address
  #int email
  #Date quantity
  +int description
  +cancelCreatedat()
  +createPhone()
  +setType()
}
class Room {
  -String type
  #int total
  +double name
  +float description
  +deleteUpdatedat()
  +validateId()
  +validateLevel()
}
class Invoice {
  #int quantity
  -long price
  +createDuration()
  +setCode()
}
interface Reservation {
  +long address
  -boolean total
  +int amount
  #long updatedAt
  +findStatus()
}
Reservation ..> Invoice : "*"
Reservation --|> Housekeeping
@enduml