@startuml
skinparam monochrome true
class Library {
  +Date price
  #String address
  +Date description
  +cancelAddress()
  +sendDuration()
}
class Teacher {
  #int level
  +Date amount
  -double createdAt
  +getType()
}
abstract class Attendance {
  -float quantity
  -String duration
  +int price
  +String amount
  +validatePrice()
}
class Classroom {
  #long code
  -float note
  +float price
  #Date address
  +getType()
  +sendDuration()
  +deletePhone()
}
Teacher --> Classroom : "1..*"
Attendance --* Teacher
@enduml