@startuml
skinparam monochrome true
skinparam shadowing true
abstract class Return {
  +boolean description
  -double active
  +float type
  #float address
  -long level
  +setEmail()
}
class Product {
  -boolean id
  #boolean level
  +sendPrice()
  +createName()
}
class Shipment {
  +boolean email
  #boolean address
  #float createdAt
  +String name
  +deleteAmount()
  +cancelScore()
  +deleteId()
}
interface Invoice {
  -String active
  +String name
  #float note
  +saveQuantity()
  +setLevel()
}
class Customer {
  #Date id
  -float description
  +float duration
  -double name
  #long quantity
  +findPhone()
  +calculateLevel()
  +deleteQuantity()
  +saveUpdatedat()
}
Invoice --* Product
Shipment --> Product : "0..1"
@enduml