@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
abstract class Catalog {
  +double duration
  #int active
  -int name
  +cancelPhone()
  +createUpdatedat()
  +validateUpdatedat()
  +createStatus()
}
class Loan {
  +double note
  #Date quantity
  +int price
  #long address
  +String amount
  +validateId()
  +setUpdatedat()
}
class Fine {
  -float code
  +int id
  -String description
  +createId()
}
interface Publisher {
  -long amount
  #double note
  +long status
  +processCode()
}
Publisher --> Catalog : "*"
Catalog --o Publisher
Publisher ..> Loan : "*"
@enduml