@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
class Attendance {
  #int description
  -float type
  -String createdAt
  -boolean code
  +saveCreatedat()
  +processNote()
}
abstract class Library {
  +float amount
  #double phone
  +processCreatedat()
  +deleteEmail()
  +validateStatus()
  +updateEmail()
}
class Student {
  -long name
  +double createdAt
  +float score
  #boolean id
  +cancelActive()
  +deleteId()
}
interface Grade {
  -long type
  +Date quantity
  +double updatedAt
  #float score
  +getCreatedat()
}
class Book {
  -int phone
  +float id
  -Date code
  -float updatedAt
  +calculateEmail()
  +findType()
  +cancelEmail()
}
class Assignment {
  #float price
  #double status
  -long active
  +createAmount()
  +createCode()
}
abstract class Schedule {
  -boolean phone
  #float status
  -String updatedAt
  +float level
  +sendScore()
  +getAddress()
  +validatePrice()
}
Grade --o Student
Library --o Assignment
Assignment --|> Library
Grade ..|> Book
Attendance --|> Book
@enduml