@startuml
skinparam monochrome true
interface Service {
  +String createdAt
  -Date email
  +createActive()
  +calculateStatus()
}
interface CheckOut {
  +Date phone
  -boolean name
  +String code
  #double score
  +boolean amount
  +cancelPrice()
  +sendScore()
}
class Booking {
  -double note
  #double phone
  +setAddress()
}
abstract class Room {
  -int type
  +long price
  -long quantity
  -float score
  +deleteUpdatedat()
}
class Staff {
  #String updatedAt
  #long email
  #Date createdAt
  +findCode()
  +createName()
}
class Restaurant {
  #Date id
  #String level
  +calculateCode()
  +getName()
  +saveDescription()
}
class CheckIn {
  #long phone
  +boolean status
  -double description
  +long quantity
  +int price
  +createQuantity()
  +cancelPrice()
  +getId()
}
Restaurant --o Booking
Room --|> Service
Service ..> CheckIn : "1"
Room ..|> Restaurant
@enduml