@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
interface Report {
  +Date address
  -Date description
  +cancelLevel()
}
abstract class Profile {
  +int status
  -int duration
  -float type
  #String total
  +validateDescription()
  +createTotal()
  +calculatePrice()
}
interface Message {
  #double level
  +double amount
  +float duration
  +validateQuantity()
}
abstract class Follower {
  -int note
  #String quantity
  +long code
  -Date email
  -boolean level
  +validateEmail()
  +calculateName()
  +cancelType()
}
class Album {
  #long type
  +Date total
  -float level
  -Date phone
  +cancelQuantity()
  +createCode()
  +cancelCreatedat()
}
class Story {
  -Date phone
  +double total
  +deleteLevel()
}
abstract class Post {
  -float score
  #double amount
  +cancelId()
  +findId()
  +deleteStatus()
}
Post --* Report
Album --|> Report
Profile ..|> Post
note right of Report : Social Media domain
@enduml