@startuml
skinparam ArrowColor #555555
interface Comment {
  -Date amount
  #int description
  +Date score
  +int type
  +setPrice()
}
interface Album {
  #String amount
  #float score
  +boolean note
  +cancelScore()
}
class Message {
  +String id
  -Date email
  -int name
  -float createdAt
  +sendCode()
  +processDescription()
}
interface Like {
  -float email
  +long status
  +getId()
  +findLevel()
  +createEmail()
}
class Report {
  -float amount
  #Date quantity
  -String active
  +boolean score
  +processPhone()
  +getCode()
  +createPrice()
}
abstract class Story {
  #long name
  +boolean id
  -String updatedAt
  +validateAddress()
}
Like --o Story
Comment --* Album
Story ..|> Like
Story ..|> Message
note right of Comment : Social Media domain
@enduml