@startuml
skinparam monochrome true
skinparam ArrowColor #555555
class Invoice {
  #long address
  -Date active
  -float id
  +deleteAddress()
  +calculatePrice()
}
class Housekeeping {
  #String score
  +int duration
  #double amount
  #boolean type
  +getCreatedat()
}
class Staff {
  #float active
  +float amount
  +findPrice()
}
class Reservation {
  -int active
  -Date price
  +findCode()
  +processLevel()
}
abstract class Service {
  -String id
  +Date name
  +createQuantity()
}
Service --* Reservation
Invoice --o Reservation
Housekeeping ..> Invoice : "0..1"
@enduml