@startuml

abstract class Enrollment {
  +float id
  +String updatedAt
  #int description
  +getLevel()
  +processNote()
}
class Schedule {
  -double createdAt
  #boolean active
  #double duration
  +int email
  +calculateUpdatedat()
}
class Book {
  #double total
  #int quantity
  +updatePrice()
}
interface Library {
  +Date id
  +float address
  -boolean updatedAt
  #boolean description
  -String active
  +updateTotal()
  +processLevel()
  +createId()
}
interface Attendance {
  -boolean price
  -String phone
  +validatePrice()
  +setUpdatedat()
  +sendCode()
}
Enrollment --o Book
Attendance --o Library
Book ..|> Enrollment
Attendance --|> Enrollment
@enduml