@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
abstract class Doctor {
  -long amount
  -Date quantity
  +processName()
}
class Patient {
  +String description
  -int email
  -int updatedAt
  +double type
  -double id
  +saveEmail()
}
class Billing {
  +long phone
  +double description
  #float duration
  +cancelUpdatedat()
  +calculatePrice()
  +setUpdatedat()
  +processName()
}
interface Nurse {
  #double description
  +Date name
  #boolean email
  +findQuantity()
  +validateStatus()
  +saveCreatedat()
  +deleteActive()
}
Doctor --* Patient
Doctor --o Nurse
@enduml