@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
interface User {
  #boolean name
  +boolean total
  -long status
  +int createdAt
  +updateNote()
  +sendAmount()
}
class Post {
  +long status
  #long name
  -int phone
  +processEmail()
  +savePhone()
}
interface Profile {
  -float note
  +String level
  #double description
  #int type
  +boolean active
  +sendId()
  +cancelQuantity()
  +cancelNote()
}
class Like {
  #String email
  #String name
  -long level
  -float code
  +sendAddress()
  +sendUpdatedat()
}
abstract class Follower {
  +String amount
  #int type
  #double name
  +float description
  +Date phone
  +findLevel()
  +saveName()
  +saveEmail()
  +setCode()
}
User --> Post : "1"
Like ..|> Profile
User --|> Profile
note right of User : Social Media domain
@enduml