@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
abstract class Prescription {
  #double description
  +Date email
  #Date updatedAt
  +int price
  +saveCode()
}
abstract class Treatment {
  #Date active
  +int name
  -float id
  +Date score
  #int description
  +findTotal()
}
interface MedicalRecord {
  +boolean quantity
  -boolean duration
  +long type
  -int level
  #long price
  +getCreatedat()
  +saveAddress()
  +createPrice()
}
interface Patient {
  -double updatedAt
  +boolean email
  +sendAmount()
  +findTotal()
  +createDuration()
  +getDescription()
}
class LabTest {
  -long note
  +int score
  +calculateActive()
}
interface Insurance {
  -int note
  -long status
  +String duration
  +findAmount()
  +sendDuration()
  +getAmount()
}
Insurance --> Prescription : "1"
LabTest --o Prescription
Prescription --|> Patient
Patient --o MedicalRecord
@enduml