@startuml
skinparam ArrowColor #555555
class Staff {
  -String quantity
  -double email
  -Date address
  +Date score
  #long createdAt
  +createCode()
  +cancelNote()
  +savePrice()
  +getNote()
}
class Amenity {
  #double id
  -Date total
  #float level
  +findDescription()
}
interface Restaurant {
  +String total
  +float description
  +int updatedAt
  #int active
  +updateId()
  +findUpdatedat()
}
interface CheckOut {
  #Date updatedAt
  -float type
  +float active
  -String id
  +cancelStatus()
  +setName()
}
Restaurant ..> CheckOut : "0..1"
Restaurant ..|> Amenity
note right of Staff : Hotel domain
@enduml