@startuml
skinparam defaultFontSize 11
class Report {
  -Date description
  +String address
  +Date score
  +updateAmount()
}
class Hashtag {
  +double phone
  -float note
  +cancelQuantity()
}
interface Album {
  #long updatedAt
  +boolean code
  -float note
  +setEmail()
  +sendDescription()
}
class Notification {
  #int description
  #int address
  +boolean email
  -boolean updatedAt
  +calculateAmount()
  +setCreatedat()
}
Album --|> Notification
Notification ..> Hashtag : "1"
note right of Report : Social Media domain
@enduml