@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
class Album {
  -boolean code
  #long description
  +validateUpdatedat()
  +validateScore()
  +cancelEmail()
  +saveTotal()
}
interface Story {
  +long status
  #int price
  -int code
  -double updatedAt
  +int createdAt
  +createName()
  +updateName()
}
abstract class User {
  #String id
  +long price
  +setName()
  +calculateId()
}
class Hashtag {
  -double type
  +double createdAt
  -int duration
  +double price
  +validateUpdatedat()
  +processActive()
  +updateCode()
}
class Notification {
  -boolean duration
  -double status
  -String note
  -long createdAt
  +findType()
}
Story ..> Notification : "0..1"
Album ..|> User
Notification --* Story
@enduml