@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
abstract class Diagnosis {
  +int updatedAt
  +int id
  -float address
  +createName()
  +sendDescription()
}
class MedicalRecord {
  #float price
  -boolean quantity
  -int score
  +deletePhone()
}
class Doctor {
  +double updatedAt
  +long active
  #Date note
  -long quantity
  +calculateId()
  +findScore()
  +deleteCode()
  +processUpdatedat()
}
class Patient {
  +Date duration
  #double createdAt
  -String description
  +boolean code
  -boolean price
  +calculateStatus()
  +deleteTotal()
  +cancelPrice()
  +processType()
}
class Insurance {
  #float description
  +String total
  #long email
  +setPhone()
  +setQuantity()
}
Doctor --* Diagnosis
Diagnosis --o Insurance
MedicalRecord --o Doctor
@enduml