@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
class User {
  -int duration
  +boolean address
  #Date phone
  +double status
  #float updatedAt
  +createName()
  +cancelScore()
  +findAmount()
  +validateActive()
}
interface Story {
  -boolean active
  +boolean level
  -String duration
  +setTotal()
  +cancelName()
  +deleteDescription()
  +createTotal()
}
class Post {
  +String status
  +double code
  -String email
  +String name
  +savePhone()
  +updateType()
}
class Profile {
  -float createdAt
  -int note
  +String status
  +deleteLevel()
}
class Message {
  -long quantity
  #boolean level
  +validateLevel()
}
class Report {
  -double amount
  -float score
  +sendAddress()
  +createActive()
  +findPhone()
}
class Hashtag {
  -int updatedAt
  +Date id
  +cancelType()
  +updateTotal()
  +sendPrice()
}
User --|> Hashtag
Report ..> Hashtag : "1..*"
Report --* Story
Report ..|> Profile
Message ..> Hashtag : "0..1"
Profile --|> Report
@enduml