@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
class Customer {
  +boolean id
  +String duration
  +int name
  +Date description
  +deleteName()
  +deleteAddress()
  +processNote()
  +getPrice()
}
class Transaction {
  -boolean note
  -Date price
  +boolean total
  #boolean score
  -boolean quantity
  +processLevel()
}
class Loan {
  #float createdAt
  -boolean status
  +float duration
  -double updatedAt
  +sendDuration()
  +setStatus()
}
class Withdrawal {
  -double type
  #Date status
  -long updatedAt
  -float total
  -int active
  +setStatus()
  +deleteNote()
  +deleteId()
}
class Card {
  #double score
  +String duration
  -float email
  -String note
  +setAddress()
}
class Deposit {
  +String level
  -long price
  -boolean address
  +double active
  +float updatedAt
  +deleteStatus()
  +validateTotal()
}
Transaction --* Card
Deposit --o Customer
@enduml