@startuml
skinparam shadowing true
class Member {
  -long active
  +String email
  +boolean description
  -int duration
  +updatePrice()
  +createAddress()
}
interface Branch {
  -double type
  +double quantity
  +updateStatus()
}
abstract class Publisher {
  #String duration
  -int status
  -double createdAt
  +float active
  -int address
  +setType()
  +cancelDescription()
  +validateQuantity()
}
abstract class Reservation {
  #double type
  -float email
  -long updatedAt
  -float createdAt
  #String duration
  +updateLevel()
}
Publisher --|> Reservation
Member --o Reservation
@enduml