@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
class Renewal {
  #boolean duration
  #long email
  +findStatus()
}
class Publisher {
  -Date level
  -Date name
  +saveType()
  +createId()
  +saveTotal()
}
abstract class Reservation {
  -double amount
  #int price
  +float description
  #String address
  +deleteCode()
}
class Fine {
  +boolean note
  -Date duration
  +deleteQuantity()
  +processPrice()
  +updateScore()
  +setName()
}
class Branch {
  -float address
  -double note
  #int price
  -float active
  +getStatus()
  +saveActive()
  +deleteId()
}
abstract class Librarian {
  #String note
  #float description
  +double active
  +long code
  +getType()
  +sendScore()
  +createPhone()
}
Fine --|> Reservation
Librarian --|> Publisher
Branch --o Fine
@enduml