@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
interface Branch {
  -float price
  #Date total
  +saveLevel()
  +sendAmount()
}
class Account {
  -Date status
  +boolean phone
  +validateTotal()
  +validateName()
  +validateScore()
}
class Teller {
  #int name
  +long duration
  #Date type
  +deleteActive()
}
class Interest {
  #String code
  +boolean price
  +long quantity
  +boolean email
  +cancelLevel()
  +processStatus()
}
Branch --> Teller : "*"
Account --* Teller
Teller ..> Interest : "*"
@enduml