@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
class Author {
  -int quantity
  +boolean updatedAt
  #boolean duration
  #int code
  +double email
  +saveEmail()
  +findId()
}
interface Publisher {
  -int code
  #int email
  +float description
  #long total
  +validateScore()
}
abstract class Librarian {
  #Date status
  -double email
  +String id
  #boolean price
  +String active
  +getActive()
}
class Loan {
  +long updatedAt
  +long code
  +double email
  #long score
  +getPhone()
}
abstract class Reservation {
  #boolean type
  #Date price
  +float name
  +validateScore()
  +getName()
}
Reservation ..|> Author
Librarian --o Loan
@enduml