@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
class Librarian {
  -int name
  +int level
  +float id
  #double active
  +calculateLevel()
}
class Fine {
  -Date phone
  #long note
  -String duration
  +Date name
  +createScore()
  +updateCreatedat()
  +sendStatus()
}
class Book {
  #long email
  #long address
  +deleteNote()
  +processDuration()
  +saveTotal()
  +deleteEmail()
}
class Member {
  -double total
  -int active
  #boolean email
  #long type
  -String status
  +findTotal()
  +createStatus()
  +getScore()
}
Member --o Fine
Librarian ..> Fine : "1..*"
Member ..|> Book
@enduml