@startuml
skinparam monochrome true
skinparam defaultFontSize 13
class Hashtag {
  #Date description
  #int level
  #Date updatedAt
  +setCode()
  +calculateLevel()
  +deleteAddress()
}
class Profile {
  #String level
  +double score
  -float address
  +calculateAmount()
  +validateTotal()
  +cancelLevel()
  +setQuantity()
}
interface Report {
  -String code
  #float status
  +long active
  -Date id
  +findUpdatedat()
  +calculateId()
  +deleteNote()
}
class Follower {
  #double price
  #double phone
  -Date total
  -Date id
  -long status
  +saveType()
  +sendType()
  +deleteUpdatedat()
}
class Album {
  +int quantity
  #String duration
  -long active
  #float address
  +boolean note
  +cancelCode()
  +cancelName()
}
class User {
  +float updatedAt
  +Date level
  +boolean quantity
  +int code
  #float phone
  +findDescription()
  +validateQuantity()
}
abstract class Like {
  #String id
  +String updatedAt
  #Date duration
  +boolean level
  +long type
  +createType()
}
Album --> Hashtag : "1"
Profile --* Album
@enduml