@startuml
skinparam monochrome true
skinparam defaultFontSize 11
abstract class Interest {
  +double description
  #String name
  +getCreatedat()
}
class Branch {
  +long phone
  #float name
  +float createdAt
  #float quantity
  -float duration
  +setDuration()
  +calculateName()
  +setDescription()
}
abstract class Transaction {
  +Date createdAt
  +float price
  #String duration
  +boolean phone
  +cancelCode()
  +findAmount()
  +createAddress()
  +cancelStatus()
}
interface Statement {
  -Date description
  #double updatedAt
  -Date total
  +float id
  #int status
  +sendAddress()
  +createUpdatedat()
}
class Customer {
  #double createdAt
  +boolean level
  +saveDuration()
  +getPhone()
  +sendStatus()
}
class Withdrawal {
  -float price
  -float amount
  -Date level
  -long quantity
  +updateEmail()
}
class Deposit {
  -boolean active
  #long quantity
  -boolean updatedAt
  +createScore()
}
Branch --o Interest
Interest ..> Deposit : "1..*"
@enduml