@startuml
skinparam shadowing true
interface Story {
  #double duration
  +Date price
  #double type
  #int updatedAt
  +deleteEmail()
  +getId()
}
interface Message {
  -int name
  #boolean email
  +findAddress()
  +validateEmail()
  +calculateScore()
  +processQuantity()
}
class Follower {
  #String description
  -int quantity
  #Date status
  #int total
  +getNote()
  +findNote()
}
interface Profile {
  -boolean address
  -float score
  #Date note
  #double duration
  +savePrice()
  +sendPrice()
  +processDescription()
}
abstract class Post {
  -String quantity
  -String status
  +cancelLevel()
  +createCode()
}
Story ..|> Message
Follower --|> Message
note right of Story : Social Media domain
@enduml