@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
class Account {
  #boolean type
  +String description
  #float score
  +saveAddress()
}
class Teller {
  +long address
  -boolean email
  #long code
  -double note
  +setDuration()
  +deletePhone()
}
class Statement {
  -int phone
  -boolean id
  +long amount
  +calculateScore()
  +calculateAddress()
  +createQuantity()
}
abstract class Withdrawal {
  -int address
  -float total
  +updateType()
}
abstract class Deposit {
  #int type
  -String name
  #long price
  +long description
  +validatePrice()
  +sendLevel()
}
Statement ..|> Withdrawal
Teller --|> Withdrawal
Teller ..> Account : "1"
@enduml