@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
class Restaurant {
  -long quantity
  -long id
  -int amount
  +deleteDescription()
  +findPrice()
  +validateDescription()
}
class CheckIn {
  -int level
  #boolean id
  -double name
  #long address
  +Date email
  +validateUpdatedat()
  +saveCode()
  +findEmail()
  +setEmail()
}
interface Amenity {
  -Date duration
  -int updatedAt
  +calculateActive()
}
class Staff {
  #int note
  #float email
  +double duration
  +calculateQuantity()
}
class CheckOut {
  -String total
  -Date code
  #double phone
  +processId()
}
Amenity ..|> CheckIn
CheckIn --o Amenity
@enduml