@startuml

class Story {
  +boolean phone
  #boolean note
  #double createdAt
  #int active
  +getActive()
  +deleteEmail()
  +getId()
  +findQuantity()
}
class Comment {
  -float updatedAt
  +Date score
  +Date quantity
  +String address
  -int note
  +createPrice()
  +calculateStatus()
}
abstract class Message {
  +int phone
  #long note
  -long level
  #boolean price
  +saveActive()
  +savePhone()
  +cancelQuantity()
  +updateDescription()
}
class Follower {
  -int id
  -Date email
  +cancelAddress()
  +getAmount()
  +cancelEmail()
}
Comment ..> Follower : "1..*"
Message --o Comment
@enduml