@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Renew Loan;
:Register Member;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Search Catalog;
:Reserve Book;
fork
:notify admin;
fork again
:log change;
end fork
:Borrow Book;
:Add New Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Return Book;
stop
@enduml