@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
start
:Pay Fine;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Register Member;
:Add New Book;
fork
:notify system;
fork again
:log event;
end fork
:Search Catalog;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Reserve Book;
fork
:notify system;
fork again
:log event;
end fork
:Return Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
:Renew Loan;
stop
@enduml