@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
start
:Clean Room;
:Book Room;
:Process Payment;
:Cancel Reservation;
:Check In;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Request Service;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Order Room Service;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check Out;
stop
@enduml