@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
start
:Withdraw Cash;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log action;
end fork
:Open Account;
:Pay Bill;
:Transfer Funds;
:Apply For Loan;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:View Statement;
:Deposit Money;
:Block Card;
stop
@enduml