@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
start
:Examine Patient;
:Update Medical Record;
:Discharge Patient;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Run Lab Test;
:Admit Patient;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Appointment;
stop
@enduml