@startuml
skinparam defaultFontSize 11
start
:Like Post;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Send Message;
:Report Content;
:Edit Profile;
:Comment;
:Share Post;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify system;
fork again
:log change;
end fork
:Create Post;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log action;
end fork
:Follow User;
stop
@enduml