@startuml
skinparam monochrome true
skinparam ArrowColor #555555
start
:Reserve Book;
:Borrow Book;
:Return Book;
:Register Member;
:Pay Fine;
:Add New Book;
:Search Catalog;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Renew Loan;
stop
@enduml