@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
start
:Add To Cart;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Apply Coupon;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Make Payment;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Manage Inventory;
:Cancel Order;
fork
:notify system;
fork again
:log action;
end fork
:Browse Products;
stop
@enduml