@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
start
:Issue Prescription;
:Admit Patient;
:Process Insurance Claim;
:Run Lab Test;
:Book Appointment;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Examine Patient;
:Discharge Patient;
stop
@enduml