@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
start
:Grade Exam;
:Take Attendance;
:Issue Certificate;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Enroll Course;
:Submit Assignment;
stop
@enduml