@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
start
:Grade Exam;
:Take Attendance;
:Register Student;
:View Schedule;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
stop
@enduml