@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
start
:Manage Inventory;
:Checkout;
:Write Review;
:Add To Cart;
:Apply Coupon;
stop
@enduml