@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
start
:Track Order;
:Cancel Order;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Write Review;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Make Payment;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Checkout;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Browse Products;
:Add To Cart;
:Manage Inventory;
stop
@enduml