@startuml
skinparam monochrome true
start
:Cancel Order;
:Make Payment;
:Write Review;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Checkout;
:Add To Cart;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Track Order;
stop
@enduml