@startuml
skinparam defaultFontSize 11
start
:View Statement;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Transfer Funds;
:Deposit Money;
:Apply For Loan;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log change;
end fork
:Pay Bill;
:Open Account;
stop
@enduml