@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
start
:Borrow Book;
:Pay Fine;
:Add New Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Reserve Book;
:Register Member;
stop
@enduml