@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
start
:Book Room;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify system;
fork again
:log event;
end fork
:Clean Room;
:Check Out;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Reservation;
:Request Service;
stop
@enduml