@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
start
:Apply Coupon;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Track Order;
:Make Payment;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Order;
:Manage Inventory;
fork
:notify user;
fork again
:log change;
end fork
stop
@enduml