@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
start
:Book Room;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Order Room Service;
:Process Payment;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log change;
end fork
:Check In;
:Cancel Reservation;
:Clean Room;
stop
@enduml