@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
start
:Renew Loan;
:Register Member;
:Pay Fine;
:Search Catalog;
:Reserve Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Add New Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log change;
end fork
:Return Book;
stop
@enduml