@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
start
:Request Service;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Room;
:Check Out;
:Order Room Service;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check In;
:Cancel Reservation;
:Process Payment;
:Clean Room;
stop
@enduml