@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
start
:Pay Bill;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Apply For Loan;
:View Statement;
:Transfer Funds;
fork
:notify user;
fork again
:log action;
end fork
:Withdraw Cash;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Deposit Money;
stop
@enduml