@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
start
:Transfer Funds;
:Pay Bill;
:Block Card;
fork
:notify admin;
fork again
:log action;
end fork
:Open Account;
:Apply For Loan;
:Withdraw Cash;
fork
:notify user;
fork again
:log event;
end fork
:Deposit Money;
stop
@enduml