@startuml
skinparam monochrome true
skinparam defaultFontSize 13
start
:Manage Inventory;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Browse Products;
:Cancel Order;
:Write Review;
:Make Payment;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Apply Coupon;
stop
@enduml