@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
start
:Write Review;
:Manage Inventory;
:Apply Coupon;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Checkout;
:Cancel Order;
fork
:notify system;
fork again
:log event;
end fork
stop
@enduml