@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
start
:Pay Bill;
:Withdraw Cash;
:View Statement;
:Deposit Money;
:Transfer Funds;
:Apply For Loan;
:Open Account;
fork
:notify admin;
fork again
:log change;
end fork
:Block Card;
stop
@enduml