@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
start
:Reserve Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Register Member;
:Pay Fine;
:Borrow Book;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Renew Loan;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log event;
end fork
:Add New Book;
:Return Book;
fork
:notify admin;
fork again
:log change;
end fork
:Search Catalog;
stop
@enduml