@startuml
skinparam monochrome true
start
:Grade Exam;
:Submit Assignment;
:Borrow Book;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Enroll Course;
:View Schedule;
fork
:notify user;
fork again
:log event;
end fork
stop
@enduml