@startuml
skinparam defaultFontSize 13
start
:Checkout;
:Make Payment;
:Apply Coupon;
:Browse Products;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Write Review;
stop
@enduml