@startuml

start
:Process Payment;
:Book Room;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Order Room Service;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Reservation;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check In;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check Out;
stop
@enduml