@startuml
skinparam monochrome true
skinparam defaultFontSize 13
start
:Run Lab Test;
:Admit Patient;
:Issue Prescription;
:Examine Patient;
:Discharge Patient;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Insurance Claim;
fork
:notify admin;
fork again
:log event;
end fork
:Book Appointment;
stop
@enduml