@startuml
skinparam monochrome true
skinparam ArrowColor #555555
start
:Make Payment;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Apply Coupon;
:Manage Inventory;
:Track Order;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Order;
:Checkout;
:Add To Cart;
:Browse Products;
stop
@enduml