@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
start
:Share Post;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Send Message;
:Comment;
fork
:notify system;
fork again
:log action;
end fork
:Create Post;
:Edit Profile;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Follow User;
:Report Content;
:Like Post;
stop
@enduml