@startuml
skinparam monochrome true
start
:Register Member;
:Search Catalog;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Return Book;
:Add New Book;
:Reserve Book;
:Pay Fine;
fork
:notify system;
fork again
:log event;
end fork
stop
@enduml