@startuml
skinparam monochrome true
skinparam shadowing true
start
:Make Payment;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Manage Inventory;
:Apply Coupon;
:Add To Cart;
:Track Order;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Browse Products;
:Checkout;
stop
@enduml