@startuml
skinparam defaultFontSize 11
start
:Book Room;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Reservation;
:Order Room Service;
:Request Service;
:Check Out;
:Process Payment;
stop
@enduml