@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
start
:Request Service;
:Process Payment;
:Check In;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check Out;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log change;
end fork
:Order Room Service;
stop
@enduml