@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
start
:Cancel Order;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify system;
fork again
:log change;
end fork
:Track Order;
fork
:notify user;
fork again
:log change;
end fork
:Apply Coupon;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Add To Cart;
:Make Payment;
fork
:notify system;
fork again
:log change;
end fork
stop
@enduml