@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
start
:Apply For Loan;
:Open Account;
fork
:notify admin;
fork again
:log change;
end fork
:Deposit Money;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Withdraw Cash;
:Block Card;
:Pay Bill;
:View Statement;
:Transfer Funds;
stop
@enduml