@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Request Service;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Room;
:Check In;
:Order Room Service;
:Check Out;
:Clean Room;
:Process Payment;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Reservation;
fork
:notify system;
fork again
:log change;
end fork
stop
@enduml