@startuml
skinparam monochrome true
skinparam ArrowColor #555555
start
:Register Member;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Renew Loan;
fork
:notify user;
fork again
:log change;
end fork
:Borrow Book;
:Add New Book;
:Search Catalog;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Reserve Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Fine;
stop
@enduml