@startuml

start
:Pay Fine;
:Search Catalog;
:Return Book;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log change;
end fork
:Register Member;
:Reserve Book;
:Add New Book;
:Borrow Book;
:Renew Loan;
stop
@enduml