@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
start
:Load Package;
:Schedule Pickup;
:Report Issue;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log change;
end fork
:Fuel Vehicle;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Assign Route;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Update Inventory;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log change;
end fork
:Track Shipment;
:Deliver Package;
stop
@enduml