@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
start
:Admit Patient;
:Run Lab Test;
:Discharge Patient;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Examine Patient;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Issue Prescription;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Insurance Claim;
stop
@enduml