@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
start
:Share Post;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Comment;
:Create Post;
:Report Content;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Send Message;
stop
@enduml