@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
start
:Cancel Reservation;
:Check Out;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Payment;
:Request Service;
:Order Room Service;
:Book Room;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Clean Room;
fork
:notify admin;
fork again
:log change;
end fork
stop
@enduml