@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Track Order;
:Checkout;
:Browse Products;
:Cancel Order;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Add To Cart;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log event;
end fork
:Manage Inventory;
:Write Review;
stop
@enduml