@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
start
:Issue Certificate;
:View Schedule;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Register Student;
:Enroll Course;
:Take Attendance;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Submit Assignment;
:Grade Exam;
stop
@enduml