@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
start
:Renew Loan;
:Borrow Book;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log action;
end fork
:Return Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Reserve Book;
:Search Catalog;
stop
@enduml