@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
start
:Checkout;
:Add To Cart;
:Cancel Order;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Write Review;
:Manage Inventory;
:Make Payment;
:Browse Products;
stop
@enduml