@startuml
skinparam monochrome true
skinparam ArrowColor #555555
start
:Follow User;
:Report Content;
fork
:notify user;
fork again
:log action;
end fork
:Comment;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Create Post;
:Edit Profile;
stop
@enduml