@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
start
:Add New Book;
:Pay Fine;
:Reserve Book;
:Borrow Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Return Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Search Catalog;
:Register Member;
stop
@enduml