@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
start
:Make Payment;
:Browse Products;
:Track Order;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Write Review;
:Checkout;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify system;
fork again
:log change;
end fork
:Cancel Order;
stop
@enduml