@startuml
skinparam ArrowColor #555555
start
:Track Shipment;
:Assign Route;
:Report Issue;
:Schedule Pickup;
:Update Inventory;
:Deliver Package;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Load Package;
:Fuel Vehicle;
stop
@enduml