@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
start
:Update Medical Record;
:Issue Prescription;
:Admit Patient;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Run Lab Test;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Discharge Patient;
:Examine Patient;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Appointment;
:Process Insurance Claim;
stop
@enduml