@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
start
:Check In;
:Clean Room;
:Cancel Reservation;
:Order Room Service;
:Book Room;
:Process Payment;
fork
:notify admin;
fork again
:log change;
end fork
stop
@enduml