@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
start
:Take Attendance;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:View Schedule;
:Submit Assignment;
:Enroll Course;
:Grade Exam;
:Borrow Book;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Issue Certificate;
stop
@enduml