@startuml

start
:Add New Book;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Renew Loan;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
:Search Catalog;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Reserve Book;
stop
@enduml