@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
start
:Book Appointment;
:Issue Prescription;
:Discharge Patient;
:Process Insurance Claim;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Run Lab Test;
stop
@enduml