@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
start
:Discharge Patient;
:Examine Patient;
:Book Appointment;
:Issue Prescription;
:Admit Patient;
:Run Lab Test;
:Update Medical Record;
stop
@enduml