@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
start
:Process Insurance Claim;
:Run Lab Test;
:Examine Patient;
:Discharge Patient;
:Update Medical Record;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Issue Prescription;
:Book Appointment;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Admit Patient;
stop
@enduml