@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
start
:Transfer Funds;
:View Statement;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Open Account;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Apply For Loan;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Block Card;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Deposit Money;
:Withdraw Cash;
:Pay Bill;
stop
@enduml