@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
start
:Issue Prescription;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Admit Patient;
:Book Appointment;
:Run Lab Test;
:Examine Patient;
:Process Insurance Claim;
:Discharge Patient;
stop
@enduml