@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Update Inventory;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Assign Route;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Fuel Vehicle;
fork
:notify admin;
fork again
:log action;
end fork
:Schedule Pickup;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Load Package;
stop
@enduml