@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
start
:Withdraw Cash;
:View Statement;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Block Card;
:Deposit Money;
:Open Account;
stop
@enduml