@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
start
:Update Medical Record;
:Admit Patient;
:Book Appointment;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Run Lab Test;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Insurance Claim;
:Examine Patient;
fork
:notify system;
fork again
:log change;
end fork
:Issue Prescription;
fork
:notify admin;
fork again
:log change;
end fork
stop
@enduml