@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Withdraw Cash;
:Block Card;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Bill;
:View Statement;
:Deposit Money;
:Open Account;
:Apply For Loan;
stop
@enduml