@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Deliver Package;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Fuel Vehicle;
:Schedule Pickup;
:Load Package;
:Update Inventory;
stop
@enduml