@startuml
skinparam monochrome true
skinparam ArrowColor #555555
start
:Manage Inventory;
:Write Review;
:Checkout;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Browse Products;
:Track Order;
:Apply Coupon;
stop
@enduml