@startuml
skinparam defaultFontSize 11
start
:Order Room Service;
fork
:notify admin;
fork again
:log action;
end fork
:Request Service;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Room;
:Process Payment;
:Cancel Reservation;
:Check In;
stop
@enduml