@startuml
skinparam ArrowColor #555555
start
:Cancel Reservation;
:Clean Room;
:Order Room Service;
:Check Out;
:Book Room;
:Process Payment;
:Request Service;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log action;
end fork
:Check In;
stop
@enduml