@startuml
skinparam defaultFontSize 13
start
:Renew Loan;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Register Member;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Return Book;
:Search Catalog;
:Add New Book;
:Reserve Book;
:Borrow Book;
stop
@enduml