@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Assign Route;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Report Issue;
:Deliver Package;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify system;
fork again
:log event;
end fork
:Fuel Vehicle;
:Update Inventory;
stop
@enduml