@startuml

start
:Borrow Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Fine;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Renew Loan;
:Reserve Book;
:Register Member;
fork
:notify admin;
fork again
:log event;
end fork
:Return Book;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Add New Book;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log event;
end fork
:Search Catalog;
stop
@enduml