@startuml
skinparam monochrome true
skinparam shadowing true
start
:Schedule Pickup;
:Fuel Vehicle;
:Deliver Package;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Update Inventory;
:Load Package;
:Assign Route;
stop
@enduml