@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
start
:Renew Loan;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Search Catalog;
:Return Book;
:Add New Book;
:Pay Fine;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
:Reserve Book;
:Register Member;
stop
@enduml