@startuml
skinparam defaultFontSize 11
start
:Book Appointment;
:Issue Prescription;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Admit Patient;
:Discharge Patient;
:Examine Patient;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Update Medical Record;
:Run Lab Test;
stop
@enduml