@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
start
:Withdraw Cash;
:Transfer Funds;
:Apply For Loan;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:View Statement;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Bill;
stop
@enduml