@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
start
:Pay Bill;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Open Account;
:Block Card;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Transfer Funds;
:Withdraw Cash;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Deposit Money;
:Apply For Loan;
stop
@enduml