@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
start
:Process Insurance Claim;
:Book Appointment;
fork
:notify system;
fork again
:log change;
end fork
:Issue Prescription;
:Admit Patient;
:Discharge Patient;
stop
@enduml