@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
start
:Edit Profile;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log event;
end fork
:Create Post;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Like Post;
:Comment;
:Share Post;
:Report Content;
:Send Message;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Follow User;
stop
@enduml