@startuml
skinparam shadowing true
start
:Book Room;
:Process Payment;
:Clean Room;
:Check Out;
:Check In;
:Request Service;
:Cancel Reservation;
fork
:notify user;
fork again
:log action;
end fork
:Order Room Service;
stop
@enduml