@startuml
skinparam monochrome true
skinparam shadowing true
start
:Share Post;
:Report Content;
:Follow User;
:Create Post;
fork
:notify system;
fork again
:log action;
end fork
:Comment;
stop
@enduml