@startuml
skinparam monochrome true
skinparam shadowing true
start
:Manage Inventory;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify system;
fork again
:log event;
end fork
:Apply Coupon;
:Write Review;
:Checkout;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Add To Cart;
:Browse Products;
stop
@enduml