@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
start
:Order Room Service;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log event;
end fork
:Clean Room;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check In;
:Book Room;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Payment;
:Check Out;
:Cancel Reservation;
fork
:notify admin;
fork again
:log action;
end fork
:Request Service;
stop
@enduml