@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
start
:Apply Coupon;
:Checkout;
fork
:notify admin;
fork again
:log action;
end fork
:Manage Inventory;
:Cancel Order;
:Add To Cart;
:Browse Products;
:Write Review;
stop
@enduml