@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
start
:Check In;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Clean Room;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Request Service;
:Cancel Reservation;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check Out;
stop
@enduml