@startuml
skinparam defaultFontSize 11
start
:Discharge Patient;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Admit Patient;
:Run Lab Test;
:Update Medical Record;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Appointment;
stop
@enduml