@startuml

start
:Examine Patient;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Insurance Claim;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Discharge Patient;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Appointment;
:Update Medical Record;
stop
@enduml