@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam defaultFontSize 11
start
:Pay Bill;
:Apply For Loan;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:View Statement;
:Transfer Funds;
:Block Card;
:Open Account;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Withdraw Cash;
stop
@enduml