@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Cancel Reservation;
:Check Out;
:Request Service;
:Clean Room;
:Order Room Service;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Room;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check In;
:Process Payment;
stop
@enduml