@startuml
skinparam shadowing true
start
:Deliver Package;
:Schedule Pickup;
:Update Inventory;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Assign Route;
:Load Package;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Fuel Vehicle;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Track Shipment;
stop
@enduml