@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
start
:Cancel Order;
:Add To Cart;
fork
:notify admin;
fork again
:log change;
end fork
:Make Payment;
:Track Order;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Write Review;
:Checkout;
stop
@enduml