@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
start
:Return Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Register Member;
:Add New Book;
fork
:notify system;
fork again
:log event;
end fork
:Reserve Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Fine;
stop
@enduml