@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
start
:Examine Patient;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Run Lab Test;
:Process Insurance Claim;
fork
:notify admin;
fork again
:log action;
end fork
:Issue Prescription;
:Discharge Patient;
:Admit Patient;
:Book Appointment;
:Update Medical Record;
stop
@enduml