@startuml
skinparam monochrome true
skinparam ArrowColor #555555
start
:Examine Patient;
:Issue Prescription;
:Process Insurance Claim;
:Discharge Patient;
:Run Lab Test;
:Update Medical Record;
stop
@enduml