@startuml
skinparam defaultFontSize 13
start
:Pay Fine;
:Borrow Book;
fork
:notify system;
fork again
:log change;
end fork
:Reserve Book;
:Register Member;
:Return Book;
:Add New Book;
:Search Catalog;
stop
@enduml