@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
start
:Request Service;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Room;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check Out;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Clean Room;
:Cancel Reservation;
:Check In;
stop
@enduml