@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
start
:Open Account;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Bill;
:Transfer Funds;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:View Statement;
:Apply For Loan;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Block Card;
:Deposit Money;
:Withdraw Cash;
stop
@enduml