@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
start
:Load Package;
:Fuel Vehicle;
:Update Inventory;
:Assign Route;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Schedule Pickup;
:Track Shipment;
stop
@enduml