@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
start
:Search Catalog;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
fork
:notify user;
fork again
:log change;
end fork
:Renew Loan;
:Register Member;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Add New Book;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Fine;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Reserve Book;
stop
@enduml