@startuml
skinparam defaultFontSize 11
start
:Check In;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Reservation;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Payment;
:Clean Room;
:Book Room;
stop
@enduml