@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
start
:View Statement;
:Transfer Funds;
:Apply For Loan;
:Pay Bill;
:Deposit Money;
:Open Account;
stop
@enduml