@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
start
:Clean Room;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Room;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Reservation;
:Check Out;
:Process Payment;
fork
:notify admin;
fork again
:log action;
end fork
:Order Room Service;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check In;
stop
@enduml