@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
start
:Schedule Pickup;
:Load Package;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Deliver Package;
:Track Shipment;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Report Issue;
:Assign Route;
:Fuel Vehicle;
stop
@enduml