@startuml
skinparam monochrome true
skinparam defaultFontSize 13
start
:Grade Exam;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Take Attendance;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Register Student;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Enroll Course;
:Borrow Book;
stop
@enduml