@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
start
:Block Card;
:Withdraw Cash;
:Pay Bill;
:Open Account;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log change;
end fork
:Transfer Funds;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:View Statement;
:Apply For Loan;
fork
:notify admin;
fork again
:log change;
end fork
stop
@enduml