@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
start
:Register Member;
:Renew Loan;
:Search Catalog;
:Borrow Book;
:Add New Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Return Book;
stop
@enduml