@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 13
start
:Cancel Order;
:Checkout;
:Add To Cart;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Track Order;
:Make Payment;
fork
:notify system;
fork again
:log action;
end fork
stop
@enduml