@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Fuel Vehicle;
:Assign Route;
fork
:notify admin;
fork again
:log event;
end fork
:Deliver Package;
:Load Package;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Report Issue;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Schedule Pickup;
:Update Inventory;
stop
@enduml