@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
start
:Renew Loan;
:Register Member;
:Reserve Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Return Book;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Fine;
stop
@enduml