@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
start
:Block Card;
:Pay Bill;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log action;
end fork
:View Statement;
:Deposit Money;
:Apply For Loan;
:Transfer Funds;
:Withdraw Cash;
:Open Account;
stop
@enduml