@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
start
:Discharge Patient;
:Admit Patient;
:Process Insurance Claim;
:Book Appointment;
fork
:notify user;
fork again
:log action;
end fork
:Issue Prescription;
stop
@enduml