@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Book Appointment;
:Process Insurance Claim;
:Issue Prescription;
:Admit Patient;
:Update Medical Record;
:Run Lab Test;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Discharge Patient;
stop
@enduml