@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
start
:Checkout;
:Browse Products;
:Add To Cart;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Order;
:Manage Inventory;
:Apply Coupon;
:Track Order;
fork
:notify system;
fork again
:log change;
end fork
stop
@enduml