@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
start
:Follow User;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Edit Profile;
:Like Post;
:Report Content;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Comment;
:Create Post;
:Send Message;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Share Post;
stop
@enduml