@startuml

start
:Checkout;
:Add To Cart;
:Apply Coupon;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Make Payment;
:Track Order;
:Browse Products;
:Manage Inventory;
fork
:notify user;
fork again
:log event;
end fork
stop
@enduml