@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
start
:Assign Route;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Schedule Pickup;
:Load Package;
:Fuel Vehicle;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Deliver Package;
stop
@enduml