@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
start
:Make Payment;
fork
:notify user;
fork again
:log action;
end fork
:Add To Cart;
:Track Order;
:Checkout;
:Browse Products;
:Manage Inventory;
:Write Review;
stop
@enduml