@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam ArrowColor #555555
start
:Order Room Service;
:Check Out;
:Book Room;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Request Service;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Clean Room;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Payment;
stop
@enduml