@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
start
:Report Issue;
:Deliver Package;
:Track Shipment;
:Load Package;
:Schedule Pickup;
fork
:notify admin;
fork again
:log action;
end fork
stop
@enduml