@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
start
:Fuel Vehicle;
:Deliver Package;
:Assign Route;
fork
:notify admin;
fork again
:log change;
end fork
:Track Shipment;
:Schedule Pickup;
fork
:notify user;
fork again
:log change;
end fork
stop
@enduml