@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
start
:Cancel Reservation;
:Check Out;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Payment;
:Book Room;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Clean Room;
stop
@enduml