@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Process Payment;
:Order Room Service;
:Clean Room;
:Book Room;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check In;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check Out;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Request Service;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Reservation;
stop
@enduml