@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
start
:Check Out;
:Request Service;
fork
:notify system;
fork again
:log event;
end fork
:Check In;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Payment;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Room;
:Order Room Service;
:Cancel Reservation;
stop
@enduml