@startuml
skinparam monochrome true
start
:Make Payment;
:Track Order;
:Apply Coupon;
:Add To Cart;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Write Review;
:Browse Products;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Manage Inventory;
stop
@enduml