@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
start
:Checkout;
:Cancel Order;
:Write Review;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Manage Inventory;
:Apply Coupon;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log action;
end fork
:Add To Cart;
:Browse Products;
stop
@enduml