@startuml
skinparam monochrome true
skinparam ArrowColor #555555
start
:Track Order;
:Add To Cart;
:Make Payment;
:Manage Inventory;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Browse Products;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Order;
:Checkout;
:Write Review;
fork
:notify admin;
fork again
:log action;
end fork
stop
@enduml