@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Pay Fine;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Search Catalog;
:Reserve Book;
:Renew Loan;
:Borrow Book;
:Add New Book;
:Return Book;
stop
@enduml