@startuml
skinparam defaultFontSize 11
start
:Borrow Book;
:Register Member;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Add New Book;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Return Book;
:Renew Loan;
stop
@enduml