@startuml

start
:Cancel Reservation;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check In;
:Book Room;
:Order Room Service;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Request Service;
:Check Out;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Clean Room;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Payment;
stop
@enduml