@startuml
skinparam monochrome true
skinparam ArrowColor #555555
start
:View Schedule;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Grade Exam;
:Issue Certificate;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Register Student;
:Borrow Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Take Attendance;
:Enroll Course;
stop
@enduml