@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 13
start
:Track Order;
:Apply Coupon;
:Add To Cart;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Browse Products;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Make Payment;
:Cancel Order;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Checkout;
:Manage Inventory;
stop
@enduml