@startuml
skinparam monochrome true
skinparam defaultFontSize 13
start
:Like Post;
:Create Post;
:Edit Profile;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Send Message;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Comment;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Follow User;
stop
@enduml