@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Process Insurance Claim;
:Issue Prescription;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Examine Patient;
:Admit Patient;
:Discharge Patient;
stop
@enduml