@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam shadowing true
start
:Register Member;
:Renew Loan;
fork
:notify system;
fork again
:log action;
end fork
:Return Book;
:Borrow Book;
:Pay Fine;
:Search Catalog;
:Add New Book;
stop
@enduml