@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 11
start
:Check Out;
:Request Service;
fork
:notify user;
fork again
:log event;
end fork
:Check In;
fork
:notify user;
fork again
:log action;
end fork
:Process Payment;
:Clean Room;
stop
@enduml