@startuml
skinparam defaultFontSize 11
start
:Edit Profile;
:Create Post;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify system;
fork again
:log action;
end fork
:Follow User;
:Comment;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Share Post;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Send Message;
stop
@enduml