@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam ArrowColor #555555
start
:Discharge Patient;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log change;
end fork
:Issue Prescription;
:Examine Patient;
:Process Insurance Claim;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Run Lab Test;
:Admit Patient;
stop
@enduml