@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
start
:Track Shipment;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Assign Route;
:Report Issue;
:Schedule Pickup;
:Load Package;
:Fuel Vehicle;
:Deliver Package;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Update Inventory;
stop
@enduml