@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
start
:Manage Inventory;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Make Payment;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Checkout;
:Add To Cart;
:Cancel Order;
:Apply Coupon;
stop
@enduml