@startuml
skinparam defaultFontSize 11
start
:Pay Fine;
:Add New Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Reserve Book;
:Borrow Book;
:Register Member;
stop
@enduml