@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
start
:Apply For Loan;
:View Statement;
fork
:notify user;
fork again
:log change;
end fork
:Deposit Money;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify admin;
fork again
:log action;
end fork
:Open Account;
:Pay Bill;
fork
:notify admin;
fork again
:log action;
end fork
stop
@enduml