@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
start
:Deposit Money;
:Pay Bill;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log change;
end fork
:Block Card;
fork
:notify user;
fork again
:log action;
end fork
:Open Account;
fork
:notify admin;
fork again
:log change;
end fork
:Transfer Funds;
:Withdraw Cash;
:Apply For Loan;
stop
@enduml