@startuml
skinparam defaultFontSize 13
start
:Assign Route;
:Fuel Vehicle;
:Report Issue;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Schedule Pickup;
fork
:notify system;
fork again
:log change;
end fork
:Update Inventory;
:Load Package;
stop
@enduml