@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:View Schedule;
:Grade Exam;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
:Take Attendance;
:Issue Certificate;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Enroll Course;
:Register Student;
stop
@enduml