@startuml
skinparam shadowing true
start
:Clean Room;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Book Room;
:Cancel Reservation;
:Process Payment;
:Order Room Service;
:Request Service;
:Check Out;
fork
:notify system;
fork again
:log action;
end fork
:Check In;
stop
@enduml