@startuml
skinparam monochrome true
start
:Check Out;
:Check In;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Reservation;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Request Service;
:Order Room Service;
stop
@enduml