@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
start
:Renew Loan;
:Reserve Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Add New Book;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Borrow Book;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Pay Fine;
:Register Member;
stop
@enduml