@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
start
:View Statement;
:Withdraw Cash;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Open Account;
:Transfer Funds;
:Block Card;
fork
:notify user;
fork again
:log action;
end fork
:Deposit Money;
:Pay Bill;
:Apply For Loan;
stop
@enduml