@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
start
:Block Card;
fork
:notify system;
fork again
:log change;
end fork
:Deposit Money;
:Transfer Funds;
:Apply For Loan;
:Pay Bill;
:Open Account;
fork
:notify system;
fork again
:log change;
end fork
:View Statement;
stop
@enduml