@startuml
skinparam monochrome true
skinparam shadowing true
start
:Grade Exam;
:Borrow Book;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Issue Certificate;
:Register Student;
:View Schedule;
stop
@enduml