@startuml

start
:Deposit Money;
fork
:notify system;
fork again
:log event;
end fork
:Open Account;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log action;
end fork
:View Statement;
:Apply For Loan;
:Withdraw Cash;
stop
@enduml