@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
start
:Add To Cart;
:Write Review;
:Checkout;
:Cancel Order;
:Apply Coupon;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Manage Inventory;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Track Order;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Make Payment;
stop
@enduml