@startuml
skinparam ArrowColor #555555
start
:Order Room Service;
:Clean Room;
:Check In;
:Check Out;
:Book Room;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Request Service;
:Cancel Reservation;
:Process Payment;
stop
@enduml