@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Fuel Vehicle;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Assign Route;
:Report Issue;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Track Shipment;
:Deliver Package;
stop
@enduml