@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
start
:Pay Fine;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Register Member;
:Return Book;
:Add New Book;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Search Catalog;
:Renew Loan;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Reserve Book;
stop
@enduml