@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Schedule Pickup;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Update Inventory;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Fuel Vehicle;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify system;
fork again
:log event;
end fork
:Assign Route;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Load Package;
:Report Issue;
stop
@enduml