@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
start
:Add New Book;
:Pay Fine;
:Return Book;
:Borrow Book;
:Search Catalog;
:Reserve Book;
:Register Member;
stop
@enduml