@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Follow User;
:Create Post;
:Send Message;
:Like Post;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Edit Profile;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Comment;
stop
@enduml