@startuml
skinparam monochrome true
skinparam defaultFontSize 11
start
:Make Payment;
:Manage Inventory;
:Checkout;
:Write Review;
fork
:notify system;
fork again
:log action;
end fork
:Cancel Order;
stop
@enduml