@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Pay Fine;
:Borrow Book;
:Reserve Book;
:Search Catalog;
:Renew Loan;
:Return Book;
:Register Member;
:Add New Book;
stop
@enduml