@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Discharge Patient;
:Process Insurance Claim;
:Issue Prescription;
:Run Lab Test;
fork
:notify user;
fork again
:log action;
end fork
:Examine Patient;
:Book Appointment;
:Admit Patient;
stop
@enduml