@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
start
:View Statement;
fork
:notify admin;
fork again
:log action;
end fork
:Block Card;
:Apply For Loan;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Open Account;
:Pay Bill;
:Deposit Money;
:Transfer Funds;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Withdraw Cash;
stop
@enduml