@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
start
:Apply For Loan;
:Transfer Funds;
if (success?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Withdraw Cash;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Open Account;
fork
:notify user;
fork again
:log change;
end fork
:View Statement;
stop
@enduml