@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
start
:Load Package;
:Report Issue;
:Schedule Pickup;
:Assign Route;
:Fuel Vehicle;
:Deliver Package;
stop
@enduml