@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
start
:Book Room;
fork
:notify admin;
fork again
:log event;
end fork
:Cancel Reservation;
:Check Out;
:Request Service;
if (approved?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Process Payment;
:Order Room Service;
stop
@enduml