@startuml

start
:Request Service;
:Process Payment;
:Check In;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
fork
:notify user;
fork again
:log action;
end fork
:Book Room;
:Order Room Service;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Clean Room;
:Cancel Reservation;
if (valid?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Check Out;
stop
@enduml