@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
start
:Manage Inventory;
:Browse Products;
:Make Payment;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Checkout;
if (available?) then (yes)
:continue process;
else (no)
:handle error;
stop
endif
:Cancel Order;
stop
@enduml