@startuml
skinparam ArrowColor #555555
control "Chef" as C
participant "Receptionist" as R
boundary "Housekeeper" as H
participant "Manager" as M
entity "Guest" as G
C ->> R : Order Room Service
C --> G : Check Out
H --> G : Cancel Reservation
G ->> C : Clean Room
note over C : processing clean room
@enduml