@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
control "Librarian" as L
actor "Admin" as A
actor "Member" as M
L --> A : Pay Fine
A --> L : Reserve Book
activate L
L --> A : ACK
deactivate L
M --> L : Borrow Book
L -> M : Add New Book
activate M
M --> L : ACK
deactivate M
note over M : processing add new book
@enduml