@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
actor "Receptionist" as R
participant "Housekeeper" as H
participant "Manager" as M
boundary "Chef" as C
participant "Guest" as G
C -> H : Check In
H ->> M : Clean Room
R --> G : Process Payment
C -> M : Cancel Reservation
note over M : processing cancel reservation
M ->> G : Book Room
@enduml