@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
boundary "Teacher" as T
entity "Parent" as P
control "Registrar" as R
participant "Librarian" as L
T --> P : Grade Exam
P ->> T : Register Student
L --> T : Take Attendance
note over T : processing take attendance
L --> P : Issue Certificate
@enduml