@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam ArrowColor #555555
entity "Bank Teller" as BT
actor "Auditor" as A
boundary "ATM" as A2
participant "Branch Manager" as BM
A2 ->> A : Apply For Loan
activate A
A --> A2 : ACK
deactivate A
BM -> A2 : View Statement
note over A2 : processing view statement
A2 -> A : Open Account
BM -> BT : Transfer Funds
@enduml