@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
control "Auditor" as A
actor "Branch Manager" as BM
boundary "ATM" as A2
participant "Account Holder" as AH
entity "Bank Teller" as BT
AH --> BT : View Statement
BM -> BT : Transfer Funds
AH ->> A : Open Account
activate A
A --> AH : ACK
deactivate A
BT -> BM : Pay Bill
@enduml