@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
boundary "User" as U
participant "Advertiser" as A
control "Moderator" as M
participant "Admin" as A2
U -> M : Follow User
activate M
M --> U : ACK
deactivate M
M ->> U : Comment
A --> M : Share Post
activate M
M --> A : ACK
deactivate M
A ->> U : Edit Profile
note over U : processing edit profile
@enduml