@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
boundary "Registrar" as R
actor "Student" as S
participant "Parent" as P
P -> R : Issue Certificate
R ->> P : Take Attendance
P -> S : View Schedule
note over S : processing view schedule
S ->> R : Submit Assignment
@enduml