@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
entity "Librarian" as L
control "Member" as M
participant "Admin" as A
L -> M : Register Member
M --> L : Search Catalog
A ->> L : Pay Fine
A ->> L : Return Book
A ->> L : Borrow Book
activate L
L --> A : ACK
deactivate L
@enduml