@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
actor "Driver" as D
boundary "Fleet Manager" as FM
entity "Warehouse Staff" as WS
actor "Customer" as C
C --> FM : Schedule Pickup
activate FM
FM --> C : ACK
deactivate FM
note over FM : processing schedule pickup
FM ->> D : Load Package
activate D
D --> FM : ACK
deactivate D
FM ->> C : Update Inventory
note over C : processing update inventory
D ->> WS : Track Shipment
activate WS
WS --> D : ACK
deactivate WS
note over WS : processing track shipment
D --> C : Deliver Package
note over C : processing deliver package
@enduml