@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
participant "Warehouse Staff" as WS
entity "Fleet Manager" as FM
actor "Dispatcher" as D
FM --> WS : Update Inventory
activate WS
WS --> FM : ACK
deactivate WS
note over WS : processing update inventory
D ->> FM : Report Issue
note over FM : processing report issue
FM -> WS : Load Package
D -> WS : Track Shipment
activate WS
WS --> D : ACK
deactivate WS
@enduml