@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam defaultFontSize 13
boundary "Customer" as C
participant "Delivery Service" as DS
participant "Payment Gateway" as PG
boundary "Admin" as A
boundary "Seller" as S
C --> A : Add To Cart
activate A
A --> C : ACK
deactivate A
C -> PG : Track Order
S ->> A : Write Review
A --> DS : Checkout
activate DS
DS --> A : ACK
deactivate DS
A ->> C : Apply Coupon
PG -> S : Browse Products
S --> DS : Make Payment
activate DS
DS --> S : ACK
deactivate DS
note over DS : processing make payment
@enduml