@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
control "Registrar" as R
participant "Teacher" as T
participant "Admin" as A
R ->> A : Borrow Book
activate A
A --> R : ACK
deactivate A
R --> A : Grade Exam
activate A
A --> R : ACK
deactivate A
R --> T : Submit Assignment
R -> A : Enroll Course
@enduml