@startuml
skinparam shadowing true
actor "Delivery Service" as DS
boundary "Seller" as S
boundary "Admin" as A
DS --> A : Checkout
A ->> S : Browse Products
A ->> DS : Track Order
activate DS
DS --> A : ACK
deactivate DS
A ->> DS : Manage Inventory
activate DS
DS --> A : ACK
deactivate DS
@enduml