@startuml
skinparam defaultFontSize 13
control "Receptionist" as R
actor "Nurse" as N
control "Insurance Provider" as IP
N ->> IP : Issue Prescription
N ->> IP : Examine Patient
activate IP
IP --> N : ACK
deactivate IP
R --> IP : Admit Patient
R -> IP : Book Appointment
@enduml