@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
control "Delivery Service" as DS
participant "Customer" as C
participant "Admin" as A
A ->> DS : Manage Inventory
DS -> A : Write Review
DS -> C : Track Order
activate C
C --> DS : ACK
deactivate C
A ->> DS : Browse Products
activate DS
DS --> A : ACK
deactivate DS
A ->> DS : Cancel Order
DS ->> A : Apply Coupon
note over A : processing apply coupon
@enduml