@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
actor "Librarian" as L
entity "Admin" as A
entity "Member" as M
A ->> L : Pay Fine
L --> A : Register Member
activate A
A --> L : ACK
deactivate A
M -> A : Add New Book
note over A : processing add new book
L ->> M : Search Catalog
L --> M : Borrow Book
L -> M : Reserve Book
@enduml