@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
control "Lab Technician" as LT
actor "Receptionist" as R
control "Nurse" as N
actor "Patient" as P
P ->> LT : Process Insurance Claim
activate LT
LT --> P : ACK
deactivate LT
note over LT : processing process insurance claim
N -> LT : Book Appointment
note over LT : processing book appointment
LT --> P : Admit Patient
LT -> R : Examine Patient
N ->> LT : Update Medical Record
activate LT
LT --> N : ACK
deactivate LT
@enduml