@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
actor "Delivery Service" as DS
participant "Payment Gateway" as PG
actor "Admin" as A
PG -> A : Browse Products
A ->> PG : Write Review
DS --> PG : Apply Coupon
PG --> DS : Cancel Order
DS -> A : Make Payment
@enduml