@startuml

boundary "Housekeeper" as H
participant "Guest" as G
actor "Receptionist" as R
R --> H : Request Service
G --> H : Book Room
activate H
H --> G : ACK
deactivate H
G ->> R : Check Out
H --> R : Process Payment
H ->> R : Clean Room
activate R
R --> H : ACK
deactivate R
@enduml