@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
participant "Account Holder" as AH
control "Branch Manager" as BM
control "Auditor" as A
BM -> A : Pay Bill
AH -> BM : Block Card
BM --> A : Apply For Loan
BM -> AH : Withdraw Cash
note over AH : processing withdraw cash
AH -> A : Transfer Funds
note over A : processing transfer funds
A ->> AH : Open Account
activate AH
AH --> A : ACK
deactivate AH
note over AH : processing open account
@enduml