@startuml
skinparam defaultFontSize 13
actor "Moderator" as M
participant "Admin" as A
boundary "Advertiser" as A2
M ->> A2 : Like Post
activate A2
A2 --> M : ACK
deactivate A2
A2 --> A : Send Message
activate A
A --> A2 : ACK
deactivate A
A2 -> M : Comment
M ->> A2 : Report Content
A -> A2 : Edit Profile
@enduml