@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
boundary "Admin" as A
actor "Moderator" as M
entity "Advertiser" as A2
participant "User" as U
A ->> U : Share Post
A2 --> U : Report Content
M --> U : Follow User
M -> A : Send Message
activate A
A --> M : ACK
deactivate A
U ->> A : Create Post
activate A
A --> U : ACK
deactivate A
A --> U : Like Post
@enduml