@startuml
skinparam shadowing true
entity "Delivery Service" as DS
boundary "Customer" as C
control "Admin" as A
control "Payment Gateway" as PG
DS ->> C : Checkout
A ->> C : Apply Coupon
activate C
C --> A : ACK
deactivate C
PG --> A : Cancel Order
note over A : processing cancel order
A -> PG : Make Payment
activate PG
PG --> A : ACK
deactivate PG
C --> A : Browse Products
A --> DS : Add To Cart
@enduml