@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
control "User" as U
entity "Admin" as A
entity "Advertiser" as A2
A -> A2 : Send Message
activate A2
A2 --> A : ACK
deactivate A2
note over A2 : processing send message
A --> U : Report Content
note over U : processing report content
A ->> U : Like Post
activate U
U --> A : ACK
deactivate U
A -> A2 : Comment
note over A2 : processing comment
@enduml