@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
participant "Advertiser" as A
control "Moderator" as M
entity "User" as U
control "Admin" as A2
M ->> A : Like Post
U -> M : Edit Profile
activate M
M --> U : ACK
deactivate M
M --> A : Comment
A -> M : Create Post
A ->> A2 : Follow User
activate A2
A2 --> A : ACK
deactivate A2
A --> A2 : Share Post
@enduml