@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
boundary "Account Holder" as AH
participant "ATM" as A
actor "Auditor" as A2
A --> AH : Apply For Loan
AH -> A : Deposit Money
AH -> A : Withdraw Cash
activate A
A --> AH : ACK
deactivate A
note over A : processing withdraw cash
A2 ->> AH : Transfer Funds
@enduml