@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
actor "Teacher" as T
entity "Parent" as P
actor "Librarian" as L
P --> L : Register Student
L --> P : Issue Certificate
activate P
P --> L : ACK
deactivate P
L --> P : Take Attendance
L ->> P : Borrow Book
note over P : processing borrow book
@enduml