@startuml
skinparam monochrome true
skinparam ArrowColor #555555
control "User" as U
participant "Advertiser" as A
actor "Moderator" as M
U ->> A : Send Message
M ->> A : Comment
U --> M : Like Post
A --> U : Follow User
@enduml