@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
boundary "Librarian" as L
boundary "Member" as M
entity "Admin" as A
L --> M : Search Catalog
L ->> M : Borrow Book
A -> M : Pay Fine
L --> A : Add New Book
@enduml