@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam shadowing true
entity "Parent" as P
entity "Librarian" as L
entity "Student" as S
L -> P : Grade Exam
S ->> P : Register Student
activate P
P --> S : ACK
deactivate P
S -> L : Take Attendance
activate L
L --> S : ACK
deactivate L
L ->> S : Submit Assignment
activate S
S --> L : ACK
deactivate S
S ->> L : View Schedule
@enduml