@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
entity "Librarian" as L
entity "Admin" as A
boundary "Registrar" as R
boundary "Teacher" as T
T ->> A : Take Attendance
T -> A : Submit Assignment
activate A
A --> T : ACK
deactivate A
A --> L : Borrow Book
A --> T : Issue Certificate
T ->> A : View Schedule
@enduml