@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
control "Moderator" as M
actor "Advertiser" as A
participant "Admin" as A2
actor "User" as U
A2 ->> U : Like Post
A ->> M : Edit Profile
activate M
M --> A : ACK
deactivate M
U -> A2 : Share Post
activate A2
A2 --> U : ACK
deactivate A2
A2 -> M : Report Content
activate M
M --> A2 : ACK
deactivate M
A2 ->> M : Create Post
activate M
M --> A2 : ACK
deactivate M
@enduml