@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
actor "Librarian" as L
participant "Member" as M
entity "Admin" as A
L -> M : Return Book
activate M
M --> L : ACK
deactivate M
A --> M : Register Member
activate M
M --> A : ACK
deactivate M
A ->> M : Renew Loan
L --> A : Pay Fine
L --> A : Add New Book
note over A : processing add new book
L -> A : Reserve Book
note over A : processing reserve book
@enduml