@startuml
skinparam shadowing true
participant "Fleet Manager" as FM
entity "Driver" as D
participant "Customer" as C
C ->> FM : Fuel Vehicle
activate FM
FM --> C : ACK
deactivate FM
C -> D : Update Inventory
FM --> D : Schedule Pickup
activate D
D --> FM : ACK
deactivate D
D ->> FM : Assign Route
activate FM
FM --> D : ACK
deactivate FM
@enduml