@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam shadowing true
participant "Bank Teller" as BT
actor "Account Holder" as AH
control "Branch Manager" as BM
boundary "ATM" as A
BM ->> BT : Apply For Loan
AH -> A : View Statement
note over A : processing view statement
BM ->> A : Pay Bill
BM --> A : Withdraw Cash
@enduml