@startuml

actor "Payment Gateway" as PG
participant "Delivery Service" as DS
control "Customer" as C
actor "Seller" as S
S -> PG : Apply Coupon
S --> DS : Track Order
PG ->> S : Write Review
activate S
S --> PG : ACK
deactivate S
S ->> DS : Make Payment
PG --> S : Browse Products
activate S
S --> PG : ACK
deactivate S
@enduml