@startuml

boundary "Admin" as A
participant "Librarian" as L
entity "Member" as M
L -> A : Borrow Book
activate A
A --> L : ACK
deactivate A
A --> L : Add New Book
L -> M : Search Catalog
A ->> M : Renew Loan
A ->> M : Register Member
M --> L : Return Book
@enduml