@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
participant "Student" as S
actor "Teacher" as T
actor "Registrar" as R
S -> R : Issue Certificate
T --> R : Submit Assignment
S -> R : Borrow Book
activate R
R --> S : ACK
deactivate R
R ->> S : View Schedule
S -> T : Register Student
@enduml