@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam defaultFontSize 13
participant "ATM" as A
control "Bank Teller" as BT
entity "Branch Manager" as BM
participant "Account Holder" as AH
A ->> BT : Apply For Loan
A -> BM : View Statement
BM ->> A : Open Account
note over A : processing open account
AH --> BM : Block Card
activate BM
BM --> AH : ACK
deactivate BM
A ->> BT : Transfer Funds
BT -> A : Pay Bill
BM -> A : Deposit Money
activate A
A --> BM : ACK
deactivate A
note over A : processing deposit money
@enduml