@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
participant "Member" as M
boundary "Librarian" as L
control "Admin" as A
L -> A : Return Book
L -> M : Add New Book
activate M
M --> L : ACK
deactivate M
M --> L : Borrow Book
L ->> M : Reserve Book
activate M
M --> L : ACK
deactivate M
@enduml