@startuml

control "Receptionist" as R
actor "Guest" as G
entity "Manager" as M
entity "Housekeeper" as H
entity "Chef" as C
G -> C : Check Out
M --> G : Cancel Reservation
activate G
G --> M : ACK
deactivate G
R ->> C : Check In
C --> R : Book Room
activate R
R --> C : ACK
deactivate R
@enduml