@startuml
skinparam monochrome true
skinparam ArrowColor #555555
control "Housekeeper" as H
actor "Guest" as G
participant "Manager" as M
boundary "Chef" as C
M --> C : Check Out
C -> G : Check In
C --> M : Process Payment
G ->> M : Order Room Service
M -> H : Book Room
activate H
H --> M : ACK
deactivate H
@enduml