@startuml
skinparam monochrome true
skinparam ArrowColor #555555
control "Bank Teller" as BT
participant "ATM" as A
entity "Branch Manager" as BM
BT --> A : Apply For Loan
BM ->> BT : Withdraw Cash
BT -> A : Block Card
note over A : processing block card
BT -> BM : Transfer Funds
A -> BM : Pay Bill
activate BM
BM --> A : ACK
deactivate BM
note over BM : processing pay bill
@enduml