@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
entity "Fleet Manager" as FM
actor "Dispatcher" as D
actor "Customer" as C
control "Driver" as D2
D2 -> FM : Fuel Vehicle
D2 --> D : Update Inventory
C --> D2 : Deliver Package
D2 -> FM : Assign Route
note over FM : processing assign route
@enduml