@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
entity "Moderator" as M
actor "Admin" as A
control "Advertiser" as A2
boundary "User" as U
M -> U : Edit Profile
activate U
U --> M : ACK
deactivate U
A ->> U : Create Post
U -> A : Send Message
A ->> U : Like Post
note over U : processing like post
M --> U : Report Content
@enduml