@startuml
skinparam monochrome true
skinparam defaultFontSize 13
control "Auditor" as A
entity "Account Holder" as AH
participant "Bank Teller" as BT
AH ->> A : Deposit Money
activate A
A --> AH : ACK
deactivate A
AH ->> A : Open Account
AH --> BT : Transfer Funds
note over BT : processing transfer funds
A ->> AH : Apply For Loan
A ->> AH : Withdraw Cash
AH --> BT : Block Card
@enduml