@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
control "Teacher" as T
actor "Parent" as P
boundary "Student" as S
P -> S : Take Attendance
T ->> P : Issue Certificate
P ->> S : View Schedule
P ->> S : Borrow Book
note over S : processing borrow book
S -> T : Enroll Course
activate T
T --> S : ACK
deactivate T
@enduml