@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
entity "Branch Manager" as BM
control "Account Holder" as AH
actor "Auditor" as A
boundary "Bank Teller" as BT
boundary "ATM" as A2
BM ->> BT : Transfer Funds
activate BT
BT --> BM : ACK
deactivate BT
note over BT : processing transfer funds
A --> A2 : Apply For Loan
AH ->> BM : Open Account
BT --> A2 : Pay Bill
activate A2
A2 --> BT : ACK
deactivate A2
@enduml