@startuml
skinparam monochrome true
skinparam defaultFontSize 13
control "Lab Technician" as LT
boundary "Patient" as P
participant "Insurance Provider" as IP
participant "Receptionist" as R
P ->> R : Update Medical Record
P ->> LT : Admit Patient
IP --> LT : Discharge Patient
P --> LT : Examine Patient
@enduml