@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
entity "Teacher" as T
boundary "Student" as S
boundary "Parent" as P
boundary "Librarian" as L
entity "Admin" as A
P ->> S : View Schedule
activate S
S --> P : ACK
deactivate S
A -> S : Submit Assignment
S -> L : Issue Certificate
note over L : processing issue certificate
P -> L : Grade Exam
@enduml