@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
entity "Librarian" as L
actor "Member" as M
actor "Admin" as A
L --> M : Borrow Book
activate M
M --> L : ACK
deactivate M
L --> M : Renew Loan
activate M
M --> L : ACK
deactivate M
A ->> L : Reserve Book
activate L
L --> A : ACK
deactivate L
A --> L : Add New Book
A ->> L : Register Member
L -> M : Return Book
note over M : processing return book
@enduml