@startuml
skinparam defaultFontSize 13
participant "Admin" as A
control "Teacher" as T
actor "Librarian" as L
L ->> A : Submit Assignment
T --> L : Enroll Course
A ->> T : Grade Exam
T -> A : Borrow Book
activate A
A --> T : ACK
deactivate A
L ->> T : Register Student
T -> A : View Schedule
note over A : processing view schedule
@enduml