@startuml
skinparam defaultFontSize 11
entity "Registrar" as R
entity "Admin" as A
boundary "Teacher" as T
T --> A : Submit Assignment
note over A : processing submit assignment
T ->> A : Issue Certificate
activate A
A --> T : ACK
deactivate A
note over A : processing issue certificate
T -> A : Borrow Book
A --> T : Register Student
@enduml