@startuml

participant "Chef" as C
participant "Manager" as M
participant "Housekeeper" as H
H -> M : Cancel Reservation
M --> H : Check In
H -> C : Order Room Service
activate C
C --> H : ACK
deactivate C
C --> H : Process Payment
M -> H : Book Room
@enduml