@startuml
skinparam monochrome true
skinparam defaultFontSize 13
boundary "Moderator" as M
actor "Advertiser" as A
actor "User" as U
control "Admin" as A2
A ->> U : Send Message
A ->> M : Follow User
A2 --> A : Edit Profile
activate A
A --> A2 : ACK
deactivate A
A2 --> U : Report Content
activate U
U --> A2 : ACK
deactivate U
A -> M : Share Post
@enduml