@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
control "Teacher" as T
control "Parent" as P
entity "Registrar" as R
R -> T : Borrow Book
P -> T : Grade Exam
P --> T : Register Student
R -> P : Take Attendance
activate P
P --> R : ACK
deactivate P
R -> P : Issue Certificate
activate P
P --> R : ACK
deactivate P
T --> R : View Schedule
T -> R : Submit Assignment
@enduml