@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
participant "Admin" as A
entity "Customer" as C
actor "Payment Gateway" as PG
participant "Delivery Service" as DS
DS --> PG : Cancel Order
note over PG : processing cancel order
A ->> C : Apply Coupon
note over C : processing apply coupon
PG -> DS : Browse Products
activate DS
DS --> PG : ACK
deactivate DS
note over DS : processing browse products
DS --> C : Checkout
DS --> C : Manage Inventory
PG ->> C : Add To Cart
@enduml