@startuml
skinparam monochrome true
skinparam defaultFontSize 11
control "User" as U
boundary "Advertiser" as A
entity "Admin" as A2
actor "Moderator" as M
A -> A2 : Report Content
note over A2 : processing report content
A2 --> A : Like Post
M -> A : Comment
activate A
A --> M : ACK
deactivate A
A2 -> A : Edit Profile
@enduml