@startuml
skinparam monochrome true
skinparam ArrowColor #555555
participant "Member" as M
participant "Admin" as A
control "Librarian" as L
L -> A : Search Catalog
L -> M : Reserve Book
L -> M : Pay Fine
L ->> A : Register Member
activate A
A --> L : ACK
deactivate A
L -> M : Add New Book
L -> M : Return Book
activate M
M --> L : ACK
deactivate M
@enduml