@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
actor "Branch Manager" as BM
boundary "ATM" as A
entity "Bank Teller" as BT
BM -> BT : Transfer Funds
BM -> A : Pay Bill
A -> BT : Open Account
BT --> A : Apply For Loan
BT --> BM : Block Card
BT ->> A : View Statement
activate A
A --> BT : ACK
deactivate A
@enduml