@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
control "Advertiser" as A
control "Admin" as A2
participant "Moderator" as M
actor "User" as U
U --> M : Send Message
A ->> M : Create Post
activate M
M --> A : ACK
deactivate M
A --> A2 : Follow User
U -> M : Report Content
U --> A2 : Edit Profile
@enduml