@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
participant "Admin" as A
boundary "Advertiser" as A2
control "User" as U
entity "Moderator" as M
U ->> A : Share Post
A ->> U : Comment
M --> A : Report Content
A --> U : Edit Profile
activate U
U --> A : ACK
deactivate U
@enduml