@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 11
entity "Branch Manager" as BM
control "Bank Teller" as BT
actor "Auditor" as A
A --> BM : Open Account
BM ->> A : Block Card
note over A : processing block card
BT --> A : Transfer Funds
note over A : processing transfer funds
BT --> A : Apply For Loan
BT ->> BM : View Statement
activate BM
BM --> BT : ACK
deactivate BM
note over BM : processing view statement
BM -> A : Withdraw Cash
A --> BM : Pay Bill
activate BM
BM --> A : ACK
deactivate BM
@enduml