@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
control "Admin" as A
actor "Moderator" as M
actor "Advertiser" as A2
A ->> A2 : Follow User
M -> A : Comment
activate A
A --> M : ACK
deactivate A
A2 --> A : Edit Profile
A2 -> M : Report Content
A2 ->> A : Send Message
@enduml