@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
entity "Librarian" as L
control "Admin" as A
participant "Student" as S
A --> L : Enroll Course
A ->> S : Grade Exam
activate S
S --> A : ACK
deactivate S
S --> A : Borrow Book
S --> A : Issue Certificate
A --> S : Register Student
activate S
S --> A : ACK
deactivate S
note over S : processing register student
@enduml