@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
entity "Teacher" as T
entity "Student" as S
control "Librarian" as L
S --> T : View Schedule
note over T : processing view schedule
S --> T : Grade Exam
L ->> S : Borrow Book
L -> S : Register Student
T ->> L : Submit Assignment
@enduml