@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
control "Moderator" as M
entity "Advertiser" as A
actor "Admin" as A2
actor "User" as U
A2 -> A : Create Post
activate A
A --> A2 : ACK
deactivate A
note over A : processing create post
M --> A2 : Send Message
note over A2 : processing send message
A ->> A2 : Edit Profile
activate A2
A2 --> A : ACK
deactivate A2
A -> A2 : Like Post
activate A2
A2 --> A : ACK
deactivate A2
@enduml