@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
participant "Teacher" as T
control "Admin" as A
entity "Librarian" as L
L --> T : Grade Exam
activate T
T --> L : ACK
deactivate T
note over T : processing grade exam
A --> L : Take Attendance
L -> T : Issue Certificate
note over T : processing issue certificate
L --> A : Borrow Book
A ->> L : View Schedule
note over L : processing view schedule
@enduml