@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
actor "Student" as S
boundary "Parent" as P
actor "Librarian" as L
P -> S : Submit Assignment
activate S
S --> P : ACK
deactivate S
P --> L : View Schedule
activate L
L --> P : ACK
deactivate L
L --> P : Register Student
activate P
P --> L : ACK
deactivate P
S -> L : Issue Certificate
activate L
L --> S : ACK
deactivate L
@enduml