@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
participant "Receptionist" as R
boundary "Guest" as G
entity "Manager" as M
boundary "Housekeeper" as H
M --> H : Order Room Service
H ->> M : Process Payment
activate M
M --> H : ACK
deactivate M
M -> G : Clean Room
G ->> R : Cancel Reservation
H -> R : Check Out
activate R
R --> H : ACK
deactivate R
@enduml