@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam ArrowColor #555555
control "Account Holder" as AH
control "Bank Teller" as BT
control "ATM" as A
entity "Auditor" as A2
A -> AH : Pay Bill
note over AH : processing pay bill
A2 --> AH : Open Account
AH ->> A2 : Block Card
activate A2
A2 --> AH : ACK
deactivate A2
BT --> A2 : View Statement
@enduml