@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
control "Admin" as A
boundary "Member" as M
participant "Librarian" as L
M ->> L : Register Member
activate L
L --> M : ACK
deactivate L
A ->> L : Search Catalog
M --> L : Borrow Book
M -> L : Reserve Book
@enduml