@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 13
entity "Delivery Service" as DS
boundary "Customer" as C
actor "Seller" as S
DS ->> S : Manage Inventory
note over S : processing manage inventory
DS ->> C : Browse Products
DS --> C : Make Payment
note over C : processing make payment
C -> S : Checkout
@enduml