@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
actor "Admin" as A
participant "Advertiser" as A2
entity "User" as U
entity "Moderator" as M
A --> U : Report Content
note over U : processing report content
U --> M : Create Post
M ->> U : Comment
M ->> U : Share Post
@enduml