@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
actor "Housekeeper" as H
actor "Manager" as M
entity "Chef" as C
H ->> C : Check In
note over C : processing check in
C --> H : Process Payment
activate H
H --> C : ACK
deactivate H
H --> M : Check Out
C ->> H : Book Room
@enduml