@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
participant "Member" as M
participant "Librarian" as L
participant "Admin" as A
M --> A : Renew Loan
activate A
A --> M : ACK
deactivate A
L -> M : Reserve Book
note over M : processing reserve book
M -> L : Borrow Book
M ->> L : Pay Fine
activate L
L --> M : ACK
deactivate L
A -> L : Register Member
@enduml