@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
participant "Housekeeper" as H
actor "Receptionist" as R
participant "Manager" as M
entity "Chef" as C
H --> R : Request Service
R -> H : Check In
activate H
H --> R : ACK
deactivate H
R ->> H : Check Out
R --> M : Order Room Service
activate M
M --> R : ACK
deactivate M
H ->> R : Clean Room
@enduml