@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
entity "Admin" as A
participant "Teacher" as T
boundary "Parent" as P
P --> T : Take Attendance
A --> P : Grade Exam
P ->> A : Submit Assignment
A --> T : Enroll Course
T ->> P : Issue Certificate
A ->> P : Register Student
@enduml