@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
participant "Registrar" as R
actor "Librarian" as L
participant "Admin" as A
participant "Student" as S
participant "Parent" as P
L -> R : Issue Certificate
activate R
R --> L : ACK
deactivate R
A ->> R : Borrow Book
S --> P : Take Attendance
A -> R : Grade Exam
note over R : processing grade exam
A --> R : Submit Assignment
L -> S : Register Student
activate S
S --> L : ACK
deactivate S
@enduml