@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
participant "Admin" as A
entity "Member" as M
control "Librarian" as L
L -> A : Register Member
M ->> L : Reserve Book
note over L : processing reserve book
M -> A : Borrow Book
activate A
A --> M : ACK
deactivate A
M ->> A : Renew Loan
note over A : processing renew loan
A -> L : Add New Book
activate L
L --> A : ACK
deactivate L
note over L : processing add new book
M -> A : Search Catalog
M -> A : Return Book
@enduml