@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
entity "Lab Technician" as LT
entity "Receptionist" as R
actor "Doctor" as D
actor "Patient" as P
actor "Insurance Provider" as IP
IP --> P : Process Insurance Claim
IP --> LT : Update Medical Record
R --> IP : Run Lab Test
D --> IP : Book Appointment
R -> D : Discharge Patient
activate D
D --> R : ACK
deactivate D
@enduml