@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
boundary "Student" as S
boundary "Librarian" as L
boundary "Parent" as P
L --> S : Register Student
activate S
S --> L : ACK
deactivate S
S ->> L : Submit Assignment
activate L
L --> S : ACK
deactivate L
note over L : processing submit assignment
P --> L : Grade Exam
L ->> S : View Schedule
@enduml