@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
entity "Patient" as P
boundary "Insurance Provider" as IP
participant "Lab Technician" as LT
entity "Receptionist" as R
actor "Doctor" as D
R --> D : Run Lab Test
IP -> R : Process Insurance Claim
IP ->> D : Issue Prescription
R ->> IP : Examine Patient
activate IP
IP --> R : ACK
deactivate IP
IP -> D : Discharge Patient
note over D : processing discharge patient
@enduml