@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
control "Librarian" as L
entity "Admin" as A
actor "Member" as M
A --> M : Return Book
A -> L : Borrow Book
L -> A : Search Catalog
activate A
A --> L : ACK
deactivate A
L --> A : Reserve Book
A -> M : Pay Fine
@enduml