@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
participant "Librarian" as L
control "Member" as M
actor "Admin" as A
M ->> L : Search Catalog
A --> M : Reserve Book
note over M : processing reserve book
A -> M : Borrow Book
activate M
M --> A : ACK
deactivate M
note over M : processing borrow book
A -> M : Add New Book
@enduml