@startuml
skinparam monochrome true
skinparam ArrowColor #555555
participant "Chef" as C
control "Manager" as M
boundary "Housekeeper" as H
H --> C : Check Out
C --> H : Request Service
activate H
H --> C : ACK
deactivate H
M --> C : Cancel Reservation
M -> H : Check In
activate H
H --> M : ACK
deactivate H
@enduml