@startuml
skinparam ArrowColor #555555
entity "Admin" as A
participant "Teacher" as T
entity "Student" as S
control "Registrar" as R
A --> R : View Schedule
activate R
R --> A : ACK
deactivate R
T -> S : Borrow Book
R --> A : Submit Assignment
T -> R : Register Student
@enduml