@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
actor "Manager" as M
actor "Guest" as G
participant "Receptionist" as R
boundary "Chef" as C
actor "Housekeeper" as H
H ->> G : Book Room
note over G : processing book room
H ->> M : Cancel Reservation
C -> R : Clean Room
C -> R : Request Service
C ->> M : Check In
@enduml