@startuml

actor "Auditor" as A
participant "Branch Manager" as BM
boundary "Account Holder" as AH
entity "Bank Teller" as BT
A ->> BT : Withdraw Cash
note over BT : processing withdraw cash
A --> AH : Transfer Funds
note over AH : processing transfer funds
A -> BM : Apply For Loan
A ->> BT : Open Account
note over BT : processing open account
@enduml