@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
control "Branch Manager" as BM
boundary "ATM" as A
entity "Account Holder" as AH
control "Bank Teller" as BT
AH ->> BT : Open Account
activate BT
BT --> AH : ACK
deactivate BT
BM -> BT : Deposit Money
AH -> BT : Transfer Funds
A --> BT : Apply For Loan
BM ->> BT : Pay Bill
activate BT
BT --> BM : ACK
deactivate BT
@enduml