@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
actor "Registrar" as R
control "Student" as S
participant "Parent" as P
participant "Teacher" as T
T --> P : Register Student
activate P
P --> T : ACK
deactivate P
note over P : processing register student
S -> R : View Schedule
activate R
R --> S : ACK
deactivate R
S --> P : Take Attendance
activate P
P --> S : ACK
deactivate P
P ->> S : Borrow Book
@enduml