@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
control "Dispatcher" as D
boundary "Warehouse Staff" as WS
boundary "Customer" as C
D ->> C : Deliver Package
activate C
C --> D : ACK
deactivate C
C --> D : Track Shipment
note over D : processing track shipment
WS --> C : Update Inventory
activate C
C --> WS : ACK
deactivate C
D -> C : Assign Route
activate C
C --> D : ACK
deactivate C
@enduml