@startuml
skinparam backgroundColor #FAFAFA
skinparam classBackgroundColor #FFF3E0
skinparam classBorderColor #E65100
participant "Manager" as M
actor "Housekeeper" as H
entity "Guest" as G
G -> M : Book Room
H --> M : Request Service
activate M
M --> H : ACK
deactivate M
H -> G : Clean Room
note over G : processing clean room
G -> M : Check Out
M --> G : Process Payment
note over G : processing process payment
@enduml