@startuml
skinparam monochrome true
actor "Admin" as A
actor "Teacher" as T
control "Parent" as P
actor "Registrar" as R
entity "Student" as S
T ->> S : Borrow Book
T ->> A : Grade Exam
note over A : processing grade exam
A -> S : Enroll Course
note over S : processing enroll course
A ->> P : Submit Assignment
S -> A : Register Student
note over A : processing register student
A -> R : Issue Certificate
T -> R : Take Attendance
@enduml