@startuml

actor "Doctor" as D
entity "Patient" as P
actor "Insurance Provider" as IP
boundary "Lab Technician" as LT
IP -> LT : Process Insurance Claim
activate LT
LT --> IP : ACK
deactivate LT
D ->> LT : Issue Prescription
P --> LT : Examine Patient
activate LT
LT --> P : ACK
deactivate LT
D --> LT : Admit Patient
activate LT
LT --> D : ACK
deactivate LT
LT -> D : Discharge Patient
D -> P : Run Lab Test
note over P : processing run lab test
IP ->> LT : Book Appointment
note over LT : processing book appointment
@enduml