@startuml
skinparam monochrome true
skinparam shadowing true
participant "Student" as S
control "Parent" as P
control "Registrar" as R
P -> R : Register Student
activate R
R --> P : ACK
deactivate R
R ->> P : Grade Exam
activate P
P --> R : ACK
deactivate P
R --> P : Take Attendance
R -> S : View Schedule
S -> P : Borrow Book
activate P
P --> S : ACK
deactivate P
P -> R : Enroll Course
activate R
R --> P : ACK
deactivate R
@enduml