@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
participant "Manager" as M
actor "Receptionist" as R
control "Housekeeper" as H
R --> H : Order Room Service
R --> M : Book Room
R --> H : Request Service
activate H
H --> R : ACK
deactivate H
M -> H : Process Payment
M -> R : Check Out
@enduml