@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam shadowing true
actor "Branch Manager" as BM
actor "Account Holder" as AH
boundary "Bank Teller" as BT
participant "Auditor" as A
AH --> BT : Block Card
BM ->> A : Pay Bill
activate A
A --> BM : ACK
deactivate A
A --> BM : Transfer Funds
activate BM
BM --> A : ACK
deactivate BM
BT --> AH : Apply For Loan
@enduml