@startuml
skinparam ArrowColor #555555
participant "Registrar" as R
participant "Teacher" as T
boundary "Librarian" as L
R --> L : View Schedule
R ->> T : Grade Exam
activate T
T --> R : ACK
deactivate T
R --> L : Enroll Course
activate L
L --> R : ACK
deactivate L
R --> T : Submit Assignment
activate T
T --> R : ACK
deactivate T
T ->> R : Issue Certificate
activate R
R --> T : ACK
deactivate R
@enduml