@startuml
skinparam shadowing true
participant "Parent" as P
participant "Admin" as A
actor "Registrar" as R
actor "Librarian" as L
P ->> L : Submit Assignment
P --> L : Issue Certificate
activate L
L --> P : ACK
deactivate L
P --> L : Borrow Book
L ->> R : Take Attendance
R ->> A : View Schedule
L ->> P : Enroll Course
@enduml