@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
boundary "Admin" as A
entity "Member" as M
participant "Librarian" as L
A ->> L : Return Book
M -> L : Renew Loan
M -> L : Reserve Book
note over L : processing reserve book
M ->> A : Register Member
L ->> M : Add New Book
activate M
M --> L : ACK
deactivate M
M ->> L : Search Catalog
activate L
L --> M : ACK
deactivate L
note over L : processing search catalog
A ->> L : Pay Fine
@enduml