@startuml

control "Insurance Provider" as IP
control "Doctor" as D
boundary "Receptionist" as R
D -> R : Admit Patient
activate R
R --> D : ACK
deactivate R
D ->> R : Book Appointment
R -> IP : Process Insurance Claim
D --> R : Examine Patient
activate R
R --> D : ACK
deactivate R
@enduml