@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
participant "User" as U
entity "Moderator" as M
control "Admin" as A
participant "Advertiser" as A2
M ->> U : Comment
note over U : processing comment
U --> M : Share Post
M ->> A : Send Message
A ->> U : Report Content
U --> M : Edit Profile
activate M
M --> U : ACK
deactivate M
note over M : processing edit profile
U ->> A : Create Post
@enduml