@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
boundary "Admin" as A
control "Member" as M
entity "Librarian" as L
L -> A : Pay Fine
M --> A : Register Member
L ->> M : Borrow Book
M --> L : Renew Loan
activate L
L --> M : ACK
deactivate L
@enduml