@startuml
skinparam monochrome true
skinparam defaultFontSize 13
control "Delivery Service" as DS
participant "Payment Gateway" as PG
actor "Admin" as A
entity "Customer" as C
control "Seller" as S
A ->> S : Track Order
A -> PG : Make Payment
A ->> C : Cancel Order
note over C : processing cancel order
S ->> C : Apply Coupon
DS --> S : Add To Cart
activate S
S --> DS : ACK
deactivate S
note over S : processing add to cart
@enduml