@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
boundary "Branch Manager" as BM
participant "Bank Teller" as BT
entity "Auditor" as A
BM ->> A : Pay Bill
A -> BT : Transfer Funds
BM ->> BT : Withdraw Cash
A ->> BM : Open Account
@enduml