@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 13
boundary "Chef" as C
control "Guest" as G
boundary "Receptionist" as R
entity "Manager" as M
C ->> R : Clean Room
G -> M : Check Out
R -> C : Book Room
R --> C : Cancel Reservation
activate C
C --> R : ACK
deactivate C
G -> C : Order Room Service
note over C : processing order room service
@enduml