@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 13
actor "Account Holder" as AH
entity "Bank Teller" as BT
actor "Auditor" as A
A -> AH : Transfer Funds
activate AH
AH --> A : ACK
deactivate AH
BT --> AH : Block Card
A ->> BT : View Statement
activate BT
BT --> A : ACK
deactivate BT
BT ->> AH : Deposit Money
@enduml