@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
entity "User" as U
boundary "Admin" as A
entity "Moderator" as M
control "Advertiser" as A2
M -> A : Create Post
U ->> A : Comment
activate A
A --> U : ACK
deactivate A
A2 ->> A : Like Post
M ->> U : Send Message
activate U
U --> M : ACK
deactivate U
@enduml