@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
boundary "Admin" as A
participant "Moderator" as M
actor "User" as U
participant "Advertiser" as A2
M -> A2 : Report Content
note over A2 : processing report content
U -> A2 : Follow User
M ->> A : Share Post
A -> A2 : Comment
A -> U : Like Post
@enduml