@startuml
skinparam defaultFontSize 13
control "Teacher" as T
boundary "Admin" as A
actor "Librarian" as L
control "Registrar" as R
participant "Parent" as P
L ->> T : Issue Certificate
activate T
T --> L : ACK
deactivate T
A --> P : Register Student
P ->> L : Submit Assignment
A ->> P : Enroll Course
@enduml