@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 13
control "Moderator" as M
entity "User" as U
boundary "Admin" as A
entity "Advertiser" as A2
A2 ->> U : Share Post
activate U
U --> A2 : ACK
deactivate U
A -> U : Comment
activate U
U --> A : ACK
deactivate U
A ->> M : Follow User
A2 -> A : Edit Profile
@enduml