@startuml
skinparam defaultFontSize 13
boundary "Admin" as A
participant "User" as U
entity "Moderator" as M
participant "Advertiser" as A2
M ->> A : Follow User
activate A
A --> M : ACK
deactivate A
U --> M : Report Content
U --> A : Edit Profile
M --> U : Send Message
activate U
U --> M : ACK
deactivate U
@enduml