@startuml
skinparam backgroundColor #FAFAFA
skinparam classBackgroundColor #FFF3E0
skinparam classBorderColor #E65100
component "Booking Service" as C_BookingService
component "Guest Service" as C_GuestService
component "Staff Service" as C_StaffService
component "Service Service" as C_ServiceService
component "Restaurant Service" as C_RestaurantService
database "Hotel DB" as DB_hotel
C_BookingService --> DB_hotel
C_ServiceService --> DB_hotel
C_RestaurantService --> DB_hotel
C_ServiceService ..> C_GuestService : gRPC
C_ServiceService ..> C_RestaurantService : MQ
C_GuestService ..> C_StaffService : MQ
C_ServiceService ..> C_GuestService : MQ
@enduml