@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam shadowing true
component "Room Service" as C_RoomService
component "CheckIn Service" as C_CheckInService
component "Service Service" as C_ServiceService
component "Restaurant Service" as C_RestaurantService
component "Payment Service" as C_PaymentService
database "Hotel DB" as DB_hotel
C_RoomService --> DB_hotel
C_CheckInService --> DB_hotel
C_ServiceService --> DB_hotel
C_RestaurantService --> DB_hotel
C_PaymentService --> DB_hotel
C_RoomService ..> C_CheckInService : gRPC
C_RestaurantService ..> C_RoomService : REST
C_RestaurantService ..> C_RoomService : REST
@enduml