@startuml
skinparam defaultFontSize 11
component "CheckOut Service" as C_CheckOutService
component "Service Service" as C_ServiceService
component "Guest Service" as C_GuestService
component "Staff Service" as C_StaffService
database "Hotel DB" as DB_hotel
C_ServiceService --> DB_hotel
C_GuestService --> DB_hotel
C_StaffService --> DB_hotel
C_ServiceService ..> C_CheckOutService : gRPC
C_GuestService ..> C_CheckOutService : HTTP
@enduml