@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
component "Shipment Service" as C_ShipmentService
component "Depot Service" as C_DepotService
component "Package Service" as C_PackageService
component "Vehicle Service" as C_VehicleService
database "Logistics DB" as DB_logistics
C_PackageService --> DB_logistics
C_VehicleService --> DB_logistics
C_ShipmentService ..> C_PackageService : HTTP
C_ShipmentService ..> C_VehicleService : MQ
@enduml