@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
component "Review Service" as C_ReviewService
component "Coupon Service" as C_CouponService
component "Invoice Service" as C_InvoiceService
component "Customer Service" as C_CustomerService
database "Ecommerce DB" as DB_ecommerce
C_ReviewService --> DB_ecommerce
C_CouponService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_CustomerService --> DB_ecommerce
C_ReviewService ..> C_InvoiceService : gRPC
C_CustomerService ..> C_ReviewService : REST
C_CustomerService ..> C_ReviewService : HTTP
@enduml