@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 13
component "Report Service" as C_ReportService
component "Story Service" as C_StoryService
component "Comment Service" as C_CommentService
component "Follower Service" as C_FollowerService
component "Hashtag Service" as C_HashtagService
component "Post Service" as C_PostService
database "Social Media DB" as DB_social_media
C_ReportService --> DB_social_media
C_FollowerService --> DB_social_media
C_PostService --> DB_social_media
C_HashtagService ..> C_FollowerService : MQ
C_FollowerService ..> C_StoryService : MQ
C_CommentService ..> C_HashtagService : REST
C_StoryService ..> C_FollowerService : REST
@enduml