@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
component "Coupon Service" as C_CouponService
component "Invoice Service" as C_InvoiceService
component "Product Service" as C_ProductService
component "Shipment Service" as C_ShipmentService
component "Supplier Service" as C_SupplierService
database "Ecommerce DB" as DB_ecommerce
C_ProductService --> DB_ecommerce
C_ShipmentService --> DB_ecommerce
C_SupplierService ..> C_InvoiceService : REST
C_ProductService ..> C_ShipmentService : gRPC
C_ShipmentService ..> C_InvoiceService : MQ
@enduml