@startuml
skinparam backgroundColor #FAFAFA
skinparam classBackgroundColor #FFF3E0
skinparam classBorderColor #E65100
skinparam ArrowColor #555555
component "Profile Service" as C_ProfileService
component "Like Service" as C_LikeService
component "Message Service" as C_MessageService
component "Hashtag Service" as C_HashtagService
component "User Service" as C_UserService
component "Report Service" as C_ReportService
database "Social Media DB" as DB_social_media
C_ProfileService --> DB_social_media
C_LikeService --> DB_social_media
C_MessageService --> DB_social_media
C_UserService --> DB_social_media
C_ReportService --> DB_social_media
C_LikeService ..> C_UserService : REST
C_MessageService ..> C_ReportService : MQ
@enduml