@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
component "Follower Service" as C_FollowerService
component "User Service" as C_UserService
component "Message Service" as C_MessageService
component "Notification Service" as C_NotificationService
component "Group Service" as C_GroupService
database "Social Media DB" as DB_social_media
C_FollowerService --> DB_social_media
C_UserService --> DB_social_media
C_MessageService --> DB_social_media
C_NotificationService --> DB_social_media
C_GroupService --> DB_social_media
C_GroupService ..> C_UserService : HTTP
C_MessageService ..> C_GroupService : gRPC
@enduml