@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
component "Loan Service" as C_LoanService
component "Transaction Service" as C_TransactionService
component "Transfer Service" as C_TransferService
component "Beneficiary Service" as C_BeneficiaryService
component "Branch Service" as C_BranchService
component "Deposit Service" as C_DepositService
component "Withdrawal Service" as C_WithdrawalService
database "Banking DB" as DB_banking
C_LoanService --> DB_banking
C_TransactionService --> DB_banking
C_TransferService --> DB_banking
C_BranchService --> DB_banking
C_DepositService --> DB_banking
C_WithdrawalService --> DB_banking
C_DepositService ..> C_WithdrawalService : gRPC
C_LoanService ..> C_TransactionService : gRPC
C_LoanService ..> C_BranchService : HTTP
@enduml