@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
component "Reservation Service" as C_ReservationService
component "Publisher Service" as C_PublisherService
component "Fine Service" as C_FineService
component "Librarian Service" as C_LibrarianService
component "Author Service" as C_AuthorService
component "Loan Service" as C_LoanService
database "Library DB" as DB_library
C_ReservationService --> DB_library
C_LoanService --> DB_library
C_ReservationService ..> C_LoanService : REST
C_FineService ..> C_AuthorService : REST
@enduml