@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
component "Shipment Service" as C_ShipmentService
component "Category Service" as C_CategoryService
component "Order Service" as C_OrderService
component "Return Service" as C_ReturnService
component "Payment Service" as C_PaymentService
component "Product Service" as C_ProductService
database "Ecommerce DB" as DB_ecommerce
C_OrderService --> DB_ecommerce
C_PaymentService --> DB_ecommerce
C_ProductService --> DB_ecommerce
C_ProductService ..> C_ReturnService : HTTP
C_ProductService ..> C_OrderService : gRPC
@enduml