@startuml
skinparam monochrome true
component "Amenity Service" as C_AmenityService
component "Invoice Service" as C_InvoiceService
component "CheckOut Service" as C_CheckOutService
component "Room Service" as C_RoomService
database "Hotel DB" as DB_hotel
C_CheckOutService --> DB_hotel
C_RoomService --> DB_hotel
C_InvoiceService ..> C_RoomService : HTTP
C_InvoiceService ..> C_CheckOutService : gRPC
@enduml