@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
component "Patient Service" as C_PatientService
component "Ward Service" as C_WardService
component "LabTest Service" as C_LabTestService
component "Appointment Service" as C_AppointmentService
component "Insurance Service" as C_InsuranceService
database "Healthcare DB" as DB_healthcare
C_PatientService --> DB_healthcare
C_WardService --> DB_healthcare
C_LabTestService --> DB_healthcare
C_InsuranceService --> DB_healthcare
C_WardService ..> C_PatientService : HTTP
C_AppointmentService ..> C_WardService : MQ
C_LabTestService ..> C_AppointmentService : HTTP
C_InsuranceService ..> C_LabTestService : MQ
@enduml