@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
component "DeliveryNote Service" as C_DeliveryNoteService
component "Driver Service" as C_DriverService
component "Inventory Service" as C_InventoryService
component "Depot Service" as C_DepotService
database "Logistics DB" as DB_logistics
C_DriverService --> DB_logistics
C_InventoryService --> DB_logistics
C_DepotService --> DB_logistics
C_DriverService ..> C_InventoryService : gRPC
C_DeliveryNoteService ..> C_InventoryService : gRPC
@enduml