@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
component "Message Service" as C_MessageService
component "Hashtag Service" as C_HashtagService
component "Story Service" as C_StoryService
component "User Service" as C_UserService
component "Follower Service" as C_FollowerService
database "Social Media DB" as DB_social_media
C_MessageService --> DB_social_media
C_HashtagService --> DB_social_media
C_StoryService --> DB_social_media
C_UserService --> DB_social_media
C_FollowerService --> DB_social_media
C_StoryService ..> C_MessageService : REST
C_UserService ..> C_FollowerService : MQ
@enduml