@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
component "Album Service" as C_AlbumService
component "User Service" as C_UserService
component "Hashtag Service" as C_HashtagService
component "Notification Service" as C_NotificationService
component "Message Service" as C_MessageService
component "Comment Service" as C_CommentService
database "Social Media DB" as DB_social_media
C_UserService --> DB_social_media
C_NotificationService --> DB_social_media
C_CommentService --> DB_social_media
C_MessageService ..> C_UserService : gRPC
C_AlbumService ..> C_MessageService : HTTP
C_NotificationService ..> C_UserService : HTTP
C_UserService ..> C_AlbumService : HTTP
@enduml