@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
component "Inventory Service" as C_InventoryService
component "Tracking Service" as C_TrackingService
component "Package Service" as C_PackageService
component "Customer Service" as C_CustomerService
database "Logistics DB" as DB_logistics
C_InventoryService --> DB_logistics
C_TrackingService --> DB_logistics
C_PackageService --> DB_logistics
C_CustomerService --> DB_logistics
C_PackageService ..> C_CustomerService : HTTP
C_TrackingService ..> C_InventoryService : gRPC
@enduml