@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
component "Return Service" as C_ReturnService
component "Supplier Service" as C_SupplierService
component "Category Service" as C_CategoryService
component "Wishlist Service" as C_WishlistService
component "Customer Service" as C_CustomerService
component "Invoice Service" as C_InvoiceService
database "Ecommerce DB" as DB_ecommerce
C_SupplierService --> DB_ecommerce
C_CategoryService --> DB_ecommerce
C_CustomerService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_CategoryService ..> C_ReturnService : MQ
C_CustomerService ..> C_ReturnService : HTTP
@enduml