@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
component "Deposit Service" as C_DepositService
component "Customer Service" as C_CustomerService
component "Transaction Service" as C_TransactionService
component "Card Service" as C_CardService
component "Teller Service" as C_TellerService
component "Withdrawal Service" as C_WithdrawalService
component "Loan Service" as C_LoanService
database "Banking DB" as DB_banking
C_DepositService --> DB_banking
C_CardService --> DB_banking
C_TellerService --> DB_banking
C_LoanService --> DB_banking
C_TransactionService ..> C_TellerService : REST
C_TransactionService ..> C_LoanService : gRPC
C_DepositService ..> C_CustomerService : HTTP
C_CardService ..> C_WithdrawalService : HTTP
C_DepositService ..> C_WithdrawalService : HTTP
@enduml