@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #E8F4FA
skinparam classBorderColor #2C7DA0
skinparam ArrowColor #555555
component "Review Service" as C_ReviewService
component "Product Service" as C_ProductService
component "Payment Service" as C_PaymentService
component "Supplier Service" as C_SupplierService
database "Ecommerce DB" as DB_ecommerce
C_ReviewService --> DB_ecommerce
C_PaymentService ..> C_ReviewService : gRPC
C_ProductService ..> C_ReviewService : HTTP
@enduml