@startuml
skinparam monochrome true
component "Card Service" as C_CardService
component "Loan Service" as C_LoanService
component "Statement Service" as C_StatementService
component "Interest Service" as C_InterestService
component "Transaction Service" as C_TransactionService
database "Banking DB" as DB_banking
C_CardService --> DB_banking
C_LoanService --> DB_banking
C_StatementService --> DB_banking
C_TransactionService --> DB_banking
C_LoanService ..> C_CardService : gRPC
C_CardService ..> C_StatementService : MQ
C_TransactionService ..> C_InterestService : HTTP
C_LoanService ..> C_TransactionService : MQ
@enduml