@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
component "Reservation Service" as C_ReservationService
component "Restaurant Service" as C_RestaurantService
component "Booking Service" as C_BookingService
component "CheckOut Service" as C_CheckOutService
component "Payment Service" as C_PaymentService
database "Hotel DB" as DB_hotel
C_ReservationService --> DB_hotel
C_RestaurantService --> DB_hotel
C_PaymentService --> DB_hotel
C_CheckOutService ..> C_BookingService : HTTP
C_CheckOutService ..> C_PaymentService : HTTP
@enduml