@startuml

component "Teacher Service" as C_TeacherService
component "Book Service" as C_BookService
component "Library Service" as C_LibraryService
component "Grade Service" as C_GradeService
component "Course Service" as C_CourseService
component "Student Service" as C_StudentService
database "Education DB" as DB_education
C_TeacherService --> DB_education
C_BookService --> DB_education
C_LibraryService --> DB_education
C_GradeService --> DB_education
C_CourseService --> DB_education
C_LibraryService ..> C_StudentService : gRPC
C_StudentService ..> C_CourseService : gRPC
@enduml