@startuml
skinparam defaultFontSize 13
component "Customer Service" as C_CustomerService
component "Wishlist Service" as C_WishlistService
component "Cart Service" as C_CartService
component "Coupon Service" as C_CouponService
database "Ecommerce DB" as DB_ecommerce
C_WishlistService --> DB_ecommerce
C_CartService --> DB_ecommerce
C_CouponService --> DB_ecommerce
C_CartService ..> C_WishlistService : REST
C_WishlistService ..> C_CustomerService : HTTP
@enduml