@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam defaultFontSize 11
component "CheckIn Service" as C_CheckInService
component "Amenity Service" as C_AmenityService
component "Staff Service" as C_StaffService
component "Booking Service" as C_BookingService
component "Service Service" as C_ServiceService
component "Guest Service" as C_GuestService
database "Hotel DB" as DB_hotel
C_StaffService --> DB_hotel
C_BookingService --> DB_hotel
C_ServiceService --> DB_hotel
C_GuestService --> DB_hotel
C_GuestService ..> C_CheckInService : MQ
C_CheckInService ..> C_GuestService : HTTP
C_ServiceService ..> C_CheckInService : gRPC
C_ServiceService ..> C_CheckInService : MQ
C_BookingService ..> C_AmenityService : MQ
@enduml