@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
component "Grade Service" as C_GradeService
component "Exam Service" as C_ExamService
component "Course Service" as C_CourseService
component "Teacher Service" as C_TeacherService
component "Schedule Service" as C_ScheduleService
component "Assignment Service" as C_AssignmentService
component "Enrollment Service" as C_EnrollmentService
database "Education DB" as DB_education
C_GradeService --> DB_education
C_CourseService --> DB_education
C_TeacherService --> DB_education
C_AssignmentService --> DB_education
C_AssignmentService ..> C_CourseService : HTTP
C_CourseService ..> C_TeacherService : gRPC
C_ScheduleService ..> C_TeacherService : gRPC
C_TeacherService ..> C_AssignmentService : HTTP
C_ScheduleService ..> C_GradeService : MQ
C_ExamService ..> C_AssignmentService : MQ
@enduml