@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
component "Teller Service" as C_TellerService
component "Statement Service" as C_StatementService
component "Interest Service" as C_InterestService
component "Loan Service" as C_LoanService
component "Customer Service" as C_CustomerService
database "Banking DB" as DB_banking
C_TellerService --> DB_banking
C_StatementService --> DB_banking
C_LoanService --> DB_banking
C_CustomerService --> DB_banking
C_LoanService ..> C_StatementService : HTTP
C_LoanService ..> C_CustomerService : MQ
C_CustomerService ..> C_InterestService : gRPC
C_StatementService ..> C_InterestService : gRPC
@enduml