@startuml
skinparam defaultFontSize 11
component "User Service" as C_UserService
component "Notification Service" as C_NotificationService
component "Message Service" as C_MessageService
component "Post Service" as C_PostService
component "Comment Service" as C_CommentService
component "Hashtag Service" as C_HashtagService
component "Album Service" as C_AlbumService
database "Social Media DB" as DB_social_media
C_UserService --> DB_social_media
C_NotificationService --> DB_social_media
C_MessageService --> DB_social_media
C_AlbumService --> DB_social_media
C_NotificationService ..> C_PostService : HTTP
C_AlbumService ..> C_HashtagService : MQ
@enduml