@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
component "Return Service" as C_ReturnService
component "Category Service" as C_CategoryService
component "Cart Service" as C_CartService
component "Product Service" as C_ProductService
component "Wishlist Service" as C_WishlistService
component "Supplier Service" as C_SupplierService
database "Ecommerce DB" as DB_ecommerce
C_CategoryService --> DB_ecommerce
C_ProductService --> DB_ecommerce
C_WishlistService --> DB_ecommerce
C_SupplierService --> DB_ecommerce
C_ProductService ..> C_SupplierService : REST
C_SupplierService ..> C_CartService : MQ
@enduml