@startuml
skinparam defaultFontSize 11
component "Product Service" as C_ProductService
component "Invoice Service" as C_InvoiceService
component "Cart Service" as C_CartService
component "Wishlist Service" as C_WishlistService
component "Review Service" as C_ReviewService
component "Return Service" as C_ReturnService
component "Shipment Service" as C_ShipmentService
database "Ecommerce DB" as DB_ecommerce
C_ProductService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_CartService --> DB_ecommerce
C_WishlistService --> DB_ecommerce
C_ReviewService --> DB_ecommerce
C_ReturnService --> DB_ecommerce
C_ShipmentService --> DB_ecommerce
C_ProductService ..> C_CartService : gRPC
C_InvoiceService ..> C_ShipmentService : REST
C_WishlistService ..> C_CartService : HTTP
C_ShipmentService ..> C_InvoiceService : MQ
C_ProductService ..> C_ShipmentService : gRPC
@enduml