@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
component "Customer Service" as C_CustomerService
component "Beneficiary Service" as C_BeneficiaryService
component "Withdrawal Service" as C_WithdrawalService
component "Deposit Service" as C_DepositService
component "Teller Service" as C_TellerService
database "Banking DB" as DB_banking
C_CustomerService --> DB_banking
C_BeneficiaryService --> DB_banking
C_WithdrawalService --> DB_banking
C_DepositService --> DB_banking
C_BeneficiaryService ..> C_TellerService : MQ
C_WithdrawalService ..> C_DepositService : HTTP
C_DepositService ..> C_CustomerService : MQ
C_WithdrawalService ..> C_BeneficiaryService : gRPC
@enduml