@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 13
component "Book Service" as C_BookService
component "Attendance Service" as C_AttendanceService
component "Assignment Service" as C_AssignmentService
component "Teacher Service" as C_TeacherService
component "Course Service" as C_CourseService
component "Exam Service" as C_ExamService
component "Enrollment Service" as C_EnrollmentService
database "Education DB" as DB_education
C_BookService --> DB_education
C_AssignmentService --> DB_education
C_CourseService --> DB_education
C_ExamService --> DB_education
C_EnrollmentService --> DB_education
C_ExamService ..> C_EnrollmentService : HTTP
C_EnrollmentService ..> C_AssignmentService : MQ
@enduml