@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam shadowing true
component "Staff Service" as C_StaffService
component "Restaurant Service" as C_RestaurantService
component "Reservation Service" as C_ReservationService
component "Guest Service" as C_GuestService
database "Hotel DB" as DB_hotel
C_RestaurantService --> DB_hotel
C_ReservationService --> DB_hotel
C_RestaurantService ..> C_ReservationService : gRPC
C_StaffService ..> C_ReservationService : gRPC
@enduml