@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
component "Course Service" as C_CourseService
component "Grade Service" as C_GradeService
component "Assignment Service" as C_AssignmentService
component "Book Service" as C_BookService
component "Teacher Service" as C_TeacherService
component "Student Service" as C_StudentService
database "Education DB" as DB_education
C_CourseService --> DB_education
C_GradeService --> DB_education
C_AssignmentService --> DB_education
C_BookService --> DB_education
C_TeacherService --> DB_education
C_StudentService --> DB_education
C_CourseService ..> C_GradeService : REST
C_GradeService ..> C_CourseService : gRPC
C_TeacherService ..> C_StudentService : HTTP
C_StudentService ..> C_GradeService : gRPC
@enduml