@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
component "Department Service" as C_DepartmentService
component "Classroom Service" as C_ClassroomService
component "Schedule Service" as C_ScheduleService
component "Student Service" as C_StudentService
database "Education DB" as DB_education
C_DepartmentService --> DB_education
C_ClassroomService --> DB_education
C_ScheduleService --> DB_education
C_ScheduleService ..> C_StudentService : gRPC
C_StudentService ..> C_ScheduleService : gRPC
C_ScheduleService ..> C_StudentService : REST
@enduml