@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
component "Wishlist Service" as C_WishlistService
component "Coupon Service" as C_CouponService
component "Product Service" as C_ProductService
component "Order Service" as C_OrderService
component "Invoice Service" as C_InvoiceService
database "Ecommerce DB" as DB_ecommerce
C_CouponService --> DB_ecommerce
C_ProductService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_CouponService ..> C_WishlistService : REST
C_InvoiceService ..> C_CouponService : HTTP
@enduml