@startuml
skinparam shadowing true
component "Booking Service" as C_BookingService
component "Room Service" as C_RoomService
component "Staff Service" as C_StaffService
component "CheckOut Service" as C_CheckOutService
component "Guest Service" as C_GuestService
database "Hotel DB" as DB_hotel
C_RoomService --> DB_hotel
C_CheckOutService --> DB_hotel
C_CheckOutService ..> C_StaffService : HTTP
C_RoomService ..> C_GuestService : REST
@enduml