@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
component "Customer Service" as C_CustomerService
component "Depot Service" as C_DepotService
component "Warehouse Service" as C_WarehouseService
component "Inventory Service" as C_InventoryService
component "Tracking Service" as C_TrackingService
component "Route Service" as C_RouteService
component "Package Service" as C_PackageService
database "Logistics DB" as DB_logistics
C_CustomerService --> DB_logistics
C_DepotService --> DB_logistics
C_TrackingService --> DB_logistics
C_RouteService --> DB_logistics
C_PackageService --> DB_logistics
C_WarehouseService ..> C_CustomerService : HTTP
C_DepotService ..> C_RouteService : MQ
C_PackageService ..> C_WarehouseService : REST
C_CustomerService ..> C_RouteService : HTTP
C_DepotService ..> C_WarehouseService : MQ
@enduml