@startuml
skinparam backgroundColor #FAFAFA
skinparam classBackgroundColor #FFF3E0
skinparam classBorderColor #E65100
skinparam ArrowColor #555555
component "Category Service" as C_CategoryService
component "Return Service" as C_ReturnService
component "Cart Service" as C_CartService
component "Review Service" as C_ReviewService
database "Ecommerce DB" as DB_ecommerce
C_CategoryService --> DB_ecommerce
C_ReturnService --> DB_ecommerce
C_CartService --> DB_ecommerce
C_ReviewService --> DB_ecommerce
C_CategoryService ..> C_ReturnService : gRPC
C_CartService ..> C_ReturnService : HTTP
@enduml