@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
component "Grade Service" as C_GradeService
component "Book Service" as C_BookService
component "Course Service" as C_CourseService
component "Department Service" as C_DepartmentService
component "Schedule Service" as C_ScheduleService
component "Attendance Service" as C_AttendanceService
database "Education DB" as DB_education
C_GradeService --> DB_education
C_CourseService --> DB_education
C_DepartmentService --> DB_education
C_AttendanceService --> DB_education
C_GradeService ..> C_DepartmentService : HTTP
C_GradeService ..> C_ScheduleService : REST
@enduml