@startuml
skinparam defaultFontSize 11
component "Course Service" as C_CourseService
component "Assignment Service" as C_AssignmentService
component "Exam Service" as C_ExamService
component "Department Service" as C_DepartmentService
component "Book Service" as C_BookService
component "Library Service" as C_LibraryService
database "Education DB" as DB_education
C_CourseService --> DB_education
C_AssignmentService --> DB_education
C_DepartmentService --> DB_education
C_LibraryService --> DB_education
C_LibraryService ..> C_AssignmentService : REST
C_AssignmentService ..> C_LibraryService : HTTP
C_BookService ..> C_ExamService : MQ
@enduml