@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
component "Route Service" as C_RouteService
component "DeliveryNote Service" as C_DeliveryNoteService
component "Vehicle Service" as C_VehicleService
component "Customer Service" as C_CustomerService
component "Inventory Service" as C_InventoryService
database "Logistics DB" as DB_logistics
C_RouteService --> DB_logistics
C_DeliveryNoteService --> DB_logistics
C_InventoryService --> DB_logistics
C_InventoryService ..> C_RouteService : gRPC
C_InventoryService ..> C_VehicleService : gRPC
C_VehicleService ..> C_InventoryService : HTTP
C_InventoryService ..> C_VehicleService : REST
@enduml