@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
component "MedicalRecord Service" as C_MedicalRecordService
component "Treatment Service" as C_TreatmentService
component "Prescription Service" as C_PrescriptionService
component "Hospital Service" as C_HospitalService
database "Healthcare DB" as DB_healthcare
C_MedicalRecordService --> DB_healthcare
C_TreatmentService --> DB_healthcare
C_PrescriptionService --> DB_healthcare
C_HospitalService --> DB_healthcare
C_HospitalService ..> C_TreatmentService : HTTP
C_MedicalRecordService ..> C_HospitalService : MQ
C_HospitalService ..> C_TreatmentService : gRPC
@enduml