@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #E8F4FA
skinparam classBorderColor #2C7DA0
skinparam ArrowColor #555555
component "Customer Service" as C_CustomerService
component "Loan Service" as C_LoanService
component "Deposit Service" as C_DepositService
component "Beneficiary Service" as C_BeneficiaryService
component "Transfer Service" as C_TransferService
database "Banking DB" as DB_banking
C_LoanService --> DB_banking
C_DepositService --> DB_banking
C_BeneficiaryService --> DB_banking
C_TransferService --> DB_banking
C_TransferService ..> C_DepositService : REST
C_TransferService ..> C_LoanService : gRPC
C_BeneficiaryService ..> C_DepositService : MQ
C_DepositService ..> C_BeneficiaryService : gRPC
@enduml