@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
component "Service Service" as C_ServiceService
component "Room Service" as C_RoomService
component "Payment Service" as C_PaymentService
component "CheckOut Service" as C_CheckOutService
component "Staff Service" as C_StaffService
database "Hotel DB" as DB_hotel
C_ServiceService --> DB_hotel
C_RoomService --> DB_hotel
C_CheckOutService --> DB_hotel
C_StaffService --> DB_hotel
C_StaffService ..> C_RoomService : MQ
C_CheckOutService ..> C_StaffService : HTTP
C_StaffService ..> C_ServiceService : MQ
@enduml