@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
component "Ward Service" as C_WardService
component "Doctor Service" as C_DoctorService
component "Hospital Service" as C_HospitalService
component "Diagnosis Service" as C_DiagnosisService
database "Healthcare DB" as DB_healthcare
C_WardService --> DB_healthcare
C_DiagnosisService ..> C_HospitalService : gRPC
C_WardService ..> C_DoctorService : HTTP
C_DoctorService ..> C_DiagnosisService : HTTP
@enduml