@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
component "Guest Service" as C_GuestService
component "Payment Service" as C_PaymentService
component "Service Service" as C_ServiceService
component "CheckIn Service" as C_CheckInService
component "Housekeeping Service" as C_HousekeepingService
database "Hotel DB" as DB_hotel
C_GuestService --> DB_hotel
C_PaymentService --> DB_hotel
C_CheckInService --> DB_hotel
C_HousekeepingService --> DB_hotel
C_GuestService ..> C_ServiceService : REST
C_PaymentService ..> C_ServiceService : MQ
C_ServiceService ..> C_PaymentService : REST
@enduml