@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
component "Supplier Service" as C_SupplierService
component "Payment Service" as C_PaymentService
component "Wishlist Service" as C_WishlistService
component "Order Service" as C_OrderService
database "Ecommerce DB" as DB_ecommerce
C_SupplierService --> DB_ecommerce
C_PaymentService --> DB_ecommerce
C_WishlistService --> DB_ecommerce
C_OrderService --> DB_ecommerce
C_SupplierService ..> C_PaymentService : MQ
C_WishlistService ..> C_SupplierService : MQ
C_OrderService ..> C_WishlistService : HTTP
@enduml