@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
component "Wishlist Service" as C_WishlistService
component "Shipment Service" as C_ShipmentService
component "Return Service" as C_ReturnService
component "Category Service" as C_CategoryService
component "Invoice Service" as C_InvoiceService
component "Warehouse Service" as C_WarehouseService
component "Customer Service" as C_CustomerService
database "Ecommerce DB" as DB_ecommerce
C_WishlistService --> DB_ecommerce
C_ShipmentService --> DB_ecommerce
C_ReturnService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_WarehouseService --> DB_ecommerce
C_CustomerService --> DB_ecommerce
C_CustomerService ..> C_WishlistService : HTTP
C_ShipmentService ..> C_CategoryService : HTTP
@enduml