@startuml
skinparam monochrome true
skinparam defaultFontSize 13
component "Customer Service" as C_CustomerService
component "Wishlist Service" as C_WishlistService
component "Product Service" as C_ProductService
component "Category Service" as C_CategoryService
component "Coupon Service" as C_CouponService
component "Invoice Service" as C_InvoiceService
component "Cart Service" as C_CartService
database "Ecommerce DB" as DB_ecommerce
C_ProductService --> DB_ecommerce
C_CategoryService --> DB_ecommerce
C_CouponService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_InvoiceService ..> C_ProductService : gRPC
C_WishlistService ..> C_CustomerService : HTTP
C_CustomerService ..> C_CartService : REST
@enduml