@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
component "Payment Service" as C_PaymentService
component "Room Service" as C_RoomService
component "Invoice Service" as C_InvoiceService
component "Amenity Service" as C_AmenityService
component "Reservation Service" as C_ReservationService
component "Guest Service" as C_GuestService
database "Hotel DB" as DB_hotel
C_PaymentService --> DB_hotel
C_RoomService --> DB_hotel
C_InvoiceService --> DB_hotel
C_AmenityService --> DB_hotel
C_GuestService --> DB_hotel
C_PaymentService ..> C_GuestService : gRPC
C_ReservationService ..> C_PaymentService : MQ
C_AmenityService ..> C_InvoiceService : gRPC
C_RoomService ..> C_ReservationService : gRPC
@enduml