@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
component "Student Service" as C_StudentService
component "Department Service" as C_DepartmentService
component "Exam Service" as C_ExamService
component "Attendance Service" as C_AttendanceService
database "Education DB" as DB_education
C_DepartmentService --> DB_education
C_ExamService --> DB_education
C_AttendanceService --> DB_education
C_ExamService ..> C_AttendanceService : REST
C_DepartmentService ..> C_AttendanceService : MQ
C_AttendanceService ..> C_ExamService : MQ
@enduml