@startuml

component "Order Service" as C_OrderService
component "Cart Service" as C_CartService
component "Shipment Service" as C_ShipmentService
component "Warehouse Service" as C_WarehouseService
component "Category Service" as C_CategoryService
component "Invoice Service" as C_InvoiceService
database "Ecommerce DB" as DB_ecommerce
C_OrderService --> DB_ecommerce
C_CartService --> DB_ecommerce
C_ShipmentService --> DB_ecommerce
C_WarehouseService --> DB_ecommerce
C_CategoryService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_OrderService ..> C_WarehouseService : REST
C_CategoryService ..> C_WarehouseService : gRPC
@enduml