@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
component "Supplier Service" as C_SupplierService
component "Customer Service" as C_CustomerService
component "Shipment Service" as C_ShipmentService
component "Product Service" as C_ProductService
database "Ecommerce DB" as DB_ecommerce
C_SupplierService --> DB_ecommerce
C_CustomerService --> DB_ecommerce
C_ShipmentService --> DB_ecommerce
C_ProductService --> DB_ecommerce
C_CustomerService ..> C_ProductService : REST
C_ShipmentService ..> C_SupplierService : HTTP
@enduml