@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
component "Shipment Service" as C_ShipmentService
component "Tracking Service" as C_TrackingService
component "Package Service" as C_PackageService
component "Vehicle Service" as C_VehicleService
database "Logistics DB" as DB_logistics
C_ShipmentService --> DB_logistics
C_TrackingService --> DB_logistics
C_PackageService --> DB_logistics
C_VehicleService ..> C_TrackingService : HTTP
C_TrackingService ..> C_ShipmentService : MQ
C_TrackingService ..> C_PackageService : REST
@enduml