@startuml
skinparam backgroundColor #FAFAFA
skinparam classBackgroundColor #FFF3E0
skinparam classBorderColor #E65100
skinparam ArrowColor #555555
component "Teller Service" as C_TellerService
component "Withdrawal Service" as C_WithdrawalService
component "Beneficiary Service" as C_BeneficiaryService
component "Interest Service" as C_InterestService
component "Loan Service" as C_LoanService
component "Account Service" as C_AccountService
component "Customer Service" as C_CustomerService
database "Banking DB" as DB_banking
C_TellerService --> DB_banking
C_WithdrawalService --> DB_banking
C_BeneficiaryService --> DB_banking
C_BeneficiaryService ..> C_AccountService : HTTP
C_CustomerService ..> C_InterestService : MQ
C_InterestService ..> C_WithdrawalService : HTTP
C_AccountService ..> C_WithdrawalService : REST
C_CustomerService ..> C_LoanService : gRPC
@enduml