@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam ArrowColor #555555
component "Shipment Service" as C_ShipmentService
component "Customer Service" as C_CustomerService
component "Package Service" as C_PackageService
component "Tracking Service" as C_TrackingService
database "Logistics DB" as DB_logistics
C_PackageService --> DB_logistics
C_TrackingService --> DB_logistics
C_CustomerService ..> C_TrackingService : REST
C_TrackingService ..> C_PackageService : HTTP
C_CustomerService ..> C_PackageService : gRPC
@enduml