@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
component "Manifest Service" as C_ManifestService
component "Shipment Service" as C_ShipmentService
component "Customer Service" as C_CustomerService
component "Depot Service" as C_DepotService
database "Logistics DB" as DB_logistics
C_ShipmentService --> DB_logistics
C_CustomerService --> DB_logistics
C_DepotService --> DB_logistics
C_CustomerService ..> C_ManifestService : MQ
C_CustomerService ..> C_DepotService : MQ
C_DepotService ..> C_ManifestService : HTTP
@enduml