@startuml

component "Card Service" as C_CardService
component "Loan Service" as C_LoanService
component "Transfer Service" as C_TransferService
component "Withdrawal Service" as C_WithdrawalService
database "Banking DB" as DB_banking
C_LoanService --> DB_banking
C_TransferService --> DB_banking
C_WithdrawalService --> DB_banking
C_WithdrawalService ..> C_TransferService : HTTP
C_WithdrawalService ..> C_TransferService : REST
@enduml