@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
component "Interest Service" as C_InterestService
component "Withdrawal Service" as C_WithdrawalService
component "Beneficiary Service" as C_BeneficiaryService
component "Teller Service" as C_TellerService
component "Statement Service" as C_StatementService
component "Customer Service" as C_CustomerService
database "Banking DB" as DB_banking
C_InterestService --> DB_banking
C_WithdrawalService --> DB_banking
C_BeneficiaryService --> DB_banking
C_TellerService --> DB_banking
C_CustomerService --> DB_banking
C_CustomerService ..> C_TellerService : MQ
C_BeneficiaryService ..> C_StatementService : MQ
@enduml