@startuml

component "Teacher Service" as C_TeacherService
component "Student Service" as C_StudentService
component "Enrollment Service" as C_EnrollmentService
component "Department Service" as C_DepartmentService
component "Classroom Service" as C_ClassroomService
component "Library Service" as C_LibraryService
component "Course Service" as C_CourseService
database "Education DB" as DB_education
C_StudentService --> DB_education
C_DepartmentService --> DB_education
C_ClassroomService --> DB_education
C_LibraryService --> DB_education
C_CourseService --> DB_education
C_LibraryService ..> C_EnrollmentService : MQ
C_ClassroomService ..> C_LibraryService : gRPC
C_EnrollmentService ..> C_StudentService : HTTP
@enduml