@startuml

component "Appointment Service" as C_AppointmentService
component "Prescription Service" as C_PrescriptionService
component "LabTest Service" as C_LabTestService
component "Diagnosis Service" as C_DiagnosisService
database "Healthcare DB" as DB_healthcare
C_AppointmentService --> DB_healthcare
C_PrescriptionService --> DB_healthcare
C_LabTestService --> DB_healthcare
C_DiagnosisService --> DB_healthcare
C_DiagnosisService ..> C_LabTestService : REST
C_LabTestService ..> C_PrescriptionService : MQ
C_LabTestService ..> C_AppointmentService : MQ
@enduml