@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam ArrowColor #555555
component "Coupon Service" as C_CouponService
component "Invoice Service" as C_InvoiceService
component "Review Service" as C_ReviewService
component "Wishlist Service" as C_WishlistService
component "Shipment Service" as C_ShipmentService
component "Payment Service" as C_PaymentService
component "Cart Service" as C_CartService
database "Ecommerce DB" as DB_ecommerce
C_CouponService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_ReviewService --> DB_ecommerce
C_ShipmentService --> DB_ecommerce
C_PaymentService --> DB_ecommerce
C_CartService --> DB_ecommerce
C_PaymentService ..> C_InvoiceService : MQ
C_ShipmentService ..> C_CartService : gRPC
C_ReviewService ..> C_ShipmentService : HTTP
C_ReviewService ..> C_CartService : HTTP
@enduml