@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
component "Ward Service" as C_WardService
component "Patient Service" as C_PatientService
component "MedicalRecord Service" as C_MedicalRecordService
component "Diagnosis Service" as C_DiagnosisService
database "Healthcare DB" as DB_healthcare
C_WardService --> DB_healthcare
C_PatientService --> DB_healthcare
C_DiagnosisService --> DB_healthcare
C_DiagnosisService ..> C_PatientService : MQ
C_WardService ..> C_MedicalRecordService : MQ
@enduml