@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
component "Diagnosis Service" as C_DiagnosisService
component "Doctor Service" as C_DoctorService
component "MedicalRecord Service" as C_MedicalRecordService
component "Patient Service" as C_PatientService
component "Treatment Service" as C_TreatmentService
database "Healthcare DB" as DB_healthcare
C_DiagnosisService --> DB_healthcare
C_DoctorService --> DB_healthcare
C_MedicalRecordService --> DB_healthcare
C_PatientService --> DB_healthcare
C_TreatmentService --> DB_healthcare
C_PatientService ..> C_DiagnosisService : gRPC
C_MedicalRecordService ..> C_TreatmentService : MQ
C_DoctorService ..> C_MedicalRecordService : MQ
C_TreatmentService ..> C_DoctorService : MQ
@enduml