@startuml

component "Comment Service" as C_CommentService
component "Post Service" as C_PostService
component "Hashtag Service" as C_HashtagService
component "Report Service" as C_ReportService
component "Album Service" as C_AlbumService
component "Message Service" as C_MessageService
database "Social Media DB" as DB_social_media
C_CommentService --> DB_social_media
C_PostService --> DB_social_media
C_HashtagService --> DB_social_media
C_AlbumService --> DB_social_media
C_MessageService --> DB_social_media
C_PostService ..> C_HashtagService : REST
C_AlbumService ..> C_MessageService : REST
C_ReportService ..> C_MessageService : HTTP
@enduml