@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
component "Patient Service" as C_PatientService
component "Insurance Service" as C_InsuranceService
component "Appointment Service" as C_AppointmentService
component "Diagnosis Service" as C_DiagnosisService
component "Nurse Service" as C_NurseService
component "Ward Service" as C_WardService
component "Hospital Service" as C_HospitalService
database "Healthcare DB" as DB_healthcare
C_PatientService --> DB_healthcare
C_InsuranceService --> DB_healthcare
C_HospitalService --> DB_healthcare
C_WardService ..> C_PatientService : REST
C_InsuranceService ..> C_DiagnosisService : MQ
C_DiagnosisService ..> C_InsuranceService : gRPC
C_PatientService ..> C_AppointmentService : MQ
@enduml