@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
component "Review Service" as C_ReviewService
component "Invoice Service" as C_InvoiceService
component "Cart Service" as C_CartService
component "Supplier Service" as C_SupplierService
database "Ecommerce DB" as DB_ecommerce
C_ReviewService --> DB_ecommerce
C_InvoiceService --> DB_ecommerce
C_CartService --> DB_ecommerce
C_SupplierService --> DB_ecommerce
C_ReviewService ..> C_InvoiceService : MQ
C_ReviewService ..> C_SupplierService : MQ
C_SupplierService ..> C_ReviewService : REST
@enduml