@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
component "Customer Service" as C_CustomerService
component "Branch Service" as C_BranchService
component "Teller Service" as C_TellerService
component "Account Service" as C_AccountService
component "Withdrawal Service" as C_WithdrawalService
component "Statement Service" as C_StatementService
database "Banking DB" as DB_banking
C_CustomerService --> DB_banking
C_BranchService --> DB_banking
C_TellerService --> DB_banking
C_WithdrawalService --> DB_banking
C_TellerService ..> C_CustomerService : HTTP
C_WithdrawalService ..> C_StatementService : HTTP
@enduml