@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 13
component "CheckIn Service" as C_CheckInService
component "Invoice Service" as C_InvoiceService
component "Service Service" as C_ServiceService
component "CheckOut Service" as C_CheckOutService
component "Staff Service" as C_StaffService
component "Reservation Service" as C_ReservationService
component "Room Service" as C_RoomService
database "Hotel DB" as DB_hotel
C_CheckInService --> DB_hotel
C_InvoiceService --> DB_hotel
C_CheckOutService --> DB_hotel
C_StaffService --> DB_hotel
C_ReservationService --> DB_hotel
C_StaffService ..> C_CheckInService : MQ
C_StaffService ..> C_InvoiceService : HTTP
C_StaffService ..> C_ReservationService : MQ
C_CheckOutService ..> C_InvoiceService : MQ
@enduml