@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
component "Like Service" as C_LikeService
component "Profile Service" as C_ProfileService
component "Story Service" as C_StoryService
component "User Service" as C_UserService
database "Social Media DB" as DB_social_media
C_LikeService --> DB_social_media
C_ProfileService --> DB_social_media
C_StoryService --> DB_social_media
C_UserService --> DB_social_media
C_StoryService ..> C_UserService : REST
C_UserService ..> C_StoryService : MQ
C_LikeService ..> C_UserService : MQ
@enduml