@startuml
skinparam defaultFontSize 11
component "Post Service" as C_PostService
component "Comment Service" as C_CommentService
component "Like Service" as C_LikeService
component "Hashtag Service" as C_HashtagService
component "Profile Service" as C_ProfileService
component "Album Service" as C_AlbumService
database "Social Media DB" as DB_social_media
C_PostService --> DB_social_media
C_LikeService --> DB_social_media
C_ProfileService --> DB_social_media
C_AlbumService --> DB_social_media
C_CommentService ..> C_HashtagService : gRPC
C_ProfileService ..> C_HashtagService : gRPC
C_HashtagService ..> C_LikeService : HTTP
C_LikeService ..> C_CommentService : HTTP
@enduml