@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
left to right direction
actor "Bank Teller" as BT
actor "Account Holder" as AH
actor "Branch Manager" as BM
actor "ATM" as A
rectangle "Banking System" {
  usecase "Pay Bill" as UC_PayBill
  usecase "Open Account" as UC_OpenAccount
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "View Statement" as UC_ViewStatement
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Block Card" as UC_BlockCard
}
BT --> UC_OpenAccount
AH --> UC_PayBill
BM --> UC_PayBill
BM --> UC_DepositMoney
A --> UC_BlockCard
A --> UC_ViewStatement
UC_WithdrawCash ..|> UC_BlockCard : <<extend>>
@enduml