@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
left to right direction
actor "Librarian" as L
actor "Student" as S
actor "Parent" as P
actor "Teacher" as T
rectangle "Education System" {
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Grade Exam" as UC_GradeExam
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Register Student" as UC_RegisterStudent
  usecase "Borrow Book" as UC_BorrowBook
}
L --> UC_TakeAttendance
L --> UC_RegisterStudent
S --> UC_SubmitAssignment
P --> UC_GradeExam
T --> UC_BorrowBook
T --> UC_GradeExam
T --> UC_RegisterStudent
@enduml