@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
left to right direction
actor "Manager" as M
actor "Housekeeper" as H
rectangle "Hotel System" {
  usecase "Check Out" as UC_CheckOut
  usecase "Clean Room" as UC_CleanRoom
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Check In" as UC_CheckIn
  usecase "Book Room" as UC_BookRoom
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Process Payment" as UC_ProcessPayment
}
M --> UC_CleanRoom
H --> UC_OrderRoomService
H --> UC_BookRoom
UC_BookRoom ..> UC_ProcessPayment : <<extend>>
@enduml