@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "Housekeeper" as H
actor "Manager" as M
actor "Receptionist" as R
rectangle "Hotel System" {
  usecase "Check In" as UC_CheckIn
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Request Service" as UC_RequestService
  usecase "Clean Room" as UC_CleanRoom
  usecase "Check Out" as UC_CheckOut
  usecase "Process Payment" as UC_ProcessPayment
}
H --> UC_CheckIn
H --> UC_RequestService
M --> UC_RequestService
M --> UC_CheckOut
M --> UC_ProcessPayment
R --> UC_CleanRoom
UC_CheckIn ..|> UC_ProcessPayment : <<extend>>
@enduml