@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Branch Manager" as BranchManager
actor "Account Holder" as AccountHolder
actor "Bank Teller" as BankTeller
rectangle "Banking System" {
  usecase "Open Account" as UC_OpenAccount
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "View Statement" as UC_ViewStatement
  usecase "Block Card" as UC_BlockCard
}
BranchManager --> UC_ApplyForLoan
BranchManager --> UC_DepositMoney
AccountHolder --> UC_WithdrawCash
BankTeller --> UC_ViewStatement
BankTeller --> UC_ApplyForLoan
BankTeller --> UC_BlockCard
@enduml