@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 13
left to right direction
actor "Account Holder" as AH
actor "Auditor" as A
actor "ATM" as A1
actor "Branch Manager" as BM
rectangle "Banking System" {
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "View Statement" as UC_ViewStatement
  usecase "Pay Bill" as UC_PayBill
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Open Account" as UC_OpenAccount
}
AH --> UC_ViewStatement
A --> UC_OpenAccount
A --> UC_PayBill
A1 --> UC_DepositMoney
A1 --> UC_WithdrawCash
A1 --> UC_PayBill
BM --> UC_DepositMoney
@enduml