@startuml
skinparam ArrowColor #555555
left to right direction
actor "Admin" as A
actor "Moderator" as M
actor "Advertiser" as A1
actor "User" as U
rectangle "Social Media System" {
  usecase "Send Message" as UC_SendMessage
  usecase "Comment" as UC_Comment
  usecase "Report Content" as UC_ReportContent
  usecase "Follow User" as UC_FollowUser
  usecase "Like Post" as UC_LikePost
  usecase "Create Post" as UC_CreatePost
  usecase "Edit Profile" as UC_EditProfile
  usecase "Share Post" as UC_SharePost
}
A --> UC_Comment
M --> UC_SendMessage
M --> UC_CreatePost
A1 --> UC_LikePost
U --> UC_LikePost
UC_EditProfile ..|> UC_LikePost : <<extend>>
@enduml