@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
left to right direction
actor "User" as U
actor "Admin" as A
rectangle "Social Media System" {
  usecase "Comment" as UC_Comment
  usecase "Edit Profile" as UC_EditProfile
  usecase "Share Post" as UC_SharePost
  usecase "Follow User" as UC_FollowUser
  usecase "Create Post" as UC_CreatePost
  usecase "Like Post" as UC_LikePost
}
U --> UC_CreatePost
U --> UC_LikePost
U --> UC_Comment
A --> UC_FollowUser
A --> UC_CreatePost
UC_Comment ..|> UC_EditProfile : <<include>>
@enduml