@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
left to right direction
actor "Guest" as G
actor "Chef" as C
actor "Manager" as M
rectangle "Hotel System" {
  usecase "Request Service" as UC_RequestService
  usecase "Check In" as UC_CheckIn
  usecase "Check Out" as UC_CheckOut
  usecase "Book Room" as UC_BookRoom
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Clean Room" as UC_CleanRoom
}
G --> UC_CheckOut
G --> UC_CheckIn
G --> UC_RequestService
C --> UC_RequestService
C --> UC_CheckIn
C --> UC_BookRoom
M --> UC_CheckIn
M --> UC_CleanRoom
M --> UC_RequestService
UC_RequestService ..|> UC_ProcessPayment : <<include>>
@enduml