@startuml
skinparam monochrome true
skinparam shadowing true
left to right direction
actor "Guest" as G
actor "Manager" as M
actor "Housekeeper" as H
rectangle "Hotel System" {
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Clean Room" as UC_CleanRoom
  usecase "Request Service" as UC_RequestService
  usecase "Book Room" as UC_BookRoom
  usecase "Process Payment" as UC_ProcessPayment
}
G --> UC_CleanRoom
G --> UC_ProcessPayment
M --> UC_RequestService
M --> UC_CleanRoom
M --> UC_BookRoom
H --> UC_RequestService
H --> UC_CancelReservation
UC_CancelReservation ..> UC_BookRoom : <<include>>
@enduml