@startuml

left to right direction
actor "Student" as S
actor "Librarian" as L
actor "Admin" as A
rectangle "Education System" {
  usecase "Register Student" as UC_RegisterStudent
  usecase "Grade Exam" as UC_GradeExam
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Take Attendance" as UC_TakeAttendance
}
S --> UC_TakeAttendance
S --> UC_SubmitAssignment
S --> UC_RegisterStudent
L --> UC_SubmitAssignment
A --> UC_GradeExam
A --> UC_SubmitAssignment
UC_RegisterStudent ..> UC_TakeAttendance : <<include>>
@enduml