@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam defaultFontSize 11
left to right direction
actor "Admin" as A
actor "Payment Gateway" as PG
rectangle "Ecommerce System" {
  usecase "Make Payment" as UC_MakePayment
  usecase "Add To Cart" as UC_AddToCart
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Track Order" as UC_TrackOrder
  usecase "Checkout" as UC_Checkout
}
A --> UC_ManageInventory
A --> UC_AddToCart
A --> UC_MakePayment
PG --> UC_ManageInventory
PG --> UC_AddToCart
PG --> UC_TrackOrder
@enduml