@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
left to right direction
actor "Admin" as A
actor "Member" as M
actor "Librarian" as L
rectangle "Library System" {
  usecase "Register Member" as UC_RegisterMember
  usecase "Return Book" as UC_ReturnBook
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Pay Fine" as UC_PayFine
  usecase "Add New Book" as UC_AddNewBook
}
A --> UC_AddNewBook
A --> UC_ReturnBook
M --> UC_AddNewBook
M --> UC_RegisterMember
L --> UC_AddNewBook
@enduml