@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
left to right direction
actor "Guest" as Guest
actor "Manager" as Manager
rectangle "Hotel System" {
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Check Out" as UC_CheckOut
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Check In" as UC_CheckIn
  usecase "Clean Room" as UC_CleanRoom
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Request Service" as UC_RequestService
  usecase "Book Room" as UC_BookRoom
}
Guest --> UC_RequestService
Manager --> UC_CancelReservation
Manager --> UC_BookRoom
@enduml