@startuml
skinparam monochrome true
skinparam defaultFontSize 13
left to right direction
actor "Admin" as Admin
actor "Moderator" as Moderator
actor "Advertiser" as Advertiser
rectangle "Social Media System" {
  usecase "Send Message" as UC_SendMessage
  usecase "Create Post" as UC_CreatePost
  usecase "Share Post" as UC_SharePost
  usecase "Comment" as UC_Comment
  usecase "Report Content" as UC_ReportContent
  usecase "Follow User" as UC_FollowUser
  usecase "Like Post" as UC_LikePost
}
Admin --> UC_ReportContent
Moderator --> UC_Comment
Moderator --> UC_ReportContent
Moderator --> UC_SendMessage
Advertiser --> UC_SharePost
Advertiser --> UC_CreatePost
Advertiser --> UC_LikePost
UC_CreatePost ..|> UC_FollowUser : <<include>>
@enduml