@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "Payment Gateway" as PaymentGateway
actor "Delivery Service" as DeliveryService
rectangle "Ecommerce System" {
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Write Review" as UC_WriteReview
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Checkout" as UC_Checkout
}
PaymentGateway --> UC_CancelOrder
DeliveryService --> UC_Checkout
UC_CancelOrder ..> UC_Checkout : <<extend>>
@enduml