@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "Manager" as M
actor "Guest" as G
actor "Chef" as C
rectangle "Hotel System" {
  usecase "Book Room" as UC_BookRoom
  usecase "Request Service" as UC_RequestService
  usecase "Check Out" as UC_CheckOut
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Check In" as UC_CheckIn
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Clean Room" as UC_CleanRoom
}
M --> UC_CheckIn
M --> UC_RequestService
M --> UC_BookRoom
G --> UC_CancelReservation
G --> UC_BookRoom
C --> UC_CheckIn
C --> UC_OrderRoomService
@enduml