@startuml
skinparam monochrome true
skinparam defaultFontSize 13
left to right direction
actor "Seller" as Seller
actor "Delivery Service" as DeliveryService
actor "Customer" as Customer
actor "Payment Gateway" as PaymentGateway
rectangle "Ecommerce System" {
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Add To Cart" as UC_AddToCart
  usecase "Checkout" as UC_Checkout
  usecase "Track Order" as UC_TrackOrder
  usecase "Write Review" as UC_WriteReview
}
Seller --> UC_Checkout
Seller --> UC_WriteReview
DeliveryService --> UC_WriteReview
Customer --> UC_AddToCart
Customer --> UC_CancelOrder
PaymentGateway --> UC_Checkout
PaymentGateway --> UC_AddToCart
UC_TrackOrder ..> UC_WriteReview : <<include>>
@enduml