@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
left to right direction
actor "Payment Gateway" as PG
actor "Admin" as A
actor "Seller" as S
actor "Customer" as C
rectangle "Ecommerce System" {
  usecase "Make Payment" as UC_MakePayment
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Write Review" as UC_WriteReview
  usecase "Track Order" as UC_TrackOrder
  usecase "Checkout" as UC_Checkout
}
PG --> UC_BrowseProducts
PG --> UC_WriteReview
PG --> UC_TrackOrder
A --> UC_TrackOrder
A --> UC_MakePayment
S --> UC_TrackOrder
S --> UC_WriteReview
C --> UC_TrackOrder
C --> UC_WriteReview
UC_Checkout ..|> UC_WriteReview : <<include>>
@enduml