@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
left to right direction
actor "Librarian" as Librarian
actor "Teacher" as Teacher
actor "Admin" as Admin
rectangle "Education System" {
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Register Student" as UC_RegisterStudent
  usecase "Borrow Book" as UC_BorrowBook
}
Librarian --> UC_SubmitAssignment
Librarian --> UC_BorrowBook
Teacher --> UC_EnrollCourse
Admin --> UC_TakeAttendance
UC_SubmitAssignment ..|> UC_BorrowBook : <<extend>>
@enduml