@startuml
skinparam shadowing true
left to right direction
actor "Customer" as Customer
actor "Payment Gateway" as PaymentGateway
actor "Seller" as Seller
actor "Admin" as Admin
rectangle "Ecommerce System" {
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Track Order" as UC_TrackOrder
  usecase "Checkout" as UC_Checkout
  usecase "Write Review" as UC_WriteReview
  usecase "Make Payment" as UC_MakePayment
  usecase "Add To Cart" as UC_AddToCart
}
Customer --> UC_TrackOrder
Customer --> UC_Checkout
PaymentGateway --> UC_TrackOrder
PaymentGateway --> UC_WriteReview
PaymentGateway --> UC_ApplyCoupon
Seller --> UC_ApplyCoupon
Admin --> UC_Checkout
Admin --> UC_MakePayment
Admin --> UC_AddToCart
UC_WriteReview ..> UC_Checkout : <<include>>
@enduml