@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "Librarian" as L
actor "Registrar" as R
actor "Admin" as A
actor "Student" as S
rectangle "Education System" {
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Register Student" as UC_RegisterStudent
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Grade Exam" as UC_GradeExam
}
L --> UC_ViewSchedule
L --> UC_GradeExam
R --> UC_GradeExam
A --> UC_ViewSchedule
S --> UC_GradeExam
S --> UC_ViewSchedule
S --> UC_RegisterStudent
@enduml