@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
left to right direction
actor "Lab Technician" as LT
actor "Insurance Provider" as IP
actor "Nurse" as N
actor "Patient" as P
rectangle "Healthcare System" {
  usecase "Examine Patient" as UC_ExaminePatient
  usecase "Admit Patient" as UC_AdmitPatient
  usecase "Discharge Patient" as UC_DischargePatient
  usecase "Update Medical Record" as UC_UpdateMedicalRecord
  usecase "Process Insurance Claim" as UC_ProcessInsuranceClaim
}
LT --> UC_AdmitPatient
LT --> UC_ProcessInsuranceClaim
LT --> UC_DischargePatient
IP --> UC_ProcessInsuranceClaim
N --> UC_AdmitPatient
N --> UC_ExaminePatient
N --> UC_UpdateMedicalRecord
P --> UC_AdmitPatient
P --> UC_ExaminePatient
P --> UC_UpdateMedicalRecord
UC_DischargePatient ..|> UC_ExaminePatient : <<extend>>
@enduml