@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
left to right direction
actor "Member" as Member
actor "Admin" as Admin
rectangle "Library System" {
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Return Book" as UC_ReturnBook
  usecase "Register Member" as UC_RegisterMember
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Add New Book" as UC_AddNewBook
}
Member --> UC_SearchCatalog
Member --> UC_RegisterMember
Member --> UC_AddNewBook
Admin --> UC_AddNewBook
@enduml