@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
left to right direction
actor "Parent" as P
actor "Librarian" as L
rectangle "Education System" {
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Register Student" as UC_RegisterStudent
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Grade Exam" as UC_GradeExam
}
P --> UC_EnrollCourse
P --> UC_SubmitAssignment
L --> UC_EnrollCourse
L --> UC_GradeExam
L --> UC_RegisterStudent
UC_BorrowBook ..> UC_EnrollCourse : <<extend>>
@enduml