@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam ArrowColor #555555
left to right direction
actor "Lab Technician" as LabTechnician
actor "Patient" as Patient
actor "Doctor" as Doctor
rectangle "Healthcare System" {
  usecase "Examine Patient" as UC_ExaminePatient
  usecase "Process Insurance Claim" as UC_ProcessInsuranceClaim
  usecase "Run Lab Test" as UC_RunLabTest
  usecase "Discharge Patient" as UC_DischargePatient
  usecase "Issue Prescription" as UC_IssuePrescription
}
LabTechnician --> UC_ProcessInsuranceClaim
LabTechnician --> UC_DischargePatient
LabTechnician --> UC_RunLabTest
Patient --> UC_ExaminePatient
Patient --> UC_ProcessInsuranceClaim
Patient --> UC_IssuePrescription
Doctor --> UC_IssuePrescription
Doctor --> UC_ExaminePatient
@enduml