@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
left to right direction
actor "Branch Manager" as BM
actor "Auditor" as A
actor "Bank Teller" as BT
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Pay Bill" as UC_PayBill
  usecase "View Statement" as UC_ViewStatement
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Transfer Funds" as UC_TransferFunds
}
BM --> UC_PayBill
BM --> UC_ApplyForLoan
A --> UC_ApplyForLoan
A --> UC_DepositMoney
A --> UC_PayBill
BT --> UC_TransferFunds
BT --> UC_ApplyForLoan
UC_PayBill ..|> UC_ApplyForLoan : <<include>>
@enduml