@startuml

left to right direction
actor "Admin" as A
actor "Librarian" as L
actor "Member" as M
rectangle "Library System" {
  usecase "Return Book" as UC_ReturnBook
  usecase "Add New Book" as UC_AddNewBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Pay Fine" as UC_PayFine
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Register Member" as UC_RegisterMember
}
A --> UC_PayFine
A --> UC_ReturnBook
A --> UC_ReserveBook
L --> UC_ReturnBook
L --> UC_RegisterMember
M --> UC_RegisterMember
UC_BorrowBook ..> UC_ReserveBook : <<extend>>
@enduml