@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
left to right direction
actor "Chef" as C
actor "Housekeeper" as H
actor "Manager" as M
rectangle "Hotel System" {
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Check Out" as UC_CheckOut
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Check In" as UC_CheckIn
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Book Room" as UC_BookRoom
  usecase "Clean Room" as UC_CleanRoom
  usecase "Request Service" as UC_RequestService
}
C --> UC_CheckOut
C --> UC_BookRoom
H --> UC_CheckIn
H --> UC_CheckOut
M --> UC_CancelReservation
M --> UC_RequestService
@enduml