@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Receptionist" as R
actor "Guest" as G
actor "Chef" as C
actor "Housekeeper" as H
rectangle "Hotel System" {
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Clean Room" as UC_CleanRoom
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Book Room" as UC_BookRoom
  usecase "Check Out" as UC_CheckOut
}
R --> UC_CleanRoom
G --> UC_CleanRoom
G --> UC_CancelReservation
G --> UC_CheckOut
C --> UC_CleanRoom
C --> UC_BookRoom
H --> UC_ProcessPayment
UC_OrderRoomService ..> UC_CancelReservation : <<include>>
@enduml