@startuml
skinparam defaultFontSize 11
left to right direction
actor "Delivery Service" as DeliveryService
actor "Customer" as Customer
rectangle "Ecommerce System" {
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Make Payment" as UC_MakePayment
  usecase "Checkout" as UC_Checkout
  usecase "Track Order" as UC_TrackOrder
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Cancel Order" as UC_CancelOrder
}
DeliveryService --> UC_BrowseProducts
DeliveryService --> UC_ApplyCoupon
Customer --> UC_ApplyCoupon
Customer --> UC_BrowseProducts
Customer --> UC_Checkout
@enduml