@startuml
skinparam defaultFontSize 11
left to right direction
actor "Librarian" as L
actor "Registrar" as R
rectangle "Education System" {
  usecase "Register Student" as UC_RegisterStudent
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Enroll Course" as UC_EnrollCourse
}
L --> UC_SubmitAssignment
L --> UC_RegisterStudent
L --> UC_ViewSchedule
R --> UC_ViewSchedule
R --> UC_EnrollCourse
UC_RegisterStudent ..|> UC_BorrowBook : <<include>>
@enduml