@startuml
skinparam monochrome true
skinparam defaultFontSize 13
left to right direction
actor "Admin" as A
actor "Librarian" as L
actor "Member" as M
rectangle "Library System" {
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Register Member" as UC_RegisterMember
  usecase "Pay Fine" as UC_PayFine
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Add New Book" as UC_AddNewBook
}
A --> UC_PayFine
L --> UC_PayFine
M --> UC_RenewLoan
UC_RegisterMember ..|> UC_PayFine : <<include>>
@enduml