@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
left to right direction
actor "Chef" as Chef
actor "Receptionist" as Receptionist
rectangle "Hotel System" {
  usecase "Clean Room" as UC_CleanRoom
  usecase "Request Service" as UC_RequestService
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Book Room" as UC_BookRoom
}
Chef --> UC_CleanRoom
Receptionist --> UC_RequestService
@enduml