@startuml
skinparam defaultFontSize 11
left to right direction
actor "Auditor" as A
actor "Account Holder" as AH
actor "Branch Manager" as BM
actor "ATM" as A1
rectangle "Banking System" {
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "View Statement" as UC_ViewStatement
  usecase "Open Account" as UC_OpenAccount
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Block Card" as UC_BlockCard
  usecase "Pay Bill" as UC_PayBill
}
A --> UC_TransferFunds
A --> UC_BlockCard
A --> UC_WithdrawCash
AH --> UC_TransferFunds
BM --> UC_ViewStatement
BM --> UC_PayBill
BM --> UC_TransferFunds
A1 --> UC_BlockCard
A1 --> UC_ViewStatement
@enduml