@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
left to right direction
actor "Librarian" as L
actor "Member" as M
rectangle "Library System" {
  usecase "Register Member" as UC_RegisterMember
  usecase "Pay Fine" as UC_PayFine
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Borrow Book" as UC_BorrowBook
}
L --> UC_PayFine
L --> UC_BorrowBook
L --> UC_SearchCatalog
M --> UC_RegisterMember
M --> UC_SearchCatalog
M --> UC_ReserveBook
UC_SearchCatalog ..> UC_RegisterMember : <<extend>>
@enduml