@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
left to right direction
actor "Branch Manager" as BranchManager
actor "Auditor" as Auditor
actor "Account Holder" as AccountHolder
actor "ATM" as ATM
rectangle "Banking System" {
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Block Card" as UC_BlockCard
  usecase "Open Account" as UC_OpenAccount
  usecase "View Statement" as UC_ViewStatement
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Pay Bill" as UC_PayBill
}
BranchManager --> UC_PayBill
BranchManager --> UC_TransferFunds
BranchManager --> UC_ApplyForLoan
Auditor --> UC_ApplyForLoan
Auditor --> UC_PayBill
AccountHolder --> UC_ViewStatement
ATM --> UC_OpenAccount
@enduml