@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
left to right direction
actor "Manager" as M
actor "Receptionist" as R
rectangle "Hotel System" {
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
  usecase "Check In" as UC_CheckIn
  usecase "Book Room" as UC_BookRoom
  usecase "Request Service" as UC_RequestService
  usecase "Order Room Service" as UC_OrderRoomService
}
M --> UC_CheckOut
R --> UC_CheckOut
R --> UC_OrderRoomService
UC_CheckIn ..> UC_ProcessPayment : <<extend>>
@enduml