@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
left to right direction
actor "Member" as Member
actor "Librarian" as Librarian
actor "Admin" as Admin
rectangle "Library System" {
  usecase "Return Book" as UC_ReturnBook
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Pay Fine" as UC_PayFine
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Reserve Book" as UC_ReserveBook
}
Member --> UC_ReturnBook
Member --> UC_RenewLoan
Librarian --> UC_BorrowBook
Admin --> UC_ReturnBook
Admin --> UC_BorrowBook
@enduml