@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
left to right direction
actor "Guest" as G
actor "Manager" as M
actor "Chef" as C
actor "Receptionist" as R
rectangle "Hotel System" {
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
  usecase "Book Room" as UC_BookRoom
  usecase "Check In" as UC_CheckIn
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Request Service" as UC_RequestService
}
G --> UC_BookRoom
G --> UC_CheckOut
M --> UC_CheckIn
C --> UC_CancelReservation
C --> UC_BookRoom
C --> UC_CheckIn
R --> UC_RequestService
R --> UC_BookRoom
R --> UC_ProcessPayment
@enduml