@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
left to right direction
actor "Member" as Member
actor "Admin" as Admin
actor "Librarian" as Librarian
rectangle "Library System" {
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Add New Book" as UC_AddNewBook
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Register Member" as UC_RegisterMember
}
Member --> UC_ReserveBook
Member --> UC_RenewLoan
Member --> UC_SearchCatalog
Admin --> UC_SearchCatalog
Admin --> UC_BorrowBook
Librarian --> UC_SearchCatalog
Librarian --> UC_BorrowBook
Librarian --> UC_AddNewBook
@enduml