@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
left to right direction
actor "Moderator" as Moderator
actor "Admin" as Admin
actor "User" as User
actor "Advertiser" as Advertiser
rectangle "Social Media System" {
  usecase "Like Post" as UC_LikePost
  usecase "Follow User" as UC_FollowUser
  usecase "Create Post" as UC_CreatePost
  usecase "Comment" as UC_Comment
  usecase "Share Post" as UC_SharePost
  usecase "Report Content" as UC_ReportContent
  usecase "Edit Profile" as UC_EditProfile
}
Moderator --> UC_FollowUser
Moderator --> UC_Comment
Admin --> UC_EditProfile
User --> UC_LikePost
Advertiser --> UC_EditProfile
Advertiser --> UC_SharePost
@enduml