@startuml
skinparam monochrome true
skinparam defaultFontSize 11
left to right direction
actor "Guest" as G
actor "Housekeeper" as H
actor "Receptionist" as R
actor "Chef" as C
rectangle "Hotel System" {
  usecase "Clean Room" as UC_CleanRoom
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Request Service" as UC_RequestService
  usecase "Book Room" as UC_BookRoom
  usecase "Check In" as UC_CheckIn
}
G --> UC_RequestService
G --> UC_CancelReservation
G --> UC_CheckIn
H --> UC_CancelReservation
H --> UC_RequestService
H --> UC_CleanRoom
R --> UC_CheckIn
C --> UC_CleanRoom
@enduml