@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Housekeeper" as H
actor "Manager" as M
actor "Chef" as C
rectangle "Hotel System" {
  usecase "Check Out" as UC_CheckOut
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Book Room" as UC_BookRoom
  usecase "Request Service" as UC_RequestService
}
H --> UC_CancelReservation
H --> UC_CheckOut
M --> UC_CancelReservation
M --> UC_ProcessPayment
C --> UC_CheckOut
UC_CheckOut ..> UC_ProcessPayment : <<extend>>
@enduml