@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
left to right direction
actor "Nurse" as N
actor "Receptionist" as R
actor "Lab Technician" as LT
rectangle "Healthcare System" {
  usecase "Run Lab Test" as UC_RunLabTest
  usecase "Issue Prescription" as UC_IssuePrescription
  usecase "Examine Patient" as UC_ExaminePatient
  usecase "Update Medical Record" as UC_UpdateMedicalRecord
  usecase "Process Insurance Claim" as UC_ProcessInsuranceClaim
}
N --> UC_RunLabTest
N --> UC_ExaminePatient
N --> UC_IssuePrescription
R --> UC_ProcessInsuranceClaim
R --> UC_ExaminePatient
LT --> UC_UpdateMedicalRecord
LT --> UC_RunLabTest
UC_UpdateMedicalRecord ..|> UC_IssuePrescription : <<extend>>
@enduml