@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
left to right direction
actor "Branch Manager" as BM
actor "Account Holder" as AH
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Open Account" as UC_OpenAccount
  usecase "Apply For Loan" as UC_ApplyForLoan
}
BM --> UC_ApplyForLoan
BM --> UC_DepositMoney
BM --> UC_TransferFunds
AH --> UC_OpenAccount
AH --> UC_DepositMoney
AH --> UC_ApplyForLoan
UC_DepositMoney ..|> UC_OpenAccount : <<extend>>
@enduml