@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
left to right direction
actor "Bank Teller" as BT
actor "Auditor" as A
actor "ATM" as A1
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "View Statement" as UC_ViewStatement
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Pay Bill" as UC_PayBill
}
BT --> UC_WithdrawCash
BT --> UC_ApplyForLoan
BT --> UC_ViewStatement
A --> UC_ViewStatement
A --> UC_ApplyForLoan
A1 --> UC_PayBill
A1 --> UC_ApplyForLoan
UC_BlockCard ..> UC_PayBill : <<extend>>
@enduml