@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
left to right direction
actor "Receptionist" as R
actor "Housekeeper" as H
actor "Manager" as M
actor "Chef" as C
rectangle "Hotel System" {
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Book Room" as UC_BookRoom
  usecase "Check In" as UC_CheckIn
  usecase "Clean Room" as UC_CleanRoom
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Check Out" as UC_CheckOut
}
R --> UC_OrderRoomService
H --> UC_CheckOut
H --> UC_OrderRoomService
H --> UC_BookRoom
M --> UC_CheckOut
M --> UC_OrderRoomService
C --> UC_CleanRoom
UC_BookRoom ..|> UC_CleanRoom : <<extend>>
@enduml