@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
left to right direction
actor "Manager" as M
actor "Guest" as G
actor "Chef" as C
rectangle "Hotel System" {
  usecase "Request Service" as UC_RequestService
  usecase "Book Room" as UC_BookRoom
  usecase "Check In" as UC_CheckIn
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Clean Room" as UC_CleanRoom
}
M --> UC_CleanRoom
G --> UC_ProcessPayment
G --> UC_CleanRoom
C --> UC_CheckIn
UC_BookRoom ..> UC_CancelReservation : <<extend>>
@enduml