@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
left to right direction
actor "Payment Gateway" as PG
actor "Seller" as S
rectangle "Ecommerce System" {
  usecase "Make Payment" as UC_MakePayment
  usecase "Checkout" as UC_Checkout
  usecase "Track Order" as UC_TrackOrder
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Add To Cart" as UC_AddToCart
}
PG --> UC_ManageInventory
PG --> UC_MakePayment
S --> UC_TrackOrder
@enduml