@startuml
skinparam shadowing true
left to right direction
actor "Librarian" as L
actor "Admin" as A
actor "Member" as M
rectangle "Library System" {
  usecase "Register Member" as UC_RegisterMember
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Add New Book" as UC_AddNewBook
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Return Book" as UC_ReturnBook
}
L --> UC_RenewLoan
L --> UC_AddNewBook
L --> UC_RegisterMember
A --> UC_ReserveBook
M --> UC_RenewLoan
@enduml