@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
left to right direction
actor "Parent" as P
actor "Admin" as A
rectangle "Education System" {
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Register Student" as UC_RegisterStudent
  usecase "Enroll Course" as UC_EnrollCourse
}
P --> UC_RegisterStudent
A --> UC_EnrollCourse
A --> UC_TakeAttendance
@enduml