@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
left to right direction
actor "Advertiser" as Advertiser
actor "Moderator" as Moderator
actor "User" as User
actor "Admin" as Admin
rectangle "Social Media System" {
  usecase "Share Post" as UC_SharePost
  usecase "Send Message" as UC_SendMessage
  usecase "Follow User" as UC_FollowUser
  usecase "Create Post" as UC_CreatePost
  usecase "Report Content" as UC_ReportContent
}
Advertiser --> UC_FollowUser
Advertiser --> UC_CreatePost
Moderator --> UC_SendMessage
User --> UC_FollowUser
User --> UC_ReportContent
User --> UC_SendMessage
Admin --> UC_SharePost
UC_SendMessage ..|> UC_CreatePost : <<include>>
@enduml