@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
left to right direction
actor "Admin" as Admin
actor "Advertiser" as Advertiser
rectangle "Social Media System" {
  usecase "Report Content" as UC_ReportContent
  usecase "Share Post" as UC_SharePost
  usecase "Follow User" as UC_FollowUser
  usecase "Send Message" as UC_SendMessage
  usecase "Like Post" as UC_LikePost
}
Admin --> UC_LikePost
Admin --> UC_SendMessage
Advertiser --> UC_SendMessage
Advertiser --> UC_FollowUser
Advertiser --> UC_SharePost
@enduml