@startuml
skinparam monochrome true
skinparam defaultFontSize 11
left to right direction
actor "Admin" as Admin
actor "Member" as Member
actor "Librarian" as Librarian
rectangle "Library System" {
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Register Member" as UC_RegisterMember
  usecase "Pay Fine" as UC_PayFine
  usecase "Add New Book" as UC_AddNewBook
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Return Book" as UC_ReturnBook
}
Admin --> UC_RenewLoan
Admin --> UC_AddNewBook
Admin --> UC_ReturnBook
Member --> UC_AddNewBook
Member --> UC_RegisterMember
Member --> UC_ReturnBook
Librarian --> UC_ReturnBook
@enduml