@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
left to right direction
actor "Guest" as Guest
actor "Chef" as Chef
actor "Manager" as Manager
rectangle "Hotel System" {
  usecase "Check In" as UC_CheckIn
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Request Service" as UC_RequestService
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Clean Room" as UC_CleanRoom
}
Guest --> UC_CancelReservation
Guest --> UC_ProcessPayment
Chef --> UC_CheckIn
Chef --> UC_ProcessPayment
Manager --> UC_CleanRoom
@enduml