@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
left to right direction
actor "Customer" as C
actor "Admin" as A
actor "Payment Gateway" as PG
rectangle "Ecommerce System" {
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Write Review" as UC_WriteReview
  usecase "Checkout" as UC_Checkout
  usecase "Make Payment" as UC_MakePayment
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Manage Inventory" as UC_ManageInventory
}
C --> UC_Checkout
A --> UC_WriteReview
PG --> UC_CancelOrder
PG --> UC_ManageInventory
UC_CancelOrder ..> UC_ManageInventory : <<include>>
@enduml