@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
left to right direction
actor "Receptionist" as R
actor "Doctor" as D
actor "Lab Technician" as LT
rectangle "Healthcare System" {
  usecase "Issue Prescription" as UC_IssuePrescription
  usecase "Update Medical Record" as UC_UpdateMedicalRecord
  usecase "Examine Patient" as UC_ExaminePatient
  usecase "Admit Patient" as UC_AdmitPatient
  usecase "Process Insurance Claim" as UC_ProcessInsuranceClaim
  usecase "Run Lab Test" as UC_RunLabTest
}
R --> UC_ExaminePatient
R --> UC_AdmitPatient
R --> UC_RunLabTest
D --> UC_ProcessInsuranceClaim
LT --> UC_ExaminePatient
LT --> UC_ProcessInsuranceClaim
UC_IssuePrescription ..|> UC_AdmitPatient : <<extend>>
@enduml