@startuml

left to right direction
actor "Admin" as Admin
actor "Librarian" as Librarian
rectangle "Library System" {
  usecase "Return Book" as UC_ReturnBook
  usecase "Register Member" as UC_RegisterMember
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Add New Book" as UC_AddNewBook
  usecase "Pay Fine" as UC_PayFine
  usecase "Renew Loan" as UC_RenewLoan
}
Admin --> UC_ReturnBook
Librarian --> UC_ReturnBook
Librarian --> UC_SearchCatalog
@enduml