@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
left to right direction
actor "Teacher" as T
actor "Student" as S
rectangle "Education System" {
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Register Student" as UC_RegisterStudent
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Grade Exam" as UC_GradeExam
}
T --> UC_TakeAttendance
T --> UC_EnrollCourse
S --> UC_EnrollCourse
S --> UC_BorrowBook
UC_EnrollCourse ..> UC_BorrowBook : <<include>>
@enduml