@startuml
skinparam monochrome true
skinparam defaultFontSize 11
left to right direction
actor "Receptionist" as Receptionist
actor "Housekeeper" as Housekeeper
rectangle "Hotel System" {
  usecase "Check In" as UC_CheckIn
  usecase "Book Room" as UC_BookRoom
  usecase "Clean Room" as UC_CleanRoom
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
  usecase "Request Service" as UC_RequestService
  usecase "Order Room Service" as UC_OrderRoomService
}
Receptionist --> UC_RequestService
Receptionist --> UC_OrderRoomService
Receptionist --> UC_CheckOut
Housekeeper --> UC_OrderRoomService
UC_RequestService ..|> UC_OrderRoomService : <<extend>>
@enduml