@startuml
skinparam monochrome true
left to right direction
actor "Student" as S
actor "Librarian" as L
rectangle "Education System" {
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Grade Exam" as UC_GradeExam
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Take Attendance" as UC_TakeAttendance
}
S --> UC_IssueCertificate
S --> UC_EnrollCourse
L --> UC_EnrollCourse
L --> UC_IssueCertificate
L --> UC_GradeExam
@enduml