@startuml
skinparam defaultFontSize 13
left to right direction
actor "ATM" as ATM
actor "Auditor" as Auditor
actor "Branch Manager" as BranchManager
rectangle "Banking System" {
  usecase "View Statement" as UC_ViewStatement
  usecase "Block Card" as UC_BlockCard
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Open Account" as UC_OpenAccount
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Pay Bill" as UC_PayBill
  usecase "Apply For Loan" as UC_ApplyForLoan
}
ATM --> UC_OpenAccount
ATM --> UC_DepositMoney
ATM --> UC_ViewStatement
Auditor --> UC_DepositMoney
Auditor --> UC_OpenAccount
BranchManager --> UC_ViewStatement
BranchManager --> UC_WithdrawCash
BranchManager --> UC_OpenAccount
@enduml