@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
left to right direction
actor "User" as U
actor "Advertiser" as A
actor "Admin" as A1
actor "Moderator" as M
rectangle "Social Media System" {
  usecase "Send Message" as UC_SendMessage
  usecase "Create Post" as UC_CreatePost
  usecase "Comment" as UC_Comment
  usecase "Like Post" as UC_LikePost
  usecase "Edit Profile" as UC_EditProfile
  usecase "Follow User" as UC_FollowUser
}
U --> UC_EditProfile
U --> UC_SendMessage
A --> UC_CreatePost
A --> UC_Comment
A1 --> UC_SendMessage
M --> UC_LikePost
M --> UC_SendMessage
@enduml