@startuml
skinparam monochrome true
left to right direction
actor "Receptionist" as Receptionist
actor "Manager" as Manager
actor "Guest" as Guest
actor "Chef" as Chef
rectangle "Hotel System" {
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Clean Room" as UC_CleanRoom
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Book Room" as UC_BookRoom
  usecase "Check In" as UC_CheckIn
  usecase "Request Service" as UC_RequestService
  usecase "Check Out" as UC_CheckOut
}
Receptionist --> UC_BookRoom
Receptionist --> UC_RequestService
Receptionist --> UC_OrderRoomService
Manager --> UC_CheckOut
Manager --> UC_CleanRoom
Guest --> UC_CheckIn
Guest --> UC_BookRoom
Guest --> UC_OrderRoomService
Chef --> UC_BookRoom
Chef --> UC_CheckOut
@enduml