@startuml
skinparam monochrome true
skinparam defaultFontSize 13
left to right direction
actor "Student" as S
actor "Teacher" as T
actor "Parent" as P
actor "Admin" as A
rectangle "Education System" {
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Grade Exam" as UC_GradeExam
}
S --> UC_GradeExam
T --> UC_ViewSchedule
T --> UC_TakeAttendance
P --> UC_GradeExam
A --> UC_BorrowBook
UC_BorrowBook ..> UC_ViewSchedule : <<include>>
@enduml