@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
left to right direction
actor "Chef" as Chef
actor "Receptionist" as Receptionist
actor "Housekeeper" as Housekeeper
rectangle "Hotel System" {
  usecase "Check In" as UC_CheckIn
  usecase "Book Room" as UC_BookRoom
  usecase "Request Service" as UC_RequestService
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Clean Room" as UC_CleanRoom
  usecase "Order Room Service" as UC_OrderRoomService
}
Chef --> UC_CancelReservation
Chef --> UC_CleanRoom
Receptionist --> UC_CheckIn
Receptionist --> UC_CleanRoom
Housekeeper --> UC_BookRoom
Housekeeper --> UC_CleanRoom
@enduml