@startuml
skinparam shadowing true
left to right direction
actor "Branch Manager" as BM
actor "Bank Teller" as BT
rectangle "Banking System" {
  usecase "Open Account" as UC_OpenAccount
  usecase "View Statement" as UC_ViewStatement
  usecase "Pay Bill" as UC_PayBill
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Block Card" as UC_BlockCard
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Transfer Funds" as UC_TransferFunds
}
BM --> UC_OpenAccount
BM --> UC_PayBill
BT --> UC_ApplyForLoan
BT --> UC_BlockCard
@enduml