@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Registrar" as Registrar
actor "Admin" as Admin
actor "Student" as Student
rectangle "Education System" {
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Register Student" as UC_RegisterStudent
  usecase "Grade Exam" as UC_GradeExam
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Submit Assignment" as UC_SubmitAssignment
}
Registrar --> UC_GradeExam
Registrar --> UC_ViewSchedule
Admin --> UC_GradeExam
Admin --> UC_SubmitAssignment
Student --> UC_SubmitAssignment
@enduml