@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
left to right direction
actor "Housekeeper" as H
actor "Chef" as C
actor "Guest" as G
rectangle "Hotel System" {
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Check Out" as UC_CheckOut
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Request Service" as UC_RequestService
  usecase "Clean Room" as UC_CleanRoom
}
H --> UC_CleanRoom
H --> UC_RequestService
H --> UC_CancelReservation
C --> UC_RequestService
C --> UC_CheckOut
G --> UC_CleanRoom
G --> UC_OrderRoomService
@enduml