@startuml
skinparam ArrowColor #555555
left to right direction
actor "ATM" as ATM
actor "Bank Teller" as BankTeller
rectangle "Banking System" {
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Block Card" as UC_BlockCard
}
ATM --> UC_BlockCard
ATM --> UC_ApplyForLoan
BankTeller --> UC_ApplyForLoan
BankTeller --> UC_TransferFunds
BankTeller --> UC_BlockCard
@enduml