@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
left to right direction
actor "Librarian" as L
actor "Member" as M
actor "Admin" as A
rectangle "Library System" {
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Pay Fine" as UC_PayFine
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Add New Book" as UC_AddNewBook
  usecase "Return Book" as UC_ReturnBook
}
L --> UC_AddNewBook
L --> UC_PayFine
L --> UC_ReturnBook
M --> UC_BorrowBook
M --> UC_ReturnBook
M --> UC_RenewLoan
A --> UC_BorrowBook
UC_ReturnBook ..> UC_BorrowBook : <<include>>
@enduml