@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
left to right direction
actor "Manager" as M
actor "Chef" as C
rectangle "Hotel System" {
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Clean Room" as UC_CleanRoom
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Request Service" as UC_RequestService
  usecase "Check In" as UC_CheckIn
  usecase "Book Room" as UC_BookRoom
}
M --> UC_CheckIn
C --> UC_CleanRoom
C --> UC_RequestService
@enduml