@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
left to right direction
actor "Librarian" as L
actor "Parent" as P
actor "Registrar" as R
actor "Student" as S
rectangle "Education System" {
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Register Student" as UC_RegisterStudent
  usecase "Grade Exam" as UC_GradeExam
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Borrow Book" as UC_BorrowBook
}
L --> UC_GradeExam
P --> UC_RegisterStudent
P --> UC_GradeExam
P --> UC_TakeAttendance
R --> UC_ViewSchedule
R --> UC_GradeExam
S --> UC_ViewSchedule
@enduml