@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
left to right direction
actor "Auditor" as A
actor "Bank Teller" as BT
actor "ATM" as A1
actor "Account Holder" as AH
rectangle "Banking System" {
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "View Statement" as UC_ViewStatement
  usecase "Pay Bill" as UC_PayBill
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Block Card" as UC_BlockCard
  usecase "Deposit Money" as UC_DepositMoney
}
A --> UC_ViewStatement
A --> UC_PayBill
BT --> UC_BlockCard
BT --> UC_WithdrawCash
BT --> UC_DepositMoney
A1 --> UC_ViewStatement
A1 --> UC_TransferFunds
AH --> UC_ViewStatement
AH --> UC_PayBill
@enduml