@startuml
skinparam shadowing true
left to right direction
actor "Admin" as A
actor "Member" as M
actor "Librarian" as L
rectangle "Library System" {
  usecase "Return Book" as UC_ReturnBook
  usecase "Register Member" as UC_RegisterMember
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Add New Book" as UC_AddNewBook
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Pay Fine" as UC_PayFine
}
A --> UC_ReturnBook
A --> UC_PayFine
M --> UC_RegisterMember
M --> UC_PayFine
L --> UC_RegisterMember
L --> UC_ReturnBook
UC_RegisterMember ..|> UC_ReturnBook : <<extend>>
@enduml