@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
left to right direction
actor "ATM" as A
actor "Bank Teller" as BT
actor "Account Holder" as AH
actor "Branch Manager" as BM
rectangle "Banking System" {
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Open Account" as UC_OpenAccount
  usecase "Pay Bill" as UC_PayBill
  usecase "Withdraw Cash" as UC_WithdrawCash
}
A --> UC_OpenAccount
A --> UC_ApplyForLoan
BT --> UC_TransferFunds
BT --> UC_PayBill
BT --> UC_ApplyForLoan
AH --> UC_ApplyForLoan
AH --> UC_WithdrawCash
BM --> UC_PayBill
UC_TransferFunds ..|> UC_ApplyForLoan : <<extend>>
@enduml