@startuml
skinparam monochrome true
left to right direction
actor "Admin" as Admin
actor "Customer" as Customer
actor "Payment Gateway" as PaymentGateway
rectangle "Ecommerce System" {
  usecase "Write Review" as UC_WriteReview
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Make Payment" as UC_MakePayment
  usecase "Add To Cart" as UC_AddToCart
  usecase "Track Order" as UC_TrackOrder
  usecase "Checkout" as UC_Checkout
  usecase "Manage Inventory" as UC_ManageInventory
}
Admin --> UC_Checkout
Customer --> UC_CancelOrder
PaymentGateway --> UC_MakePayment
PaymentGateway --> UC_CancelOrder
PaymentGateway --> UC_TrackOrder
@enduml