@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
left to right direction
actor "Bank Teller" as BankTeller
actor "Branch Manager" as BranchManager
actor "ATM" as ATM
rectangle "Banking System" {
  usecase "Open Account" as UC_OpenAccount
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Pay Bill" as UC_PayBill
  usecase "View Statement" as UC_ViewStatement
  usecase "Block Card" as UC_BlockCard
  usecase "Deposit Money" as UC_DepositMoney
}
BankTeller --> UC_ApplyForLoan
BranchManager --> UC_WithdrawCash
BranchManager --> UC_DepositMoney
BranchManager --> UC_ViewStatement
ATM --> UC_ViewStatement
@enduml