@startuml
skinparam monochrome true
skinparam defaultFontSize 13
left to right direction
actor "Advertiser" as A
actor "User" as U
actor "Admin" as A1
rectangle "Social Media System" {
  usecase "Share Post" as UC_SharePost
  usecase "Create Post" as UC_CreatePost
  usecase "Comment" as UC_Comment
  usecase "Report Content" as UC_ReportContent
  usecase "Edit Profile" as UC_EditProfile
  usecase "Send Message" as UC_SendMessage
}
A --> UC_EditProfile
U --> UC_SharePost
U --> UC_CreatePost
A1 --> UC_SendMessage
A1 --> UC_EditProfile
A1 --> UC_SharePost
UC_SharePost ..|> UC_EditProfile : <<include>>
@enduml