@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
left to right direction
actor "Advertiser" as A
actor "Admin" as A1
rectangle "Social Media System" {
  usecase "Create Post" as UC_CreatePost
  usecase "Send Message" as UC_SendMessage
  usecase "Like Post" as UC_LikePost
  usecase "Share Post" as UC_SharePost
  usecase "Report Content" as UC_ReportContent
}
A --> UC_CreatePost
A --> UC_SendMessage
A1 --> UC_SharePost
A1 --> UC_CreatePost
A1 --> UC_SendMessage
UC_LikePost ..|> UC_ReportContent : <<include>>
@enduml