@startuml
skinparam ArrowColor #555555
left to right direction
actor "Payment Gateway" as PaymentGateway
actor "Customer" as Customer
actor "Admin" as Admin
actor "Delivery Service" as DeliveryService
rectangle "Ecommerce System" {
  usecase "Write Review" as UC_WriteReview
  usecase "Checkout" as UC_Checkout
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Track Order" as UC_TrackOrder
  usecase "Add To Cart" as UC_AddToCart
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Make Payment" as UC_MakePayment
  usecase "Manage Inventory" as UC_ManageInventory
}
PaymentGateway --> UC_WriteReview
PaymentGateway --> UC_BrowseProducts
PaymentGateway --> UC_MakePayment
Customer --> UC_MakePayment
Customer --> UC_TrackOrder
Customer --> UC_AddToCart
Admin --> UC_MakePayment
Admin --> UC_WriteReview
DeliveryService --> UC_BrowseProducts
DeliveryService --> UC_ManageInventory
DeliveryService --> UC_ApplyCoupon
UC_AddToCart ..> UC_MakePayment : <<extend>>
@enduml