@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
left to right direction
actor "Admin" as Admin
actor "Student" as Student
rectangle "Education System" {
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Grade Exam" as UC_GradeExam
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Borrow Book" as UC_BorrowBook
}
Admin --> UC_GradeExam
Admin --> UC_BorrowBook
Student --> UC_TakeAttendance
Student --> UC_SubmitAssignment
Student --> UC_GradeExam
UC_EnrollCourse ..|> UC_TakeAttendance : <<extend>>
@enduml