@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
left to right direction
actor "Admin" as Admin
actor "Librarian" as Librarian
rectangle "Library System" {
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Register Member" as UC_RegisterMember
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Return Book" as UC_ReturnBook
  usecase "Pay Fine" as UC_PayFine
  usecase "Add New Book" as UC_AddNewBook
}
Admin --> UC_PayFine
Admin --> UC_BorrowBook
Admin --> UC_AddNewBook
Librarian --> UC_RegisterMember
Librarian --> UC_ReturnBook
Librarian --> UC_RenewLoan
UC_RegisterMember ..> UC_ReserveBook : <<extend>>
@enduml