@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "Manager" as M
actor "Chef" as C
actor "Guest" as G
rectangle "Hotel System" {
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Clean Room" as UC_CleanRoom
  usecase "Check Out" as UC_CheckOut
  usecase "Request Service" as UC_RequestService
  usecase "Check In" as UC_CheckIn
  usecase "Order Room Service" as UC_OrderRoomService
}
M --> UC_RequestService
M --> UC_CancelReservation
M --> UC_CheckIn
C --> UC_CancelReservation
C --> UC_CleanRoom
G --> UC_CheckIn
G --> UC_CancelReservation
G --> UC_CheckOut
@enduml