@startuml

left to right direction
actor "Account Holder" as AccountHolder
actor "Auditor" as Auditor
actor "ATM" as ATM
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Pay Bill" as UC_PayBill
}
AccountHolder --> UC_PayBill
Auditor --> UC_ApplyForLoan
ATM --> UC_BlockCard
UC_PayBill ..> UC_WithdrawCash : <<extend>>
@enduml