@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
left to right direction
actor "ATM" as ATM
actor "Auditor" as Auditor
rectangle "Banking System" {
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Pay Bill" as UC_PayBill
  usecase "Open Account" as UC_OpenAccount
  usecase "Block Card" as UC_BlockCard
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Deposit Money" as UC_DepositMoney
}
ATM --> UC_OpenAccount
ATM --> UC_PayBill
Auditor --> UC_OpenAccount
@enduml