@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
left to right direction
actor "Bank Teller" as BankTeller
actor "Auditor" as Auditor
actor "Account Holder" as AccountHolder
actor "ATM" as ATM
rectangle "Banking System" {
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "View Statement" as UC_ViewStatement
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Open Account" as UC_OpenAccount
  usecase "Block Card" as UC_BlockCard
  usecase "Pay Bill" as UC_PayBill
  usecase "Deposit Money" as UC_DepositMoney
}
BankTeller --> UC_ViewStatement
Auditor --> UC_OpenAccount
Auditor --> UC_WithdrawCash
AccountHolder --> UC_TransferFunds
AccountHolder --> UC_DepositMoney
AccountHolder --> UC_ApplyForLoan
ATM --> UC_TransferFunds
UC_ApplyForLoan ..> UC_BlockCard : <<include>>
@enduml