@startuml
skinparam monochrome true
left to right direction
actor "Bank Teller" as BT
actor "Auditor" as A
actor "ATM" as A1
rectangle "Banking System" {
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "View Statement" as UC_ViewStatement
  usecase "Open Account" as UC_OpenAccount
  usecase "Pay Bill" as UC_PayBill
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Block Card" as UC_BlockCard
  usecase "Deposit Money" as UC_DepositMoney
}
BT --> UC_TransferFunds
BT --> UC_ViewStatement
A --> UC_TransferFunds
A1 --> UC_DepositMoney
A1 --> UC_ViewStatement
@enduml