@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
left to right direction
actor "Account Holder" as AccountHolder
actor "Auditor" as Auditor
actor "ATM" as ATM
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Pay Bill" as UC_PayBill
  usecase "View Statement" as UC_ViewStatement
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Open Account" as UC_OpenAccount
}
AccountHolder --> UC_ApplyForLoan
Auditor --> UC_ViewStatement
ATM --> UC_ApplyForLoan
ATM --> UC_OpenAccount
ATM --> UC_PayBill
UC_ViewStatement ..|> UC_PayBill : <<include>>
@enduml