@startuml
skinparam monochrome true
skinparam shadowing true
left to right direction
actor "Auditor" as A
actor "Bank Teller" as BT
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Open Account" as UC_OpenAccount
  usecase "View Statement" as UC_ViewStatement
  usecase "Deposit Money" as UC_DepositMoney
}
A --> UC_OpenAccount
BT --> UC_ViewStatement
UC_ViewStatement ..> UC_TransferFunds : <<extend>>
@enduml