@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
left to right direction
actor "Moderator" as Moderator
actor "User" as User
rectangle "Social Media System" {
  usecase "Follow User" as UC_FollowUser
  usecase "Edit Profile" as UC_EditProfile
  usecase "Like Post" as UC_LikePost
  usecase "Report Content" as UC_ReportContent
  usecase "Comment" as UC_Comment
  usecase "Send Message" as UC_SendMessage
  usecase "Share Post" as UC_SharePost
  usecase "Create Post" as UC_CreatePost
}
Moderator --> UC_Comment
Moderator --> UC_LikePost
User --> UC_SendMessage
User --> UC_ReportContent
User --> UC_Comment
@enduml