@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "ATM" as ATM
actor "Bank Teller" as BankTeller
rectangle "Banking System" {
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Open Account" as UC_OpenAccount
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Pay Bill" as UC_PayBill
}
ATM --> UC_WithdrawCash
ATM --> UC_OpenAccount
BankTeller --> UC_WithdrawCash
UC_OpenAccount ..> UC_WithdrawCash : <<extend>>
@enduml