@startuml

left to right direction
actor "Admin" as Admin
actor "Member" as Member
actor "Librarian" as Librarian
rectangle "Library System" {
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Register Member" as UC_RegisterMember
  usecase "Return Book" as UC_ReturnBook
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Search Catalog" as UC_SearchCatalog
}
Admin --> UC_SearchCatalog
Admin --> UC_ReturnBook
Member --> UC_RenewLoan
Member --> UC_RegisterMember
Member --> UC_ReserveBook
Librarian --> UC_RenewLoan
Librarian --> UC_SearchCatalog
UC_ReturnBook ..|> UC_RenewLoan : <<extend>>
@enduml