@startuml

left to right direction
actor "Admin" as A
actor "Librarian" as L
rectangle "Library System" {
  usecase "Return Book" as UC_ReturnBook
  usecase "Register Member" as UC_RegisterMember
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Add New Book" as UC_AddNewBook
  usecase "Pay Fine" as UC_PayFine
  usecase "Renew Loan" as UC_RenewLoan
}
A --> UC_ReturnBook
L --> UC_ReturnBook
L --> UC_SearchCatalog
@enduml