@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
left to right direction
actor "User" as U
actor "Moderator" as M
actor "Advertiser" as A
actor "Admin" as A1
rectangle "Social Media System" {
  usecase "Share Post" as UC_SharePost
  usecase "Create Post" as UC_CreatePost
  usecase "Report Content" as UC_ReportContent
  usecase "Comment" as UC_Comment
  usecase "Send Message" as UC_SendMessage
  usecase "Follow User" as UC_FollowUser
  usecase "Edit Profile" as UC_EditProfile
  usecase "Like Post" as UC_LikePost
}
U --> UC_CreatePost
U --> UC_FollowUser
M --> UC_FollowUser
A --> UC_LikePost
A --> UC_SharePost
A1 --> UC_Comment
A1 --> UC_CreatePost
A1 --> UC_LikePost
UC_CreatePost ..> UC_ReportContent : <<extend>>
@enduml