@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
left to right direction
actor "Customer" as C
actor "Admin" as A
rectangle "Ecommerce System" {
  usecase "Add To Cart" as UC_AddToCart
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Write Review" as UC_WriteReview
  usecase "Track Order" as UC_TrackOrder
}
C --> UC_CancelOrder
C --> UC_ManageInventory
A --> UC_WriteReview
@enduml