@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
left to right direction
actor "Bank Teller" as BT
actor "Branch Manager" as BM
actor "ATM" as A
actor "Account Holder" as AH
rectangle "Banking System" {
  usecase "Open Account" as UC_OpenAccount
  usecase "Pay Bill" as UC_PayBill
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "View Statement" as UC_ViewStatement
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Block Card" as UC_BlockCard
  usecase "Withdraw Cash" as UC_WithdrawCash
}
BT --> UC_PayBill
BM --> UC_DepositMoney
BM --> UC_ApplyForLoan
BM --> UC_TransferFunds
A --> UC_TransferFunds
A --> UC_BlockCard
A --> UC_WithdrawCash
AH --> UC_TransferFunds
AH --> UC_PayBill
@enduml