@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Admin" as Admin
actor "Payment Gateway" as PaymentGateway
rectangle "Ecommerce System" {
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Add To Cart" as UC_AddToCart
}
Admin --> UC_ApplyCoupon
Admin --> UC_BrowseProducts
PaymentGateway --> UC_AddToCart
PaymentGateway --> UC_ApplyCoupon
PaymentGateway --> UC_BrowseProducts
@enduml