@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
left to right direction
actor "Manager" as M
actor "Receptionist" as R
actor "Guest" as G
rectangle "Hotel System" {
  usecase "Check In" as UC_CheckIn
  usecase "Book Room" as UC_BookRoom
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Clean Room" as UC_CleanRoom
  usecase "Request Service" as UC_RequestService
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
}
M --> UC_ProcessPayment
M --> UC_CheckOut
R --> UC_RequestService
R --> UC_CleanRoom
R --> UC_OrderRoomService
G --> UC_CheckIn
G --> UC_BookRoom
G --> UC_RequestService
@enduml