@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
left to right direction
actor "ATM" as ATM
actor "Account Holder" as AccountHolder
rectangle "Banking System" {
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Block Card" as UC_BlockCard
  usecase "Open Account" as UC_OpenAccount
  usecase "View Statement" as UC_ViewStatement
}
ATM --> UC_ViewStatement
ATM --> UC_TransferFunds
ATM --> UC_WithdrawCash
AccountHolder --> UC_ApplyForLoan
AccountHolder --> UC_OpenAccount
AccountHolder --> UC_BlockCard
UC_ApplyForLoan ..> UC_TransferFunds : <<include>>
@enduml