@startuml
skinparam defaultFontSize 13
left to right direction
actor "ATM" as A
actor "Bank Teller" as BT
actor "Account Holder" as AH
rectangle "Banking System" {
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Block Card" as UC_BlockCard
  usecase "View Statement" as UC_ViewStatement
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Open Account" as UC_OpenAccount
}
A --> UC_ViewStatement
A --> UC_DepositMoney
A --> UC_OpenAccount
BT --> UC_BlockCard
AH --> UC_ViewStatement
AH --> UC_TransferFunds
AH --> UC_WithdrawCash
UC_OpenAccount ..|> UC_ViewStatement : <<extend>>
@enduml