@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
left to right direction
actor "Bank Teller" as BT
actor "Auditor" as A
rectangle "Banking System" {
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Pay Bill" as UC_PayBill
  usecase "View Statement" as UC_ViewStatement
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Open Account" as UC_OpenAccount
}
BT --> UC_OpenAccount
A --> UC_DepositMoney
A --> UC_OpenAccount
A --> UC_PayBill
@enduml