@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Admin" as A
actor "Librarian" as L
actor "Member" as M
rectangle "Library System" {
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Pay Fine" as UC_PayFine
  usecase "Register Member" as UC_RegisterMember
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Search Catalog" as UC_SearchCatalog
}
A --> UC_SearchCatalog
A --> UC_RegisterMember
A --> UC_BorrowBook
L --> UC_ReserveBook
L --> UC_BorrowBook
M --> UC_RenewLoan
M --> UC_ReserveBook
M --> UC_BorrowBook
@enduml