@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Insurance Provider" as IP
actor "Doctor" as D
actor "Nurse" as N
actor "Patient" as P
rectangle "Healthcare System" {
  usecase "Discharge Patient" as UC_DischargePatient
  usecase "Process Insurance Claim" as UC_ProcessInsuranceClaim
  usecase "Book Appointment" as UC_BookAppointment
  usecase "Examine Patient" as UC_ExaminePatient
  usecase "Run Lab Test" as UC_RunLabTest
}
IP --> UC_ProcessInsuranceClaim
IP --> UC_BookAppointment
IP --> UC_RunLabTest
D --> UC_ProcessInsuranceClaim
N --> UC_ProcessInsuranceClaim
N --> UC_RunLabTest
N --> UC_BookAppointment
P --> UC_ExaminePatient
UC_ProcessInsuranceClaim ..> UC_ExaminePatient : <<include>>
@enduml