@startuml
skinparam defaultFontSize 11
left to right direction
actor "Moderator" as Moderator
actor "User" as User
actor "Advertiser" as Advertiser
actor "Admin" as Admin
rectangle "Social Media System" {
  usecase "Share Post" as UC_SharePost
  usecase "Send Message" as UC_SendMessage
  usecase "Report Content" as UC_ReportContent
  usecase "Like Post" as UC_LikePost
  usecase "Create Post" as UC_CreatePost
  usecase "Edit Profile" as UC_EditProfile
  usecase "Comment" as UC_Comment
}
Moderator --> UC_SharePost
Moderator --> UC_Comment
Moderator --> UC_LikePost
User --> UC_LikePost
User --> UC_EditProfile
User --> UC_Comment
Advertiser --> UC_LikePost
Advertiser --> UC_Comment
Advertiser --> UC_SendMessage
Admin --> UC_LikePost
Admin --> UC_SendMessage
Admin --> UC_ReportContent
@enduml