@startuml
skinparam defaultFontSize 13
left to right direction
actor "Librarian" as L
actor "Member" as M
rectangle "Library System" {
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Register Member" as UC_RegisterMember
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Add New Book" as UC_AddNewBook
  usecase "Pay Fine" as UC_PayFine
  usecase "Return Book" as UC_ReturnBook
  usecase "Search Catalog" as UC_SearchCatalog
}
L --> UC_AddNewBook
M --> UC_PayFine
M --> UC_SearchCatalog
M --> UC_ReserveBook
UC_RegisterMember ..|> UC_BorrowBook : <<extend>>
@enduml