@startuml
skinparam monochrome true
skinparam defaultFontSize 13
left to right direction
actor "Auditor" as A
actor "Account Holder" as AH
actor "Branch Manager" as BM
rectangle "Banking System" {
  usecase "View Statement" as UC_ViewStatement
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Block Card" as UC_BlockCard
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Open Account" as UC_OpenAccount
  usecase "Pay Bill" as UC_PayBill
}
A --> UC_ApplyForLoan
A --> UC_OpenAccount
A --> UC_TransferFunds
AH --> UC_ViewStatement
AH --> UC_TransferFunds
AH --> UC_ApplyForLoan
BM --> UC_TransferFunds
BM --> UC_WithdrawCash
BM --> UC_BlockCard
UC_WithdrawCash ..> UC_ViewStatement : <<extend>>
@enduml