@startuml

left to right direction
actor "Parent" as Parent
actor "Registrar" as Registrar
rectangle "Education System" {
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "View Schedule" as UC_ViewSchedule
}
Parent --> UC_BorrowBook
Registrar --> UC_EnrollCourse
UC_TakeAttendance ..|> UC_EnrollCourse : <<extend>>
@enduml