@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
left to right direction
actor "Member" as Member
actor "Admin" as Admin
rectangle "Library System" {
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Register Member" as UC_RegisterMember
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Add New Book" as UC_AddNewBook
  usecase "Return Book" as UC_ReturnBook
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Pay Fine" as UC_PayFine
}
Member --> UC_SearchCatalog
Member --> UC_AddNewBook
Admin --> UC_RegisterMember
Admin --> UC_SearchCatalog
@enduml