@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
left to right direction
actor "Branch Manager" as BM
actor "ATM" as A
actor "Bank Teller" as BT
actor "Account Holder" as AH
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "View Statement" as UC_ViewStatement
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Withdraw Cash" as UC_WithdrawCash
}
BM --> UC_ApplyForLoan
BM --> UC_TransferFunds
A --> UC_BlockCard
BT --> UC_DepositMoney
BT --> UC_WithdrawCash
BT --> UC_BlockCard
AH --> UC_DepositMoney
AH --> UC_ViewStatement
UC_ApplyForLoan ..> UC_WithdrawCash : <<extend>>
@enduml