@startuml

left to right direction
actor "Admin" as Admin
actor "Moderator" as Moderator
actor "User" as User
actor "Advertiser" as Advertiser
rectangle "Social Media System" {
  usecase "Create Post" as UC_CreatePost
  usecase "Follow User" as UC_FollowUser
  usecase "Like Post" as UC_LikePost
  usecase "Comment" as UC_Comment
  usecase "Report Content" as UC_ReportContent
}
Admin --> UC_Comment
Admin --> UC_ReportContent
Admin --> UC_FollowUser
Moderator --> UC_ReportContent
User --> UC_LikePost
User --> UC_ReportContent
Advertiser --> UC_Comment
@enduml