@startuml
skinparam monochrome true
left to right direction
actor "Receptionist" as R
actor "Lab Technician" as LT
rectangle "Healthcare System" {
  usecase "Process Insurance Claim" as UC_ProcessInsuranceClaim
  usecase "Update Medical Record" as UC_UpdateMedicalRecord
  usecase "Run Lab Test" as UC_RunLabTest
  usecase "Book Appointment" as UC_BookAppointment
  usecase "Examine Patient" as UC_ExaminePatient
  usecase "Admit Patient" as UC_AdmitPatient
  usecase "Discharge Patient" as UC_DischargePatient
}
R --> UC_AdmitPatient
LT --> UC_DischargePatient
LT --> UC_UpdateMedicalRecord
UC_BookAppointment ..> UC_DischargePatient : <<include>>
@enduml