@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
left to right direction
actor "Advertiser" as A
actor "Admin" as A1
actor "User" as U
rectangle "Social Media System" {
  usecase "Send Message" as UC_SendMessage
  usecase "Follow User" as UC_FollowUser
  usecase "Create Post" as UC_CreatePost
  usecase "Report Content" as UC_ReportContent
  usecase "Share Post" as UC_SharePost
  usecase "Edit Profile" as UC_EditProfile
}
A --> UC_ReportContent
A1 --> UC_EditProfile
U --> UC_ReportContent
U --> UC_EditProfile
U --> UC_SendMessage
UC_SendMessage ..> UC_CreatePost : <<include>>
@enduml