@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam defaultFontSize 13
left to right direction
actor "Customer" as Customer
actor "Delivery Service" as DeliveryService
actor "Seller" as Seller
rectangle "Ecommerce System" {
  usecase "Add To Cart" as UC_AddToCart
  usecase "Track Order" as UC_TrackOrder
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Checkout" as UC_Checkout
}
Customer --> UC_Checkout
Customer --> UC_AddToCart
DeliveryService --> UC_BrowseProducts
DeliveryService --> UC_Checkout
DeliveryService --> UC_ManageInventory
Seller --> UC_BrowseProducts
Seller --> UC_AddToCart
@enduml