@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 13
left to right direction
actor "Bank Teller" as BT
actor "ATM" as A
actor "Account Holder" as AH
actor "Branch Manager" as BM
rectangle "Banking System" {
  usecase "Pay Bill" as UC_PayBill
  usecase "Block Card" as UC_BlockCard
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Open Account" as UC_OpenAccount
  usecase "View Statement" as UC_ViewStatement
  usecase "Withdraw Cash" as UC_WithdrawCash
}
BT --> UC_TransferFunds
BT --> UC_BlockCard
A --> UC_BlockCard
AH --> UC_WithdrawCash
AH --> UC_BlockCard
AH --> UC_OpenAccount
BM --> UC_BlockCard
UC_OpenAccount ..> UC_DepositMoney : <<include>>
@enduml