@startuml
skinparam monochrome true
skinparam shadowing true
left to right direction
actor "Fleet Manager" as FM
actor "Driver" as D
rectangle "Logistics System" {
  usecase "Report Issue" as UC_ReportIssue
  usecase "Track Shipment" as UC_TrackShipment
  usecase "Assign Route" as UC_AssignRoute
  usecase "Update Inventory" as UC_UpdateInventory
  usecase "Fuel Vehicle" as UC_FuelVehicle
  usecase "Deliver Package" as UC_DeliverPackage
  usecase "Load Package" as UC_LoadPackage
}
FM --> UC_AssignRoute
FM --> UC_FuelVehicle
D --> UC_FuelVehicle
D --> UC_ReportIssue
D --> UC_DeliverPackage
@enduml