@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 13
left to right direction
actor "ATM" as A
actor "Auditor" as A1
actor "Account Holder" as AH
rectangle "Banking System" {
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Open Account" as UC_OpenAccount
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "View Statement" as UC_ViewStatement
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Pay Bill" as UC_PayBill
}
A --> UC_OpenAccount
A1 --> UC_PayBill
A1 --> UC_WithdrawCash
A1 --> UC_TransferFunds
AH --> UC_WithdrawCash
UC_TransferFunds ..|> UC_PayBill : <<include>>
@enduml