@startuml
skinparam monochrome true
skinparam defaultFontSize 11
left to right direction
actor "Customer" as Customer
actor "Seller" as Seller
actor "Delivery Service" as DeliveryService
actor "Payment Gateway" as PaymentGateway
rectangle "Ecommerce System" {
  usecase "Write Review" as UC_WriteReview
  usecase "Add To Cart" as UC_AddToCart
  usecase "Checkout" as UC_Checkout
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Make Payment" as UC_MakePayment
  usecase "Manage Inventory" as UC_ManageInventory
}
Customer --> UC_AddToCart
Seller --> UC_WriteReview
Seller --> UC_AddToCart
Seller --> UC_BrowseProducts
DeliveryService --> UC_AddToCart
PaymentGateway --> UC_Checkout
PaymentGateway --> UC_CancelOrder
PaymentGateway --> UC_WriteReview
@enduml