@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 13
left to right direction
actor "Bank Teller" as BT
actor "ATM" as A
rectangle "Banking System" {
  usecase "Open Account" as UC_OpenAccount
  usecase "View Statement" as UC_ViewStatement
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Pay Bill" as UC_PayBill
  usecase "Block Card" as UC_BlockCard
}
BT --> UC_PayBill
BT --> UC_OpenAccount
BT --> UC_ViewStatement
A --> UC_BlockCard
A --> UC_DepositMoney
A --> UC_ViewStatement
@enduml