@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
left to right direction
actor "Chef" as Chef
actor "Guest" as Guest
actor "Receptionist" as Receptionist
rectangle "Hotel System" {
  usecase "Request Service" as UC_RequestService
  usecase "Check Out" as UC_CheckOut
  usecase "Clean Room" as UC_CleanRoom
  usecase "Book Room" as UC_BookRoom
  usecase "Order Room Service" as UC_OrderRoomService
}
Chef --> UC_OrderRoomService
Chef --> UC_BookRoom
Guest --> UC_BookRoom
Receptionist --> UC_CleanRoom
Receptionist --> UC_RequestService
UC_CheckOut ..> UC_OrderRoomService : <<extend>>
@enduml