@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
left to right direction
actor "Payment Gateway" as PaymentGateway
actor "Customer" as Customer
actor "Delivery Service" as DeliveryService
rectangle "Ecommerce System" {
  usecase "Checkout" as UC_Checkout
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Write Review" as UC_WriteReview
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Track Order" as UC_TrackOrder
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Make Payment" as UC_MakePayment
  usecase "Add To Cart" as UC_AddToCart
}
PaymentGateway --> UC_Checkout
Customer --> UC_MakePayment
Customer --> UC_TrackOrder
DeliveryService --> UC_MakePayment
UC_MakePayment ..|> UC_AddToCart : <<extend>>
@enduml