@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
left to right direction
actor "Seller" as Seller
actor "Delivery Service" as DeliveryService
actor "Customer" as Customer
rectangle "Ecommerce System" {
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Add To Cart" as UC_AddToCart
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Track Order" as UC_TrackOrder
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Write Review" as UC_WriteReview
  usecase "Browse Products" as UC_BrowseProducts
}
Seller --> UC_TrackOrder
Seller --> UC_ApplyCoupon
DeliveryService --> UC_TrackOrder
Customer --> UC_AddToCart
@enduml