@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
left to right direction
actor "Admin" as A
actor "User" as U
rectangle "Social Media System" {
  usecase "Share Post" as UC_SharePost
  usecase "Send Message" as UC_SendMessage
  usecase "Follow User" as UC_FollowUser
  usecase "Like Post" as UC_LikePost
  usecase "Report Content" as UC_ReportContent
  usecase "Comment" as UC_Comment
  usecase "Create Post" as UC_CreatePost
}
A --> UC_Comment
U --> UC_FollowUser
@enduml