@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
left to right direction
actor "Manager" as M
actor "Guest" as G
actor "Housekeeper" as H
actor "Chef" as C
rectangle "Hotel System" {
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Book Room" as UC_BookRoom
  usecase "Check Out" as UC_CheckOut
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Process Payment" as UC_ProcessPayment
}
M --> UC_OrderRoomService
M --> UC_CheckOut
M --> UC_BookRoom
G --> UC_ProcessPayment
G --> UC_OrderRoomService
H --> UC_CheckOut
H --> UC_ProcessPayment
H --> UC_OrderRoomService
C --> UC_OrderRoomService
C --> UC_CancelReservation
@enduml