@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
left to right direction
actor "Admin" as A
actor "Member" as M
rectangle "Library System" {
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Return Book" as UC_ReturnBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Pay Fine" as UC_PayFine
  usecase "Borrow Book" as UC_BorrowBook
}
A --> UC_RenewLoan
A --> UC_ReserveBook
M --> UC_BorrowBook
@enduml