@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam defaultFontSize 11
left to right direction
actor "Admin" as Admin
actor "Payment Gateway" as PaymentGateway
rectangle "Ecommerce System" {
  usecase "Make Payment" as UC_MakePayment
  usecase "Add To Cart" as UC_AddToCart
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Track Order" as UC_TrackOrder
  usecase "Checkout" as UC_Checkout
}
Admin --> UC_ManageInventory
Admin --> UC_AddToCart
Admin --> UC_MakePayment
PaymentGateway --> UC_ManageInventory
PaymentGateway --> UC_AddToCart
PaymentGateway --> UC_TrackOrder
@enduml