@startuml
skinparam monochrome true
skinparam defaultFontSize 11
left to right direction
actor "Branch Manager" as BranchManager
actor "Auditor" as Auditor
rectangle "Banking System" {
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "View Statement" as UC_ViewStatement
  usecase "Open Account" as UC_OpenAccount
  usecase "Pay Bill" as UC_PayBill
  usecase "Block Card" as UC_BlockCard
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Apply For Loan" as UC_ApplyForLoan
}
BranchManager --> UC_OpenAccount
BranchManager --> UC_ViewStatement
Auditor --> UC_TransferFunds
Auditor --> UC_OpenAccount
@enduml