@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 13
left to right direction
actor "Auditor" as A
actor "ATM" as A1
actor "Bank Teller" as BT
actor "Branch Manager" as BM
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "View Statement" as UC_ViewStatement
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Pay Bill" as UC_PayBill
}
A --> UC_DepositMoney
A1 --> UC_BlockCard
A1 --> UC_PayBill
A1 --> UC_WithdrawCash
BT --> UC_PayBill
BT --> UC_DepositMoney
BM --> UC_WithdrawCash
BM --> UC_PayBill
BM --> UC_BlockCard
@enduml