@startuml
skinparam shadowing true
left to right direction
actor "Parent" as Parent
actor "Admin" as Admin
actor "Registrar" as Registrar
rectangle "Education System" {
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "View Schedule" as UC_ViewSchedule
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Submit Assignment" as UC_SubmitAssignment
}
Parent --> UC_IssueCertificate
Admin --> UC_SubmitAssignment
Admin --> UC_TakeAttendance
Admin --> UC_IssueCertificate
Registrar --> UC_IssueCertificate
Registrar --> UC_ViewSchedule
@enduml