@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
left to right direction
actor "Auditor" as A
actor "Branch Manager" as BM
rectangle "Banking System" {
  usecase "Deposit Money" as UC_DepositMoney
  usecase "View Statement" as UC_ViewStatement
  usecase "Pay Bill" as UC_PayBill
  usecase "Block Card" as UC_BlockCard
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Transfer Funds" as UC_TransferFunds
}
A --> UC_TransferFunds
A --> UC_BlockCard
BM --> UC_PayBill
BM --> UC_ViewStatement
@enduml