@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
left to right direction
actor "Admin" as Admin
actor "Member" as Member
actor "Librarian" as Librarian
rectangle "Library System" {
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Register Member" as UC_RegisterMember
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Add New Book" as UC_AddNewBook
  usecase "Return Book" as UC_ReturnBook
  usecase "Borrow Book" as UC_BorrowBook
}
Admin --> UC_ReturnBook
Admin --> UC_ReserveBook
Admin --> UC_RenewLoan
Member --> UC_BorrowBook
Member --> UC_AddNewBook
Member --> UC_ReserveBook
Librarian --> UC_BorrowBook
Librarian --> UC_RenewLoan
@enduml