@startuml
skinparam defaultFontSize 11
left to right direction
actor "Payment Gateway" as PaymentGateway
actor "Admin" as Admin
rectangle "Ecommerce System" {
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Write Review" as UC_WriteReview
  usecase "Add To Cart" as UC_AddToCart
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Make Payment" as UC_MakePayment
}
PaymentGateway --> UC_ApplyCoupon
Admin --> UC_ApplyCoupon
@enduml