@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam ArrowColor #555555
left to right direction
actor "ATM" as ATM
actor "Account Holder" as AccountHolder
actor "Auditor" as Auditor
actor "Branch Manager" as BranchManager
rectangle "Banking System" {
  usecase "Open Account" as UC_OpenAccount
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Block Card" as UC_BlockCard
  usecase "Transfer Funds" as UC_TransferFunds
}
ATM --> UC_TransferFunds
ATM --> UC_BlockCard
ATM --> UC_WithdrawCash
AccountHolder --> UC_DepositMoney
AccountHolder --> UC_TransferFunds
AccountHolder --> UC_ApplyForLoan
Auditor --> UC_TransferFunds
Auditor --> UC_OpenAccount
BranchManager --> UC_DepositMoney
BranchManager --> UC_ApplyForLoan
UC_TransferFunds ..> UC_DepositMoney : <<extend>>
@enduml