@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Admin" as A
actor "Payment Gateway" as PG
rectangle "Ecommerce System" {
  usecase "Write Review" as UC_WriteReview
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Track Order" as UC_TrackOrder
  usecase "Add To Cart" as UC_AddToCart
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Checkout" as UC_Checkout
}
A --> UC_AddToCart
A --> UC_Checkout
PG --> UC_Checkout
PG --> UC_WriteReview
PG --> UC_BrowseProducts
@enduml