@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
left to right direction
actor "ATM" as ATM
actor "Account Holder" as AccountHolder
actor "Branch Manager" as BranchManager
rectangle "Banking System" {
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Open Account" as UC_OpenAccount
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Pay Bill" as UC_PayBill
  usecase "Transfer Funds" as UC_TransferFunds
}
ATM --> UC_PayBill
AccountHolder --> UC_PayBill
BranchManager --> UC_ApplyForLoan
UC_DepositMoney ..> UC_ApplyForLoan : <<extend>>
@enduml