@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
left to right direction
actor "Auditor" as A
actor "Branch Manager" as BM
actor "Bank Teller" as BT
actor "ATM" as A1
rectangle "Banking System" {
  usecase "Open Account" as UC_OpenAccount
  usecase "Pay Bill" as UC_PayBill
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Block Card" as UC_BlockCard
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "View Statement" as UC_ViewStatement
}
A --> UC_ViewStatement
A --> UC_PayBill
BM --> UC_WithdrawCash
BM --> UC_ApplyForLoan
BT --> UC_WithdrawCash
BT --> UC_TransferFunds
A1 --> UC_OpenAccount
UC_OpenAccount ..|> UC_BlockCard : <<include>>
@enduml