@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
left to right direction
actor "Admin" as Admin
actor "Payment Gateway" as PaymentGateway
actor "Delivery Service" as DeliveryService
rectangle "Ecommerce System" {
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Write Review" as UC_WriteReview
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Checkout" as UC_Checkout
  usecase "Add To Cart" as UC_AddToCart
}
Admin --> UC_CancelOrder
PaymentGateway --> UC_BrowseProducts
PaymentGateway --> UC_WriteReview
DeliveryService --> UC_WriteReview
@enduml