@startuml

left to right direction
actor "Account Holder" as AH
actor "Auditor" as A
actor "ATM" as A1
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Pay Bill" as UC_PayBill
}
AH --> UC_PayBill
A --> UC_ApplyForLoan
A1 --> UC_BlockCard
UC_PayBill ..> UC_WithdrawCash : <<extend>>
@enduml