@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
left to right direction
actor "Librarian" as Librarian
actor "Admin" as Admin
actor "Parent" as Parent
rectangle "Education System" {
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Grade Exam" as UC_GradeExam
  usecase "Register Student" as UC_RegisterStudent
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Take Attendance" as UC_TakeAttendance
}
Librarian --> UC_SubmitAssignment
Admin --> UC_SubmitAssignment
Admin --> UC_GradeExam
Admin --> UC_RegisterStudent
Parent --> UC_IssueCertificate
Parent --> UC_TakeAttendance
Parent --> UC_GradeExam
UC_EnrollCourse ..|> UC_TakeAttendance : <<extend>>
@enduml