@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
left to right direction
actor "Chef" as Chef
actor "Receptionist" as Receptionist
actor "Housekeeper" as Housekeeper
actor "Manager" as Manager
rectangle "Hotel System" {
  usecase "Request Service" as UC_RequestService
  usecase "Check In" as UC_CheckIn
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Clean Room" as UC_CleanRoom
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Book Room" as UC_BookRoom
}
Chef --> UC_ProcessPayment
Receptionist --> UC_OrderRoomService
Receptionist --> UC_CleanRoom
Housekeeper --> UC_OrderRoomService
Housekeeper --> UC_CleanRoom
Housekeeper --> UC_CheckIn
Manager --> UC_RequestService
UC_BookRoom ..> UC_CleanRoom : <<include>>
@enduml