@startuml
skinparam defaultFontSize 11
left to right direction
actor "Receptionist" as R
actor "Manager" as M
rectangle "Hotel System" {
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
  usecase "Book Room" as UC_BookRoom
  usecase "Check In" as UC_CheckIn
  usecase "Request Service" as UC_RequestService
}
R --> UC_RequestService
M --> UC_CheckOut
M --> UC_BookRoom
M --> UC_RequestService
@enduml