@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
skinparam shadowing true
left to right direction
actor "Parent" as P
actor "Registrar" as R
rectangle "Education System" {
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Register Student" as UC_RegisterStudent
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Grade Exam" as UC_GradeExam
}
P --> UC_GradeExam
R --> UC_TakeAttendance
R --> UC_RegisterStudent
UC_TakeAttendance ..> UC_GradeExam : <<extend>>
@enduml