@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
left to right direction
actor "Admin" as A
actor "Librarian" as L
rectangle "Library System" {
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Pay Fine" as UC_PayFine
  usecase "Return Book" as UC_ReturnBook
  usecase "Register Member" as UC_RegisterMember
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Add New Book" as UC_AddNewBook
}
A --> UC_RenewLoan
A --> UC_BorrowBook
A --> UC_SearchCatalog
L --> UC_AddNewBook
L --> UC_BorrowBook
UC_AddNewBook ..|> UC_SearchCatalog : <<include>>
@enduml