@startuml
skinparam ArrowColor #555555
left to right direction
actor "Branch Manager" as BranchManager
actor "ATM" as ATM
actor "Bank Teller" as BankTeller
actor "Auditor" as Auditor
rectangle "Banking System" {
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Pay Bill" as UC_PayBill
  usecase "Open Account" as UC_OpenAccount
  usecase "Block Card" as UC_BlockCard
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Deposit Money" as UC_DepositMoney
}
BranchManager --> UC_DepositMoney
BranchManager --> UC_BlockCard
BranchManager --> UC_ApplyForLoan
ATM --> UC_ApplyForLoan
BankTeller --> UC_WithdrawCash
BankTeller --> UC_PayBill
BankTeller --> UC_OpenAccount
Auditor --> UC_BlockCard
Auditor --> UC_OpenAccount
UC_ApplyForLoan ..|> UC_OpenAccount : <<include>>
@enduml