@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #E8F4FA
skinparam classBorderColor #2C7DA0
skinparam shadowing true
left to right direction
actor "Delivery Service" as DS
actor "Payment Gateway" as PG
actor "Customer" as C
actor "Seller" as S
rectangle "Ecommerce System" {
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Checkout" as UC_Checkout
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Add To Cart" as UC_AddToCart
  usecase "Track Order" as UC_TrackOrder
  usecase "Write Review" as UC_WriteReview
}
DS --> UC_WriteReview
DS --> UC_CancelOrder
PG --> UC_TrackOrder
PG --> UC_CancelOrder
PG --> UC_WriteReview
C --> UC_CancelOrder
C --> UC_Checkout
C --> UC_WriteReview
S --> UC_TrackOrder
S --> UC_CancelOrder
S --> UC_BrowseProducts
@enduml