@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "Account Holder" as AccountHolder
actor "Bank Teller" as BankTeller
rectangle "Banking System" {
  usecase "View Statement" as UC_ViewStatement
  usecase "Open Account" as UC_OpenAccount
  usecase "Block Card" as UC_BlockCard
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Apply For Loan" as UC_ApplyForLoan
}
AccountHolder --> UC_ViewStatement
BankTeller --> UC_OpenAccount
BankTeller --> UC_DepositMoney
BankTeller --> UC_ViewStatement
UC_ViewStatement ..> UC_ApplyForLoan : <<extend>>
@enduml