@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam defaultFontSize 13
left to right direction
actor "Auditor" as Auditor
actor "Bank Teller" as BankTeller
actor "Branch Manager" as BranchManager
rectangle "Banking System" {
  usecase "Pay Bill" as UC_PayBill
  usecase "Deposit Money" as UC_DepositMoney
  usecase "View Statement" as UC_ViewStatement
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Block Card" as UC_BlockCard
}
Auditor --> UC_TransferFunds
BankTeller --> UC_DepositMoney
BankTeller --> UC_TransferFunds
BranchManager --> UC_BlockCard
BranchManager --> UC_TransferFunds
BranchManager --> UC_PayBill
UC_ApplyForLoan ..|> UC_BlockCard : <<include>>
@enduml