@startuml
skinparam monochrome true
skinparam defaultFontSize 13
left to right direction
actor "Admin" as A
actor "Librarian" as L
actor "Registrar" as R
rectangle "Education System" {
  usecase "Register Student" as UC_RegisterStudent
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Grade Exam" as UC_GradeExam
  usecase "Enroll Course" as UC_EnrollCourse
}
A --> UC_SubmitAssignment
A --> UC_EnrollCourse
L --> UC_TakeAttendance
L --> UC_SubmitAssignment
L --> UC_RegisterStudent
R --> UC_TakeAttendance
R --> UC_IssueCertificate
UC_GradeExam ..> UC_TakeAttendance : <<extend>>
@enduml