@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam defaultFontSize 11
left to right direction
actor "Auditor" as A
actor "Bank Teller" as BT
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Open Account" as UC_OpenAccount
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Transfer Funds" as UC_TransferFunds
}
A --> UC_DepositMoney
A --> UC_TransferFunds
BT --> UC_ApplyForLoan
UC_BlockCard ..|> UC_TransferFunds : <<extend>>
@enduml