@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
left to right direction
actor "Branch Manager" as BM
actor "Account Holder" as AH
actor "Auditor" as A
actor "Bank Teller" as BT
rectangle "Banking System" {
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Block Card" as UC_BlockCard
  usecase "Open Account" as UC_OpenAccount
  usecase "Deposit Money" as UC_DepositMoney
  usecase "View Statement" as UC_ViewStatement
}
BM --> UC_ApplyForLoan
AH --> UC_TransferFunds
AH --> UC_BlockCard
A --> UC_ApplyForLoan
A --> UC_DepositMoney
A --> UC_BlockCard
BT --> UC_OpenAccount
BT --> UC_DepositMoney
@enduml