@startuml
skinparam monochrome true
left to right direction
actor "Branch Manager" as BM
actor "Bank Teller" as BT
actor "Auditor" as A
actor "Account Holder" as AH
rectangle "Banking System" {
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Block Card" as UC_BlockCard
  usecase "Pay Bill" as UC_PayBill
  usecase "Open Account" as UC_OpenAccount
  usecase "Apply For Loan" as UC_ApplyForLoan
}
BM --> UC_OpenAccount
BM --> UC_BlockCard
BT --> UC_TransferFunds
BT --> UC_ApplyForLoan
A --> UC_TransferFunds
A --> UC_WithdrawCash
A --> UC_DepositMoney
AH --> UC_ApplyForLoan
AH --> UC_TransferFunds
@enduml