@startuml
skinparam monochrome true
skinparam defaultFontSize 13
left to right direction
actor "Admin" as A
actor "Member" as M
rectangle "Library System" {
  usecase "Return Book" as UC_ReturnBook
  usecase "Pay Fine" as UC_PayFine
  usecase "Register Member" as UC_RegisterMember
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Search Catalog" as UC_SearchCatalog
}
A --> UC_ReturnBook
A --> UC_PayFine
A --> UC_BorrowBook
M --> UC_BorrowBook
M --> UC_SearchCatalog
@enduml