@startuml
skinparam ArrowColor #555555
left to right direction
actor "Branch Manager" as BM
actor "Auditor" as A
actor "Account Holder" as AH
actor "ATM" as A1
rectangle "Banking System" {
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Pay Bill" as UC_PayBill
  usecase "Open Account" as UC_OpenAccount
  usecase "View Statement" as UC_ViewStatement
  usecase "Transfer Funds" as UC_TransferFunds
}
BM --> UC_ViewStatement
A --> UC_PayBill
AH --> UC_ViewStatement
A1 --> UC_PayBill
A1 --> UC_ViewStatement
A1 --> UC_ApplyForLoan
@enduml