@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "Customer" as C
actor "Payment Gateway" as PG
actor "Seller" as S
actor "Delivery Service" as DS
rectangle "Ecommerce System" {
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Checkout" as UC_Checkout
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Track Order" as UC_TrackOrder
  usecase "Apply Coupon" as UC_ApplyCoupon
}
C --> UC_ApplyCoupon
PG --> UC_ManageInventory
S --> UC_BrowseProducts
S --> UC_Checkout
S --> UC_TrackOrder
DS --> UC_TrackOrder
DS --> UC_Checkout
DS --> UC_BrowseProducts
@enduml