@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
left to right direction
actor "Member" as Member
actor "Admin" as Admin
actor "Librarian" as Librarian
rectangle "Library System" {
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Return Book" as UC_ReturnBook
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Pay Fine" as UC_PayFine
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Register Member" as UC_RegisterMember
}
Member --> UC_ReserveBook
Member --> UC_RenewLoan
Admin --> UC_ReturnBook
Admin --> UC_SearchCatalog
Admin --> UC_BorrowBook
Librarian --> UC_PayFine
@enduml