@startuml
skinparam shadowing true
left to right direction
actor "Student" as Student
actor "Teacher" as Teacher
rectangle "Education System" {
  usecase "Register Student" as UC_RegisterStudent
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "Grade Exam" as UC_GradeExam
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Take Attendance" as UC_TakeAttendance
}
Student --> UC_TakeAttendance
Teacher --> UC_SubmitAssignment
UC_RegisterStudent ..|> UC_IssueCertificate : <<include>>
@enduml