@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
left to right direction
actor "Chef" as Chef
actor "Manager" as Manager
actor "Receptionist" as Receptionist
actor "Housekeeper" as Housekeeper
rectangle "Hotel System" {
  usecase "Request Service" as UC_RequestService
  usecase "Book Room" as UC_BookRoom
  usecase "Clean Room" as UC_CleanRoom
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Check Out" as UC_CheckOut
  usecase "Cancel Reservation" as UC_CancelReservation
}
Chef --> UC_OrderRoomService
Manager --> UC_RequestService
Receptionist --> UC_CleanRoom
Housekeeper --> UC_CleanRoom
Housekeeper --> UC_CheckOut
Housekeeper --> UC_OrderRoomService
@enduml