@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
left to right direction
actor "Admin" as Admin
actor "Librarian" as Librarian
rectangle "Education System" {
  usecase "Register Student" as UC_RegisterStudent
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Enroll Course" as UC_EnrollCourse
  usecase "Issue Certificate" as UC_IssueCertificate
  usecase "View Schedule" as UC_ViewSchedule
}
Admin --> UC_RegisterStudent
Admin --> UC_ViewSchedule
Librarian --> UC_ViewSchedule
@enduml