@startuml
skinparam shadowing true
left to right direction
actor "Auditor" as A
actor "Bank Teller" as BT
actor "Account Holder" as AH
rectangle "Banking System" {
  usecase "Open Account" as UC_OpenAccount
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Block Card" as UC_BlockCard
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "View Statement" as UC_ViewStatement
  usecase "Apply For Loan" as UC_ApplyForLoan
}
A --> UC_BlockCard
A --> UC_ViewStatement
A --> UC_WithdrawCash
BT --> UC_TransferFunds
AH --> UC_DepositMoney
UC_ApplyForLoan ..> UC_BlockCard : <<extend>>
@enduml