@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
left to right direction
actor "Chef" as C
actor "Housekeeper" as H
actor "Manager" as M
actor "Guest" as G
rectangle "Hotel System" {
  usecase "Check Out" as UC_CheckOut
  usecase "Book Room" as UC_BookRoom
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Request Service" as UC_RequestService
  usecase "Cancel Reservation" as UC_CancelReservation
}
C --> UC_CheckOut
C --> UC_BookRoom
C --> UC_RequestService
H --> UC_BookRoom
H --> UC_RequestService
M --> UC_CancelReservation
M --> UC_CheckOut
M --> UC_RequestService
G --> UC_CancelReservation
G --> UC_BookRoom
G --> UC_CheckOut
@enduml