@startuml
skinparam monochrome true
skinparam shadowing true
left to right direction
actor "Housekeeper" as H
actor "Receptionist" as R
actor "Chef" as C
rectangle "Hotel System" {
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
  usecase "Request Service" as UC_RequestService
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Clean Room" as UC_CleanRoom
  usecase "Check In" as UC_CheckIn
}
H --> UC_CheckOut
R --> UC_CleanRoom
R --> UC_OrderRoomService
C --> UC_CancelReservation
@enduml