@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
left to right direction
actor "Registrar" as R
actor "Parent" as P
rectangle "Education System" {
  usecase "Submit Assignment" as UC_SubmitAssignment
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Grade Exam" as UC_GradeExam
  usecase "Take Attendance" as UC_TakeAttendance
  usecase "Register Student" as UC_RegisterStudent
}
R --> UC_BorrowBook
P --> UC_RegisterStudent
UC_RegisterStudent ..> UC_TakeAttendance : <<extend>>
@enduml