@startuml
skinparam shadowing true
left to right direction
actor "Member" as M
actor "Admin" as A
actor "Librarian" as L
rectangle "Library System" {
  usecase "Register Member" as UC_RegisterMember
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Reserve Book" as UC_ReserveBook
  usecase "Return Book" as UC_ReturnBook
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Add New Book" as UC_AddNewBook
  usecase "Pay Fine" as UC_PayFine
}
M --> UC_ReserveBook
A --> UC_RenewLoan
A --> UC_ReserveBook
L --> UC_AddNewBook
UC_PayFine ..> UC_ReturnBook : <<extend>>
@enduml