@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
left to right direction
actor "Customer" as C
actor "Seller" as S
rectangle "Ecommerce System" {
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Make Payment" as UC_MakePayment
  usecase "Add To Cart" as UC_AddToCart
  usecase "Checkout" as UC_Checkout
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Manage Inventory" as UC_ManageInventory
}
C --> UC_MakePayment
C --> UC_ApplyCoupon
S --> UC_ApplyCoupon
UC_Checkout ..> UC_AddToCart : <<include>>
@enduml