@startuml
skinparam monochrome true
skinparam ArrowColor #555555
left to right direction
actor "Admin" as A
actor "Payment Gateway" as PG
rectangle "Ecommerce System" {
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Apply Coupon" as UC_ApplyCoupon
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Add To Cart" as UC_AddToCart
}
A --> UC_ApplyCoupon
A --> UC_BrowseProducts
PG --> UC_AddToCart
PG --> UC_ApplyCoupon
PG --> UC_BrowseProducts
@enduml