@startuml
skinparam monochrome true
skinparam defaultFontSize 11
left to right direction
actor "Seller" as S
actor "Payment Gateway" as PG
rectangle "Ecommerce System" {
  usecase "Make Payment" as UC_MakePayment
  usecase "Add To Cart" as UC_AddToCart
  usecase "Checkout" as UC_Checkout
  usecase "Write Review" as UC_WriteReview
  usecase "Browse Products" as UC_BrowseProducts
}
S --> UC_BrowseProducts
S --> UC_MakePayment
PG --> UC_WriteReview
@enduml