@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
left to right direction
actor "Librarian" as L
actor "Member" as M
actor "Admin" as A
rectangle "Library System" {
  usecase "Search Catalog" as UC_SearchCatalog
  usecase "Renew Loan" as UC_RenewLoan
  usecase "Register Member" as UC_RegisterMember
  usecase "Return Book" as UC_ReturnBook
  usecase "Add New Book" as UC_AddNewBook
  usecase "Borrow Book" as UC_BorrowBook
  usecase "Reserve Book" as UC_ReserveBook
}
L --> UC_ReserveBook
L --> UC_AddNewBook
M --> UC_SearchCatalog
A --> UC_ReturnBook
A --> UC_RenewLoan
@enduml