@startuml
skinparam monochrome true
skinparam shadowing true
left to right direction
actor "Admin" as Admin
actor "Seller" as Seller
actor "Delivery Service" as DeliveryService
rectangle "Ecommerce System" {
  usecase "Checkout" as UC_Checkout
  usecase "Add To Cart" as UC_AddToCart
  usecase "Track Order" as UC_TrackOrder
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Write Review" as UC_WriteReview
  usecase "Cancel Order" as UC_CancelOrder
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Apply Coupon" as UC_ApplyCoupon
}
Admin --> UC_TrackOrder
Admin --> UC_ManageInventory
Seller --> UC_CancelOrder
Seller --> UC_ManageInventory
DeliveryService --> UC_CancelOrder
DeliveryService --> UC_ApplyCoupon
UC_Checkout ..> UC_ManageInventory : <<extend>>
@enduml