@startuml

left to right direction
actor "Bank Teller" as BT
actor "Auditor" as A
rectangle "Banking System" {
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "View Statement" as UC_ViewStatement
  usecase "Apply For Loan" as UC_ApplyForLoan
  usecase "Pay Bill" as UC_PayBill
}
BT --> UC_TransferFunds
BT --> UC_PayBill
BT --> UC_WithdrawCash
A --> UC_ViewStatement
A --> UC_PayBill
A --> UC_ApplyForLoan
@enduml