@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
left to right direction
actor "Guest" as G
actor "Chef" as C
actor "Receptionist" as R
rectangle "Hotel System" {
  usecase "Clean Room" as UC_CleanRoom
  usecase "Book Room" as UC_BookRoom
  usecase "Request Service" as UC_RequestService
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
  usecase "Check In" as UC_CheckIn
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Cancel Reservation" as UC_CancelReservation
}
G --> UC_CleanRoom
G --> UC_CheckOut
C --> UC_ProcessPayment
C --> UC_CancelReservation
C --> UC_BookRoom
R --> UC_CleanRoom
R --> UC_RequestService
UC_OrderRoomService ..|> UC_CleanRoom : <<include>>
@enduml