@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
left to right direction
actor "Delivery Service" as DS
actor "Payment Gateway" as PG
actor "Admin" as A
rectangle "Ecommerce System" {
  usecase "Write Review" as UC_WriteReview
  usecase "Manage Inventory" as UC_ManageInventory
  usecase "Track Order" as UC_TrackOrder
  usecase "Browse Products" as UC_BrowseProducts
  usecase "Make Payment" as UC_MakePayment
  usecase "Add To Cart" as UC_AddToCart
}
DS --> UC_WriteReview
DS --> UC_BrowseProducts
DS --> UC_TrackOrder
PG --> UC_WriteReview
PG --> UC_AddToCart
PG --> UC_ManageInventory
A --> UC_WriteReview
UC_ManageInventory ..|> UC_MakePayment : <<include>>
@enduml