@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
left to right direction
actor "Dispatcher" as D
actor "Driver" as D1
rectangle "Logistics System" {
  usecase "Track Shipment" as UC_TrackShipment
  usecase "Fuel Vehicle" as UC_FuelVehicle
  usecase "Deliver Package" as UC_DeliverPackage
  usecase "Update Inventory" as UC_UpdateInventory
  usecase "Assign Route" as UC_AssignRoute
}
D --> UC_DeliverPackage
D --> UC_TrackShipment
D1 --> UC_AssignRoute
@enduml