@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
left to right direction
actor "Guest" as G
actor "Manager" as M
rectangle "Hotel System" {
  usecase "Check In" as UC_CheckIn
  usecase "Book Room" as UC_BookRoom
  usecase "Cancel Reservation" as UC_CancelReservation
  usecase "Clean Room" as UC_CleanRoom
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Request Service" as UC_RequestService
  usecase "Process Payment" as UC_ProcessPayment
  usecase "Check Out" as UC_CheckOut
}
G --> UC_CheckIn
G --> UC_RequestService
G --> UC_CleanRoom
M --> UC_BookRoom
@enduml