@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
left to right direction
actor "Branch Manager" as BM
actor "Account Holder" as AH
actor "Auditor" as A
actor "ATM" as A1
rectangle "Banking System" {
  usecase "Block Card" as UC_BlockCard
  usecase "Pay Bill" as UC_PayBill
  usecase "Withdraw Cash" as UC_WithdrawCash
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Apply For Loan" as UC_ApplyForLoan
}
BM --> UC_WithdrawCash
BM --> UC_DepositMoney
AH --> UC_BlockCard
A --> UC_WithdrawCash
A1 --> UC_ApplyForLoan
A1 --> UC_BlockCard
A1 --> UC_DepositMoney
UC_DepositMoney ..|> UC_BlockCard : <<extend>>
@enduml