@startuml
skinparam defaultFontSize 11
left to right direction
actor "Chef" as C
actor "Guest" as G
rectangle "Hotel System" {
  usecase "Check In" as UC_CheckIn
  usecase "Order Room Service" as UC_OrderRoomService
  usecase "Request Service" as UC_RequestService
  usecase "Clean Room" as UC_CleanRoom
  usecase "Process Payment" as UC_ProcessPayment
}
C --> UC_OrderRoomService
C --> UC_CheckIn
G --> UC_ProcessPayment
G --> UC_OrderRoomService
@enduml