@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam ArrowColor #555555
left to right direction
actor "Account Holder" as AH
actor "ATM" as A
actor "Bank Teller" as BT
actor "Branch Manager" as BM
rectangle "Banking System" {
  usecase "Deposit Money" as UC_DepositMoney
  usecase "Block Card" as UC_BlockCard
  usecase "Transfer Funds" as UC_TransferFunds
  usecase "Pay Bill" as UC_PayBill
  usecase "Apply For Loan" as UC_ApplyForLoan
}
AH --> UC_BlockCard
AH --> UC_TransferFunds
AH --> UC_DepositMoney
A --> UC_PayBill
A --> UC_BlockCard
BT --> UC_BlockCard
BT --> UC_PayBill
BT --> UC_ApplyForLoan
BM --> UC_DepositMoney
BM --> UC_TransferFunds
@enduml