@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
[*] --> Archived
Archived --> Shipped : cancel
Shipped --> Closed : submit
Closed --> OnHold : cancel
OnHold --> Reviewed : review
Reviewed --> Approved : cancel
Reviewed : entry / log post
Reviewed --> Shipped : revert
Approved --> [*]
@enduml