@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
[*] --> Archived
Archived --> Pending : submit
Pending --> Draft : review
Draft --> Cancelled : cancel
Cancelled --> Delivered : submit
Cancelled : entry / log story
Delivered --> Created : review
Delivered : entry / log story
Draft --> Created : revert
Created --> [*]
@enduml