@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
[*] --> Cancelled
Cancelled --> Completed : reject
Completed --> Processing : update
Processing --> Reviewed : reject
Processing --> Cancelled : revert
Reviewed --> [*]
@enduml