@startuml
skinparam shadowing true
[*] --> OnHold
OnHold --> Archived : approve
OnHold : entry / log statement
Archived --> Pending : process
Pending --> Closed : process
Pending : entry / log statement
Closed --> Draft : process
Closed : entry / log statement
Draft --> [*]
@enduml