@startuml
skinparam monochrome true
skinparam ArrowColor #555555
[*] --> Approved
Approved --> Delivered : process
Delivered --> Draft : review
Draft --> Completed : submit
Completed --> Rejected : cancel
Draft --> Rejected : revert
Rejected --> [*]
@enduml