@startuml
skinparam monochrome true
[*] --> Closed
Closed --> Draft : update
Draft --> Pending : confirm
Draft : entry / log student
Pending --> Delivered : reject
Delivered --> Rejected : reject
Rejected --> [*]
@enduml