@startuml
skinparam monochrome true
skinparam defaultFontSize 13
[*] --> Reviewed
Reviewed --> Pending : approve
Pending --> Shipped : submit
Pending : entry / log labtest
Shipped --> Approved : process
Shipped : entry / log labtest
Shipped --> Pending : revert
Approved --> [*]
@enduml