@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
[*] --> OnHold
OnHold --> Archived : review
Archived --> Rejected : reject
Rejected --> Pending : review
Rejected : entry / log schedule
Pending --> Processing : process
Pending : entry / log schedule
Processing --> Rejected : revert
Processing --> [*]
@enduml