@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
[*] --> Delivered
Delivered --> Rejected : update
Rejected --> Active : update
Active --> Cancelled : approve
Active : entry / log labtest
Cancelled --> [*]
@enduml