@startuml
skinparam shadowing true
[*] --> Archived
Archived --> Active : review
Archived : entry / log diagnosis
Active --> Delivered : review
Delivered --> Draft : approve
Draft --> Approved : review
Approved --> [*]
@enduml