@startuml
skinparam ArrowColor #555555
[*] --> OnHold
OnHold --> Completed : cancel
Completed --> Cancelled : approve
Completed : entry / log prescription
Cancelled --> Pending : cancel
Cancelled : entry / log prescription
OnHold --> Cancelled : revert
Pending --> [*]
@enduml