@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
[*] --> Completed
Completed --> Reviewed : reject
Reviewed --> Created : approve
Created --> Rejected : cancel
Rejected --> Active : cancel
Completed --> Created : revert
Active --> [*]
@enduml