@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
[*] --> Completed
Completed --> Processing : update
Completed : entry / log department
Processing --> Cancelled : cancel
Cancelled --> Delivered : review
Delivered --> Reviewed : approve
Reviewed --> [*]
@enduml