@startuml
skinparam defaultFontSize 11
[*] --> Processing
Processing --> Approved : cancel
Approved --> Pending : reject
Pending --> Shipped : cancel
Shipped --> Created : approve
Shipped : entry / log treatment
Created --> Cancelled : process
Created : entry / log treatment
Cancelled --> [*]
@enduml