@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
[*] --> Created
Created --> Closed : reject
Closed --> Active : cancel
Active --> Pending : submit
Pending --> [*]
@enduml