@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
[*] --> Completed
Completed --> Delivered : cancel
Delivered --> Cancelled : reject
Cancelled --> Created : submit
Created --> Reviewed : process
Completed --> Reviewed : revert
Reviewed --> [*]
@enduml