@startuml
skinparam defaultFontSize 11
[*] --> Cancelled
Cancelled --> OnHold : cancel
OnHold --> Reviewed : process
Reviewed --> Active : review
Reviewed : entry / log restaurant
Active --> Closed : reject
Cancelled --> Reviewed : revert
Closed --> [*]
@enduml