@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
[*] --> Shipped
Shipped --> Rejected : cancel
Shipped : entry / log tracking
Rejected --> Approved : update
Approved --> Completed : cancel
Approved : entry / log tracking
Completed --> [*]
@enduml