@startuml
skinparam ArrowColor #555555
[*] --> Completed
Completed --> Processing : update
Processing --> Active : process
Active --> Cancelled : submit
Cancelled --> Created : approve
Created --> [*]
@enduml