@startuml

[*] --> Rejected
Rejected --> Approved : process
Approved --> Created : approve
Created --> Delivered : cancel
Delivered --> Pending : approve
Pending --> Delivered : revert
Pending --> [*]
@enduml