@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
[*] --> OnHold
OnHold --> Delivered : process
Delivered --> Shipped : process
Shipped --> Archived : approve
Archived --> Reviewed : approve
Reviewed --> [*]
@enduml