@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
[*] --> Delivered
Delivered --> Approved : approve
Approved --> Completed : approve
Completed --> Active : process
Active --> Processing : approve
Processing --> Archived : process
Approved --> Archived : revert
Archived --> [*]
@enduml