@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
[*] --> Processing
Processing --> Cancelled : submit
Cancelled --> Reviewed : cancel
Reviewed --> Pending : submit
Reviewed : entry / log beneficiary
Pending --> [*]
@enduml