@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
[*] --> Closed
Closed --> Rejected : cancel
Rejected --> Pending : cancel
Rejected : entry / log coupon
Pending --> OnHold : cancel
OnHold --> Archived : confirm
Archived --> [*]
@enduml