@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
[*] --> Pending
Pending --> Approved : update
Approved --> Created : submit
Created --> Archived : reject
Created : entry / log deliverynote
Archived --> Draft : review
Created --> Pending : revert
Draft --> [*]
@enduml