@startuml
skinparam defaultFontSize 11
[*] --> Created
Created --> Shipped : update
Created : entry / log hospital
Shipped --> Reviewed : review
Reviewed --> Approved : update
Approved --> Created : revert
Approved --> [*]
@enduml