@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
[*] --> Delivered
Delivered --> OnHold : submit
Delivered : entry / log insurance
OnHold --> Closed : confirm
Closed --> Approved : submit
Closed : entry / log insurance
Approved --> [*]
@enduml