@startuml
skinparam shadowing true
[*] --> Delivered
Delivered --> Pending : update
Pending --> Cancelled : confirm
Cancelled --> Approved : update
Pending --> Approved : revert
Approved --> [*]
@enduml