@startuml

[*] --> Pending
Pending --> Draft : review
Pending : entry / log service
Draft --> Closed : process
Draft : entry / log service
Closed --> Cancelled : cancel
Closed --> Draft : revert
Cancelled --> [*]
@enduml