@startuml
skinparam monochrome true
skinparam shadowing true
[*] --> Active
Active --> Approved : process
Approved --> Rejected : process
Rejected --> Cancelled : reject
Rejected : entry / log shipment
Cancelled --> Draft : approve
Draft --> Closed : review
Closed --> Active : revert
Closed --> [*]
@enduml