@startuml
skinparam ArrowColor #555555
[*] --> Active
Active --> Reviewed : reject
Reviewed --> Pending : approve
Pending --> Archived : cancel
Archived --> Approved : approve
Archived --> Approved : revert
Approved --> [*]
@enduml