@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
[*] --> Cancelled
Cancelled --> Created : review
Created --> Draft : process
Created : entry / log course
Draft --> Pending : approve
Pending --> Cancelled : revert
Pending --> [*]
@enduml