@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
[*] --> Shipped
Shipped --> Cancelled : process
Cancelled --> OnHold : review
OnHold --> Completed : process
OnHold : entry / log product
Completed --> Draft : approve
Completed : entry / log product
Draft --> Shipped : revert
Draft --> [*]
@enduml