@startuml
skinparam monochrome true
skinparam defaultFontSize 13
[*] --> Pending
Pending --> Approved : process
Pending : entry / log supplier
Approved --> Completed : cancel
Approved : entry / log supplier
Completed --> Reviewed : process
Reviewed --> [*]
@enduml