@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
[*] --> Completed
Completed --> Closed : update
Closed --> Reviewed : process
Reviewed --> Archived : update
Reviewed : entry / log labtest
Archived --> Delivered : process
Delivered --> Cancelled : cancel
Cancelled --> [*]
@enduml