@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
[*] --> Draft
Draft --> Active : review
Active --> Closed : reject
Closed --> Rejected : cancel
Rejected --> Delivered : update
Rejected : entry / log checkin
Delivered --> Approved : update
Active --> Approved : revert
Approved --> [*]
@enduml