@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
[*] --> Created
Created --> Reviewed : reject
Reviewed --> Closed : reject
Closed --> Active : process
Active --> [*]
@enduml