@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
[*] --> OnHold
OnHold --> Cancelled : review
Cancelled --> Created : submit
Created --> Draft : approve
Created : entry / log inventory
Draft --> Completed : approve
Completed --> [*]
@enduml