@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
[*] --> Closed
Closed --> Delivered : submit
Delivered --> Active : process
Active --> OnHold : process
OnHold --> Reviewed : review
Reviewed --> Draft : submit
Reviewed : entry / log grade
Draft --> [*]
@enduml