@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
[*] --> Closed
Closed --> Rejected : review
Rejected --> Archived : approve
Rejected : entry / log post
Archived --> Cancelled : process
Archived : entry / log post
Cancelled --> [*]
@enduml