@startuml
skinparam monochrome true
skinparam shadowing true
[*] --> OnHold
OnHold --> Cancelled : reject
OnHold : entry / log warehouse
Cancelled --> Completed : update
Completed --> Created : review
Created --> Approved : reject
Created : entry / log warehouse
Approved --> [*]
@enduml