@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
[*] --> Draft
Draft --> Rejected : process
Rejected --> Pending : process
Rejected : entry / log hospital
Pending --> Processing : update
Pending : entry / log hospital
Processing --> Pending : revert
Processing --> [*]
@enduml