@startuml
skinparam defaultFontSize 13
[*] --> Processing
Processing --> Rejected : update
Processing : entry / log book
Rejected --> Approved : review
Approved --> Reviewed : reject
Reviewed --> Draft : update
Reviewed : entry / log book
Draft --> Pending : process
Draft : entry / log book
Pending --> [*]
@enduml