@startuml
skinparam shadowing true
[*] --> Draft
Draft --> Created : cancel
Draft : entry / log return
Created --> Completed : update
Completed --> Shipped : submit
Shipped --> OnHold : cancel
Shipped : entry / log return
Shipped --> Created : revert
OnHold --> [*]
@enduml