@startuml
skinparam shadowing true
[*] --> Rejected
Rejected --> Delivered : update
Delivered --> Cancelled : approve
Cancelled --> Processing : reject
Processing --> Active : review
Active --> Cancelled : revert
Active --> [*]
@enduml