@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
[*] --> Closed
Closed --> Processing : approve
Closed : entry / log medicalrecord
Processing --> Created : submit
Processing : entry / log medicalrecord
Created --> Active : reject
Created : entry / log medicalrecord
Processing --> Closed : revert
Active --> [*]
@enduml