@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
[*] --> Closed
Closed --> Archived : process
Closed : entry / log post
Archived --> Pending : update
Pending --> Reviewed : cancel
Pending : entry / log post
Closed --> Pending : revert
Reviewed --> [*]
@enduml