@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
[*] --> Active
Active --> Reviewed : submit
Active : entry / log diagnosis
Reviewed --> Closed : process
Reviewed : entry / log diagnosis
Closed --> OnHold : update
Closed : entry / log diagnosis
Reviewed --> OnHold : revert
OnHold --> [*]
@enduml