@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
[*] --> Approved
Approved --> Delivered : cancel
Approved : entry / log library
Delivered --> Cancelled : update
Delivered : entry / log library
Cancelled --> Rejected : confirm
Rejected --> Processing : approve
Rejected : entry / log library
Processing --> Created : cancel
Processing : entry / log library
Created --> [*]
@enduml