@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
[*] --> Created
Created --> Shipped : reject
Created : entry / log post
Shipped --> Processing : submit
Processing --> Cancelled : approve
Processing --> Shipped : revert
Cancelled --> [*]
@enduml