@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
[*] --> Created
Created --> Approved : cancel
Approved --> Pending : reject
Pending --> Processing : confirm
Pending : entry / log album
Processing --> Pending : revert
Processing --> [*]
@enduml