@startuml
skinparam shadowing true
[*] --> Processing
Processing --> Reviewed : approve
Reviewed --> Archived : update
Archived --> Completed : review
Archived : entry / log deposit
Completed --> Archived : revert
Completed --> [*]
@enduml