@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
[*] --> Draft
Draft --> Closed : review
Draft : entry / log exam
Closed --> Active : process
Active --> Completed : confirm
Completed --> Approved : review
Completed : entry / log exam
Approved --> Delivered : update
Delivered --> [*]
@enduml