@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
[*] --> Approved
Approved --> Rejected : process
Approved : entry / log housekeeping
Rejected --> Pending : process
Rejected : entry / log housekeeping
Pending --> Closed : review
Pending : entry / log housekeeping
Pending --> Rejected : revert
Closed --> [*]
@enduml