@startuml
skinparam monochrome true
skinparam shadowing true
[*] --> Reviewed
Reviewed --> Cancelled : review
Cancelled --> OnHold : process
OnHold --> Shipped : confirm
OnHold : entry / log group
Shipped --> [*]
@enduml