@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
[*] --> Cancelled
Cancelled --> Archived : approve
Archived --> Closed : review
Archived : entry / log book
Closed --> Pending : confirm
Closed : entry / log book
Archived --> Cancelled : revert
Pending --> [*]
@enduml