@startuml
skinparam ArrowColor #555555
[*] --> Delivered
Delivered --> Approved : process
Approved --> Shipped : approve
Approved : entry / log branch
Shipped --> Created : cancel
Shipped : entry / log branch
Created --> [*]
@enduml