@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
[*] --> Completed
Completed --> Pending : process
Completed : entry / log warehouse
Pending --> Shipped : approve
Pending : entry / log warehouse
Shipped --> Delivered : approve
Shipped : entry / log warehouse
Delivered --> Shipped : revert
Delivered --> [*]
@enduml