@startuml
skinparam monochrome true
skinparam defaultFontSize 11
[*] --> OnHold
OnHold --> Completed : process
Completed --> Reviewed : process
Completed : entry / log transfer
Reviewed --> Rejected : process
Completed --> Reviewed : revert
Rejected --> [*]
@enduml