@startuml
skinparam monochrome true
skinparam shadowing true
[*] --> Created
Created --> Rejected : process
Created : entry / log invoice
Rejected --> Archived : confirm
Archived --> Draft : submit
Draft --> Processing : submit
Processing --> Approved : process
Approved --> [*]
@enduml