@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
[*] --> Cancelled
Cancelled --> Pending : confirm
Pending --> Created : submit
Pending : entry / log service
Created --> Closed : reject
Closed --> Draft : submit
Closed : entry / log service
Draft --> [*]
@enduml