@startuml
skinparam defaultFontSize 11
[*] --> Draft
Draft --> Delivered : update
Delivered --> Completed : reject
Completed --> Rejected : reject
Completed : entry / log labtest
Rejected --> Completed : revert
Rejected --> [*]
@enduml