@startuml
skinparam monochrome true
skinparam ArrowColor #555555
[*] --> Closed
Closed --> Cancelled : review
Cancelled --> Pending : process
Pending --> Rejected : approve
Pending : entry / log wishlist
Rejected --> Completed : review
Rejected : entry / log wishlist
Completed --> [*]
@enduml