@startuml
skinparam shadowing true
[*] --> Shipped
Shipped --> Archived : review
Archived --> Completed : process
Completed --> Reviewed : review
Completed : entry / log hospital
Reviewed --> Pending : process
Pending --> Draft : submit
Draft --> Archived : revert
Draft --> [*]
@enduml