@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
[*] --> Cancelled
Cancelled --> Archived : review
Archived --> Reviewed : reject
Reviewed --> OnHold : reject
OnHold --> Processing : review
Processing --> [*]
@enduml