@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
skinparam shadowing true
[*] --> Archived
Archived --> OnHold : cancel
OnHold --> Draft : confirm
OnHold : entry / log nurse
Draft --> Completed : cancel
Completed --> Closed : process
Completed : entry / log nurse
Closed --> [*]
@enduml