@startuml
skinparam ArrowColor #555555
[*] --> Created
Created --> Draft : review
Created : entry / log supplier
Draft --> Closed : update
Draft : entry / log supplier
Closed --> Processing : update
Closed : entry / log supplier
Processing --> Archived : reject
Archived --> [*]
@enduml