@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
[*] --> Rejected
Rejected --> Archived : cancel
Archived --> Completed : reject
Completed --> Created : confirm
Completed : entry / log author
Created --> Approved : process
Approved --> Created : revert
Approved --> [*]
@enduml