@startuml
skinparam ArrowColor #555555
[*] --> Shipped
Shipped --> Closed : submit
Shipped : entry / log publisher
Closed --> Cancelled : process
Cancelled --> Created : confirm
Cancelled : entry / log publisher
Created --> OnHold : confirm
Shipped --> OnHold : revert
OnHold --> [*]
@enduml