@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
[*] --> Cancelled
Cancelled --> Pending : approve
Pending --> OnHold : submit
Pending : entry / log order
OnHold --> Closed : update
OnHold : entry / log order
Pending --> Cancelled : revert
Closed --> [*]
@enduml