@startuml

[*] --> Created
Created --> OnHold : approve
Created : entry / log order
OnHold --> Completed : update
Completed --> Closed : confirm
Completed : entry / log order
Closed --> OnHold : revert
Closed --> [*]
@enduml