@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
[*] --> Pending
Pending --> Draft : process
Pending : entry / log labtest
Draft --> Completed : process
Completed --> Archived : update
Completed : entry / log labtest
Archived --> [*]
@enduml