@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam shadowing true
[*] --> Closed
Closed --> Archived : update
Archived --> Processing : update
Archived : entry / log ward
Processing --> Draft : submit
Draft --> Active : review
Draft : entry / log ward
Active --> [*]
@enduml