@startuml
skinparam ArrowColor #555555
[*] --> Processing
Processing --> OnHold : update
OnHold --> Active : confirm
Active --> Reviewed : review
Active --> Processing : revert
Reviewed --> [*]
@enduml