@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
[*] --> Delivered
Delivered --> Approved : approve
Approved --> Created : update
Created --> Rejected : review
Rejected --> Shipped : update
Rejected --> Created : revert
Shipped --> [*]
@enduml