@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam ArrowColor #555555
[*] --> Completed
Completed --> Pending : update
Pending --> Delivered : reject
Pending : entry / log checkout
Delivered --> Shipped : submit
Delivered : entry / log checkout
Pending --> Delivered : revert
Shipped --> [*]
@enduml