@startuml
skinparam backgroundColor #ECEFF1
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #455A64
skinparam shadowing true
[*] --> Completed
Completed --> OnHold : cancel
Completed : entry / log invoice
OnHold --> Approved : submit
Approved --> Cancelled : submit
Approved : entry / log invoice
Cancelled --> [*]
@enduml