@startuml
skinparam monochrome true
skinparam defaultFontSize 11
[*] --> Rejected
Rejected --> Draft : update
Draft --> Archived : approve
Archived --> Active : cancel
Archived : entry / log prescription
Archived --> Active : revert
Active --> [*]
@enduml