@startuml
skinparam monochrome true
skinparam defaultFontSize 11
[*] --> Delivered
Delivered --> Processing : review
Delivered : entry / log payment
Processing --> OnHold : cancel
Processing : entry / log payment
OnHold --> Reviewed : cancel
OnHold : entry / log payment
Reviewed --> [*]
@enduml