@startuml
skinparam shadowing true
[*] --> Processing
Processing --> Cancelled : reject
Cancelled --> Delivered : approve
Delivered --> Created : reject
Created --> Cancelled : revert
Created --> [*]
@enduml