@startuml
skinparam monochrome true
skinparam defaultFontSize 13
[*] --> Created
Created --> OnHold : confirm
Created : entry / log library
OnHold --> Shipped : update
OnHold : entry / log library
Shipped --> Completed : approve
Completed --> [*]
@enduml