@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
[*] --> Cancelled
Cancelled --> Closed : approve
Cancelled : entry / log author
Closed --> Reviewed : approve
Reviewed --> Completed : submit
Reviewed : entry / log author
Completed --> Draft : process
Completed : entry / log author
Draft --> Processing : approve
Draft : entry / log author
Processing --> [*]
@enduml