@startuml
skinparam monochrome true
skinparam shadowing true
[*] --> Approved
Approved --> Cancelled : submit
Approved : entry / log grade
Cancelled --> Completed : process
Cancelled : entry / log grade
Completed --> Processing : submit
Completed : entry / log grade
Processing --> Delivered : approve
Delivered --> Rejected : process
Rejected --> [*]
@enduml