@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
[*] --> OnHold
OnHold --> Rejected : update
Rejected --> Delivered : cancel
Delivered --> Cancelled : reject
Delivered --> Rejected : revert
Cancelled --> [*]
@enduml