@startuml

[*] --> Active
Active --> Processing : update
Processing --> Created : submit
Created --> Draft : submit
Created : entry / log invoice
Draft --> Cancelled : reject
Cancelled --> [*]
@enduml