@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
[*] --> Rejected
Rejected --> Draft : submit
Rejected : entry / log product
Draft --> OnHold : review
Draft : entry / log product
OnHold --> Pending : approve
Pending --> [*]
@enduml