@startuml
skinparam monochrome true
skinparam shadowing true
[*] --> Reviewed
Reviewed --> OnHold : review
OnHold --> Delivered : submit
Delivered --> Draft : approve
Draft --> Shipped : review
Shipped --> [*]
@enduml