@startuml
skinparam monochrome true
[*] --> Rejected
Rejected --> Created : reject
Rejected : entry / log attendance
Created --> Approved : approve
Approved --> Pending : review
Pending --> Shipped : submit
Pending : entry / log attendance
Shipped --> Processing : update
Created --> Rejected : revert
Processing --> [*]
@enduml