@startuml
skinparam monochrome true
skinparam ArrowColor #555555
[*] --> OnHold
OnHold --> Created : confirm
OnHold : entry / log course
Created --> Closed : update
Closed --> Draft : submit
Draft --> Rejected : cancel
Draft : entry / log course
Rejected --> Active : review
Active --> [*]
@enduml