@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 11
[*] --> Completed
Completed --> Processing : cancel
Processing --> Reviewed : process
Reviewed --> OnHold : cancel
OnHold --> Draft : reject
OnHold : entry / log wishlist
Completed --> OnHold : revert
Draft --> [*]
@enduml