@startuml
skinparam ArrowColor #555555
[*] --> Archived
Archived --> Created : approve
Created --> Delivered : submit
Delivered --> Completed : update
Completed --> Cancelled : update
Completed --> Cancelled : revert
Cancelled --> [*]
@enduml