@startuml
skinparam shadowing true
[*] --> OnHold
OnHold --> Created : reject
Created --> Approved : review
Approved --> Shipped : cancel
Approved : entry / log wishlist
Shipped --> Active : update
Shipped --> Created : revert
Active --> [*]
@enduml