@startuml
skinparam monochrome true
skinparam shadowing true
[*] --> Closed
Closed --> Created : approve
Created --> Archived : process
Archived --> Active : approve
Archived : entry / log treatment
Active --> Shipped : confirm
Active : entry / log treatment
Shipped --> [*]
@enduml