@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
[*] --> Reviewed
Reviewed --> Processing : approve
Processing --> Completed : cancel
Processing : entry / log wishlist
Completed --> Rejected : cancel
Completed : entry / log wishlist
Rejected --> [*]
@enduml