@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
[*] --> Draft
Draft --> OnHold : reject
Draft : entry / log comment
OnHold --> Reviewed : cancel
Reviewed --> Pending : approve
Reviewed : entry / log comment
Reviewed --> OnHold : revert
Pending --> [*]
@enduml