@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F3E5F5
skinparam classBorderColor #6A1B9A
[*] --> Archived
Archived --> Closed : process
Closed --> Created : confirm
Created --> Delivered : confirm
Created : entry / log prescription
Delivered --> OnHold : update
OnHold --> Rejected : update
Rejected --> [*]
@enduml