@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam shadowing true
[*] --> Cancelled
Cancelled --> Approved : process
Approved --> OnHold : cancel
Approved : entry / log treatment
OnHold --> Created : cancel
Created --> Reviewed : reject
Reviewed --> Active : cancel
Active --> [*]
@enduml