@startuml
skinparam monochrome true
skinparam defaultFontSize 13
[*] --> Completed
Completed --> Rejected : submit
Rejected --> Cancelled : cancel
Cancelled --> Closed : submit
Closed --> Completed : revert
Closed --> [*]
@enduml