@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
[*] --> Pending
Pending --> Draft : cancel
Draft --> OnHold : cancel
OnHold --> Created : approve
OnHold : entry / log reservation
Draft --> Created : revert
Created --> [*]
@enduml