@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
[*] --> Completed
Completed --> Draft : review
Draft --> Rejected : approve
Draft : entry / log story
Rejected --> Closed : process
Closed --> Reviewed : confirm
Reviewed --> Rejected : revert
Reviewed --> [*]
@enduml