@startuml
skinparam monochrome true
skinparam ArrowColor #555555
[*] --> Archived
Archived --> Approved : cancel
Approved --> Cancelled : submit
Approved : entry / log treatment
Cancelled --> Draft : submit
Draft --> Rejected : approve
Archived --> Cancelled : revert
Rejected --> [*]
@enduml