@startuml
skinparam monochrome true
[*] --> Processing
Processing --> Closed : cancel
Closed --> Delivered : confirm
Delivered --> Active : process
Delivered : entry / log deliverynote
Delivered --> Processing : revert
Active --> [*]
@enduml