@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam ArrowColor #555555
[*] --> Archived
Archived --> Cancelled : process
Archived : entry / log librarian
Cancelled --> Created : approve
Created --> Completed : approve
Completed --> Pending : confirm
Pending --> [*]
@enduml