@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
[*] --> Shipped
Shipped --> Approved : approve
Approved --> Completed : cancel
Completed --> Closed : reject
Completed : entry / log user
Closed --> Delivered : approve
Delivered --> [*]
@enduml