@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam ArrowColor #555555
[*] --> Reviewed
Reviewed --> Closed : confirm
Closed --> Rejected : reject
Rejected --> Delivered : submit
Rejected : entry / log renewal
Delivered --> Completed : review
Delivered : entry / log renewal
Closed --> Delivered : revert
Completed --> [*]
@enduml