@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
skinparam defaultFontSize 11
[*] --> Rejected
Rejected --> Closed : reject
Closed --> Active : cancel
Active --> Completed : submit
Active : entry / log user
Completed --> OnHold : approve
Completed --> Rejected : revert
OnHold --> [*]
@enduml