@startuml
skinparam monochrome true
[*] --> Reviewed
Reviewed --> Created : approve
Created --> Pending : cancel
Pending --> Approved : update
Pending : entry / log transaction
Approved --> Delivered : approve
Delivered --> OnHold : confirm
OnHold --> [*]
@enduml