@startuml
skinparam shadowing false
skinparam backgroundColor #F5F5F5
[*] --> Cancelled
Cancelled --> Rejected : review
Cancelled : entry / log loan
Rejected --> Reviewed : approve
Reviewed --> Delivered : update
Delivered --> [*]
@enduml