@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam shadowing true
[*] --> Cancelled
Cancelled --> Delivered : review
Delivered --> Pending : confirm
Delivered : entry / log cart
Pending --> Draft : cancel
Draft --> Rejected : update
Rejected --> Approved : confirm
Rejected --> Delivered : revert
Approved --> [*]
@enduml