@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
[*] --> Cancelled
Cancelled --> Approved : update
Approved --> Closed : process
Closed --> Draft : update
Draft --> Delivered : update
Delivered --> [*]
@enduml