@startuml
skinparam shadowing true
[*] --> Reviewed
Reviewed --> Draft : update
Reviewed : entry / log hashtag
Draft --> Pending : update
Pending --> Rejected : reject
Rejected --> Cancelled : submit
Rejected : entry / log hashtag
Cancelled --> [*]
@enduml