@startuml
skinparam defaultFontSize 11
[*] --> Active
Active --> Draft : update
Draft --> Reviewed : submit
Draft : entry / log department
Reviewed --> Closed : cancel
Reviewed : entry / log department
Closed --> Created : cancel
Created --> [*]
@enduml