@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
[*] --> OnHold
OnHold --> Rejected : approve
OnHold : entry / log checkin
Rejected --> Draft : approve
Draft --> Processing : review
Draft : entry / log checkin
Processing --> Rejected : revert
Processing --> [*]
@enduml