@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
skinparam defaultFontSize 13
[*] --> OnHold
OnHold --> Created : review
Created --> Active : submit
Created : entry / log payment
Active --> Delivered : submit
Active --> Delivered : revert
Delivered --> [*]
@enduml