@startuml
skinparam backgroundColor #FFFFFF
skinparam roundCorner 15
[*] --> Active
Active --> Cancelled : approve
Cancelled --> Created : approve
Created --> Approved : approve
Created : entry / log reservation
Approved --> OnHold : cancel
Approved : entry / log reservation
Active --> Approved : revert
OnHold --> [*]
@enduml