@startuml
skinparam backgroundColor #FFFDE7
skinparam classBackgroundColor #FFF9C4
skinparam classBorderColor #F57F17
[*] --> Cancelled
Cancelled --> Shipped : update
Shipped --> Reviewed : process
Shipped : entry / log book
Reviewed --> Created : process
Reviewed : entry / log book
Shipped --> Created : revert
Created --> [*]
@enduml