@startuml
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #F1F8E9
skinparam classBorderColor #33691E
skinparam defaultFontSize 11
[*] --> Created
Created --> OnHold : confirm
OnHold --> Completed : approve
OnHold : entry / log transfer
Completed --> Active : confirm
Completed : entry / log transfer
Completed --> Created : revert
Active --> [*]
@enduml