@startuml
skinparam monochrome true
skinparam ArrowColor #555555
[*] --> Pending
Pending --> Reviewed : approve
Pending : entry / log medicalrecord
Reviewed --> Active : process
Active --> Archived : approve
Active : entry / log medicalrecord
Active --> Archived : revert
Archived --> [*]
@enduml