@startuml
skinparam monochrome true
skinparam defaultFontSize 11
[*] --> Reviewed
Reviewed --> Approved : submit
Approved --> Pending : cancel
Approved : entry / log depot
Pending --> Active : process
Active --> Created : submit
Pending --> Reviewed : revert
Created --> [*]
@enduml