@startuml
skinparam monochrome true
skinparam defaultFontSize 11
[*] --> Created
Created --> Processing : submit
Created : entry / log payment
Processing --> Draft : process
Processing : entry / log payment
Draft --> Active : reject
Created --> Active : revert
Active --> [*]
@enduml